// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost2_wrt_rz_Nl0
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     rx: Scalar
 *     ry: Scalar
 *     rz: Scalar
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost2WrtRzNl0(
    const Scalar fh1, const Scalar fv1, const Scalar rx, const Scalar ry, const Scalar rz,
    const Scalar p_init0, const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x,
    const Scalar rot_init_y, const Scalar rot_init_z, const Scalar rot_init_w,
    const Scalar epsilon) {
  // Total ops: 1661

  // Unused inputs
  (void)epsilon;

  // Input arrays

  // Intermediate terms (519)
  const Scalar _tmp0 = std::pow(rz, Scalar(2));
  const Scalar _tmp1 = _tmp0 + std::pow(rx, Scalar(2)) + std::pow(ry, Scalar(2));
  const Scalar _tmp2 = std::sqrt(_tmp1);
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = std::cos(_tmp3);
  const Scalar _tmp5 = _tmp4 * rot_init_x;
  const Scalar _tmp6 = std::sin(_tmp3);
  const Scalar _tmp7 = _tmp6 / _tmp2;
  const Scalar _tmp8 = _tmp7 * rot_init_z;
  const Scalar _tmp9 = _tmp7 * rot_init_w;
  const Scalar _tmp10 = _tmp7 * rot_init_y;
  const Scalar _tmp11 = _tmp10 * rz;
  const Scalar _tmp12 = _tmp11 + _tmp5 - _tmp8 * ry + _tmp9 * rx;
  const Scalar _tmp13 = _tmp4 * rot_init_z;
  const Scalar _tmp14 = _tmp7 * rot_init_x;
  const Scalar _tmp15 = _tmp9 * rz;
  const Scalar _tmp16 = -_tmp10 * rx + _tmp13 + _tmp14 * ry + _tmp15;
  const Scalar _tmp17 = 2 * _tmp16;
  const Scalar _tmp18 = _tmp12 * _tmp17;
  const Scalar _tmp19 = _tmp4 * rot_init_y;
  const Scalar _tmp20 = _tmp14 * rz;
  const Scalar _tmp21 = _tmp19 - _tmp20 + _tmp8 * rx + _tmp9 * ry;
  const Scalar _tmp22 = _tmp4 * rot_init_w;
  const Scalar _tmp23 = _tmp8 * rz;
  const Scalar _tmp24 = -_tmp10 * ry - _tmp14 * rx + _tmp22 - _tmp23;
  const Scalar _tmp25 = 2 * _tmp24;
  const Scalar _tmp26 = _tmp21 * _tmp25;
  const Scalar _tmp27 = Scalar(0.20999999999999999) * _tmp18 - Scalar(0.20999999999999999) * _tmp26;
  const Scalar _tmp28 = -_tmp27;
  const Scalar _tmp29 = -2 * std::pow(_tmp12, Scalar(2));
  const Scalar _tmp30 = 1 - 2 * std::pow(_tmp21, Scalar(2));
  const Scalar _tmp31 =
      -Scalar(0.010999999999999999) * _tmp29 - Scalar(0.010999999999999999) * _tmp30;
  const Scalar _tmp32 = _tmp17 * _tmp21;
  const Scalar _tmp33 = _tmp12 * _tmp25;
  const Scalar _tmp34 = Scalar(0.20999999999999999) * _tmp32 + Scalar(0.20999999999999999) * _tmp33;
  const Scalar _tmp35 = _tmp31 - _tmp34;
  const Scalar _tmp36 = _tmp28 + _tmp35;
  const Scalar _tmp37 = -_tmp36 - p_init2 + Scalar(8.4718465799999993);
  const Scalar _tmp38 = -2 * std::pow(_tmp16, Scalar(2));
  const Scalar _tmp39 = Scalar(0.20999999999999999) * _tmp29 +
                        Scalar(0.20999999999999999) * _tmp38 + Scalar(0.20999999999999999);
  const Scalar _tmp40 = -_tmp39;
  const Scalar _tmp41 = _tmp32 - _tmp33;
  const Scalar _tmp42 = -Scalar(0.010999999999999999) * _tmp41;
  const Scalar _tmp43 = 2 * _tmp12 * _tmp21;
  const Scalar _tmp44 = _tmp16 * _tmp25;
  const Scalar _tmp45 = Scalar(0.20999999999999999) * _tmp43 + Scalar(0.20999999999999999) * _tmp44;
  const Scalar _tmp46 = _tmp42 - _tmp45;
  const Scalar _tmp47 = _tmp40 + _tmp46;
  const Scalar _tmp48 = _tmp47 + p_init1;
  const Scalar _tmp49 = -_tmp48 + Scalar(-8.3196563700000006);
  const Scalar _tmp50 = Scalar(0.20999999999999999) * _tmp30 + Scalar(0.20999999999999999) * _tmp38;
  const Scalar _tmp51 = -_tmp50;
  const Scalar _tmp52 = Scalar(0.20999999999999999) * _tmp43 - Scalar(0.20999999999999999) * _tmp44;
  const Scalar _tmp53 = _tmp18 + _tmp26;
  const Scalar _tmp54 = -Scalar(0.010999999999999999) * _tmp53;
  const Scalar _tmp55 = -_tmp52 + _tmp54;
  const Scalar _tmp56 = _tmp51 + _tmp55;
  const Scalar _tmp57 = _tmp56 + p_init0;
  const Scalar _tmp58 = -_tmp57 + Scalar(-1.9874742000000001);
  const Scalar _tmp59 = std::pow(_tmp49, Scalar(2)) + std::pow(_tmp58, Scalar(2));
  const Scalar _tmp60 = (Scalar(1) / Scalar(2)) / _tmp1;
  const Scalar _tmp61 = _tmp0 * _tmp60;
  const Scalar _tmp62 = _tmp60 * rz;
  const Scalar _tmp63 = _tmp62 * ry;
  const Scalar _tmp64 = _tmp62 * rx;
  const Scalar _tmp65 = _tmp6 / (_tmp1 * std::sqrt(_tmp1));
  const Scalar _tmp66 = _tmp0 * _tmp65;
  const Scalar _tmp67 = _tmp65 * rz;
  const Scalar _tmp68 = _tmp67 * rx;
  const Scalar _tmp69 = _tmp67 * ry;
  const Scalar _tmp70 = _tmp10 - _tmp13 * _tmp63 + _tmp19 * _tmp61 -
                        Scalar(1) / Scalar(2) * _tmp20 + _tmp22 * _tmp64 - _tmp66 * rot_init_y -
                        _tmp68 * rot_init_w + _tmp69 * rot_init_z;
  const Scalar _tmp71 = _tmp12 * _tmp70;
  const Scalar _tmp72 = Scalar(0.043999999999999997) * _tmp71;
  const Scalar _tmp73 = -Scalar(1) / Scalar(2) * _tmp11 + _tmp13 * _tmp64 - _tmp14 +
                        _tmp22 * _tmp63 - _tmp5 * _tmp61 + _tmp66 * rot_init_x -
                        _tmp68 * rot_init_z - _tmp69 * rot_init_w;
  const Scalar _tmp74 = _tmp21 * _tmp73;
  const Scalar _tmp75 = Scalar(0.043999999999999997) * _tmp74;
  const Scalar _tmp76 = -_tmp72 - _tmp75;
  const Scalar _tmp77 = _tmp19 * _tmp62;
  const Scalar _tmp78 = -_tmp13 * _tmp61 - Scalar(1) / Scalar(2) * _tmp15 - _tmp5 * _tmp64 +
                        _tmp66 * rot_init_z + _tmp68 * rot_init_x + _tmp69 * rot_init_y -
                        _tmp77 * ry - _tmp8;
  const Scalar _tmp79 = _tmp21 * _tmp78;
  const Scalar _tmp80 = Scalar(0.41999999999999998) * _tmp79;
  const Scalar _tmp81 = Scalar(0.41999999999999998) * _tmp16;
  const Scalar _tmp82 = _tmp70 * _tmp81;
  const Scalar _tmp83 = _tmp22 * _tmp61 - Scalar(1) / Scalar(2) * _tmp23 + _tmp5 * _tmp63 -
                        _tmp66 * rot_init_w + _tmp68 * rot_init_y - _tmp69 * rot_init_x -
                        _tmp77 * rx + _tmp9;
  const Scalar _tmp84 = Scalar(0.41999999999999998) * _tmp83;
  const Scalar _tmp85 = _tmp12 * _tmp84;
  const Scalar _tmp86 = Scalar(0.41999999999999998) * _tmp24;
  const Scalar _tmp87 = _tmp73 * _tmp86;
  const Scalar _tmp88 = -_tmp80 + _tmp82 + _tmp85 - _tmp87;
  const Scalar _tmp89 = _tmp76 + _tmp88;
  const Scalar _tmp90 = _tmp12 * _tmp78;
  const Scalar _tmp91 = Scalar(0.41999999999999998) * _tmp90;
  const Scalar _tmp92 = _tmp73 * _tmp81;
  const Scalar _tmp93 = _tmp21 * _tmp84;
  const Scalar _tmp94 = _tmp70 * _tmp86;
  const Scalar _tmp95 = _tmp91 + _tmp92 + _tmp93 + _tmp94;
  const Scalar _tmp96 = Scalar(0.021999999999999999) * _tmp78;
  const Scalar _tmp97 = _tmp12 * _tmp96;
  const Scalar _tmp98 = Scalar(0.021999999999999999) * _tmp16;
  const Scalar _tmp99 = _tmp73 * _tmp98;
  const Scalar _tmp100 = Scalar(0.021999999999999999) * _tmp83;
  const Scalar _tmp101 = _tmp100 * _tmp21;
  const Scalar _tmp102 = Scalar(0.021999999999999999) * _tmp24;
  const Scalar _tmp103 = _tmp102 * _tmp70;
  const Scalar _tmp104 = _tmp101 - _tmp103 - _tmp97 + _tmp99;
  const Scalar _tmp105 = _tmp16 * _tmp83;
  const Scalar _tmp106 = Scalar(0.83999999999999997) * _tmp105;
  const Scalar _tmp107 = -_tmp106;
  const Scalar _tmp108 = Scalar(0.83999999999999997) * _tmp71;
  const Scalar _tmp109 = _tmp107 - _tmp108;
  const Scalar _tmp110 = _tmp16 * _tmp78;
  const Scalar _tmp111 = Scalar(0.41999999999999998) * _tmp110;
  const Scalar _tmp112 = _tmp24 * _tmp83;
  const Scalar _tmp113 = Scalar(0.41999999999999998) * _tmp112;
  const Scalar _tmp114 = _tmp111 + _tmp113;
  const Scalar _tmp115 = _tmp21 * _tmp70;
  const Scalar _tmp116 = Scalar(0.41999999999999998) * _tmp115;
  const Scalar _tmp117 = _tmp12 * _tmp73;
  const Scalar _tmp118 = Scalar(0.41999999999999998) * _tmp117;
  const Scalar _tmp119 = _tmp116 + _tmp118;
  const Scalar _tmp120 = _tmp114 + _tmp119;
  const Scalar _tmp121 = _tmp109 + _tmp120;
  const Scalar _tmp122 = Scalar(0.83999999999999997) * _tmp74;
  const Scalar _tmp123 = _tmp107 - _tmp122;
  const Scalar _tmp124 = -_tmp111 - _tmp113;
  const Scalar _tmp125 = _tmp119 + _tmp124;
  const Scalar _tmp126 = _tmp21 * _tmp96;
  const Scalar _tmp127 = _tmp70 * _tmp98;
  const Scalar _tmp128 = _tmp100 * _tmp12;
  const Scalar _tmp129 = _tmp102 * _tmp73;
  const Scalar _tmp130 = _tmp126 + _tmp127 + _tmp128 + _tmp129;
  const Scalar _tmp131 = _tmp125 + _tmp130;
  const Scalar _tmp132 = 2 * _tmp49 * (_tmp104 + _tmp121) + 2 * _tmp58 * (_tmp123 + _tmp131);
  const Scalar _tmp133 = std::sqrt(_tmp59);
  const Scalar _tmp134 = Scalar(1.0) / (fh1);
  const Scalar _tmp135 = _tmp50 + _tmp55;
  const Scalar _tmp136 = _tmp135 + p_init0;
  const Scalar _tmp137 = _tmp136 + Scalar(-2.5202214700000001);
  const Scalar _tmp138 = Scalar(1.0) / (_tmp137);
  const Scalar _tmp139 = _tmp42 + _tmp45;
  const Scalar _tmp140 = _tmp139 + _tmp40;
  const Scalar _tmp141 = _tmp140 + p_init1;
  const Scalar _tmp142 = _tmp141 + Scalar(8.3888750099999996);
  const Scalar _tmp143 = _tmp138 * _tmp142;
  const Scalar _tmp144 = _tmp139 + _tmp39;
  const Scalar _tmp145 = _tmp144 + p_init1;
  const Scalar _tmp146 = _tmp145 + Scalar(-4.7752063900000001);
  const Scalar _tmp147 = _tmp52 + _tmp54;
  const Scalar _tmp148 = _tmp147 + _tmp50;
  const Scalar _tmp149 = _tmp148 + p_init0;
  const Scalar _tmp150 = _tmp149 + Scalar(-2.71799795);
  const Scalar _tmp151 = std::pow(_tmp146, Scalar(2)) + std::pow(_tmp150, Scalar(2));
  const Scalar _tmp152 = std::pow(_tmp151, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp153 = _tmp150 * _tmp152;
  const Scalar _tmp154 = _tmp146 * _tmp152;
  const Scalar _tmp155 = _tmp143 * _tmp153 - _tmp154;
  const Scalar _tmp156 = Scalar(1.0) / (_tmp155);
  const Scalar _tmp157 = _tmp153 * _tmp156;
  const Scalar _tmp158 = Scalar(1.0) * _tmp135;
  const Scalar _tmp159 = Scalar(1.0) * _tmp140;
  const Scalar _tmp160 = -_tmp159;
  const Scalar _tmp161 = _tmp144 + _tmp160;
  const Scalar _tmp162 = Scalar(1.0) / (_tmp161);
  const Scalar _tmp163 = -_tmp148 + _tmp158;
  const Scalar _tmp164 = _tmp162 * _tmp163;
  const Scalar _tmp165 = _tmp158 + _tmp159 * _tmp164;
  const Scalar _tmp166 = 0;
  const Scalar _tmp167 = _tmp27 + _tmp35;
  const Scalar _tmp168 = _tmp153 * _tmp167;
  const Scalar _tmp169 = _tmp31 + _tmp34;
  const Scalar _tmp170 = _tmp169 + _tmp27;
  const Scalar _tmp171 = -_tmp143 * _tmp168 + _tmp154 * _tmp170;
  const Scalar _tmp172 = _tmp39 + _tmp46;
  const Scalar _tmp173 = _tmp172 + p_init1;
  const Scalar _tmp174 = _tmp173 + Scalar(-4.8333311099999996);
  const Scalar _tmp175 = _tmp147 + _tmp51;
  const Scalar _tmp176 = _tmp175 + p_init0;
  const Scalar _tmp177 = _tmp176 + Scalar(1.79662371);
  const Scalar _tmp178 = std::pow(_tmp174, Scalar(2)) + std::pow(_tmp177, Scalar(2));
  const Scalar _tmp179 = std::pow(_tmp178, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp180 = _tmp177 * _tmp179;
  const Scalar _tmp181 = _tmp174 * _tmp179;
  const Scalar _tmp182 = _tmp143 * _tmp180 - _tmp181;
  const Scalar _tmp183 = _tmp156 * _tmp182;
  const Scalar _tmp184 = _tmp167 * _tmp180;
  const Scalar _tmp185 = _tmp169 + _tmp28;
  const Scalar _tmp186 = -_tmp143 * _tmp184 - _tmp171 * _tmp183 + _tmp181 * _tmp185;
  const Scalar _tmp187 = -_tmp153 * _tmp170 + _tmp168;
  const Scalar _tmp188 = -_tmp164 * _tmp186 - _tmp180 * _tmp185 - _tmp183 * _tmp187 + _tmp184;
  const Scalar _tmp189 = Scalar(1.0) / (_tmp188);
  const Scalar _tmp190 = _tmp182 * _tmp189;
  const Scalar _tmp191 = _tmp166 * _tmp190;
  const Scalar _tmp192 = _tmp166 * _tmp189;
  const Scalar _tmp193 = -_tmp157 * _tmp191 + _tmp180 * _tmp192;
  const Scalar _tmp194 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp195 = std::pow(_tmp137, Scalar(2));
  const Scalar _tmp196 = std::pow(_tmp142, Scalar(2)) + _tmp195;
  const Scalar _tmp197 = std::sqrt(_tmp196);
  const Scalar _tmp198 = _tmp138 * _tmp197;
  const Scalar _tmp199 = _tmp194 * _tmp198;
  const Scalar _tmp200 = Scalar(1.0) / (_tmp197);
  const Scalar _tmp201 = _tmp140 * _tmp200;
  const Scalar _tmp202 = _tmp142 * _tmp200;
  const Scalar _tmp203 = _tmp135 * _tmp202 - _tmp137 * _tmp201;
  const Scalar _tmp204 = _tmp198 * _tmp203;
  const Scalar _tmp205 = _tmp144 * _tmp153 - _tmp148 * _tmp154 + _tmp153 * _tmp204;
  const Scalar _tmp206 =
      _tmp172 * _tmp180 - _tmp175 * _tmp181 + _tmp180 * _tmp204 - _tmp183 * _tmp205;
  const Scalar _tmp207 = Scalar(1.0) / (_tmp206);
  const Scalar _tmp208 = Scalar(1.0) * _tmp207;
  const Scalar _tmp209 = _tmp183 * _tmp208;
  const Scalar _tmp210 = -_tmp153 * _tmp209 + _tmp180 * _tmp208;
  const Scalar _tmp211 = _tmp57 + Scalar(1.9874742000000001);
  const Scalar _tmp212 = _tmp48 + Scalar(8.3196563700000006);
  const Scalar _tmp213 = std::pow(_tmp211, Scalar(2)) + std::pow(_tmp212, Scalar(2));
  const Scalar _tmp214 = std::pow(_tmp213, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp215 = _tmp214 * _tmp47;
  const Scalar _tmp216 = _tmp212 * _tmp214;
  const Scalar _tmp217 = fh1 * (-_tmp211 * _tmp215 + _tmp216 * _tmp56);
  const Scalar _tmp218 = _tmp198 * _tmp217;
  const Scalar _tmp219 = Scalar(1.0) * _tmp156;
  const Scalar _tmp220 = Scalar(1.0) * _tmp162;
  const Scalar _tmp221 = _tmp163 * _tmp220;
  const Scalar _tmp222 = _tmp156 * _tmp221;
  const Scalar _tmp223 = _tmp171 * _tmp222 - _tmp187 * _tmp219;
  const Scalar _tmp224 = _tmp189 * _tmp223;
  const Scalar _tmp225 = -_tmp205 * _tmp219 - _tmp206 * _tmp224;
  const Scalar _tmp226 = _tmp188 * _tmp207;
  const Scalar _tmp227 = _tmp225 * _tmp226;
  const Scalar _tmp228 = _tmp223 + _tmp227;
  const Scalar _tmp229 = _tmp189 * _tmp228;
  const Scalar _tmp230 = -_tmp182 * _tmp229 + Scalar(1.0);
  const Scalar _tmp231 = _tmp157 * _tmp230 + _tmp180 * _tmp229;
  const Scalar _tmp232 = _tmp216 * fh1;
  const Scalar _tmp233 = _tmp198 * _tmp232;
  const Scalar _tmp234 = _tmp143 * _tmp156;
  const Scalar _tmp235 = _tmp143 * _tmp167;
  const Scalar _tmp236 = _tmp171 * _tmp234 + _tmp235;
  const Scalar _tmp237 = -_tmp164 * _tmp236 - _tmp167 + _tmp187 * _tmp234;
  const Scalar _tmp238 = _tmp189 * _tmp206;
  const Scalar _tmp239 = -_tmp204 + _tmp205 * _tmp234 - _tmp237 * _tmp238;
  const Scalar _tmp240 = _tmp226 * _tmp239;
  const Scalar _tmp241 = _tmp237 + _tmp240;
  const Scalar _tmp242 = _tmp189 * _tmp241;
  const Scalar _tmp243 = -_tmp143 - _tmp182 * _tmp242;
  const Scalar _tmp244 = _tmp157 * _tmp243 + _tmp180 * _tmp242 + Scalar(1.0);
  const Scalar _tmp245 = _tmp214 * fh1;
  const Scalar _tmp246 = _tmp211 * _tmp245;
  const Scalar _tmp247 = _tmp198 * _tmp246;
  const Scalar _tmp248 =
      -_tmp193 * _tmp199 - _tmp210 * _tmp218 - _tmp231 * _tmp233 - _tmp244 * _tmp247;
  const Scalar _tmp249 = Scalar(1.0) / (_tmp248);
  const Scalar _tmp250 = _tmp160 + _tmp172;
  const Scalar _tmp251 = _tmp164 * _tmp250;
  const Scalar _tmp252 = _tmp158 - _tmp175 - _tmp251;
  const Scalar _tmp253 = Scalar(1.0) / (_tmp252);
  const Scalar _tmp254 = _tmp250 * _tmp253;
  const Scalar _tmp255 = _tmp171 * _tmp219;
  const Scalar _tmp256 = -_tmp186 * _tmp229 + _tmp227 * _tmp254 - _tmp255;
  const Scalar _tmp257 = Scalar(1.0) * _tmp253;
  const Scalar _tmp258 = -_tmp220 * _tmp256 + _tmp227 * _tmp257;
  const Scalar _tmp259 = Scalar(1.0) * _tmp258;
  const Scalar _tmp260 = _tmp186 * _tmp189;
  const Scalar _tmp261 = _tmp236 + _tmp240 * _tmp254 - _tmp241 * _tmp260;
  const Scalar _tmp262 = -_tmp220 * _tmp261 + _tmp240 * _tmp257;
  const Scalar _tmp263 = Scalar(1.0) * _tmp246;
  const Scalar _tmp264 = _tmp246 * _tmp36 + Scalar(3.29616) * _tmp53 + _tmp56 * fv1;
  const Scalar _tmp265 = _tmp162 * _tmp257;
  const Scalar _tmp266 = Scalar(1.0) * _tmp250 * _tmp265 - Scalar(1.0) * _tmp257;
  const Scalar _tmp267 = _tmp165 * _tmp253;
  const Scalar _tmp268 = _tmp160 - _tmp166 * _tmp260 - _tmp250 * _tmp267;
  const Scalar _tmp269 = Scalar(1.0) * _tmp194;
  const Scalar _tmp270 = _tmp226 * _tmp257;
  const Scalar _tmp271 = -_tmp186 * _tmp208 + _tmp250 * _tmp270;
  const Scalar _tmp272 = -Scalar(1.0) * _tmp220 * _tmp271 + Scalar(1.0) * _tmp270;
  const Scalar _tmp273 = _tmp251 * _tmp257 + Scalar(1.0);
  const Scalar _tmp274 = _tmp164 * _tmp257;
  const Scalar _tmp275 = -_tmp220 * _tmp273 + _tmp274;
  const Scalar _tmp276 = -_tmp232 * _tmp36 - Scalar(3.29616) * _tmp41 - _tmp47 * fv1;
  const Scalar _tmp277 = Scalar(1.0) * _tmp276;
  const Scalar _tmp278 =
      _tmp217 * _tmp272 + _tmp232 * _tmp259 + _tmp262 * _tmp263 + _tmp264 * _tmp266 +
      _tmp269 * (-_tmp165 * _tmp257 - _tmp220 * _tmp268 + Scalar(1.0)) + _tmp275 * _tmp277;
  const Scalar _tmp279 = std::asinh(_tmp249 * _tmp278);
  const Scalar _tmp280 = Scalar(9.6622558468725703) * _tmp248;
  const Scalar _tmp281 = -_tmp141 + Scalar(-8.3888750099999996);
  const Scalar _tmp282 = Scalar(2.5202214700000001) - _tmp136;
  const Scalar _tmp283 = std::pow(_tmp281, Scalar(2)) + std::pow(_tmp282, Scalar(2));
  const Scalar _tmp284 = std::sqrt(_tmp283);
  const Scalar _tmp285 = -_tmp279 * _tmp280 - _tmp284;
  const Scalar _tmp286 = Scalar(0.1034955) * _tmp249;
  const Scalar _tmp287 = _tmp285 * _tmp286;
  const Scalar _tmp288 = std::pow(_tmp248, Scalar(-2));
  const Scalar _tmp289 = -_tmp101 + _tmp103 + _tmp97 - _tmp99;
  const Scalar _tmp290 = _tmp121 + _tmp289;
  const Scalar _tmp291 = -_tmp126 - _tmp127 - _tmp128 - _tmp129;
  const Scalar _tmp292 = _tmp123 + _tmp291;
  const Scalar _tmp293 = _tmp125 + _tmp292;
  const Scalar _tmp294 =
      (2 * _tmp146 * _tmp290 + 2 * _tmp150 * _tmp293) / (_tmp151 * std::sqrt(_tmp151));
  const Scalar _tmp295 = (Scalar(1) / Scalar(2)) * _tmp294;
  const Scalar _tmp296 = _tmp146 * _tmp295;
  const Scalar _tmp297 = -_tmp116 - _tmp118;
  const Scalar _tmp298 = _tmp114 + _tmp297;
  const Scalar _tmp299 = _tmp292 + _tmp298;
  const Scalar _tmp300 = _tmp299 / _tmp195;
  const Scalar _tmp301 = _tmp197 * _tmp300;
  const Scalar _tmp302 = _tmp203 * _tmp301;
  const Scalar _tmp303 = _tmp106 + _tmp108;
  const Scalar _tmp304 = _tmp120 + _tmp303;
  const Scalar _tmp305 = _tmp289 + _tmp304;
  const Scalar _tmp306 = _tmp137 * _tmp299 + _tmp142 * _tmp305;
  const Scalar _tmp307 = _tmp138 * _tmp200 * _tmp306;
  const Scalar _tmp308 = _tmp203 * _tmp307;
  const Scalar _tmp309 = _tmp150 * _tmp295;
  const Scalar _tmp310 = _tmp152 * _tmp293;
  const Scalar _tmp311 = _tmp152 * _tmp290;
  const Scalar _tmp312 = _tmp200 * _tmp305;
  const Scalar _tmp313 = _tmp306 / (_tmp196 * std::sqrt(_tmp196));
  const Scalar _tmp314 =
      _tmp198 * (-_tmp135 * _tmp142 * _tmp313 + _tmp135 * _tmp312 + _tmp137 * _tmp140 * _tmp313 -
                 _tmp137 * _tmp312 - _tmp201 * _tmp299 + _tmp202 * _tmp299);
  const Scalar _tmp315 = -_tmp144 * _tmp309 + _tmp144 * _tmp310 + _tmp148 * _tmp296 -
                         _tmp148 * _tmp311 + _tmp150 * _tmp311 - _tmp153 * _tmp302 +
                         _tmp153 * _tmp308 + _tmp153 * _tmp314 - _tmp154 * _tmp293 -
                         _tmp204 * _tmp309 + _tmp204 * _tmp310;
  const Scalar _tmp316 = _tmp106 + _tmp122;
  const Scalar _tmp317 = _tmp291 + _tmp316;
  const Scalar _tmp318 = _tmp125 + _tmp317;
  const Scalar _tmp319 = _tmp124 + _tmp297;
  const Scalar _tmp320 = _tmp109 + _tmp319;
  const Scalar _tmp321 = _tmp289 + _tmp320;
  const Scalar _tmp322 =
      (2 * _tmp174 * _tmp321 + 2 * _tmp177 * _tmp318) / (_tmp178 * std::sqrt(_tmp178));
  const Scalar _tmp323 = (Scalar(1) / Scalar(2)) * _tmp322;
  const Scalar _tmp324 = _tmp174 * _tmp323;
  const Scalar _tmp325 = _tmp142 * _tmp300;
  const Scalar _tmp326 = _tmp138 * _tmp305;
  const Scalar _tmp327 = (-_tmp143 * _tmp309 + _tmp143 * _tmp310 - _tmp153 * _tmp325 +
                          _tmp153 * _tmp326 + _tmp296 - _tmp311) /
                         std::pow(_tmp155, Scalar(2));
  const Scalar _tmp328 = _tmp182 * _tmp327;
  const Scalar _tmp329 = _tmp177 * _tmp323;
  const Scalar _tmp330 = _tmp179 * _tmp321;
  const Scalar _tmp331 = _tmp179 * _tmp318;
  const Scalar _tmp332 = -_tmp143 * _tmp329 + _tmp143 * _tmp331 - _tmp180 * _tmp325 +
                         _tmp180 * _tmp326 + _tmp324 - _tmp330;
  const Scalar _tmp333 = _tmp156 * _tmp332;
  const Scalar _tmp334 = -_tmp172 * _tmp329 + _tmp172 * _tmp331 + _tmp175 * _tmp324 -
                         _tmp175 * _tmp330 + _tmp177 * _tmp330 - _tmp180 * _tmp302 +
                         _tmp180 * _tmp308 + _tmp180 * _tmp314 - _tmp181 * _tmp318 -
                         _tmp183 * _tmp315 - _tmp204 * _tmp329 + _tmp204 * _tmp331 +
                         _tmp205 * _tmp328 - _tmp205 * _tmp333;
  const Scalar _tmp335 = Scalar(0.83999999999999997) * _tmp110;
  const Scalar _tmp336 = Scalar(0.83999999999999997) * _tmp112;
  const Scalar _tmp337 =
      -Scalar(0.83999999999999997) * _tmp115 - Scalar(0.83999999999999997) * _tmp117;
  const Scalar _tmp338 = _tmp335 + _tmp336 + _tmp337;
  const Scalar _tmp339 = -Scalar(1.6799999999999999) * _tmp105;
  const Scalar _tmp340 = _tmp339 - Scalar(1.6799999999999999) * _tmp71;
  const Scalar _tmp341 = _tmp340 / std::pow(_tmp161, Scalar(2));
  const Scalar _tmp342 = _tmp163 * _tmp341;
  const Scalar _tmp343 = Scalar(1.0) * _tmp327;
  const Scalar _tmp344 = -_tmp91 - _tmp92 - _tmp93 - _tmp94;
  const Scalar _tmp345 = _tmp72 + _tmp75;
  const Scalar _tmp346 = _tmp344 + _tmp345;
  const Scalar _tmp347 = _tmp346 + _tmp88;
  const Scalar _tmp348 = _tmp153 * _tmp347;
  const Scalar _tmp349 = _tmp345 + _tmp95;
  const Scalar _tmp350 = _tmp349 + _tmp88;
  const Scalar _tmp351 = _tmp167 * _tmp310;
  const Scalar _tmp352 = -_tmp153 * _tmp350 - _tmp167 * _tmp309 + _tmp170 * _tmp309 -
                         _tmp170 * _tmp310 + _tmp348 + _tmp351;
  const Scalar _tmp353 = _tmp167 * _tmp326;
  const Scalar _tmp354 = -_tmp143 * _tmp348 - _tmp143 * _tmp351 - _tmp153 * _tmp353 +
                         _tmp154 * _tmp350 + _tmp168 * _tmp325 - _tmp170 * _tmp296 +
                         _tmp170 * _tmp311 + _tmp235 * _tmp309;
  const Scalar _tmp355 = _tmp156 * _tmp171 * _tmp220 * _tmp338 - _tmp171 * _tmp221 * _tmp327 +
                         _tmp187 * _tmp343 - _tmp219 * _tmp352 + _tmp222 * _tmp354 -
                         _tmp255 * _tmp342;
  const Scalar _tmp356 = _tmp167 * _tmp331;
  const Scalar _tmp357 = _tmp180 * _tmp347;
  const Scalar _tmp358 = _tmp80 - _tmp82 - _tmp85 + _tmp87;
  const Scalar _tmp359 = _tmp349 + _tmp358;
  const Scalar _tmp360 = _tmp162 * _tmp338;
  const Scalar _tmp361 = -_tmp143 * _tmp356 - _tmp143 * _tmp357 + _tmp171 * _tmp328 -
                         _tmp171 * _tmp333 + _tmp181 * _tmp359 - _tmp183 * _tmp354 +
                         _tmp184 * _tmp325 - _tmp184 * _tmp326 - _tmp185 * _tmp324 +
                         _tmp185 * _tmp330 + _tmp235 * _tmp329;
  const Scalar _tmp362 = -_tmp164 * _tmp361 - _tmp167 * _tmp329 - _tmp180 * _tmp359 -
                         _tmp183 * _tmp352 + _tmp185 * _tmp329 - _tmp185 * _tmp331 +
                         _tmp186 * _tmp342 - _tmp186 * _tmp360 + _tmp187 * _tmp328 -
                         _tmp187 * _tmp333 + _tmp356 + _tmp357;
  const Scalar _tmp363 = _tmp362 / std::pow(_tmp188, Scalar(2));
  const Scalar _tmp364 = _tmp206 * _tmp363;
  const Scalar _tmp365 = _tmp226 * (_tmp205 * _tmp343 - _tmp219 * _tmp315 + _tmp223 * _tmp364 -
                                    _tmp224 * _tmp334 - _tmp238 * _tmp355);
  const Scalar _tmp366 = _tmp207 * _tmp362;
  const Scalar _tmp367 = _tmp225 * _tmp366;
  const Scalar _tmp368 = _tmp334 / std::pow(_tmp206, Scalar(2));
  const Scalar _tmp369 = _tmp188 * _tmp368;
  const Scalar _tmp370 = _tmp225 * _tmp369;
  const Scalar _tmp371 = _tmp355 + _tmp365 + _tmp367 - _tmp370;
  const Scalar _tmp372 = _tmp180 * _tmp189;
  const Scalar _tmp373 = _tmp182 * _tmp363;
  const Scalar _tmp374 = -_tmp190 * _tmp371 + _tmp228 * _tmp373 - _tmp229 * _tmp332;
  const Scalar _tmp375 = _tmp156 * _tmp230;
  const Scalar _tmp376 = _tmp153 * _tmp327;
  const Scalar _tmp377 = _tmp180 * _tmp363;
  const Scalar _tmp378 = _tmp156 * _tmp310;
  const Scalar _tmp379 = _tmp298 + _tmp317;
  const Scalar _tmp380 = _tmp303 + _tmp319;
  const Scalar _tmp381 = _tmp289 + _tmp380;
  const Scalar _tmp382 =
      (2 * _tmp211 * _tmp379 + 2 * _tmp212 * _tmp381) / (_tmp213 * std::sqrt(_tmp213));
  const Scalar _tmp383 = (Scalar(1) / Scalar(2)) * _tmp382;
  const Scalar _tmp384 = _tmp212 * _tmp383;
  const Scalar _tmp385 = _tmp214 * _tmp381;
  const Scalar _tmp386 = _tmp211 * _tmp383;
  const Scalar _tmp387 = fh1 * (-_tmp211 * _tmp385 - _tmp215 * _tmp379 + _tmp216 * _tmp379 -
                                _tmp384 * _tmp56 + _tmp385 * _tmp56 + _tmp386 * _tmp47);
  const Scalar _tmp388 = _tmp193 * _tmp194;
  const Scalar _tmp389 = _tmp153 * _tmp333;
  const Scalar _tmp390 = _tmp153 * _tmp183;
  const Scalar _tmp391 = _tmp210 * _tmp217;
  const Scalar _tmp392 = _tmp231 * _tmp232;
  const Scalar _tmp393 = _tmp198 * _tmp231;
  const Scalar _tmp394 = _tmp384 * fh1;
  const Scalar _tmp395 = _tmp156 * _tmp243;
  const Scalar _tmp396 = _tmp143 * _tmp327;
  const Scalar _tmp397 = _tmp156 * _tmp325;
  const Scalar _tmp398 = _tmp156 * _tmp326;
  const Scalar _tmp399 = _tmp143 * _tmp347 - _tmp167 * _tmp325 - _tmp171 * _tmp396 -
                         _tmp171 * _tmp397 + _tmp171 * _tmp398 + _tmp234 * _tmp354 + _tmp353;
  const Scalar _tmp400 = _tmp358 + _tmp76;
  const Scalar _tmp401 = _tmp400 + _tmp95;
  const Scalar _tmp402 = -_tmp164 * _tmp399 - _tmp187 * _tmp396 - _tmp187 * _tmp397 +
                         _tmp187 * _tmp398 + _tmp234 * _tmp352 + _tmp236 * _tmp342 -
                         _tmp236 * _tmp360 + _tmp401;
  const Scalar _tmp403 =
      _tmp226 *
      (-_tmp189 * _tmp237 * _tmp334 - _tmp205 * _tmp396 - _tmp205 * _tmp397 + _tmp205 * _tmp398 +
       _tmp234 * _tmp315 + _tmp237 * _tmp364 - _tmp238 * _tmp402 + _tmp302 - _tmp308 - _tmp314);
  const Scalar _tmp404 = _tmp239 * _tmp369;
  const Scalar _tmp405 = _tmp239 * _tmp366;
  const Scalar _tmp406 = _tmp402 + _tmp403 - _tmp404 + _tmp405;
  const Scalar _tmp407 =
      -_tmp190 * _tmp406 + _tmp241 * _tmp373 - _tmp242 * _tmp332 + _tmp325 - _tmp326;
  const Scalar _tmp408 = _tmp245 * _tmp379;
  const Scalar _tmp409 = _tmp198 * _tmp244;
  const Scalar _tmp410 = _tmp385 * fh1;
  const Scalar _tmp411 = Scalar(1.0) * _tmp368;
  const Scalar _tmp412 = Scalar(0.5) * _tmp207;
  const Scalar _tmp413 = _tmp386 * fh1;
  const Scalar _tmp414 = _tmp244 * _tmp246;
  const Scalar _tmp415 =
      -_tmp198 * _tmp210 * _tmp387 -
      _tmp199 * (_tmp156 * _tmp191 * _tmp309 + _tmp166 * _tmp363 * _tmp390 - _tmp166 * _tmp377 +
                 _tmp191 * _tmp376 - _tmp191 * _tmp378 - _tmp192 * _tmp329 + _tmp192 * _tmp331 -
                 _tmp192 * _tmp389) -
      _tmp218 * (_tmp150 * _tmp183 * _tmp294 * _tmp412 + _tmp153 * _tmp208 * _tmp328 -
                 _tmp177 * _tmp322 * _tmp412 - _tmp180 * _tmp411 + _tmp208 * _tmp331 -
                 _tmp208 * _tmp389 - _tmp209 * _tmp310 + _tmp390 * _tmp411) -
      _tmp233 * (_tmp157 * _tmp374 - _tmp228 * _tmp377 - _tmp229 * _tmp329 + _tmp229 * _tmp331 -
                 _tmp230 * _tmp376 + _tmp230 * _tmp378 - _tmp309 * _tmp375 + _tmp371 * _tmp372) -
      _tmp247 * (_tmp157 * _tmp407 - _tmp241 * _tmp377 - _tmp242 * _tmp329 + _tmp242 * _tmp331 -
                 _tmp243 * _tmp376 + _tmp243 * _tmp378 - _tmp309 * _tmp395 + _tmp372 * _tmp406) +
      _tmp301 * _tmp388 + _tmp301 * _tmp391 + _tmp301 * _tmp392 + _tmp301 * _tmp414 -
      _tmp307 * _tmp388 - _tmp307 * _tmp391 - _tmp307 * _tmp392 - _tmp307 * _tmp414 +
      _tmp393 * _tmp394 - _tmp393 * _tmp410 - _tmp408 * _tmp409 + _tmp409 * _tmp413;
  const Scalar _tmp416 = _tmp288 * _tmp415;
  const Scalar _tmp417 = _tmp104 + _tmp320;
  const Scalar _tmp418 = 2 * _tmp281 * _tmp417 + 2 * _tmp282 * (_tmp131 + _tmp316);
  const Scalar _tmp419 = _tmp250 * _tmp342;
  const Scalar _tmp420 = -_tmp335 - _tmp336 + _tmp337 + _tmp340;
  const Scalar _tmp421 = _tmp164 * _tmp420;
  const Scalar _tmp422 = _tmp250 * _tmp360;
  const Scalar _tmp423 =
      (_tmp338 + _tmp339 + _tmp419 - _tmp421 - _tmp422 - Scalar(1.6799999999999999) * _tmp74) /
      std::pow(_tmp252, Scalar(2));
  const Scalar _tmp424 = Scalar(1.0) * _tmp423;
  const Scalar _tmp425 = _tmp226 * _tmp424;
  const Scalar _tmp426 = _tmp257 * _tmp366;
  const Scalar _tmp427 = _tmp257 * _tmp369;
  const Scalar _tmp428 = _tmp186 * _tmp411 - _tmp208 * _tmp361 - _tmp250 * _tmp425 +
                         _tmp250 * _tmp426 - _tmp250 * _tmp427 + _tmp270 * _tmp420;
  const Scalar _tmp429 = Scalar(1.0) * _tmp341;
  const Scalar _tmp430 = Scalar(0.5) * _tmp382 * fh1;
  const Scalar _tmp431 = _tmp250 * _tmp423;
  const Scalar _tmp432 =
      -_tmp221 * _tmp431 - _tmp257 * _tmp419 + _tmp257 * _tmp421 + _tmp257 * _tmp422;
  const Scalar _tmp433 = _tmp221 * _tmp423;
  const Scalar _tmp434 = _tmp257 * _tmp360;
  const Scalar _tmp435 = Scalar(6.59232) * _tmp16;
  const Scalar _tmp436 = Scalar(6.59232) * _tmp83;
  const Scalar _tmp437 = _tmp36 * fh1;
  const Scalar _tmp438 = Scalar(6.59232) * _tmp24;
  const Scalar _tmp439 = _tmp346 + _tmp358;
  const Scalar _tmp440 = -_tmp21 * _tmp436 - _tmp232 * _tmp439 - _tmp36 * _tmp410 - _tmp381 * fv1 +
                         _tmp384 * _tmp437 - _tmp435 * _tmp73 + _tmp438 * _tmp70 +
                         Scalar(6.59232) * _tmp90;
  const Scalar _tmp441 = _tmp12 * _tmp436 + _tmp246 * _tmp439 + _tmp36 * _tmp408 + _tmp379 * fv1 -
                         _tmp386 * _tmp437 + _tmp435 * _tmp70 + _tmp438 * _tmp73 +
                         Scalar(6.59232) * _tmp79;
  const Scalar _tmp442 = _tmp250 * _tmp341;
  const Scalar _tmp443 = _tmp220 * _tmp431;
  const Scalar _tmp444 = -_tmp159 * _tmp342 + _tmp159 * _tmp360 + _tmp221 * _tmp305 + _tmp299;
  const Scalar _tmp445 = _tmp165 * _tmp423;
  const Scalar _tmp446 = _tmp253 * _tmp444;
  const Scalar _tmp447 = _tmp186 * _tmp363;
  const Scalar _tmp448 = _tmp166 * _tmp447 - _tmp192 * _tmp361 + _tmp250 * _tmp445 -
                         _tmp250 * _tmp446 - _tmp267 * _tmp420 + _tmp417;
  const Scalar _tmp449 = _tmp253 * _tmp420;
  const Scalar _tmp450 = _tmp171 * _tmp343 - _tmp219 * _tmp354 - _tmp227 * _tmp431 +
                         _tmp227 * _tmp449 + _tmp228 * _tmp447 - _tmp229 * _tmp361 +
                         _tmp254 * _tmp365 + _tmp254 * _tmp367 - _tmp254 * _tmp370 -
                         _tmp260 * _tmp371;
  const Scalar _tmp451 = -_tmp240 * _tmp431 + _tmp240 * _tmp449 + _tmp241 * _tmp447 -
                         _tmp242 * _tmp361 + _tmp254 * _tmp403 - _tmp254 * _tmp404 +
                         _tmp254 * _tmp405 - _tmp260 * _tmp406 + _tmp399;
  const Scalar _tmp452 =
      (_tmp249 *
           (-_tmp211 * _tmp262 * _tmp430 - _tmp212 * _tmp258 * _tmp430 +
            Scalar(1.0) * _tmp217 *
                (-_tmp220 * _tmp428 + _tmp271 * _tmp429 - _tmp425 + _tmp426 - _tmp427) +
            Scalar(1.0) * _tmp232 *
                (-_tmp220 * _tmp450 - _tmp227 * _tmp424 + _tmp256 * _tmp429 + _tmp257 * _tmp365 +
                 _tmp257 * _tmp367 - _tmp257 * _tmp370) +
            _tmp259 * _tmp410 + Scalar(1.0) * _tmp262 * _tmp408 +
            _tmp263 * (-_tmp220 * _tmp451 - _tmp240 * _tmp424 + _tmp257 * _tmp403 -
                       _tmp257 * _tmp404 + _tmp257 * _tmp405 + _tmp261 * _tmp429) +
            Scalar(1.0) * _tmp264 * (-_tmp257 * _tmp442 + _tmp265 * _tmp420 + _tmp424 - _tmp443) +
            _tmp266 * _tmp441 +
            _tmp269 *
                (_tmp165 * _tmp424 - _tmp220 * _tmp448 - _tmp257 * _tmp444 + _tmp268 * _tmp429) +
            _tmp272 * _tmp387 + Scalar(1.0) * _tmp275 * _tmp440 +
            _tmp277 *
                (-_tmp220 * _tmp432 - _tmp257 * _tmp342 + _tmp273 * _tmp429 - _tmp433 + _tmp434)) -
       _tmp278 * _tmp416) /
      std::sqrt(Scalar(std::pow(_tmp278, Scalar(2)) * _tmp288 + 1));
  const Scalar _tmp453 = Scalar(9.6622558468725703) * _tmp415;
  const Scalar _tmp454 = Scalar(1.0) * _tmp279;
  const Scalar _tmp455 = -_tmp167 - p_init2 + Scalar(8.4693136199999994);
  const Scalar _tmp456 = _tmp156 * _tmp232;
  const Scalar _tmp457 = _tmp166 * _tmp194;
  const Scalar _tmp458 = _tmp190 * _tmp457;
  const Scalar _tmp459 = _tmp208 * _tmp217;
  const Scalar _tmp460 =
      -_tmp156 * _tmp458 - _tmp183 * _tmp459 + _tmp230 * _tmp456 + _tmp246 * _tmp395;
  const Scalar _tmp461 = Scalar(1.0) / (_tmp460);
  const Scalar _tmp462 = _tmp162 * _tmp271;
  const Scalar _tmp463 = _tmp257 * _tmp264;
  const Scalar _tmp464 = _tmp162 * _tmp250;
  const Scalar _tmp465 = _tmp162 * _tmp256;
  const Scalar _tmp466 = _tmp162 * _tmp276;
  const Scalar _tmp467 = _tmp162 * _tmp194;
  const Scalar _tmp468 = _tmp162 * _tmp246;
  const Scalar _tmp469 = _tmp217 * _tmp462 + _tmp232 * _tmp465 + _tmp261 * _tmp468 +
                         _tmp268 * _tmp467 + _tmp273 * _tmp466 - _tmp463 * _tmp464;
  const Scalar _tmp470 = std::asinh(_tmp461 * _tmp469);
  const Scalar _tmp471 = Scalar(1.0) * _tmp470;
  const Scalar _tmp472 = _tmp162 * _tmp261;
  const Scalar _tmp473 = _tmp276 * _tmp341;
  const Scalar _tmp474 = _tmp257 * _tmp441;
  const Scalar _tmp475 = std::pow(_tmp460, Scalar(-2));
  const Scalar _tmp476 = _tmp363 * _tmp457;
  const Scalar _tmp477 = _tmp217 * _tmp411;
  const Scalar _tmp478 = _tmp192 * _tmp194;
  const Scalar _tmp479 = _tmp208 * _tmp387;
  const Scalar _tmp480 =
      _tmp156 * _tmp246 * _tmp407 + _tmp183 * _tmp476 + _tmp183 * _tmp477 - _tmp183 * _tmp479 -
      _tmp230 * _tmp232 * _tmp327 - _tmp243 * _tmp246 * _tmp327 + _tmp327 * _tmp458 +
      _tmp328 * _tmp459 - _tmp333 * _tmp459 - _tmp333 * _tmp478 + _tmp374 * _tmp456 -
      _tmp375 * _tmp394 + _tmp375 * _tmp410 + _tmp395 * _tmp408 - _tmp395 * _tmp413;
  const Scalar _tmp481 = _tmp475 * _tmp480;
  const Scalar _tmp482 =
      (_tmp461 * (_tmp162 * _tmp217 * _tmp428 + _tmp162 * _tmp232 * _tmp450 +
                  _tmp162 * _tmp273 * _tmp440 - _tmp162 * _tmp420 * _tmp463 -
                  _tmp194 * _tmp268 * _tmp341 - _tmp217 * _tmp271 * _tmp341 -
                  _tmp232 * _tmp256 * _tmp341 - _tmp246 * _tmp261 * _tmp341 + _tmp264 * _tmp443 -
                  _tmp273 * _tmp473 + _tmp387 * _tmp462 - _tmp394 * _tmp465 + _tmp408 * _tmp472 +
                  _tmp410 * _tmp465 - _tmp413 * _tmp472 + _tmp432 * _tmp466 + _tmp442 * _tmp463 +
                  _tmp448 * _tmp467 + _tmp451 * _tmp468 - _tmp464 * _tmp474) -
       _tmp469 * _tmp481) /
      std::sqrt(Scalar(std::pow(_tmp469, Scalar(2)) * _tmp475 + 1));
  const Scalar _tmp483 = Scalar(9.6622558468725703) * _tmp460;
  const Scalar _tmp484 = Scalar(4.7752063900000001) - _tmp145;
  const Scalar _tmp485 = Scalar(2.71799795) - _tmp149;
  const Scalar _tmp486 = std::pow(_tmp484, Scalar(2)) + std::pow(_tmp485, Scalar(2));
  const Scalar _tmp487 = std::sqrt(_tmp486);
  const Scalar _tmp488 = -_tmp470 * _tmp483 - _tmp487;
  const Scalar _tmp489 = Scalar(0.1034955) * _tmp461;
  const Scalar _tmp490 = _tmp488 * _tmp489;
  const Scalar _tmp491 = _tmp130 + _tmp298;
  const Scalar _tmp492 = 2 * _tmp484 * (_tmp104 + _tmp380) + 2 * _tmp485 * (_tmp316 + _tmp491);
  const Scalar _tmp493 = Scalar(9.6622558468725703) * _tmp480;
  const Scalar _tmp494 = -_tmp170 - p_init2 + Scalar(8.36416322);
  const Scalar _tmp495 = -_tmp185 - p_init2 + Scalar(8.3700199099999999);
  const Scalar _tmp496 = Scalar(4.8333311099999996) - _tmp173;
  const Scalar _tmp497 = -_tmp176 + Scalar(-1.79662371);
  const Scalar _tmp498 = 2 * _tmp496 * (_tmp104 + _tmp304) + 2 * _tmp497 * (_tmp123 + _tmp491);
  const Scalar _tmp499 = std::pow(_tmp496, Scalar(2)) + std::pow(_tmp497, Scalar(2));
  const Scalar _tmp500 = std::sqrt(_tmp499);
  const Scalar _tmp501 = _tmp232 * _tmp253;
  const Scalar _tmp502 = _tmp246 * _tmp253;
  const Scalar _tmp503 = _tmp194 * _tmp267 - _tmp217 * _tmp270 - _tmp227 * _tmp501 -
                         _tmp240 * _tmp502 - _tmp274 * _tmp276 + _tmp463;
  const Scalar _tmp504 = _tmp229 * _tmp232 + _tmp242 * _tmp246 + _tmp459 + _tmp478;
  const Scalar _tmp505 = Scalar(1.0) / (_tmp504);
  const Scalar _tmp506 = std::asinh(_tmp503 * _tmp505);
  const Scalar _tmp507 = _tmp189 * _tmp232 * _tmp371 + _tmp189 * _tmp246 * _tmp406 -
                         _tmp228 * _tmp232 * _tmp363 - _tmp229 * _tmp394 + _tmp229 * _tmp410 -
                         _tmp241 * _tmp246 * _tmp363 + _tmp242 * _tmp408 - _tmp242 * _tmp413 -
                         _tmp476 - _tmp477 + _tmp479;
  const Scalar _tmp508 = Scalar(9.6622558468725703) * _tmp507;
  const Scalar _tmp509 = Scalar(9.6622558468725703) * _tmp504;
  const Scalar _tmp510 = _tmp227 * _tmp253;
  const Scalar _tmp511 = _tmp240 * _tmp253;
  const Scalar _tmp512 = std::pow(_tmp504, Scalar(-2));
  const Scalar _tmp513 = _tmp507 * _tmp512;
  const Scalar _tmp514 =
      (-_tmp503 * _tmp513 +
       _tmp505 * (_tmp163 * _tmp257 * _tmp473 - _tmp194 * _tmp445 + _tmp194 * _tmp446 +
                  _tmp217 * _tmp425 - _tmp217 * _tmp426 + _tmp217 * _tmp427 +
                  _tmp227 * _tmp232 * _tmp423 + _tmp240 * _tmp246 * _tmp423 - _tmp264 * _tmp424 -
                  _tmp270 * _tmp387 - _tmp274 * _tmp440 + _tmp276 * _tmp433 - _tmp276 * _tmp434 -
                  _tmp365 * _tmp501 - _tmp367 * _tmp501 + _tmp370 * _tmp501 + _tmp394 * _tmp510 -
                  _tmp403 * _tmp502 + _tmp404 * _tmp502 - _tmp405 * _tmp502 - _tmp408 * _tmp511 -
                  _tmp410 * _tmp510 + _tmp413 * _tmp511 + _tmp474)) /
      std::sqrt(Scalar(std::pow(_tmp503, Scalar(2)) * _tmp512 + 1));
  const Scalar _tmp515 = Scalar(0.1034955) * _tmp505;
  const Scalar _tmp516 = -_tmp500 - _tmp506 * _tmp509;
  const Scalar _tmp517 = _tmp515 * _tmp516;
  const Scalar _tmp518 = Scalar(1.0) * _tmp506;

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) =
      Scalar(0.5) * _tmp132 *
          std::cosh(Scalar(0.1034955) * _tmp134 *
                    (-_tmp133 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp134 * fv1))) /
          _tmp133 -
      Scalar(1) / Scalar(2) * (_tmp132 + 2 * _tmp37 * (_tmp89 + _tmp95)) /
          std::sqrt(Scalar(std::pow(_tmp37, Scalar(2)) + _tmp59));
  _res(1, 0) = _tmp280 * (-Scalar(1.0) * _tmp452 * std::cosh(_tmp454) -
                          (-Scalar(0.1034955) * _tmp285 * _tmp416 +
                           _tmp286 * (-_tmp279 * _tmp453 - _tmp280 * _tmp452 -
                                      Scalar(1) / Scalar(2) * _tmp418 / _tmp284)) *
                              std::cosh(_tmp287)) +
               _tmp453 * (-std::sinh(_tmp287) - std::sinh(_tmp454)) -
               Scalar(1) / Scalar(2) * (2 * _tmp401 * _tmp455 + _tmp418) /
                   std::sqrt(Scalar(_tmp283 + std::pow(_tmp455, Scalar(2))));
  _res(2, 0) = _tmp483 * (-Scalar(1.0) * _tmp482 * std::cosh(_tmp471) -
                          (-Scalar(0.1034955) * _tmp481 * _tmp488 +
                           _tmp489 * (-_tmp470 * _tmp493 - _tmp482 * _tmp483 -
                                      Scalar(1) / Scalar(2) * _tmp492 / _tmp487)) *
                              std::cosh(_tmp490)) +
               _tmp493 * (-std::sinh(_tmp471) - std::sinh(_tmp490)) -
               Scalar(1) / Scalar(2) * (_tmp492 + 2 * _tmp494 * (_tmp344 + _tmp400)) /
                   std::sqrt(Scalar(_tmp486 + std::pow(_tmp494, Scalar(2))));
  _res(3, 0) = _tmp508 * (-std::sinh(_tmp517) - std::sinh(_tmp518)) +
               _tmp509 * (-Scalar(1.0) * _tmp514 * std::cosh(_tmp518) -
                          (-Scalar(0.1034955) * _tmp513 * _tmp516 +
                           _tmp515 * (-Scalar(1) / Scalar(2) * _tmp498 / _tmp500 -
                                      _tmp506 * _tmp508 - _tmp509 * _tmp514)) *
                              std::cosh(_tmp517)) -
               Scalar(1) / Scalar(2) * (2 * _tmp495 * (_tmp344 + _tmp89) + _tmp498) /
                   std::sqrt(Scalar(std::pow(_tmp495, Scalar(2)) + _tmp499));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
