// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost3_wrt_rz_Nl1
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     rx: Scalar
 *     ry: Scalar
 *     rz: Scalar
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost3WrtRzNl1(
    const Scalar fh1, const Scalar fv1, const Scalar rx, const Scalar ry, const Scalar rz,
    const Scalar p_init0, const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x,
    const Scalar rot_init_y, const Scalar rot_init_z, const Scalar rot_init_w,
    const Scalar epsilon) {
  // Total ops: 985

  // Unused inputs
  (void)p_init2;
  (void)epsilon;

  // Input arrays

  // Intermediate terms (318)
  const Scalar _tmp0 = std::pow(rz, Scalar(2));
  const Scalar _tmp1 = _tmp0 + std::pow(rx, Scalar(2)) + std::pow(ry, Scalar(2));
  const Scalar _tmp2 = std::sqrt(_tmp1);
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = std::cos(_tmp3);
  const Scalar _tmp5 = _tmp4 * rot_init_y;
  const Scalar _tmp6 = std::sin(_tmp3);
  const Scalar _tmp7 = _tmp6 / _tmp2;
  const Scalar _tmp8 = _tmp7 * rot_init_w;
  const Scalar _tmp9 = _tmp7 * rot_init_z;
  const Scalar _tmp10 = _tmp7 * rot_init_x;
  const Scalar _tmp11 = _tmp10 * rz;
  const Scalar _tmp12 = -_tmp11 + _tmp5 + _tmp8 * ry + _tmp9 * rx;
  const Scalar _tmp13 = _tmp4 * rot_init_x;
  const Scalar _tmp14 = _tmp7 * rot_init_y;
  const Scalar _tmp15 = _tmp14 * rz;
  const Scalar _tmp16 = _tmp13 + _tmp15 + _tmp8 * rx - _tmp9 * ry;
  const Scalar _tmp17 = 2 * _tmp12 * _tmp16;
  const Scalar _tmp18 = _tmp4 * rot_init_z;
  const Scalar _tmp19 = _tmp8 * rz;
  const Scalar _tmp20 = _tmp10 * ry - _tmp14 * rx + _tmp18 + _tmp19;
  const Scalar _tmp21 = _tmp4 * rot_init_w;
  const Scalar _tmp22 = _tmp9 * rz;
  const Scalar _tmp23 = -_tmp10 * rx - _tmp14 * ry + _tmp21 - _tmp22;
  const Scalar _tmp24 = 2 * _tmp23;
  const Scalar _tmp25 = _tmp20 * _tmp24;
  const Scalar _tmp26 = Scalar(0.20999999999999999) * _tmp17 + Scalar(0.20999999999999999) * _tmp25;
  const Scalar _tmp27 = -_tmp26;
  const Scalar _tmp28 = -2 * std::pow(_tmp20, Scalar(2));
  const Scalar _tmp29 = 1 - 2 * std::pow(_tmp16, Scalar(2));
  const Scalar _tmp30 = Scalar(0.20999999999999999) * _tmp28 + Scalar(0.20999999999999999) * _tmp29;
  const Scalar _tmp31 = 2 * _tmp20;
  const Scalar _tmp32 = _tmp12 * _tmp31;
  const Scalar _tmp33 = _tmp16 * _tmp24;
  const Scalar _tmp34 =
      -Scalar(0.010999999999999999) * _tmp32 + Scalar(0.010999999999999999) * _tmp33;
  const Scalar _tmp35 = -_tmp30 + _tmp34;
  const Scalar _tmp36 = _tmp27 + _tmp35;
  const Scalar _tmp37 = _tmp36 + p_init1 + Scalar(8.3196563700000006);
  const Scalar _tmp38 = Scalar(0.20999999999999999) * _tmp17 - Scalar(0.20999999999999999) * _tmp25;
  const Scalar _tmp39 = -_tmp38;
  const Scalar _tmp40 = -2 * std::pow(_tmp12, Scalar(2));
  const Scalar _tmp41 = Scalar(0.20999999999999999) * _tmp28 +
                        Scalar(0.20999999999999999) * _tmp40 + Scalar(0.20999999999999999);
  const Scalar _tmp42 = _tmp16 * _tmp31;
  const Scalar _tmp43 = _tmp12 * _tmp24;
  const Scalar _tmp44 =
      -Scalar(0.010999999999999999) * _tmp42 - Scalar(0.010999999999999999) * _tmp43;
  const Scalar _tmp45 = -_tmp41 + _tmp44;
  const Scalar _tmp46 = _tmp39 + _tmp45;
  const Scalar _tmp47 = _tmp46 + p_init0 + Scalar(1.9874742000000001);
  const Scalar _tmp48 = std::pow(_tmp37, Scalar(2)) + std::pow(_tmp47, Scalar(2));
  const Scalar _tmp49 = std::pow(_tmp48, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp50 = _tmp37 * _tmp49;
  const Scalar _tmp51 = _tmp41 + _tmp44;
  const Scalar _tmp52 = _tmp39 + _tmp51;
  const Scalar _tmp53 = _tmp52 + p_init0 + Scalar(-2.5202214700000001);
  const Scalar _tmp54 = Scalar(1.0) / (_tmp53);
  const Scalar _tmp55 = _tmp26 + _tmp35;
  const Scalar _tmp56 = _tmp55 + p_init1 + Scalar(8.3888750099999996);
  const Scalar _tmp57 = _tmp54 * _tmp56;
  const Scalar _tmp58 =
      -Scalar(0.010999999999999999) * _tmp29 - Scalar(0.010999999999999999) * _tmp40;
  const Scalar _tmp59 = Scalar(0.20999999999999999) * _tmp32 + Scalar(0.20999999999999999) * _tmp33;
  const Scalar _tmp60 = Scalar(0.20999999999999999) * _tmp42 - Scalar(0.20999999999999999) * _tmp43;
  const Scalar _tmp61 = _tmp58 - _tmp59 + _tmp60;
  const Scalar _tmp62 = _tmp30 + _tmp34;
  const Scalar _tmp63 = _tmp27 + _tmp62;
  const Scalar _tmp64 = _tmp63 + p_init1 + Scalar(-4.8333311099999996);
  const Scalar _tmp65 = _tmp38 + _tmp45;
  const Scalar _tmp66 = _tmp65 + p_init0 + Scalar(1.79662371);
  const Scalar _tmp67 = std::pow(_tmp64, Scalar(2)) + std::pow(_tmp66, Scalar(2));
  const Scalar _tmp68 = std::pow(_tmp67, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp69 = _tmp66 * _tmp68;
  const Scalar _tmp70 = _tmp61 * _tmp69;
  const Scalar _tmp71 = _tmp58 + _tmp59;
  const Scalar _tmp72 = -_tmp60 + _tmp71;
  const Scalar _tmp73 = _tmp64 * _tmp68;
  const Scalar _tmp74 = -_tmp57 * _tmp70 + _tmp72 * _tmp73;
  const Scalar _tmp75 = Scalar(1.0) * _tmp55;
  const Scalar _tmp76 = _tmp63 - _tmp75;
  const Scalar _tmp77 = Scalar(1.0) / (_tmp76);
  const Scalar _tmp78 = Scalar(1.0) * _tmp52;
  const Scalar _tmp79 = -_tmp65 + _tmp78;
  const Scalar _tmp80 = _tmp77 * _tmp79;
  const Scalar _tmp81 = _tmp57 * _tmp69 - _tmp73;
  const Scalar _tmp82 = Scalar(1.0) / (_tmp81);
  const Scalar _tmp83 = Scalar(1.0) * _tmp82;
  const Scalar _tmp84 = _tmp80 * _tmp83;
  const Scalar _tmp85 = -_tmp69 * _tmp72 + _tmp70;
  const Scalar _tmp86 = _tmp74 * _tmp84 - _tmp83 * _tmp85;
  const Scalar _tmp87 = _tmp26 + _tmp62;
  const Scalar _tmp88 = _tmp87 + p_init1 + Scalar(-4.7752063900000001);
  const Scalar _tmp89 = _tmp38 + _tmp51;
  const Scalar _tmp90 = _tmp89 + p_init0 + Scalar(-2.71799795);
  const Scalar _tmp91 = std::pow(_tmp88, Scalar(2)) + std::pow(_tmp90, Scalar(2));
  const Scalar _tmp92 = std::pow(_tmp91, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp93 = _tmp90 * _tmp92;
  const Scalar _tmp94 = _tmp88 * _tmp92;
  const Scalar _tmp95 = _tmp57 * _tmp93 - _tmp94;
  const Scalar _tmp96 = _tmp82 * _tmp95;
  const Scalar _tmp97 = _tmp61 * _tmp93;
  const Scalar _tmp98 = _tmp60 + _tmp71;
  const Scalar _tmp99 = -_tmp57 * _tmp97 - _tmp74 * _tmp96 + _tmp94 * _tmp98;
  const Scalar _tmp100 = -_tmp80 * _tmp99 - _tmp85 * _tmp96 - _tmp93 * _tmp98 + _tmp97;
  const Scalar _tmp101 = Scalar(1.0) / (_tmp100);
  const Scalar _tmp102 = std::pow(_tmp53, Scalar(2));
  const Scalar _tmp103 = _tmp102 + std::pow(_tmp56, Scalar(2));
  const Scalar _tmp104 = std::sqrt(_tmp103);
  const Scalar _tmp105 = Scalar(1.0) / (_tmp104);
  const Scalar _tmp106 = _tmp105 * _tmp53;
  const Scalar _tmp107 = _tmp105 * _tmp56;
  const Scalar _tmp108 = -_tmp106 * _tmp55 + _tmp107 * _tmp52;
  const Scalar _tmp109 = _tmp104 * _tmp54;
  const Scalar _tmp110 = _tmp108 * _tmp109;
  const Scalar _tmp111 = _tmp110 * _tmp69 + _tmp63 * _tmp69 - _tmp65 * _tmp73;
  const Scalar _tmp112 = _tmp110 * _tmp93 - _tmp111 * _tmp96 + _tmp87 * _tmp93 - _tmp89 * _tmp94;
  const Scalar _tmp113 = _tmp101 * _tmp112;
  const Scalar _tmp114 = -_tmp111 * _tmp83 - _tmp113 * _tmp86;
  const Scalar _tmp115 = Scalar(1.0) / (_tmp112);
  const Scalar _tmp116 = _tmp100 * _tmp115;
  const Scalar _tmp117 = _tmp114 * _tmp116 + _tmp86;
  const Scalar _tmp118 = _tmp101 * _tmp95;
  const Scalar _tmp119 = -_tmp117 * _tmp118 + Scalar(1.0);
  const Scalar _tmp120 = _tmp69 * _tmp82;
  const Scalar _tmp121 = _tmp101 * _tmp93;
  const Scalar _tmp122 = _tmp117 * _tmp121 + _tmp119 * _tmp120;
  const Scalar _tmp123 = _tmp109 * fh1;
  const Scalar _tmp124 = _tmp122 * _tmp123;
  const Scalar _tmp125 = Scalar(1.0) * _tmp115;
  const Scalar _tmp126 = _tmp125 * _tmp69;
  const Scalar _tmp127 = _tmp125 * _tmp93 - _tmp126 * _tmp96;
  const Scalar _tmp128 = _tmp47 * _tmp49;
  const Scalar _tmp129 = _tmp46 * _tmp49;
  const Scalar _tmp130 = fh1 * (-_tmp128 * _tmp36 + _tmp129 * _tmp37);
  const Scalar _tmp131 = _tmp109 * _tmp130;
  const Scalar _tmp132 = _tmp57 * _tmp61;
  const Scalar _tmp133 = _tmp57 * _tmp82;
  const Scalar _tmp134 = _tmp132 + _tmp133 * _tmp74;
  const Scalar _tmp135 = _tmp133 * _tmp85 - _tmp134 * _tmp80 - _tmp61;
  const Scalar _tmp136 = -_tmp110 + _tmp111 * _tmp133 - _tmp113 * _tmp135;
  const Scalar _tmp137 = _tmp116 * _tmp136 + _tmp135;
  const Scalar _tmp138 = -_tmp118 * _tmp137 - _tmp57;
  const Scalar _tmp139 = _tmp120 * _tmp138 + _tmp121 * _tmp137 + Scalar(1.0);
  const Scalar _tmp140 = _tmp123 * _tmp139;
  const Scalar _tmp141 = _tmp75 * _tmp80 + _tmp78;
  const Scalar _tmp142 = 0;
  const Scalar _tmp143 = _tmp101 * _tmp142;
  const Scalar _tmp144 = _tmp143 * _tmp69;
  const Scalar _tmp145 = _tmp143 * _tmp93 - _tmp144 * _tmp96;
  const Scalar _tmp146 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp147 = _tmp109 * _tmp146;
  const Scalar _tmp148 = (Scalar(1) / Scalar(2)) / _tmp1;
  const Scalar _tmp149 = _tmp0 * _tmp148;
  const Scalar _tmp150 = _tmp148 * rz;
  const Scalar _tmp151 = _tmp150 * ry;
  const Scalar _tmp152 = _tmp150 * rx;
  const Scalar _tmp153 = _tmp6 / (_tmp1 * std::sqrt(_tmp1));
  const Scalar _tmp154 = _tmp0 * _tmp153;
  const Scalar _tmp155 = _tmp153 * rz;
  const Scalar _tmp156 = _tmp155 * rot_init_x;
  const Scalar _tmp157 = _tmp155 * ry;
  const Scalar _tmp158 = -_tmp13 * _tmp152 - _tmp149 * _tmp18 - _tmp151 * _tmp5 +
                         _tmp154 * rot_init_z + _tmp156 * rx + _tmp157 * rot_init_y -
                         Scalar(1) / Scalar(2) * _tmp19 - _tmp9;
  const Scalar _tmp159 = _tmp158 * _tmp20;
  const Scalar _tmp160 = Scalar(0.41999999999999998) * _tmp159;
  const Scalar _tmp161 = _tmp155 * rx;
  const Scalar _tmp162 = _tmp13 * _tmp151 + _tmp149 * _tmp21 - _tmp152 * _tmp5 -
                         _tmp154 * rot_init_w - _tmp156 * ry + _tmp161 * rot_init_y -
                         Scalar(1) / Scalar(2) * _tmp22 + _tmp8;
  const Scalar _tmp163 = Scalar(0.41999999999999998) * _tmp162;
  const Scalar _tmp164 = _tmp163 * _tmp23;
  const Scalar _tmp165 = _tmp160 + _tmp164;
  const Scalar _tmp166 = Scalar(0.83999999999999997) * _tmp162;
  const Scalar _tmp167 = _tmp166 * _tmp20;
  const Scalar _tmp168 = -_tmp167;
  const Scalar _tmp169 = -Scalar(1) / Scalar(2) * _tmp11 + _tmp14 + _tmp149 * _tmp5 -
                         _tmp151 * _tmp18 + _tmp152 * _tmp21 - _tmp154 * rot_init_y +
                         _tmp157 * rot_init_z - _tmp161 * rot_init_w;
  const Scalar _tmp170 = Scalar(0.41999999999999998) * _tmp169;
  const Scalar _tmp171 = _tmp12 * _tmp170;
  const Scalar _tmp172 = -_tmp10 - _tmp13 * _tmp149 - Scalar(1) / Scalar(2) * _tmp15 +
                         _tmp151 * _tmp21 + _tmp152 * _tmp18 + _tmp154 * rot_init_x -
                         _tmp157 * rot_init_w - _tmp161 * rot_init_z;
  const Scalar _tmp173 = Scalar(0.41999999999999998) * _tmp172;
  const Scalar _tmp174 = _tmp16 * _tmp173;
  const Scalar _tmp175 = -_tmp171 - _tmp174;
  const Scalar _tmp176 = _tmp168 + _tmp175;
  const Scalar _tmp177 = Scalar(0.83999999999999997) * _tmp172;
  const Scalar _tmp178 = _tmp12 * _tmp177;
  const Scalar _tmp179 = Scalar(0.021999999999999999) * _tmp12;
  const Scalar _tmp180 = Scalar(0.021999999999999999) * _tmp20;
  const Scalar _tmp181 = Scalar(0.021999999999999999) * _tmp16;
  const Scalar _tmp182 = Scalar(0.021999999999999999) * _tmp23;
  const Scalar _tmp183 =
      -_tmp158 * _tmp179 - _tmp162 * _tmp181 - _tmp169 * _tmp180 - _tmp172 * _tmp182;
  const Scalar _tmp184 = -_tmp178 + _tmp183;
  const Scalar _tmp185 = _tmp165 + _tmp176 + _tmp184;
  const Scalar _tmp186 = _tmp171 + _tmp174;
  const Scalar _tmp187 = _tmp165 + _tmp167;
  const Scalar _tmp188 = Scalar(0.83999999999999997) * _tmp169;
  const Scalar _tmp189 = _tmp16 * _tmp188;
  const Scalar _tmp190 =
      _tmp158 * _tmp181 - _tmp162 * _tmp179 + _tmp169 * _tmp182 - _tmp172 * _tmp180;
  const Scalar _tmp191 = _tmp189 + _tmp190;
  const Scalar _tmp192 = _tmp186 + _tmp187 + _tmp191;
  const Scalar _tmp193 = _tmp185 * _tmp53 + _tmp192 * _tmp56;
  const Scalar _tmp194 = _tmp105 * _tmp193 * _tmp54;
  const Scalar _tmp195 = _tmp128 * fh1;
  const Scalar _tmp196 = _tmp139 * _tmp195;
  const Scalar _tmp197 = -_tmp160 - _tmp164;
  const Scalar _tmp198 = _tmp167 + _tmp197;
  const Scalar _tmp199 = _tmp178 + _tmp183;
  const Scalar _tmp200 = _tmp186 + _tmp198 + _tmp199;
  const Scalar _tmp201 = -_tmp189 + _tmp190;
  const Scalar _tmp202 = _tmp176 + _tmp197 + _tmp201;
  const Scalar _tmp203 =
      (2 * _tmp200 * _tmp66 + 2 * _tmp202 * _tmp64) / (_tmp67 * std::sqrt(_tmp67));
  const Scalar _tmp204 = (Scalar(1) / Scalar(2)) * _tmp203;
  const Scalar _tmp205 = _tmp204 * _tmp66;
  const Scalar _tmp206 = _tmp205 * _tmp82;
  const Scalar _tmp207 = _tmp168 + _tmp186;
  const Scalar _tmp208 = _tmp165 + _tmp201 + _tmp207;
  const Scalar _tmp209 = _tmp184 + _tmp197 + _tmp207;
  const Scalar _tmp210 =
      (2 * _tmp208 * _tmp88 + 2 * _tmp209 * _tmp90) / (_tmp91 * std::sqrt(_tmp91));
  const Scalar _tmp211 = (Scalar(1) / Scalar(2)) * _tmp210;
  const Scalar _tmp212 = _tmp211 * _tmp88;
  const Scalar _tmp213 = _tmp204 * _tmp64;
  const Scalar _tmp214 = _tmp202 * _tmp68;
  const Scalar _tmp215 = _tmp185 / _tmp102;
  const Scalar _tmp216 = _tmp104 * _tmp215;
  const Scalar _tmp217 = _tmp108 * _tmp216;
  const Scalar _tmp218 = _tmp200 * _tmp68;
  const Scalar _tmp219 = _tmp193 / (_tmp103 * std::sqrt(_tmp103));
  const Scalar _tmp220 =
      _tmp109 * (-_tmp105 * _tmp185 * _tmp55 + _tmp105 * _tmp192 * _tmp52 - _tmp106 * _tmp192 +
                 _tmp107 * _tmp185 - _tmp219 * _tmp52 * _tmp56 + _tmp219 * _tmp53 * _tmp55);
  const Scalar _tmp221 = _tmp108 * _tmp194;
  const Scalar _tmp222 = -_tmp110 * _tmp205 + _tmp110 * _tmp218 - _tmp200 * _tmp73 -
                         _tmp205 * _tmp63 + _tmp213 * _tmp65 - _tmp214 * _tmp65 + _tmp214 * _tmp66 -
                         _tmp217 * _tmp69 + _tmp218 * _tmp63 + _tmp220 * _tmp69 + _tmp221 * _tmp69;
  const Scalar _tmp223 = _tmp211 * _tmp90;
  const Scalar _tmp224 = _tmp209 * _tmp92;
  const Scalar _tmp225 = _tmp208 * _tmp92;
  const Scalar _tmp226 = _tmp215 * _tmp56;
  const Scalar _tmp227 = _tmp192 * _tmp54;
  const Scalar _tmp228 =
      _tmp212 - _tmp223 * _tmp57 + _tmp224 * _tmp57 - _tmp225 - _tmp226 * _tmp93 + _tmp227 * _tmp93;
  const Scalar _tmp229 = _tmp228 * _tmp82;
  const Scalar _tmp230 = (-_tmp205 * _tmp57 + _tmp213 - _tmp214 + _tmp218 * _tmp57 -
                          _tmp226 * _tmp69 + _tmp227 * _tmp69) /
                         std::pow(_tmp81, Scalar(2));
  const Scalar _tmp231 = _tmp230 * _tmp95;
  const Scalar _tmp232 = -_tmp110 * _tmp223 + _tmp110 * _tmp224 - _tmp111 * _tmp229 +
                         _tmp111 * _tmp231 - _tmp209 * _tmp94 + _tmp212 * _tmp89 -
                         _tmp217 * _tmp93 + _tmp220 * _tmp93 + _tmp221 * _tmp93 - _tmp222 * _tmp96 -
                         _tmp223 * _tmp87 + _tmp224 * _tmp87 - _tmp225 * _tmp89 + _tmp225 * _tmp90;
  const Scalar _tmp233 = _tmp232 / std::pow(_tmp112, Scalar(2));
  const Scalar _tmp234 = _tmp100 * _tmp233;
  const Scalar _tmp235 = Scalar(1.0) * _tmp230;
  const Scalar _tmp236 = _tmp218 * _tmp61;
  const Scalar _tmp237 = Scalar(0.41999999999999998) * _tmp158;
  const Scalar _tmp238 = _tmp16 * _tmp237;
  const Scalar _tmp239 = _tmp173 * _tmp20;
  const Scalar _tmp240 = _tmp12 * _tmp163;
  const Scalar _tmp241 = _tmp170 * _tmp23;
  const Scalar _tmp242 = _tmp12 * _tmp237;
  const Scalar _tmp243 = _tmp170 * _tmp20;
  const Scalar _tmp244 = _tmp16 * _tmp163;
  const Scalar _tmp245 = _tmp173 * _tmp23;
  const Scalar _tmp246 = _tmp16 * _tmp169;
  const Scalar _tmp247 = Scalar(0.043999999999999997) * _tmp246;
  const Scalar _tmp248 = _tmp12 * _tmp172;
  const Scalar _tmp249 = Scalar(0.043999999999999997) * _tmp248;
  const Scalar _tmp250 = _tmp247 + _tmp249;
  const Scalar _tmp251 = -_tmp242 + _tmp243 + _tmp244 - _tmp245 + _tmp250;
  const Scalar _tmp252 = -_tmp238 - _tmp239 - _tmp240 - _tmp241 + _tmp251;
  const Scalar _tmp253 = _tmp252 * _tmp69;
  const Scalar _tmp254 = _tmp238 + _tmp239 + _tmp240 + _tmp241;
  const Scalar _tmp255 = _tmp242 - _tmp243 - _tmp244 + _tmp245 + _tmp254;
  const Scalar _tmp256 = _tmp250 + _tmp255;
  const Scalar _tmp257 = -_tmp205 * _tmp61 + _tmp205 * _tmp72 - _tmp218 * _tmp72 + _tmp236 +
                         _tmp253 - _tmp256 * _tmp69;
  const Scalar _tmp258 = Scalar(0.83999999999999997) * _tmp159;
  const Scalar _tmp259 = _tmp166 * _tmp23;
  const Scalar _tmp260 =
      -_tmp12 * _tmp188 - _tmp16 * _tmp177 - Scalar(1.6799999999999999) * _tmp162 * _tmp20;
  const Scalar _tmp261 =
      _tmp77 * (-Scalar(1.6799999999999999) * _tmp248 + _tmp258 + _tmp259 + _tmp260);
  const Scalar _tmp262 = _tmp79 *
                         (-Scalar(1.6799999999999999) * _tmp246 - _tmp258 - _tmp259 + _tmp260) /
                         std::pow(_tmp76, Scalar(2));
  const Scalar _tmp263 = _tmp251 + _tmp254;
  const Scalar _tmp264 = _tmp224 * _tmp61;
  const Scalar _tmp265 = _tmp252 * _tmp57;
  const Scalar _tmp266 = _tmp132 * _tmp205 - _tmp213 * _tmp72 + _tmp214 * _tmp72 +
                         _tmp226 * _tmp70 - _tmp227 * _tmp70 - _tmp236 * _tmp57 - _tmp253 * _tmp57 +
                         _tmp256 * _tmp73;
  const Scalar _tmp267 =
      -_tmp223 * _tmp61 + _tmp223 * _tmp98 - _tmp224 * _tmp98 - _tmp229 * _tmp85 +
      _tmp231 * _tmp85 + _tmp252 * _tmp93 - _tmp257 * _tmp96 - _tmp261 * _tmp99 + _tmp262 * _tmp99 -
      _tmp263 * _tmp93 + _tmp264 -
      _tmp80 * (_tmp132 * _tmp223 - _tmp212 * _tmp98 + _tmp225 * _tmp98 + _tmp226 * _tmp97 -
                _tmp227 * _tmp97 - _tmp229 * _tmp74 + _tmp231 * _tmp74 + _tmp263 * _tmp94 -
                _tmp264 * _tmp57 - _tmp265 * _tmp93 - _tmp266 * _tmp96);
  const Scalar _tmp268 = _tmp267 / std::pow(_tmp100, Scalar(2));
  const Scalar _tmp269 = _tmp112 * _tmp268;
  const Scalar _tmp270 = _tmp74 * _tmp83;
  const Scalar _tmp271 = -_tmp235 * _tmp74 * _tmp80 + _tmp235 * _tmp85 - _tmp257 * _tmp83 +
                         _tmp261 * _tmp270 - _tmp262 * _tmp270 + _tmp266 * _tmp84;
  const Scalar _tmp272 = _tmp101 * _tmp232;
  const Scalar _tmp273 = _tmp115 * _tmp267;
  const Scalar _tmp274 = -_tmp114 * _tmp234 + _tmp114 * _tmp273 +
                         _tmp116 * (_tmp111 * _tmp235 - _tmp113 * _tmp271 - _tmp222 * _tmp83 +
                                    _tmp269 * _tmp86 - _tmp272 * _tmp86) +
                         _tmp271;
  const Scalar _tmp275 = _tmp230 * _tmp69;
  const Scalar _tmp276 = _tmp268 * _tmp93;
  const Scalar _tmp277 = _tmp101 * _tmp224;
  const Scalar _tmp278 = _tmp218 * _tmp82;
  const Scalar _tmp279 = _tmp101 * _tmp223;
  const Scalar _tmp280 = _tmp101 * _tmp228;
  const Scalar _tmp281 = _tmp268 * _tmp95;
  const Scalar _tmp282 = -_tmp117 * _tmp280 + _tmp117 * _tmp281 - _tmp118 * _tmp274;
  const Scalar _tmp283 = _tmp127 * _tmp130;
  const Scalar _tmp284 = _tmp227 * _tmp82;
  const Scalar _tmp285 = _tmp230 * _tmp57;
  const Scalar _tmp286 = _tmp226 * _tmp82;
  const Scalar _tmp287 =
      _tmp133 * _tmp257 - _tmp134 * _tmp261 + _tmp134 * _tmp262 - _tmp247 - _tmp249 + _tmp255 +
      _tmp284 * _tmp85 - _tmp285 * _tmp85 - _tmp286 * _tmp85 -
      _tmp80 * (_tmp133 * _tmp266 - _tmp226 * _tmp61 + _tmp227 * _tmp61 + _tmp265 +
                _tmp284 * _tmp74 - _tmp285 * _tmp74 - _tmp286 * _tmp74);
  const Scalar _tmp288 = _tmp116 * (_tmp111 * _tmp284 - _tmp111 * _tmp285 - _tmp111 * _tmp286 -
                                    _tmp113 * _tmp287 + _tmp133 * _tmp222 + _tmp135 * _tmp269 -
                                    _tmp135 * _tmp272 + _tmp217 - _tmp220 - _tmp221) -
                         _tmp136 * _tmp234 + _tmp136 * _tmp273 + _tmp287;
  const Scalar _tmp289 =
      -_tmp118 * _tmp288 - _tmp137 * _tmp280 + _tmp137 * _tmp281 + _tmp226 - _tmp227;
  const Scalar _tmp290 = _tmp145 * _tmp146;
  const Scalar _tmp291 = _tmp175 + _tmp187 + _tmp199;
  const Scalar _tmp292 = _tmp291 * _tmp49;
  const Scalar _tmp293 = _tmp175 + _tmp191 + _tmp198;
  const Scalar _tmp294 = (Scalar(1) / Scalar(2)) * (2 * _tmp291 * _tmp47 + 2 * _tmp293 * _tmp37) /
                         (_tmp48 * std::sqrt(_tmp48));
  const Scalar _tmp295 = _tmp294 * _tmp37;
  const Scalar _tmp296 = _tmp294 * _tmp47;
  const Scalar _tmp297 = fh1 * (-_tmp128 * _tmp293 + _tmp129 * _tmp293 - _tmp292 * _tmp36 +
                                _tmp292 * _tmp37 - _tmp295 * _tmp46 + _tmp296 * _tmp36);
  const Scalar _tmp298 = _tmp50 * fh1;
  const Scalar _tmp299 = _tmp122 * _tmp298;
  const Scalar _tmp300 = _tmp293 * _tmp49;
  const Scalar _tmp301 = Scalar(0.5) * _tmp115;
  const Scalar _tmp302 = Scalar(1.0) * _tmp233;
  const Scalar _tmp303 = _tmp69 * _tmp96;
  const Scalar _tmp304 = _tmp218 * _tmp96;
  const Scalar _tmp305 = _tmp142 * _tmp268;
  const Scalar _tmp306 = _tmp82 * fh1;
  const Scalar _tmp307 = _tmp119 * _tmp306;
  const Scalar _tmp308 = _tmp138 * _tmp306;
  const Scalar _tmp309 = _tmp125 * _tmp130;
  const Scalar _tmp310 = _tmp143 * _tmp146;
  const Scalar _tmp311 = _tmp125 * _tmp297;
  const Scalar _tmp312 = _tmp130 * _tmp302;
  const Scalar _tmp313 = _tmp146 * _tmp305;
  const Scalar _tmp314 = _tmp101 * fh1;
  const Scalar _tmp315 = _tmp117 * _tmp314;
  const Scalar _tmp316 = _tmp128 * _tmp314;
  const Scalar _tmp317 = _tmp137 * _tmp314;

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) = 0;
  _res(1, 0) =
      -(-_tmp109 * _tmp127 * _tmp297 -
        _tmp123 * _tmp128 *
            (_tmp120 * _tmp289 + _tmp121 * _tmp288 - _tmp137 * _tmp276 + _tmp137 * _tmp277 -
             _tmp137 * _tmp279 - _tmp138 * _tmp206 - _tmp138 * _tmp275 + _tmp138 * _tmp278) -
        _tmp123 * _tmp50 *
            (-_tmp117 * _tmp276 + _tmp117 * _tmp277 - _tmp117 * _tmp279 - _tmp119 * _tmp206 -
             _tmp119 * _tmp275 + _tmp119 * _tmp278 + _tmp120 * _tmp282 + _tmp121 * _tmp274) +
        _tmp124 * _tmp295 - _tmp124 * _tmp300 -
        _tmp131 * (_tmp125 * _tmp224 - _tmp125 * _tmp304 - _tmp126 * _tmp229 + _tmp126 * _tmp231 +
                   _tmp203 * _tmp301 * _tmp66 * _tmp96 - _tmp210 * _tmp301 * _tmp90 +
                   _tmp302 * _tmp303 - _tmp302 * _tmp93) -
        _tmp140 * _tmp292 + _tmp140 * _tmp296 -
        _tmp147 * (_tmp143 * _tmp205 * _tmp96 - _tmp143 * _tmp223 + _tmp143 * _tmp224 -
                   _tmp143 * _tmp304 - _tmp144 * _tmp229 + _tmp144 * _tmp231 + _tmp303 * _tmp305 -
                   _tmp305 * _tmp93) -
        _tmp194 * _tmp196 - _tmp194 * _tmp283 - _tmp194 * _tmp290 - _tmp194 * _tmp299 +
        _tmp196 * _tmp216 + _tmp216 * _tmp283 + _tmp216 * _tmp290 + _tmp216 * _tmp299) *
      std::exp(_tmp124 * _tmp50 + _tmp127 * _tmp131 + _tmp128 * _tmp140 + _tmp145 * _tmp147);
  _res(2, 0) =
      -(-_tmp119 * _tmp230 * _tmp298 + _tmp128 * _tmp289 * _tmp306 - _tmp138 * _tmp195 * _tmp230 -
        _tmp229 * _tmp309 - _tmp229 * _tmp310 + _tmp231 * _tmp309 + _tmp231 * _tmp310 +
        _tmp282 * _tmp306 * _tmp50 + _tmp292 * _tmp308 - _tmp295 * _tmp307 - _tmp296 * _tmp308 +
        _tmp300 * _tmp307 - _tmp311 * _tmp96 + _tmp312 * _tmp96 + _tmp313 * _tmp96) *
      std::exp(-_tmp128 * _tmp308 - _tmp307 * _tmp50 + _tmp309 * _tmp96 + _tmp310 * _tmp96);
  _res(3, 0) =
      -(-_tmp117 * _tmp268 * _tmp298 - _tmp137 * _tmp195 * _tmp268 + _tmp274 * _tmp314 * _tmp50 +
        _tmp288 * _tmp316 + _tmp292 * _tmp317 - _tmp295 * _tmp315 - _tmp296 * _tmp317 +
        _tmp300 * _tmp315 + _tmp311 - _tmp312 - _tmp313) *
      std::exp(-_tmp137 * _tmp316 - _tmp309 - _tmp310 - _tmp315 * _tmp50);

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
