// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost1_wrt_ry_Nl13
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     rx: Scalar
 *     ry: Scalar
 *     rz: Scalar
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost1WrtRyNl13(
    const Scalar fh1, const Scalar fv1, const Scalar rx, const Scalar ry, const Scalar rz,
    const Scalar p_init0, const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x,
    const Scalar rot_init_y, const Scalar rot_init_z, const Scalar rot_init_w,
    const Scalar epsilon) {
  // Total ops: 1626

  // Unused inputs
  (void)p_init2;
  (void)epsilon;

  // Input arrays

  // Intermediate terms (501)
  const Scalar _tmp0 = std::pow(ry, Scalar(2));
  const Scalar _tmp1 = _tmp0 + std::pow(rx, Scalar(2)) + std::pow(rz, Scalar(2));
  const Scalar _tmp2 = std::sqrt(_tmp1);
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = std::cos(_tmp3);
  const Scalar _tmp5 = _tmp4 * rot_init_x;
  const Scalar _tmp6 = std::sin(_tmp3);
  const Scalar _tmp7 = _tmp6 / _tmp2;
  const Scalar _tmp8 = _tmp7 * rot_init_z;
  const Scalar _tmp9 = _tmp8 * ry;
  const Scalar _tmp10 = _tmp7 * rot_init_w;
  const Scalar _tmp11 = _tmp7 * rot_init_y;
  const Scalar _tmp12 = _tmp10 * rx + _tmp11 * rz + _tmp5 - _tmp9;
  const Scalar _tmp13 = -2 * std::pow(_tmp12, Scalar(2));
  const Scalar _tmp14 = _tmp4 * rot_init_z;
  const Scalar _tmp15 = _tmp7 * rot_init_x;
  const Scalar _tmp16 = _tmp15 * ry;
  const Scalar _tmp17 = _tmp10 * rz - _tmp11 * rx + _tmp14 + _tmp16;
  const Scalar _tmp18 = -2 * std::pow(_tmp17, Scalar(2));
  const Scalar _tmp19 = Scalar(0.20999999999999999) * _tmp13 +
                        Scalar(0.20999999999999999) * _tmp18 + Scalar(0.20999999999999999);
  const Scalar _tmp20 = _tmp4 * rot_init_y;
  const Scalar _tmp21 = _tmp10 * ry;
  const Scalar _tmp22 = -_tmp15 * rz + _tmp20 + _tmp21 + _tmp8 * rx;
  const Scalar _tmp23 = 2 * _tmp17;
  const Scalar _tmp24 = _tmp22 * _tmp23;
  const Scalar _tmp25 = _tmp4 * rot_init_w;
  const Scalar _tmp26 = _tmp11 * ry;
  const Scalar _tmp27 = -_tmp15 * rx + _tmp25 - _tmp26 - _tmp8 * rz;
  const Scalar _tmp28 = 2 * _tmp27;
  const Scalar _tmp29 = _tmp12 * _tmp28;
  const Scalar _tmp30 = _tmp24 - _tmp29;
  const Scalar _tmp31 = -Scalar(0.010999999999999999) * _tmp30;
  const Scalar _tmp32 = 2 * _tmp12 * _tmp22;
  const Scalar _tmp33 = _tmp17 * _tmp28;
  const Scalar _tmp34 = Scalar(0.20999999999999999) * _tmp32 + Scalar(0.20999999999999999) * _tmp33;
  const Scalar _tmp35 = _tmp31 + _tmp34;
  const Scalar _tmp36 = _tmp19 + _tmp35;
  const Scalar _tmp37 = _tmp36 + p_init1;
  const Scalar _tmp38 = Scalar(4.7752063900000001) - _tmp37;
  const Scalar _tmp39 = 1 - 2 * std::pow(_tmp22, Scalar(2));
  const Scalar _tmp40 = Scalar(0.20999999999999999) * _tmp18 + Scalar(0.20999999999999999) * _tmp39;
  const Scalar _tmp41 = _tmp12 * _tmp23;
  const Scalar _tmp42 = _tmp22 * _tmp28;
  const Scalar _tmp43 = _tmp41 + _tmp42;
  const Scalar _tmp44 = -Scalar(0.010999999999999999) * _tmp43;
  const Scalar _tmp45 = Scalar(0.20999999999999999) * _tmp32 - Scalar(0.20999999999999999) * _tmp33;
  const Scalar _tmp46 = _tmp44 + _tmp45;
  const Scalar _tmp47 = _tmp40 + _tmp46;
  const Scalar _tmp48 = _tmp47 + p_init0;
  const Scalar _tmp49 = Scalar(2.71799795) - _tmp48;
  const Scalar _tmp50 =
      std::sqrt(Scalar(std::pow(_tmp38, Scalar(2)) + std::pow(_tmp49, Scalar(2))));
  const Scalar _tmp51 = Scalar(1.0) / (fh1);
  const Scalar _tmp52 = (Scalar(1) / Scalar(2)) / _tmp1;
  const Scalar _tmp53 = _tmp0 * _tmp52;
  const Scalar _tmp54 = _tmp52 * ry;
  const Scalar _tmp55 = _tmp54 * rz;
  const Scalar _tmp56 = _tmp54 * rx;
  const Scalar _tmp57 = _tmp6 / (_tmp1 * std::sqrt(_tmp1));
  const Scalar _tmp58 = _tmp0 * _tmp57;
  const Scalar _tmp59 = _tmp57 * ry;
  const Scalar _tmp60 = _tmp59 * rx;
  const Scalar _tmp61 = _tmp59 * rz;
  const Scalar _tmp62 = -_tmp14 * _tmp53 - Scalar(1) / Scalar(2) * _tmp16 + _tmp20 * _tmp55 +
                        _tmp25 * _tmp56 + _tmp58 * rot_init_z - _tmp60 * rot_init_w -
                        _tmp61 * rot_init_y - _tmp8;
  const Scalar _tmp63 = Scalar(0.021999999999999999) * _tmp27;
  const Scalar _tmp64 = _tmp62 * _tmp63;
  const Scalar _tmp65 = -_tmp11 - _tmp14 * _tmp55 - _tmp20 * _tmp53 -
                        Scalar(1) / Scalar(2) * _tmp21 - _tmp5 * _tmp56 + _tmp58 * rot_init_y +
                        _tmp60 * rot_init_x + _tmp61 * rot_init_z;
  const Scalar _tmp66 = Scalar(0.021999999999999999) * _tmp65;
  const Scalar _tmp67 = _tmp12 * _tmp66;
  const Scalar _tmp68 = _tmp15 - _tmp20 * _tmp56 + _tmp25 * _tmp55 + _tmp5 * _tmp53 -
                        _tmp58 * rot_init_x + _tmp60 * rot_init_y - _tmp61 * rot_init_w -
                        Scalar(1) / Scalar(2) * _tmp9;
  const Scalar _tmp69 = _tmp22 * _tmp68;
  const Scalar _tmp70 = Scalar(0.021999999999999999) * _tmp69;
  const Scalar _tmp71 = _tmp10 + _tmp14 * _tmp56 + _tmp25 * _tmp53 -
                        Scalar(1) / Scalar(2) * _tmp26 - _tmp5 * _tmp55 - _tmp58 * rot_init_w -
                        _tmp60 * rot_init_z + _tmp61 * rot_init_x;
  const Scalar _tmp72 = _tmp17 * _tmp71;
  const Scalar _tmp73 = Scalar(0.021999999999999999) * _tmp72;
  const Scalar _tmp74 = -_tmp64 - _tmp67 + _tmp70 + _tmp73;
  const Scalar _tmp75 = Scalar(0.41999999999999998) * _tmp12;
  const Scalar _tmp76 = _tmp71 * _tmp75;
  const Scalar _tmp77 = Scalar(0.41999999999999998) * _tmp62;
  const Scalar _tmp78 = _tmp22 * _tmp77;
  const Scalar _tmp79 = -_tmp76 - _tmp78;
  const Scalar _tmp80 = Scalar(0.41999999999999998) * _tmp27;
  const Scalar _tmp81 = _tmp68 * _tmp80;
  const Scalar _tmp82 = Scalar(0.41999999999999998) * _tmp65;
  const Scalar _tmp83 = _tmp17 * _tmp82;
  const Scalar _tmp84 = -_tmp81 - _tmp83;
  const Scalar _tmp85 = _tmp79 + _tmp84;
  const Scalar _tmp86 = Scalar(0.83999999999999997) * _tmp68;
  const Scalar _tmp87 = _tmp17 * _tmp86;
  const Scalar _tmp88 = Scalar(0.83999999999999997) * _tmp62;
  const Scalar _tmp89 = _tmp12 * _tmp88;
  const Scalar _tmp90 = _tmp87 + _tmp89;
  const Scalar _tmp91 = _tmp85 + _tmp90;
  const Scalar _tmp92 = _tmp81 + _tmp83;
  const Scalar _tmp93 = _tmp79 + _tmp92;
  const Scalar _tmp94 = _tmp63 * _tmp71;
  const Scalar _tmp95 = _tmp22 * _tmp66;
  const Scalar _tmp96 = _tmp12 * _tmp68;
  const Scalar _tmp97 = Scalar(0.021999999999999999) * _tmp96;
  const Scalar _tmp98 = Scalar(0.021999999999999999) * _tmp17 * _tmp62;
  const Scalar _tmp99 = _tmp94 + _tmp95 + _tmp97 + _tmp98;
  const Scalar _tmp100 = Scalar(0.83999999999999997) * _tmp71;
  const Scalar _tmp101 = _tmp100 * _tmp22;
  const Scalar _tmp102 = _tmp101 + _tmp87;
  const Scalar _tmp103 = _tmp102 + _tmp99;
  const Scalar _tmp104 = _tmp22 * _tmp71;
  const Scalar _tmp105 = Scalar(0.043999999999999997) * _tmp104;
  const Scalar _tmp106 = _tmp12 * _tmp62;
  const Scalar _tmp107 = Scalar(0.043999999999999997) * _tmp106;
  const Scalar _tmp108 = _tmp105 + _tmp107;
  const Scalar _tmp109 = _tmp27 * _tmp77;
  const Scalar _tmp110 = _tmp65 * _tmp75;
  const Scalar _tmp111 = Scalar(0.41999999999999998) * _tmp69;
  const Scalar _tmp112 = Scalar(0.41999999999999998) * _tmp72;
  const Scalar _tmp113 = _tmp109 + _tmp110 + _tmp111 + _tmp112;
  const Scalar _tmp114 = _tmp108 + _tmp113;
  const Scalar _tmp115 = _tmp71 * _tmp80;
  const Scalar _tmp116 = _tmp22 * _tmp82;
  const Scalar _tmp117 = _tmp68 * _tmp75;
  const Scalar _tmp118 = _tmp17 * _tmp77;
  const Scalar _tmp119 = -_tmp115 - _tmp116 + _tmp117 + _tmp118;
  const Scalar _tmp120 = _tmp114 + _tmp119;
  const Scalar _tmp121 =
      Scalar(0.20999999999999999) * _tmp24 + Scalar(0.20999999999999999) * _tmp29;
  const Scalar _tmp122 = -_tmp121;
  const Scalar _tmp123 =
      -Scalar(0.010999999999999999) * _tmp13 - Scalar(0.010999999999999999) * _tmp39;
  const Scalar _tmp124 =
      Scalar(0.20999999999999999) * _tmp41 - Scalar(0.20999999999999999) * _tmp42;
  const Scalar _tmp125 = _tmp123 + _tmp124;
  const Scalar _tmp126 = _tmp122 + _tmp125;
  const Scalar _tmp127 = _tmp44 - _tmp45;
  const Scalar _tmp128 = _tmp127 + _tmp40;
  const Scalar _tmp129 = _tmp128 + p_init0;
  const Scalar _tmp130 = _tmp129 + Scalar(-2.5202214700000001);
  const Scalar _tmp131 = -_tmp19;
  const Scalar _tmp132 = _tmp131 + _tmp35;
  const Scalar _tmp133 = _tmp132 + p_init1;
  const Scalar _tmp134 = _tmp133 + Scalar(8.3888750099999996);
  const Scalar _tmp135 = std::pow(_tmp130, Scalar(2)) + std::pow(_tmp134, Scalar(2));
  const Scalar _tmp136 = std::pow(_tmp135, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp137 = _tmp130 * _tmp136;
  const Scalar _tmp138 = _tmp134 * _tmp136;
  const Scalar _tmp139 = _tmp31 - _tmp34;
  const Scalar _tmp140 = _tmp131 + _tmp139;
  const Scalar _tmp141 = _tmp140 + p_init1;
  const Scalar _tmp142 = _tmp141 + Scalar(8.3196563700000006);
  const Scalar _tmp143 = -_tmp40;
  const Scalar _tmp144 = _tmp127 + _tmp143;
  const Scalar _tmp145 = _tmp144 + p_init0;
  const Scalar _tmp146 = _tmp145 + Scalar(1.9874742000000001);
  const Scalar _tmp147 = Scalar(1.0) / (_tmp146);
  const Scalar _tmp148 = _tmp142 * _tmp147;
  const Scalar _tmp149 = _tmp123 - _tmp124;
  const Scalar _tmp150 = _tmp122 + _tmp149;
  const Scalar _tmp151 = _tmp137 * _tmp150;
  const Scalar _tmp152 = _tmp139 + _tmp19;
  const Scalar _tmp153 = _tmp152 + p_init1;
  const Scalar _tmp154 = _tmp153 + Scalar(-4.8333311099999996);
  const Scalar _tmp155 = _tmp143 + _tmp46;
  const Scalar _tmp156 = _tmp155 + p_init0;
  const Scalar _tmp157 = _tmp156 + Scalar(1.79662371);
  const Scalar _tmp158 = std::pow(_tmp154, Scalar(2)) + std::pow(_tmp157, Scalar(2));
  const Scalar _tmp159 = std::pow(_tmp158, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp160 = _tmp157 * _tmp159;
  const Scalar _tmp161 = _tmp150 * _tmp160;
  const Scalar _tmp162 = _tmp121 + _tmp149;
  const Scalar _tmp163 = _tmp154 * _tmp159;
  const Scalar _tmp164 = -_tmp148 * _tmp161 + _tmp162 * _tmp163;
  const Scalar _tmp165 = _tmp137 * _tmp148 - _tmp138;
  const Scalar _tmp166 = _tmp148 * _tmp160 - _tmp163;
  const Scalar _tmp167 = Scalar(1.0) / (_tmp166);
  const Scalar _tmp168 = _tmp165 * _tmp167;
  const Scalar _tmp169 = _tmp126 * _tmp138 - _tmp148 * _tmp151 - _tmp164 * _tmp168;
  const Scalar _tmp170 = Scalar(1.0) * _tmp140;
  const Scalar _tmp171 = -_tmp170;
  const Scalar _tmp172 = _tmp152 + _tmp171;
  const Scalar _tmp173 = Scalar(1.0) / (_tmp172);
  const Scalar _tmp174 = Scalar(1.0) * _tmp144;
  const Scalar _tmp175 = -_tmp155 + _tmp174;
  const Scalar _tmp176 = _tmp173 * _tmp175;
  const Scalar _tmp177 = -_tmp160 * _tmp162 + _tmp161;
  const Scalar _tmp178 = -_tmp126 * _tmp137 + _tmp151 - _tmp168 * _tmp177 - _tmp169 * _tmp176;
  const Scalar _tmp179 = Scalar(1.0) / (_tmp178);
  const Scalar _tmp180 = _tmp170 * _tmp176 + _tmp174;
  const Scalar _tmp181 = 0;
  const Scalar _tmp182 = _tmp179 * _tmp181;
  const Scalar _tmp183 = _tmp160 * _tmp167;
  const Scalar _tmp184 = _tmp165 * _tmp179;
  const Scalar _tmp185 = _tmp181 * _tmp184;
  const Scalar _tmp186 = _tmp137 * _tmp182 - _tmp183 * _tmp185;
  const Scalar _tmp187 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp188 = std::pow(_tmp146, Scalar(2));
  const Scalar _tmp189 = std::pow(_tmp142, Scalar(2)) + _tmp188;
  const Scalar _tmp190 = std::sqrt(_tmp189);
  const Scalar _tmp191 = _tmp147 * _tmp190;
  const Scalar _tmp192 = _tmp187 * _tmp191;
  const Scalar _tmp193 = Scalar(1.0) / (_tmp190);
  const Scalar _tmp194 = _tmp140 * _tmp193;
  const Scalar _tmp195 = _tmp142 * _tmp144;
  const Scalar _tmp196 = -_tmp146 * _tmp194 + _tmp193 * _tmp195;
  const Scalar _tmp197 = _tmp191 * _tmp196;
  const Scalar _tmp198 = _tmp148 * _tmp167;
  const Scalar _tmp199 = _tmp148 * _tmp150;
  const Scalar _tmp200 = _tmp164 * _tmp198 + _tmp199;
  const Scalar _tmp201 = -_tmp150 - _tmp176 * _tmp200 + _tmp177 * _tmp198;
  const Scalar _tmp202 = _tmp152 * _tmp160 - _tmp155 * _tmp163 + _tmp160 * _tmp197;
  const Scalar _tmp203 = _tmp132 * _tmp136;
  const Scalar _tmp204 =
      -_tmp128 * _tmp138 + _tmp130 * _tmp203 + _tmp137 * _tmp197 - _tmp168 * _tmp202;
  const Scalar _tmp205 = _tmp179 * _tmp204;
  const Scalar _tmp206 = -_tmp197 + _tmp198 * _tmp202 - _tmp201 * _tmp205;
  const Scalar _tmp207 = Scalar(1.0) / (_tmp204);
  const Scalar _tmp208 = _tmp178 * _tmp207;
  const Scalar _tmp209 = _tmp206 * _tmp208;
  const Scalar _tmp210 = _tmp201 + _tmp209;
  const Scalar _tmp211 = -_tmp148 - _tmp184 * _tmp210;
  const Scalar _tmp212 = _tmp137 * _tmp179;
  const Scalar _tmp213 = _tmp183 * _tmp211 + _tmp210 * _tmp212 + Scalar(1.0);
  const Scalar _tmp214 = _tmp37 + Scalar(-4.7752063900000001);
  const Scalar _tmp215 = _tmp48 + Scalar(-2.71799795);
  const Scalar _tmp216 = std::pow(_tmp214, Scalar(2)) + std::pow(_tmp215, Scalar(2));
  const Scalar _tmp217 = std::pow(_tmp216, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp218 = _tmp215 * _tmp217;
  const Scalar _tmp219 = _tmp218 * fh1;
  const Scalar _tmp220 = _tmp191 * _tmp219;
  const Scalar _tmp221 = Scalar(1.0) * _tmp167;
  const Scalar _tmp222 = Scalar(1.0) * _tmp173;
  const Scalar _tmp223 = _tmp175 * _tmp222;
  const Scalar _tmp224 = _tmp167 * _tmp223;
  const Scalar _tmp225 = _tmp164 * _tmp224 - _tmp177 * _tmp221;
  const Scalar _tmp226 = -_tmp202 * _tmp221 - _tmp205 * _tmp225;
  const Scalar _tmp227 = _tmp208 * _tmp226;
  const Scalar _tmp228 = _tmp225 + _tmp227;
  const Scalar _tmp229 = -_tmp184 * _tmp228 + Scalar(1.0);
  const Scalar _tmp230 = _tmp183 * _tmp229 + _tmp212 * _tmp228;
  const Scalar _tmp231 = _tmp214 * _tmp217;
  const Scalar _tmp232 = _tmp231 * fh1;
  const Scalar _tmp233 = _tmp191 * _tmp232;
  const Scalar _tmp234 = -_tmp218 * _tmp36 + _tmp231 * _tmp47;
  const Scalar _tmp235 = _tmp234 * fh1;
  const Scalar _tmp236 = Scalar(1.0) * _tmp207;
  const Scalar _tmp237 = _tmp168 * _tmp236;
  const Scalar _tmp238 = _tmp137 * _tmp236 - _tmp160 * _tmp237;
  const Scalar _tmp239 = _tmp191 * _tmp238;
  const Scalar _tmp240 =
      -_tmp186 * _tmp192 - _tmp213 * _tmp220 - _tmp230 * _tmp233 - _tmp235 * _tmp239;
  const Scalar _tmp241 = Scalar(1.0) / (_tmp240);
  const Scalar _tmp242 = _tmp132 + _tmp171;
  const Scalar _tmp243 = _tmp176 * _tmp242;
  const Scalar _tmp244 = -_tmp128 + _tmp174 - _tmp243;
  const Scalar _tmp245 = Scalar(1.0) / (_tmp244);
  const Scalar _tmp246 = Scalar(1.0) * _tmp245;
  const Scalar _tmp247 = _tmp164 * _tmp221;
  const Scalar _tmp248 = _tmp169 * _tmp179;
  const Scalar _tmp249 = _tmp227 * _tmp245;
  const Scalar _tmp250 = -_tmp228 * _tmp248 + _tmp242 * _tmp249 - _tmp247;
  const Scalar _tmp251 = -_tmp222 * _tmp250 + _tmp227 * _tmp246;
  const Scalar _tmp252 = Scalar(1.0) * _tmp251;
  const Scalar _tmp253 = fh1 * (_tmp121 + _tmp125);
  const Scalar _tmp254 = -_tmp231 * _tmp253 - Scalar(3.29616) * _tmp30 - _tmp36 * fv1;
  const Scalar _tmp255 = _tmp176 * _tmp246;
  const Scalar _tmp256 = _tmp243 * _tmp246 + Scalar(1.0);
  const Scalar _tmp257 = -Scalar(1.0) * _tmp222 * _tmp256 + Scalar(1.0) * _tmp255;
  const Scalar _tmp258 = _tmp208 * _tmp246;
  const Scalar _tmp259 = -_tmp169 * _tmp236 + _tmp242 * _tmp258;
  const Scalar _tmp260 = -_tmp222 * _tmp259 + _tmp258;
  const Scalar _tmp261 = Scalar(1.0) * _tmp235;
  const Scalar _tmp262 = _tmp218 * _tmp253 + Scalar(3.29616) * _tmp43 + _tmp47 * fv1;
  const Scalar _tmp263 = _tmp173 * _tmp246;
  const Scalar _tmp264 = Scalar(1.0) * _tmp242 * _tmp263 - Scalar(1.0) * _tmp246;
  const Scalar _tmp265 = _tmp180 * _tmp245;
  const Scalar _tmp266 = -_tmp169 * _tmp182 + _tmp171 - _tmp242 * _tmp265;
  const Scalar _tmp267 = Scalar(1.0) * _tmp187;
  const Scalar _tmp268 = _tmp242 * _tmp245;
  const Scalar _tmp269 = _tmp200 + _tmp209 * _tmp268 - _tmp210 * _tmp248;
  const Scalar _tmp270 = _tmp209 * _tmp246 - _tmp222 * _tmp269;
  const Scalar _tmp271 = Scalar(1.0) * _tmp270;
  const Scalar _tmp272 = _tmp219 * _tmp271 + _tmp232 * _tmp252 + _tmp254 * _tmp257 +
                         _tmp260 * _tmp261 + _tmp262 * _tmp264 +
                         _tmp267 * (-_tmp180 * _tmp246 - _tmp222 * _tmp266 + Scalar(1.0));
  const Scalar _tmp273 = std::asinh(_tmp241 * _tmp272);
  const Scalar _tmp274 = Scalar(9.6622558468725703) * _tmp240;
  const Scalar _tmp275 = -_tmp141 + Scalar(-8.3196563700000006);
  const Scalar _tmp276 = -_tmp145 + Scalar(-1.9874742000000001);
  const Scalar _tmp277 =
      std::sqrt(Scalar(std::pow(_tmp275, Scalar(2)) + std::pow(_tmp276, Scalar(2))));
  const Scalar _tmp278 = -_tmp273 * _tmp274 - _tmp277;
  const Scalar _tmp279 = Scalar(0.1034955) * _tmp241;
  const Scalar _tmp280 = _tmp278 * _tmp279;
  const Scalar _tmp281 = Scalar(1.0) * _tmp273;
  const Scalar _tmp282 = -_tmp94 - _tmp95 - _tmp97 - _tmp98;
  const Scalar _tmp283 = _tmp282 + _tmp93;
  const Scalar _tmp284 = _tmp102 + _tmp283;
  const Scalar _tmp285 = Scalar(1.0) / (_tmp188);
  const Scalar _tmp286 = _tmp190 * _tmp284 * _tmp285;
  const Scalar _tmp287 = _tmp213 * _tmp219;
  const Scalar _tmp288 = -_tmp87;
  const Scalar _tmp289 = -_tmp101 + _tmp288;
  const Scalar _tmp290 = _tmp283 + _tmp289;
  const Scalar _tmp291 = _tmp136 * _tmp290;
  const Scalar _tmp292 = _tmp76 + _tmp78;
  const Scalar _tmp293 = _tmp292 + _tmp92;
  const Scalar _tmp294 = _tmp293 + _tmp90;
  const Scalar _tmp295 = _tmp64 + _tmp67 - _tmp70 - _tmp73;
  const Scalar _tmp296 = _tmp294 + _tmp295;
  const Scalar _tmp297 =
      (2 * _tmp130 * _tmp290 + 2 * _tmp134 * _tmp296) / (_tmp135 * std::sqrt(_tmp135));
  const Scalar _tmp298 = (Scalar(1) / Scalar(2)) * _tmp297;
  const Scalar _tmp299 = _tmp130 * _tmp298;
  const Scalar _tmp300 = Scalar(1.6799999999999999) * _tmp17 * _tmp68;
  const Scalar _tmp301 =
      (-Scalar(1.6799999999999999) * _tmp106 - _tmp300) / std::pow(_tmp172, Scalar(2));
  const Scalar _tmp302 = _tmp175 * _tmp301;
  const Scalar _tmp303 = _tmp292 + _tmp84;
  const Scalar _tmp304 = _tmp282 + _tmp303;
  const Scalar _tmp305 = _tmp102 + _tmp304;
  const Scalar _tmp306 = _tmp159 * _tmp305;
  const Scalar _tmp307 = _tmp288 - _tmp89;
  const Scalar _tmp308 = _tmp295 + _tmp307;
  const Scalar _tmp309 = _tmp308 + _tmp85;
  const Scalar _tmp310 =
      (2 * _tmp154 * _tmp309 + 2 * _tmp157 * _tmp305) / (_tmp158 * std::sqrt(_tmp158));
  const Scalar _tmp311 = (Scalar(1) / Scalar(2)) * _tmp310;
  const Scalar _tmp312 = _tmp157 * _tmp311;
  const Scalar _tmp313 = _tmp115 + _tmp116 - _tmp117 - _tmp118;
  const Scalar _tmp314 = _tmp108 - _tmp109 - _tmp110 - _tmp111 - _tmp112;
  const Scalar _tmp315 = _tmp313 + _tmp314;
  const Scalar _tmp316 = _tmp114 + _tmp313;
  const Scalar _tmp317 = _tmp150 * _tmp306 - _tmp150 * _tmp312 + _tmp160 * _tmp315 -
                         _tmp160 * _tmp316 - _tmp162 * _tmp306 + _tmp162 * _tmp312;
  const Scalar _tmp318 = _tmp119 + _tmp314;
  const Scalar _tmp319 = _tmp137 * _tmp315;
  const Scalar _tmp320 = _tmp100 * _tmp12;
  const Scalar _tmp321 = _tmp22 * _tmp88;
  const Scalar _tmp322 = Scalar(0.83999999999999997) * _tmp17 * _tmp65 + _tmp27 * _tmp86;
  const Scalar _tmp323 = _tmp173 * (-_tmp320 - _tmp321 + _tmp322);
  const Scalar _tmp324 = _tmp295 + _tmp91;
  const Scalar _tmp325 = _tmp147 * _tmp324;
  const Scalar _tmp326 = _tmp134 * _tmp298;
  const Scalar _tmp327 = _tmp142 * _tmp284;
  const Scalar _tmp328 = _tmp285 * _tmp327;
  const Scalar _tmp329 = _tmp136 * _tmp296;
  const Scalar _tmp330 = _tmp137 * _tmp325 - _tmp137 * _tmp328 + _tmp148 * _tmp291 -
                         _tmp148 * _tmp299 + _tmp326 - _tmp329;
  const Scalar _tmp331 = _tmp167 * _tmp330;
  const Scalar _tmp332 = _tmp154 * _tmp311;
  const Scalar _tmp333 = _tmp159 * _tmp309;
  const Scalar _tmp334 = (_tmp148 * _tmp306 - _tmp148 * _tmp312 + _tmp160 * _tmp325 -
                          _tmp160 * _tmp328 + _tmp332 - _tmp333) /
                         std::pow(_tmp166, Scalar(2));
  const Scalar _tmp335 = _tmp165 * _tmp334;
  const Scalar _tmp336 = _tmp148 * _tmp315;
  const Scalar _tmp337 = -_tmp160 * _tmp336 - _tmp161 * _tmp325 + _tmp161 * _tmp328 -
                         _tmp162 * _tmp332 + _tmp162 * _tmp333 + _tmp163 * _tmp316 -
                         _tmp199 * _tmp306 + _tmp199 * _tmp312;
  const Scalar _tmp338 = -_tmp126 * _tmp326 + _tmp126 * _tmp329 + _tmp138 * _tmp318 -
                         _tmp148 * _tmp319 - _tmp151 * _tmp325 + _tmp151 * _tmp328 -
                         _tmp164 * _tmp331 + _tmp164 * _tmp335 - _tmp168 * _tmp337 -
                         _tmp199 * _tmp291 + _tmp199 * _tmp299;
  const Scalar _tmp339 = -_tmp126 * _tmp291 + _tmp126 * _tmp299 - _tmp137 * _tmp318 +
                         _tmp150 * _tmp291 - _tmp150 * _tmp299 - _tmp168 * _tmp317 +
                         _tmp169 * _tmp302 - _tmp169 * _tmp323 - _tmp176 * _tmp338 -
                         _tmp177 * _tmp331 + _tmp177 * _tmp335 + _tmp319;
  const Scalar _tmp340 = _tmp339 / std::pow(_tmp178, Scalar(2));
  const Scalar _tmp341 = _tmp137 * _tmp340;
  const Scalar _tmp342 = _tmp160 * _tmp331;
  const Scalar _tmp343 = _tmp167 * _tmp306;
  const Scalar _tmp344 = _tmp160 * _tmp334;
  const Scalar _tmp345 = _tmp142 * _tmp324 + _tmp146 * _tmp284;
  const Scalar _tmp346 = _tmp147 * _tmp193 * _tmp345;
  const Scalar _tmp347 = _tmp186 * _tmp187;
  const Scalar _tmp348 = _tmp191 * _tmp230;
  const Scalar _tmp349 = _tmp293 + _tmp308;
  const Scalar _tmp350 = _tmp289 + _tmp304;
  const Scalar _tmp351 =
      (2 * _tmp214 * _tmp349 + 2 * _tmp215 * _tmp350) / (_tmp216 * std::sqrt(_tmp216));
  const Scalar _tmp352 = (Scalar(1) / Scalar(2)) * _tmp351;
  const Scalar _tmp353 = _tmp214 * _tmp352;
  const Scalar _tmp354 = _tmp353 * fh1;
  const Scalar _tmp355 = _tmp230 * _tmp232;
  const Scalar _tmp356 = _tmp217 * _tmp350;
  const Scalar _tmp357 = _tmp356 * fh1;
  const Scalar _tmp358 = _tmp191 * _tmp213;
  const Scalar _tmp359 = _tmp235 * _tmp238;
  const Scalar _tmp360 = _tmp167 * _tmp211;
  const Scalar _tmp361 = _tmp179 * _tmp291;
  const Scalar _tmp362 = _tmp179 * _tmp210;
  const Scalar _tmp363 = _tmp196 * _tmp346;
  const Scalar _tmp364 = _tmp196 * _tmp286;
  const Scalar _tmp365 = _tmp345 / (_tmp189 * std::sqrt(_tmp189));
  const Scalar _tmp366 = _tmp193 * _tmp324;
  const Scalar _tmp367 =
      _tmp191 * (_tmp140 * _tmp146 * _tmp365 + _tmp144 * _tmp366 - _tmp146 * _tmp366 +
                 _tmp193 * _tmp327 - _tmp194 * _tmp284 - _tmp195 * _tmp365);
  const Scalar _tmp368 = _tmp152 * _tmp306 - _tmp152 * _tmp312 + _tmp155 * _tmp332 -
                         _tmp155 * _tmp333 + _tmp157 * _tmp333 + _tmp160 * _tmp363 -
                         _tmp160 * _tmp364 + _tmp160 * _tmp367 - _tmp163 * _tmp305 +
                         _tmp197 * _tmp306 - _tmp197 * _tmp312;
  const Scalar _tmp369 = _tmp167 * _tmp325;
  const Scalar _tmp370 = _tmp148 * _tmp334;
  const Scalar _tmp371 = _tmp167 * _tmp328;
  const Scalar _tmp372 = _tmp150 * _tmp325 - _tmp150 * _tmp328 + _tmp164 * _tmp369 -
                         _tmp164 * _tmp370 - _tmp164 * _tmp371 + _tmp198 * _tmp337 + _tmp336;
  const Scalar _tmp373 = -_tmp105 - _tmp107 + _tmp113 + _tmp119 - _tmp176 * _tmp372 +
                         _tmp177 * _tmp369 - _tmp177 * _tmp370 - _tmp177 * _tmp371 +
                         _tmp198 * _tmp317 + _tmp200 * _tmp302 - _tmp200 * _tmp323;
  const Scalar _tmp374 = _tmp128 * _tmp326 - _tmp128 * _tmp329 + _tmp130 * _tmp329 -
                         _tmp132 * _tmp299 + _tmp137 * _tmp363 - _tmp137 * _tmp364 +
                         _tmp137 * _tmp367 - _tmp138 * _tmp290 - _tmp168 * _tmp368 +
                         _tmp197 * _tmp291 - _tmp197 * _tmp299 - _tmp202 * _tmp331 +
                         _tmp202 * _tmp335 + _tmp203 * _tmp290;
  const Scalar _tmp375 = _tmp179 * _tmp374;
  const Scalar _tmp376 = _tmp204 * _tmp340;
  const Scalar _tmp377 = _tmp208 * (_tmp198 * _tmp368 - _tmp201 * _tmp375 + _tmp201 * _tmp376 +
                                    _tmp202 * _tmp369 - _tmp202 * _tmp370 - _tmp202 * _tmp371 -
                                    _tmp205 * _tmp373 - _tmp363 + _tmp364 - _tmp367);
  const Scalar _tmp378 = _tmp374 / std::pow(_tmp204, Scalar(2));
  const Scalar _tmp379 = _tmp178 * _tmp378;
  const Scalar _tmp380 = _tmp206 * _tmp379;
  const Scalar _tmp381 = _tmp207 * _tmp339;
  const Scalar _tmp382 = _tmp206 * _tmp381;
  const Scalar _tmp383 = _tmp373 + _tmp377 - _tmp380 + _tmp382;
  const Scalar _tmp384 = _tmp165 * _tmp340;
  const Scalar _tmp385 = _tmp179 * _tmp330;
  const Scalar _tmp386 =
      -_tmp184 * _tmp383 + _tmp210 * _tmp384 - _tmp210 * _tmp385 - _tmp325 + _tmp328;
  const Scalar _tmp387 = Scalar(0.5) * _tmp207;
  const Scalar _tmp388 = _tmp165 * _tmp221 * _tmp378;
  const Scalar _tmp389 = Scalar(1.0) * _tmp378;
  const Scalar _tmp390 = _tmp167 * _tmp229;
  const Scalar _tmp391 = _tmp179 * _tmp228;
  const Scalar _tmp392 = Scalar(1.0) * _tmp334;
  const Scalar _tmp393 = -_tmp164 * _tmp223 * _tmp334 + _tmp177 * _tmp392 - _tmp221 * _tmp317 +
                         _tmp224 * _tmp337 - _tmp247 * _tmp302 + _tmp247 * _tmp323;
  const Scalar _tmp394 = _tmp208 * (_tmp202 * _tmp392 - _tmp205 * _tmp393 - _tmp221 * _tmp368 -
                                    _tmp225 * _tmp375 + _tmp225 * _tmp376);
  const Scalar _tmp395 = _tmp178 * _tmp226;
  const Scalar _tmp396 = _tmp378 * _tmp395;
  const Scalar _tmp397 = _tmp226 * _tmp381;
  const Scalar _tmp398 = _tmp393 + _tmp394 - _tmp396 + _tmp397;
  const Scalar _tmp399 = -_tmp184 * _tmp398 + _tmp228 * _tmp384 - _tmp228 * _tmp385;
  const Scalar _tmp400 = _tmp217 * _tmp349;
  const Scalar _tmp401 = _tmp400 * fh1;
  const Scalar _tmp402 = _tmp215 * _tmp352;
  const Scalar _tmp403 = -_tmp218 * _tmp349 + _tmp231 * _tmp350 - _tmp353 * _tmp47 -
                         _tmp356 * _tmp36 + _tmp36 * _tmp402 + _tmp400 * _tmp47;
  const Scalar _tmp404 = _tmp403 * fh1;
  const Scalar _tmp405 = _tmp402 * fh1;
  const Scalar _tmp406 =
      -_tmp191 * _tmp235 *
          (-_tmp130 * _tmp297 * _tmp387 - _tmp137 * _tmp389 +
           _tmp157 * _tmp168 * _tmp310 * _tmp387 + _tmp160 * _tmp236 * _tmp335 + _tmp160 * _tmp388 +
           _tmp236 * _tmp291 - _tmp236 * _tmp342 - _tmp237 * _tmp306) -
      _tmp192 * (_tmp160 * _tmp168 * _tmp181 * _tmp340 + _tmp167 * _tmp185 * _tmp312 -
                 _tmp181 * _tmp341 + _tmp182 * _tmp291 - _tmp182 * _tmp299 - _tmp182 * _tmp342 -
                 _tmp185 * _tmp343 + _tmp185 * _tmp344) -
      _tmp220 * (_tmp183 * _tmp386 - _tmp210 * _tmp341 + _tmp210 * _tmp361 + _tmp211 * _tmp343 -
                 _tmp211 * _tmp344 + _tmp212 * _tmp383 - _tmp299 * _tmp362 - _tmp312 * _tmp360) -
      _tmp233 * (_tmp183 * _tmp399 + _tmp212 * _tmp398 - _tmp228 * _tmp341 + _tmp228 * _tmp361 +
                 _tmp229 * _tmp343 - _tmp229 * _tmp344 - _tmp299 * _tmp391 - _tmp312 * _tmp390) -
      _tmp239 * _tmp404 + _tmp286 * _tmp287 + _tmp286 * _tmp347 + _tmp286 * _tmp355 +
      _tmp286 * _tmp359 - _tmp287 * _tmp346 - _tmp346 * _tmp347 - _tmp346 * _tmp355 -
      _tmp346 * _tmp359 + _tmp348 * _tmp354 - _tmp348 * _tmp401 - _tmp357 * _tmp358 +
      _tmp358 * _tmp405;
  const Scalar _tmp407 = Scalar(9.6622558468725703) * _tmp406;
  const Scalar _tmp408 = std::pow(_tmp240, Scalar(-2));
  const Scalar _tmp409 = _tmp406 * _tmp408;
  const Scalar _tmp410 = _tmp120 * fh1;
  const Scalar _tmp411 = Scalar(6.59232) * _tmp65;
  const Scalar _tmp412 = Scalar(6.59232) * _tmp62;
  const Scalar _tmp413 = _tmp17 * _tmp412 + _tmp218 * _tmp410 + _tmp22 * _tmp411 +
                         _tmp253 * _tmp356 - _tmp253 * _tmp402 + Scalar(6.59232) * _tmp27 * _tmp71 +
                         _tmp350 * fv1 + Scalar(6.59232) * _tmp96;
  const Scalar _tmp414 = Scalar(0.5) * _tmp351 * fh1;
  const Scalar _tmp415 = -_tmp170 * _tmp302 + _tmp170 * _tmp323 + _tmp223 * _tmp324 + _tmp284;
  const Scalar _tmp416 = _tmp245 * _tmp415;
  const Scalar _tmp417 = _tmp320 + _tmp321 + _tmp322;
  const Scalar _tmp418 = _tmp176 * _tmp417;
  const Scalar _tmp419 = _tmp242 * _tmp302;
  const Scalar _tmp420 = _tmp242 * _tmp323;
  const Scalar _tmp421 =
      (Scalar(1.6799999999999999) * _tmp104 + _tmp300 - _tmp418 + _tmp419 - _tmp420) /
      std::pow(_tmp244, Scalar(2));
  const Scalar _tmp422 = _tmp180 * _tmp421;
  const Scalar _tmp423 = _tmp169 * _tmp340;
  const Scalar _tmp424 = _tmp307 + _tmp74;
  const Scalar _tmp425 = _tmp293 + _tmp424;
  const Scalar _tmp426 = _tmp181 * _tmp423 - _tmp182 * _tmp338 - _tmp242 * _tmp416 +
                         _tmp242 * _tmp422 - _tmp265 * _tmp417 + _tmp425;
  const Scalar _tmp427 = Scalar(1.0) * _tmp421;
  const Scalar _tmp428 = Scalar(1.0) * _tmp301;
  const Scalar _tmp429 = _tmp246 * _tmp379;
  const Scalar _tmp430 = _tmp246 * _tmp381;
  const Scalar _tmp431 = _tmp242 * _tmp421;
  const Scalar _tmp432 = _tmp178 * _tmp236;
  const Scalar _tmp433 = _tmp169 * _tmp389 - _tmp236 * _tmp338 - _tmp242 * _tmp429 +
                         _tmp242 * _tmp430 + _tmp258 * _tmp417 - _tmp431 * _tmp432;
  const Scalar _tmp434 = _tmp421 * _tmp432;
  const Scalar _tmp435 = _tmp242 * _tmp301;
  const Scalar _tmp436 = _tmp222 * _tmp431;
  const Scalar _tmp437 = _tmp246 * _tmp302;
  const Scalar _tmp438 = _tmp223 * _tmp421;
  const Scalar _tmp439 =
      -_tmp223 * _tmp431 + _tmp246 * _tmp418 - _tmp246 * _tmp419 + _tmp246 * _tmp420;
  const Scalar _tmp440 = _tmp246 * _tmp323;
  const Scalar _tmp441 = _tmp209 * _tmp245;
  const Scalar _tmp442 = _tmp179 * _tmp338;
  const Scalar _tmp443 = -_tmp209 * _tmp431 + _tmp210 * _tmp423 - _tmp210 * _tmp442 -
                         _tmp248 * _tmp383 + _tmp268 * _tmp377 - _tmp268 * _tmp380 +
                         _tmp268 * _tmp382 + _tmp372 + _tmp417 * _tmp441;
  const Scalar _tmp444 = _tmp12 * _tmp411 - _tmp231 * _tmp410 + _tmp253 * _tmp353 -
                         _tmp253 * _tmp400 + _tmp27 * _tmp412 - _tmp349 * fv1 -
                         Scalar(6.59232) * _tmp69 - Scalar(6.59232) * _tmp72;
  const Scalar _tmp445 = _tmp164 * _tmp392 - _tmp221 * _tmp337 - _tmp227 * _tmp431 +
                         _tmp228 * _tmp423 - _tmp228 * _tmp442 - _tmp248 * _tmp398 +
                         _tmp249 * _tmp417 + _tmp268 * _tmp394 - _tmp268 * _tmp396 +
                         _tmp268 * _tmp397;
  const Scalar _tmp446 =
      (_tmp241 *
           (-_tmp214 * _tmp251 * _tmp414 - _tmp215 * _tmp270 * _tmp414 +
            Scalar(1.0) * _tmp219 *
                (-_tmp206 * _tmp434 - _tmp222 * _tmp443 + _tmp246 * _tmp377 - _tmp246 * _tmp380 +
                 _tmp246 * _tmp382 + _tmp269 * _tmp428) +
            Scalar(1.0) * _tmp232 *
                (-_tmp222 * _tmp445 - _tmp236 * _tmp395 * _tmp421 + _tmp246 * _tmp394 -
                 _tmp246 * _tmp396 + _tmp246 * _tmp397 + _tmp250 * _tmp428) +
            _tmp252 * _tmp401 +
            Scalar(1.0) * _tmp254 *
                (-_tmp222 * _tmp439 + _tmp256 * _tmp428 - _tmp437 - _tmp438 + _tmp440) +
            _tmp257 * _tmp444 + Scalar(1.0) * _tmp260 * _tmp404 +
            _tmp261 * (-_tmp222 * _tmp433 + _tmp259 * _tmp428 - _tmp429 + _tmp430 - _tmp434) +
            Scalar(1.0) * _tmp262 * (-_tmp246 * _tmp435 + _tmp263 * _tmp417 + _tmp427 - _tmp436) +
            _tmp264 * _tmp413 +
            _tmp267 *
                (_tmp180 * _tmp427 - _tmp222 * _tmp426 - _tmp246 * _tmp415 + _tmp266 * _tmp428) +
            _tmp271 * _tmp357) -
       _tmp272 * _tmp409) /
      std::sqrt(Scalar(std::pow(_tmp272, Scalar(2)) * _tmp408 + 1));
  const Scalar _tmp447 = _tmp289 + _tmp99;
  const Scalar _tmp448 = _tmp235 * _tmp236;
  const Scalar _tmp449 = _tmp181 * _tmp187;
  const Scalar _tmp450 = _tmp184 * _tmp449;
  const Scalar _tmp451 =
      -_tmp167 * _tmp450 - _tmp168 * _tmp448 + _tmp219 * _tmp360 + _tmp232 * _tmp390;
  const Scalar _tmp452 = Scalar(1.0) / (_tmp451);
  const Scalar _tmp453 = _tmp173 * fh1;
  const Scalar _tmp454 = _tmp234 * _tmp453;
  const Scalar _tmp455 = _tmp173 * _tmp256;
  const Scalar _tmp456 = _tmp231 * _tmp453;
  const Scalar _tmp457 = _tmp173 * _tmp187;
  const Scalar _tmp458 = _tmp246 * _tmp262;
  const Scalar _tmp459 = _tmp173 * _tmp458;
  const Scalar _tmp460 = _tmp269 * _tmp453;
  const Scalar _tmp461 = _tmp218 * _tmp460 - _tmp242 * _tmp459 + _tmp250 * _tmp456 +
                         _tmp254 * _tmp455 + _tmp259 * _tmp454 + _tmp266 * _tmp457;
  const Scalar _tmp462 = std::asinh(_tmp452 * _tmp461);
  const Scalar _tmp463 = Scalar(9.6622558468725703) * _tmp451;
  const Scalar _tmp464 = Scalar(4.8333311099999996) - _tmp153;
  const Scalar _tmp465 = -_tmp156 + Scalar(-1.79662371);
  const Scalar _tmp466 =
      std::sqrt(Scalar(std::pow(_tmp464, Scalar(2)) + std::pow(_tmp465, Scalar(2))));
  const Scalar _tmp467 = -_tmp462 * _tmp463 - _tmp466;
  const Scalar _tmp468 = Scalar(0.1034955) * _tmp452;
  const Scalar _tmp469 = _tmp467 * _tmp468;
  const Scalar _tmp470 = Scalar(1.0) * _tmp462;
  const Scalar _tmp471 = _tmp340 * _tmp449;
  const Scalar _tmp472 = _tmp236 * _tmp404;
  const Scalar _tmp473 = _tmp182 * _tmp187;
  const Scalar _tmp474 = _tmp167 * _tmp219 * _tmp386 + _tmp167 * _tmp232 * _tmp399 +
                         _tmp168 * _tmp471 - _tmp168 * _tmp472 - _tmp211 * _tmp219 * _tmp334 -
                         _tmp229 * _tmp232 * _tmp334 + _tmp235 * _tmp388 - _tmp331 * _tmp448 -
                         _tmp331 * _tmp473 + _tmp334 * _tmp450 + _tmp335 * _tmp448 -
                         _tmp354 * _tmp390 + _tmp357 * _tmp360 - _tmp360 * _tmp405 +
                         _tmp390 * _tmp401;
  const Scalar _tmp475 = Scalar(9.6622558468725703) * _tmp474;
  const Scalar _tmp476 = _tmp246 * _tmp413;
  const Scalar _tmp477 = _tmp250 * _tmp453;
  const Scalar _tmp478 = std::pow(_tmp451, Scalar(-2));
  const Scalar _tmp479 = _tmp474 * _tmp478;
  const Scalar _tmp480 =
      (_tmp452 * (-_tmp173 * _tmp242 * _tmp476 + _tmp173 * _tmp254 * _tmp439 -
                  _tmp187 * _tmp266 * _tmp301 + _tmp218 * _tmp443 * _tmp453 -
                  _tmp219 * _tmp269 * _tmp301 - _tmp232 * _tmp250 * _tmp301 -
                  _tmp235 * _tmp259 * _tmp301 - _tmp254 * _tmp256 * _tmp301 +
                  _tmp259 * _tmp403 * _tmp453 + _tmp262 * _tmp436 - _tmp353 * _tmp477 +
                  _tmp356 * _tmp460 + _tmp400 * _tmp477 - _tmp402 * _tmp460 - _tmp417 * _tmp459 +
                  _tmp426 * _tmp457 + _tmp433 * _tmp454 + _tmp435 * _tmp458 + _tmp444 * _tmp455 +
                  _tmp445 * _tmp456) -
       _tmp461 * _tmp479) /
      std::sqrt(Scalar(std::pow(_tmp461, Scalar(2)) * _tmp478 + 1));
  const Scalar _tmp481 = _tmp187 * _tmp265 - _tmp219 * _tmp441 - _tmp232 * _tmp249 -
                         _tmp235 * _tmp258 - _tmp254 * _tmp255 + _tmp458;
  const Scalar _tmp482 = _tmp179 * _tmp232;
  const Scalar _tmp483 = _tmp219 * _tmp362 + _tmp228 * _tmp482 + _tmp448 + _tmp473;
  const Scalar _tmp484 = Scalar(1.0) / (_tmp483);
  const Scalar _tmp485 = std::asinh(_tmp481 * _tmp484);
  const Scalar _tmp486 = Scalar(1.0) * _tmp485;
  const Scalar _tmp487 = Scalar(9.6622558468725703) * _tmp483;
  const Scalar _tmp488 = -_tmp133 + Scalar(-8.3888750099999996);
  const Scalar _tmp489 = Scalar(2.5202214700000001) - _tmp129;
  const Scalar _tmp490 =
      std::sqrt(Scalar(std::pow(_tmp488, Scalar(2)) + std::pow(_tmp489, Scalar(2))));
  const Scalar _tmp491 = -_tmp485 * _tmp487 - _tmp490;
  const Scalar _tmp492 = Scalar(0.1034955) * _tmp484;
  const Scalar _tmp493 = _tmp491 * _tmp492;
  const Scalar _tmp494 = _tmp179 * _tmp219 * _tmp383 - _tmp210 * _tmp219 * _tmp340 -
                         _tmp228 * _tmp232 * _tmp340 - _tmp261 * _tmp378 - _tmp354 * _tmp391 +
                         _tmp357 * _tmp362 - _tmp362 * _tmp405 + _tmp391 * _tmp401 +
                         _tmp398 * _tmp482 - _tmp471 + _tmp472;
  const Scalar _tmp495 = Scalar(9.6622558468725703) * _tmp494;
  const Scalar _tmp496 = _tmp232 * _tmp245;
  const Scalar _tmp497 = _tmp219 * _tmp245;
  const Scalar _tmp498 = std::pow(_tmp483, Scalar(-2));
  const Scalar _tmp499 = _tmp494 * _tmp498;
  const Scalar _tmp500 =
      (-_tmp481 * _tmp499 +
       _tmp484 * (_tmp178 * _tmp421 * _tmp448 + _tmp187 * _tmp416 - _tmp187 * _tmp422 +
                  _tmp209 * _tmp219 * _tmp421 + _tmp227 * _tmp232 * _tmp421 + _tmp235 * _tmp429 -
                  _tmp235 * _tmp430 + _tmp249 * _tmp354 - _tmp249 * _tmp401 + _tmp254 * _tmp437 +
                  _tmp254 * _tmp438 - _tmp254 * _tmp440 - _tmp255 * _tmp444 - _tmp258 * _tmp404 -
                  _tmp262 * _tmp427 - _tmp357 * _tmp441 - _tmp377 * _tmp497 + _tmp380 * _tmp497 -
                  _tmp382 * _tmp497 - _tmp394 * _tmp496 + _tmp396 * _tmp496 - _tmp397 * _tmp496 +
                  _tmp405 * _tmp441 + _tmp476)) /
      std::sqrt(Scalar(std::pow(_tmp481, Scalar(2)) * _tmp498 + 1));

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) =
      _tmp120 -
      Scalar(0.5) * (2 * _tmp38 * (_tmp74 + _tmp91) + 2 * _tmp49 * (_tmp103 + _tmp93)) *
          std::sinh(Scalar(0.1034955) * _tmp51 *
                    (-_tmp50 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp51 * fv1))) /
          _tmp50;
  _res(1, 0) =
      -_tmp274 *
          (-Scalar(0.87679799772039002) * _tmp409 + Scalar(1.0) * _tmp446 * std::sinh(_tmp281) -
           (-Scalar(0.1034955) * _tmp278 * _tmp409 +
            _tmp279 * (-_tmp273 * _tmp407 - _tmp274 * _tmp446 -
                       Scalar(1) / Scalar(2) *
                           (2 * _tmp275 * _tmp425 + 2 * _tmp276 * (_tmp303 + _tmp447)) / _tmp277)) *
               std::sinh(_tmp280)) +
      _tmp315 -
      _tmp407 * (Scalar(0.87679799772039002) * _tmp241 - std::cosh(_tmp280) + std::cosh(_tmp281));
  _res(2, 0) =
      _tmp316 -
      _tmp463 *
          (-Scalar(0.86625939559540499) * _tmp479 + Scalar(1.0) * _tmp480 * std::sinh(_tmp470) -
           (-Scalar(0.1034955) * _tmp467 * _tmp479 +
            _tmp468 * (-_tmp462 * _tmp475 - _tmp463 * _tmp480 -
                       Scalar(1) / Scalar(2) *
                           (2 * _tmp464 * (_tmp294 + _tmp74) + 2 * _tmp465 * (_tmp447 + _tmp93)) /
                           _tmp466)) *
               std::sinh(_tmp469)) -
      _tmp475 * (Scalar(0.86625939559540499) * _tmp452 - std::cosh(_tmp469) + std::cosh(_tmp470));
  _res(3, 0) =
      _tmp318 -
      _tmp487 *
          (-Scalar(0.87653584775870996) * _tmp499 + Scalar(1.0) * _tmp500 * std::sinh(_tmp486) -
           (-Scalar(0.1034955) * _tmp491 * _tmp499 +
            _tmp492 * (-_tmp485 * _tmp495 - _tmp487 * _tmp500 -
                       Scalar(1) / Scalar(2) *
                           (2 * _tmp488 * (_tmp424 + _tmp85) + 2 * _tmp489 * (_tmp103 + _tmp303)) /
                           _tmp490)) *
               std::sinh(_tmp493)) -
      _tmp495 * (Scalar(0.87653584775870996) * _tmp484 + std::cosh(_tmp486) - std::cosh(_tmp493));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
