// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: resedual_func_cost2_wrt_ry_l2
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     rx: Scalar
 *     ry: Scalar
 *     rz: Scalar
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> ResedualFuncCost2WrtRyL2(
    const Scalar fh1, const Scalar fv1, const Scalar rx, const Scalar ry, const Scalar rz,
    const Scalar p_init0, const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x,
    const Scalar rot_init_y, const Scalar rot_init_z, const Scalar rot_init_w,
    const Scalar epsilon) {
  // Total ops: 1670

  // Unused inputs
  (void)epsilon;

  // Input arrays

  // Intermediate terms (521)
  const Scalar _tmp0 = Scalar(1.0) / (fh1);
  const Scalar _tmp1 = std::pow(ry, Scalar(2));
  const Scalar _tmp2 = _tmp1 + std::pow(rx, Scalar(2)) + std::pow(rz, Scalar(2));
  const Scalar _tmp3 = std::sqrt(_tmp2);
  const Scalar _tmp4 = (Scalar(1) / Scalar(2)) * _tmp3;
  const Scalar _tmp5 = std::cos(_tmp4);
  const Scalar _tmp6 = _tmp5 * rot_init_x;
  const Scalar _tmp7 = std::sin(_tmp4);
  const Scalar _tmp8 = _tmp7 / _tmp3;
  const Scalar _tmp9 = _tmp8 * rot_init_z;
  const Scalar _tmp10 = _tmp9 * ry;
  const Scalar _tmp11 = _tmp8 * rot_init_w;
  const Scalar _tmp12 = _tmp8 * rot_init_y;
  const Scalar _tmp13 = -_tmp10 + _tmp11 * rx + _tmp12 * rz + _tmp6;
  const Scalar _tmp14 = -2 * std::pow(_tmp13, Scalar(2));
  const Scalar _tmp15 = _tmp5 * rot_init_z;
  const Scalar _tmp16 = _tmp8 * rot_init_x;
  const Scalar _tmp17 = _tmp16 * ry;
  const Scalar _tmp18 = _tmp11 * rz - _tmp12 * rx + _tmp15 + _tmp17;
  const Scalar _tmp19 = -2 * std::pow(_tmp18, Scalar(2));
  const Scalar _tmp20 = Scalar(0.20999999999999999) * _tmp14 +
                        Scalar(0.20999999999999999) * _tmp19 + Scalar(0.20999999999999999);
  const Scalar _tmp21 = -_tmp20;
  const Scalar _tmp22 = _tmp5 * rot_init_y;
  const Scalar _tmp23 = _tmp11 * ry;
  const Scalar _tmp24 = -_tmp16 * rz + _tmp22 + _tmp23 + _tmp9 * rx;
  const Scalar _tmp25 = 2 * _tmp18;
  const Scalar _tmp26 = _tmp24 * _tmp25;
  const Scalar _tmp27 = _tmp5 * rot_init_w;
  const Scalar _tmp28 = _tmp12 * ry;
  const Scalar _tmp29 = -_tmp16 * rx + _tmp27 - _tmp28 - _tmp9 * rz;
  const Scalar _tmp30 = 2 * _tmp29;
  const Scalar _tmp31 = _tmp13 * _tmp30;
  const Scalar _tmp32 = _tmp26 - _tmp31;
  const Scalar _tmp33 = -Scalar(0.010999999999999999) * _tmp32;
  const Scalar _tmp34 = 2 * _tmp13 * _tmp24;
  const Scalar _tmp35 = _tmp25 * _tmp29;
  const Scalar _tmp36 = Scalar(0.20999999999999999) * _tmp34 + Scalar(0.20999999999999999) * _tmp35;
  const Scalar _tmp37 = _tmp33 + _tmp36;
  const Scalar _tmp38 = _tmp21 + _tmp37;
  const Scalar _tmp39 = _tmp38 + p_init1;
  const Scalar _tmp40 = -_tmp39 + Scalar(-8.3888750099999996);
  const Scalar _tmp41 = Scalar(0.20999999999999999) * _tmp34 - Scalar(0.20999999999999999) * _tmp35;
  const Scalar _tmp42 = -_tmp41;
  const Scalar _tmp43 = _tmp13 * _tmp25;
  const Scalar _tmp44 = _tmp24 * _tmp30;
  const Scalar _tmp45 = _tmp43 + _tmp44;
  const Scalar _tmp46 = -Scalar(0.010999999999999999) * _tmp45;
  const Scalar _tmp47 = 1 - 2 * std::pow(_tmp24, Scalar(2));
  const Scalar _tmp48 = Scalar(0.20999999999999999) * _tmp19 + Scalar(0.20999999999999999) * _tmp47;
  const Scalar _tmp49 = _tmp46 + _tmp48;
  const Scalar _tmp50 = _tmp42 + _tmp49;
  const Scalar _tmp51 = _tmp50 + p_init0;
  const Scalar _tmp52 = Scalar(2.5202214700000001) - _tmp51;
  const Scalar _tmp53 = std::pow(_tmp40, Scalar(2)) + std::pow(_tmp52, Scalar(2));
  const Scalar _tmp54 = std::sqrt(_tmp53);
  const Scalar _tmp55 = (Scalar(1) / Scalar(2)) / _tmp2;
  const Scalar _tmp56 = _tmp1 * _tmp55;
  const Scalar _tmp57 = _tmp55 * ry;
  const Scalar _tmp58 = _tmp57 * rz;
  const Scalar _tmp59 = _tmp57 * rx;
  const Scalar _tmp60 = _tmp7 / (_tmp2 * std::sqrt(_tmp2));
  const Scalar _tmp61 = _tmp1 * _tmp60;
  const Scalar _tmp62 = _tmp60 * ry;
  const Scalar _tmp63 = _tmp62 * rx;
  const Scalar _tmp64 = _tmp62 * rz;
  const Scalar _tmp65 = -_tmp15 * _tmp56 - Scalar(1) / Scalar(2) * _tmp17 + _tmp22 * _tmp58 +
                        _tmp27 * _tmp59 + _tmp61 * rot_init_z - _tmp63 * rot_init_w -
                        _tmp64 * rot_init_y - _tmp9;
  const Scalar _tmp66 = Scalar(0.021999999999999999) * _tmp29;
  const Scalar _tmp67 = _tmp65 * _tmp66;
  const Scalar _tmp68 = -_tmp12 - _tmp15 * _tmp58 - _tmp22 * _tmp56 -
                        Scalar(1) / Scalar(2) * _tmp23 - _tmp59 * _tmp6 + _tmp61 * rot_init_y +
                        _tmp63 * rot_init_x + _tmp64 * rot_init_z;
  const Scalar _tmp69 = Scalar(0.021999999999999999) * _tmp13;
  const Scalar _tmp70 = _tmp68 * _tmp69;
  const Scalar _tmp71 = -Scalar(1) / Scalar(2) * _tmp10 + _tmp16 - _tmp22 * _tmp59 +
                        _tmp27 * _tmp58 + _tmp56 * _tmp6 - _tmp61 * rot_init_x +
                        _tmp63 * rot_init_y - _tmp64 * rot_init_w;
  const Scalar _tmp72 = _tmp24 * _tmp71;
  const Scalar _tmp73 = Scalar(0.021999999999999999) * _tmp72;
  const Scalar _tmp74 = _tmp11 + _tmp15 * _tmp59 + _tmp27 * _tmp56 -
                        Scalar(1) / Scalar(2) * _tmp28 - _tmp58 * _tmp6 - _tmp61 * rot_init_w -
                        _tmp63 * rot_init_z + _tmp64 * rot_init_x;
  const Scalar _tmp75 = _tmp18 * _tmp74;
  const Scalar _tmp76 = Scalar(0.021999999999999999) * _tmp75;
  const Scalar _tmp77 = -_tmp67 - _tmp70 + _tmp73 + _tmp76;
  const Scalar _tmp78 = _tmp29 * _tmp71;
  const Scalar _tmp79 = Scalar(0.41999999999999998) * _tmp78;
  const Scalar _tmp80 = Scalar(0.41999999999999998) * _tmp68;
  const Scalar _tmp81 = _tmp18 * _tmp80;
  const Scalar _tmp82 = -_tmp79 - _tmp81;
  const Scalar _tmp83 = Scalar(0.41999999999999998) * _tmp13;
  const Scalar _tmp84 = _tmp74 * _tmp83;
  const Scalar _tmp85 = Scalar(0.41999999999999998) * _tmp65;
  const Scalar _tmp86 = _tmp24 * _tmp85;
  const Scalar _tmp87 = -_tmp84 - _tmp86;
  const Scalar _tmp88 = _tmp82 + _tmp87;
  const Scalar _tmp89 = Scalar(0.83999999999999997) * _tmp18;
  const Scalar _tmp90 = _tmp71 * _tmp89;
  const Scalar _tmp91 = -_tmp90;
  const Scalar _tmp92 = Scalar(0.83999999999999997) * _tmp65;
  const Scalar _tmp93 = _tmp13 * _tmp92;
  const Scalar _tmp94 = _tmp91 - _tmp93;
  const Scalar _tmp95 = _tmp88 + _tmp94;
  const Scalar _tmp96 = _tmp24 * _tmp74;
  const Scalar _tmp97 = Scalar(0.83999999999999997) * _tmp96;
  const Scalar _tmp98 = _tmp90 + _tmp97;
  const Scalar _tmp99 = _tmp84 + _tmp86;
  const Scalar _tmp100 = _tmp82 + _tmp99;
  const Scalar _tmp101 = _tmp66 * _tmp74;
  const Scalar _tmp102 = Scalar(0.021999999999999999) * _tmp24 * _tmp68;
  const Scalar _tmp103 = _tmp69 * _tmp71;
  const Scalar _tmp104 = Scalar(0.021999999999999999) * _tmp18 * _tmp65;
  const Scalar _tmp105 = _tmp101 + _tmp102 + _tmp103 + _tmp104;
  const Scalar _tmp106 = _tmp100 + _tmp105;
  const Scalar _tmp107 = 2 * _tmp40 * (_tmp77 + _tmp95) + 2 * _tmp52 * (_tmp106 + _tmp98);
  const Scalar _tmp108 =
      Scalar(0.20999999999999999) * _tmp26 + Scalar(0.20999999999999999) * _tmp31;
  const Scalar _tmp109 = -_tmp108;
  const Scalar _tmp110 =
      -Scalar(0.010999999999999999) * _tmp14 - Scalar(0.010999999999999999) * _tmp47;
  const Scalar _tmp111 =
      Scalar(0.20999999999999999) * _tmp43 - Scalar(0.20999999999999999) * _tmp44;
  const Scalar _tmp112 = _tmp110 + _tmp111;
  const Scalar _tmp113 = _tmp109 + _tmp112;
  const Scalar _tmp114 = -_tmp113 - p_init2 + Scalar(8.4693136199999994);
  const Scalar _tmp115 = Scalar(0.41999999999999998) * _tmp29;
  const Scalar _tmp116 = _tmp115 * _tmp74;
  const Scalar _tmp117 = _tmp24 * _tmp80;
  const Scalar _tmp118 = _tmp71 * _tmp83;
  const Scalar _tmp119 = _tmp18 * _tmp85;
  const Scalar _tmp120 = _tmp116 + _tmp117 - _tmp118 - _tmp119;
  const Scalar _tmp121 = _tmp115 * _tmp65;
  const Scalar _tmp122 = _tmp68 * _tmp83;
  const Scalar _tmp123 = Scalar(0.41999999999999998) * _tmp72;
  const Scalar _tmp124 = Scalar(0.41999999999999998) * _tmp75;
  const Scalar _tmp125 = _tmp121 + _tmp122 + _tmp123 + _tmp124;
  const Scalar _tmp126 = Scalar(0.043999999999999997) * _tmp96;
  const Scalar _tmp127 = _tmp13 * _tmp65;
  const Scalar _tmp128 = Scalar(0.043999999999999997) * _tmp127;
  const Scalar _tmp129 = -_tmp126 - _tmp128;
  const Scalar _tmp130 = _tmp125 + _tmp129;
  const Scalar _tmp131 = _tmp33 - _tmp36;
  const Scalar _tmp132 = _tmp131 + _tmp21;
  const Scalar _tmp133 = _tmp132 + p_init1;
  const Scalar _tmp134 = _tmp133 + Scalar(8.3196563700000006);
  const Scalar _tmp135 = _tmp46 - _tmp48;
  const Scalar _tmp136 = _tmp135 + _tmp42;
  const Scalar _tmp137 = _tmp136 + p_init0;
  const Scalar _tmp138 = _tmp137 + Scalar(1.9874742000000001);
  const Scalar _tmp139 = std::pow(_tmp134, Scalar(2)) + std::pow(_tmp138, Scalar(2));
  const Scalar _tmp140 = std::pow(_tmp139, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp141 = _tmp138 * _tmp140;
  const Scalar _tmp142 = _tmp131 + _tmp20;
  const Scalar _tmp143 = _tmp142 + p_init1;
  const Scalar _tmp144 = _tmp143 + Scalar(-4.8333311099999996);
  const Scalar _tmp145 = _tmp135 + _tmp41;
  const Scalar _tmp146 = _tmp145 + p_init0;
  const Scalar _tmp147 = _tmp146 + Scalar(1.79662371);
  const Scalar _tmp148 = Scalar(1.0) / (_tmp147);
  const Scalar _tmp149 = _tmp144 * _tmp148;
  const Scalar _tmp150 = _tmp110 - _tmp111;
  const Scalar _tmp151 = _tmp108 + _tmp150;
  const Scalar _tmp152 = _tmp141 * _tmp151;
  const Scalar _tmp153 = _tmp109 + _tmp150;
  const Scalar _tmp154 = _tmp134 * _tmp140;
  const Scalar _tmp155 = _tmp20 + _tmp37;
  const Scalar _tmp156 = _tmp155 + p_init1;
  const Scalar _tmp157 = _tmp156 + Scalar(-4.7752063900000001);
  const Scalar _tmp158 = _tmp41 + _tmp49;
  const Scalar _tmp159 = _tmp158 + p_init0;
  const Scalar _tmp160 = _tmp159 + Scalar(-2.71799795);
  const Scalar _tmp161 = std::pow(_tmp157, Scalar(2)) + std::pow(_tmp160, Scalar(2));
  const Scalar _tmp162 = std::pow(_tmp161, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp163 = _tmp160 * _tmp162;
  const Scalar _tmp164 = _tmp149 * _tmp151;
  const Scalar _tmp165 = _tmp108 + _tmp112;
  const Scalar _tmp166 = _tmp157 * _tmp162;
  const Scalar _tmp167 = -_tmp163 * _tmp164 + _tmp165 * _tmp166;
  const Scalar _tmp168 = _tmp149 * _tmp163 - _tmp166;
  const Scalar _tmp169 = Scalar(1.0) / (_tmp168);
  const Scalar _tmp170 = _tmp141 * _tmp149 - _tmp154;
  const Scalar _tmp171 = _tmp169 * _tmp170;
  const Scalar _tmp172 = -_tmp149 * _tmp152 + _tmp153 * _tmp154 - _tmp167 * _tmp171;
  const Scalar _tmp173 = Scalar(1.0) * _tmp145;
  const Scalar _tmp174 = -_tmp158 + _tmp173;
  const Scalar _tmp175 = Scalar(1.0) * _tmp142;
  const Scalar _tmp176 = -_tmp175;
  const Scalar _tmp177 = _tmp155 + _tmp176;
  const Scalar _tmp178 = Scalar(1.0) / (_tmp177);
  const Scalar _tmp179 = _tmp174 * _tmp178;
  const Scalar _tmp180 = _tmp151 * _tmp163;
  const Scalar _tmp181 = -_tmp163 * _tmp165 + _tmp180;
  const Scalar _tmp182 = -_tmp141 * _tmp153 + _tmp152 - _tmp171 * _tmp181 - _tmp172 * _tmp179;
  const Scalar _tmp183 = Scalar(1.0) / (_tmp182);
  const Scalar _tmp184 = _tmp173 + _tmp175 * _tmp179;
  const Scalar _tmp185 = 0;
  const Scalar _tmp186 = _tmp183 * _tmp185;
  const Scalar _tmp187 = _tmp163 * _tmp171;
  const Scalar _tmp188 = _tmp141 * _tmp186 - _tmp186 * _tmp187;
  const Scalar _tmp189 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp190 = std::pow(_tmp147, Scalar(2));
  const Scalar _tmp191 = std::pow(_tmp144, Scalar(2)) + _tmp190;
  const Scalar _tmp192 = std::sqrt(_tmp191);
  const Scalar _tmp193 = _tmp148 * _tmp192;
  const Scalar _tmp194 = _tmp189 * _tmp193;
  const Scalar _tmp195 = _tmp51 + Scalar(-2.5202214700000001);
  const Scalar _tmp196 = _tmp39 + Scalar(8.3888750099999996);
  const Scalar _tmp197 = std::pow(_tmp195, Scalar(2)) + std::pow(_tmp196, Scalar(2));
  const Scalar _tmp198 = std::pow(_tmp197, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp199 = _tmp195 * _tmp198;
  const Scalar _tmp200 = _tmp198 * _tmp50;
  const Scalar _tmp201 = fh1 * (_tmp196 * _tmp200 - _tmp199 * _tmp38);
  const Scalar _tmp202 = Scalar(1.0) / (_tmp192);
  const Scalar _tmp203 = _tmp145 * _tmp202;
  const Scalar _tmp204 = _tmp147 * _tmp202;
  const Scalar _tmp205 = -_tmp142 * _tmp204 + _tmp144 * _tmp203;
  const Scalar _tmp206 = _tmp193 * _tmp205;
  const Scalar _tmp207 = _tmp155 * _tmp163 - _tmp158 * _tmp166 + _tmp163 * _tmp206;
  const Scalar _tmp208 =
      _tmp132 * _tmp141 - _tmp136 * _tmp154 + _tmp141 * _tmp206 - _tmp171 * _tmp207;
  const Scalar _tmp209 = Scalar(1.0) / (_tmp208);
  const Scalar _tmp210 = Scalar(1.0) * _tmp209;
  const Scalar _tmp211 = _tmp141 * _tmp210 - _tmp187 * _tmp210;
  const Scalar _tmp212 = _tmp193 * _tmp211;
  const Scalar _tmp213 = Scalar(1.0) * _tmp169;
  const Scalar _tmp214 = _tmp167 * _tmp213;
  const Scalar _tmp215 = _tmp179 * _tmp214 - _tmp181 * _tmp213;
  const Scalar _tmp216 = _tmp183 * _tmp208;
  const Scalar _tmp217 = -_tmp207 * _tmp213 - _tmp215 * _tmp216;
  const Scalar _tmp218 = _tmp209 * _tmp217;
  const Scalar _tmp219 = _tmp182 * _tmp218;
  const Scalar _tmp220 = _tmp215 + _tmp219;
  const Scalar _tmp221 = _tmp141 * _tmp183;
  const Scalar _tmp222 = _tmp170 * _tmp183;
  const Scalar _tmp223 = -_tmp220 * _tmp222 + Scalar(1.0);
  const Scalar _tmp224 = _tmp163 * _tmp169;
  const Scalar _tmp225 = _tmp220 * _tmp221 + _tmp223 * _tmp224;
  const Scalar _tmp226 = _tmp196 * _tmp198;
  const Scalar _tmp227 = _tmp226 * fh1;
  const Scalar _tmp228 = _tmp193 * _tmp227;
  const Scalar _tmp229 = _tmp199 * fh1;
  const Scalar _tmp230 = _tmp149 * _tmp169;
  const Scalar _tmp231 = _tmp164 + _tmp167 * _tmp230;
  const Scalar _tmp232 = -_tmp151 - _tmp179 * _tmp231 + _tmp181 * _tmp230;
  const Scalar _tmp233 = -_tmp206 + _tmp207 * _tmp230 - _tmp216 * _tmp232;
  const Scalar _tmp234 = _tmp182 * _tmp209;
  const Scalar _tmp235 = _tmp233 * _tmp234;
  const Scalar _tmp236 = _tmp232 + _tmp235;
  const Scalar _tmp237 = -_tmp149 - _tmp222 * _tmp236;
  const Scalar _tmp238 = _tmp221 * _tmp236 + _tmp224 * _tmp237 + Scalar(1.0);
  const Scalar _tmp239 = _tmp193 * _tmp238;
  const Scalar _tmp240 =
      -_tmp188 * _tmp194 - _tmp201 * _tmp212 - _tmp225 * _tmp228 - _tmp229 * _tmp239;
  const Scalar _tmp241 = Scalar(1.0) / (_tmp240);
  const Scalar _tmp242 = _tmp132 + _tmp176;
  const Scalar _tmp243 = _tmp179 * _tmp242;
  const Scalar _tmp244 = -_tmp136 + _tmp173 - _tmp243;
  const Scalar _tmp245 = Scalar(1.0) / (_tmp244);
  const Scalar _tmp246 = Scalar(1.0) * _tmp245;
  const Scalar _tmp247 = _tmp234 * _tmp246;
  const Scalar _tmp248 = -_tmp172 * _tmp210 + _tmp242 * _tmp247;
  const Scalar _tmp249 = Scalar(1.0) * _tmp178;
  const Scalar _tmp250 = _tmp247 - _tmp248 * _tmp249;
  const Scalar _tmp251 = Scalar(1.0) * _tmp201;
  const Scalar _tmp252 = _tmp172 * _tmp183;
  const Scalar _tmp253 = _tmp242 * _tmp245;
  const Scalar _tmp254 = -_tmp214 + _tmp219 * _tmp253 - _tmp220 * _tmp252;
  const Scalar _tmp255 = _tmp219 * _tmp246 - _tmp249 * _tmp254;
  const Scalar _tmp256 = Scalar(1.0) * _tmp227;
  const Scalar _tmp257 = _tmp113 * fh1;
  const Scalar _tmp258 = _tmp199 * _tmp257 + Scalar(3.29616) * _tmp45 + _tmp50 * fv1;
  const Scalar _tmp259 = _tmp178 * _tmp246;
  const Scalar _tmp260 = Scalar(1.0) * _tmp242 * _tmp259 - Scalar(1.0) * _tmp246;
  const Scalar _tmp261 = _tmp231 + _tmp235 * _tmp253 - _tmp236 * _tmp252;
  const Scalar _tmp262 = _tmp235 * _tmp246 - _tmp249 * _tmp261;
  const Scalar _tmp263 = Scalar(1.0) * _tmp229;
  const Scalar _tmp264 = _tmp179 * _tmp246;
  const Scalar _tmp265 = _tmp243 * _tmp246 + Scalar(1.0);
  const Scalar _tmp266 = -_tmp249 * _tmp265 + _tmp264;
  const Scalar _tmp267 = -_tmp226 * _tmp257 - Scalar(3.29616) * _tmp32 - _tmp38 * fv1;
  const Scalar _tmp268 = Scalar(1.0) * _tmp267;
  const Scalar _tmp269 = _tmp184 * _tmp245;
  const Scalar _tmp270 = _tmp176 - _tmp185 * _tmp252 - _tmp242 * _tmp269;
  const Scalar _tmp271 = Scalar(1.0) * _tmp189;
  const Scalar _tmp272 = _tmp250 * _tmp251 + _tmp255 * _tmp256 + _tmp258 * _tmp260 +
                         _tmp262 * _tmp263 + _tmp266 * _tmp268 +
                         _tmp271 * (-_tmp184 * _tmp246 - _tmp249 * _tmp270 + Scalar(1.0));
  const Scalar _tmp273 = std::asinh(_tmp241 * _tmp272);
  const Scalar _tmp274 = Scalar(9.6622558468725703) * _tmp240;
  const Scalar _tmp275 = Scalar(4.8333311099999996) - _tmp143;
  const Scalar _tmp276 = -_tmp146 + Scalar(-1.79662371);
  const Scalar _tmp277 = std::pow(_tmp275, Scalar(2)) + std::pow(_tmp276, Scalar(2));
  const Scalar _tmp278 = std::sqrt(_tmp277);
  const Scalar _tmp279 = -_tmp273 * _tmp274 - _tmp278;
  const Scalar _tmp280 = Scalar(0.1034955) * _tmp241;
  const Scalar _tmp281 = _tmp279 * _tmp280;
  const Scalar _tmp282 = std::pow(_tmp240, Scalar(-2));
  const Scalar _tmp283 = _tmp79 + _tmp81;
  const Scalar _tmp284 = _tmp283 + _tmp99;
  const Scalar _tmp285 = _tmp90 + _tmp93;
  const Scalar _tmp286 = _tmp67 + _tmp70 - _tmp73 - _tmp76;
  const Scalar _tmp287 = _tmp285 + _tmp286;
  const Scalar _tmp288 = _tmp284 + _tmp287;
  const Scalar _tmp289 = _tmp198 * _tmp288;
  const Scalar _tmp290 = _tmp289 * fh1;
  const Scalar _tmp291 = _tmp193 * _tmp225;
  const Scalar _tmp292 = -_tmp101 - _tmp102 - _tmp103 - _tmp104;
  const Scalar _tmp293 = _tmp292 + _tmp98;
  const Scalar _tmp294 = _tmp100 + _tmp293;
  const Scalar _tmp295 = Scalar(1.0) / (_tmp190);
  const Scalar _tmp296 = _tmp192 * _tmp294 * _tmp295;
  const Scalar _tmp297 = _tmp201 * _tmp211;
  const Scalar _tmp298 = _tmp225 * _tmp227;
  const Scalar _tmp299 = _tmp144 * _tmp294;
  const Scalar _tmp300 = _tmp286 + _tmp95;
  const Scalar _tmp301 = _tmp144 * _tmp300 + _tmp147 * _tmp294;
  const Scalar _tmp302 = _tmp301 / (_tmp191 * std::sqrt(_tmp191));
  const Scalar _tmp303 = _tmp193 * (_tmp142 * _tmp147 * _tmp302 - _tmp142 * _tmp202 * _tmp294 -
                                    _tmp144 * _tmp145 * _tmp302 + _tmp202 * _tmp299 +
                                    _tmp203 * _tmp300 - _tmp204 * _tmp300);
  const Scalar _tmp304 = _tmp283 + _tmp87;
  const Scalar _tmp305 = _tmp293 + _tmp304;
  const Scalar _tmp306 = _tmp287 + _tmp88;
  const Scalar _tmp307 =
      (2 * _tmp134 * _tmp306 + 2 * _tmp138 * _tmp305) / (_tmp139 * std::sqrt(_tmp139));
  const Scalar _tmp308 = (Scalar(1) / Scalar(2)) * _tmp307;
  const Scalar _tmp309 = _tmp138 * _tmp308;
  const Scalar _tmp310 = _tmp134 * _tmp308;
  const Scalar _tmp311 = _tmp148 * _tmp300;
  const Scalar _tmp312 = _tmp140 * _tmp306;
  const Scalar _tmp313 = _tmp295 * _tmp299;
  const Scalar _tmp314 = _tmp140 * _tmp305;
  const Scalar _tmp315 = _tmp141 * _tmp311 - _tmp141 * _tmp313 - _tmp149 * _tmp309 +
                         _tmp149 * _tmp314 + _tmp310 - _tmp312;
  const Scalar _tmp316 = _tmp169 * _tmp315;
  const Scalar _tmp317 = _tmp148 * _tmp202 * _tmp301;
  const Scalar _tmp318 = _tmp205 * _tmp317;
  const Scalar _tmp319 = _tmp205 * _tmp296;
  const Scalar _tmp320 = _tmp284 + _tmp94;
  const Scalar _tmp321 = _tmp286 + _tmp320;
  const Scalar _tmp322 = _tmp91 - _tmp97;
  const Scalar _tmp323 = _tmp292 + _tmp322;
  const Scalar _tmp324 = _tmp100 + _tmp323;
  const Scalar _tmp325 =
      (2 * _tmp157 * _tmp321 + 2 * _tmp160 * _tmp324) / (_tmp161 * std::sqrt(_tmp161));
  const Scalar _tmp326 = (Scalar(1) / Scalar(2)) * _tmp325;
  const Scalar _tmp327 = _tmp160 * _tmp326;
  const Scalar _tmp328 = _tmp162 * _tmp324;
  const Scalar _tmp329 = _tmp162 * _tmp321;
  const Scalar _tmp330 = _tmp157 * _tmp326;
  const Scalar _tmp331 = -_tmp155 * _tmp327 + _tmp155 * _tmp328 - _tmp158 * _tmp329 +
                         _tmp158 * _tmp330 + _tmp160 * _tmp329 + _tmp163 * _tmp303 +
                         _tmp163 * _tmp318 - _tmp163 * _tmp319 - _tmp166 * _tmp324 -
                         _tmp206 * _tmp327 + _tmp206 * _tmp328;
  const Scalar _tmp332 = (-_tmp149 * _tmp327 + _tmp149 * _tmp328 + _tmp163 * _tmp311 -
                          _tmp163 * _tmp313 - _tmp329 + _tmp330) /
                         std::pow(_tmp168, Scalar(2));
  const Scalar _tmp333 = _tmp170 * _tmp332;
  const Scalar _tmp334 = -_tmp132 * _tmp309 + _tmp132 * _tmp314 + _tmp136 * _tmp310 -
                         _tmp136 * _tmp312 + _tmp138 * _tmp312 + _tmp141 * _tmp303 +
                         _tmp141 * _tmp318 - _tmp141 * _tmp319 - _tmp154 * _tmp305 -
                         _tmp171 * _tmp331 - _tmp206 * _tmp309 + _tmp206 * _tmp314 -
                         _tmp207 * _tmp316 + _tmp207 * _tmp333;
  const Scalar _tmp335 = _tmp334 / std::pow(_tmp208, Scalar(2));
  const Scalar _tmp336 = Scalar(1.0) * _tmp335;
  const Scalar _tmp337 = Scalar(0.5) * _tmp209;
  const Scalar _tmp338 = _tmp163 * _tmp210;
  const Scalar _tmp339 = _tmp171 * _tmp328;
  const Scalar _tmp340 = _tmp304 + _tmp323;
  const Scalar _tmp341 = _tmp198 * _tmp340;
  const Scalar _tmp342 =
      (2 * _tmp195 * _tmp340 + 2 * _tmp196 * _tmp288) / (_tmp197 * std::sqrt(_tmp197));
  const Scalar _tmp343 = (Scalar(1) / Scalar(2)) * _tmp342;
  const Scalar _tmp344 = _tmp195 * _tmp343;
  const Scalar _tmp345 = _tmp196 * _tmp343;
  const Scalar _tmp346 = fh1 * (_tmp196 * _tmp341 - _tmp199 * _tmp288 + _tmp200 * _tmp288 -
                                _tmp341 * _tmp38 + _tmp344 * _tmp38 - _tmp345 * _tmp50);
  const Scalar _tmp347 = _tmp169 * _tmp328;
  const Scalar _tmp348 = _tmp183 * _tmp236;
  const Scalar _tmp349 = Scalar(0.83999999999999997) * _tmp78;
  const Scalar _tmp350 = _tmp68 * _tmp89;
  const Scalar _tmp351 = Scalar(0.83999999999999997) * _tmp13 * _tmp74 + _tmp24 * _tmp92;
  const Scalar _tmp352 = (_tmp349 + _tmp350 + _tmp351) / std::pow(_tmp177, Scalar(2));
  const Scalar _tmp353 = _tmp174 * _tmp352;
  const Scalar _tmp354 = Scalar(1.6799999999999999) * _tmp18 * _tmp71;
  const Scalar _tmp355 = _tmp354 + Scalar(1.6799999999999999) * _tmp96;
  const Scalar _tmp356 = _tmp178 * _tmp355;
  const Scalar _tmp357 = _tmp126 + _tmp128;
  const Scalar _tmp358 = -_tmp121 - _tmp122 - _tmp123 - _tmp124;
  const Scalar _tmp359 = _tmp120 + _tmp358;
  const Scalar _tmp360 = _tmp357 + _tmp359;
  const Scalar _tmp361 = _tmp125 + _tmp357;
  const Scalar _tmp362 = _tmp120 + _tmp361;
  const Scalar _tmp363 = _tmp141 * _tmp362;
  const Scalar _tmp364 = -_tmp116 - _tmp117 + _tmp118 + _tmp119;
  const Scalar _tmp365 = _tmp361 + _tmp364;
  const Scalar _tmp366 = _tmp151 * _tmp311;
  const Scalar _tmp367 = _tmp163 * _tmp362;
  const Scalar _tmp368 = -_tmp149 * _tmp367 - _tmp163 * _tmp366 + _tmp164 * _tmp327 -
                         _tmp164 * _tmp328 + _tmp165 * _tmp329 - _tmp165 * _tmp330 +
                         _tmp166 * _tmp365 + _tmp180 * _tmp313;
  const Scalar _tmp369 = _tmp151 * _tmp314;
  const Scalar _tmp370 = -_tmp141 * _tmp366 - _tmp149 * _tmp363 - _tmp149 * _tmp369 +
                         _tmp152 * _tmp313 - _tmp153 * _tmp310 + _tmp153 * _tmp312 +
                         _tmp154 * _tmp360 + _tmp164 * _tmp309 - _tmp167 * _tmp316 +
                         _tmp167 * _tmp333 - _tmp171 * _tmp368;
  const Scalar _tmp371 = -_tmp151 * _tmp327 + _tmp151 * _tmp328 - _tmp163 * _tmp365 +
                         _tmp165 * _tmp327 - _tmp165 * _tmp328 + _tmp367;
  const Scalar _tmp372 = -_tmp141 * _tmp360 - _tmp151 * _tmp309 + _tmp153 * _tmp309 -
                         _tmp153 * _tmp314 - _tmp171 * _tmp371 + _tmp172 * _tmp353 -
                         _tmp172 * _tmp356 - _tmp179 * _tmp370 - _tmp181 * _tmp316 +
                         _tmp181 * _tmp333 + _tmp363 + _tmp369;
  const Scalar _tmp373 = _tmp372 / std::pow(_tmp182, Scalar(2));
  const Scalar _tmp374 = _tmp141 * _tmp373;
  const Scalar _tmp375 = _tmp163 * _tmp332;
  const Scalar _tmp376 = _tmp209 * _tmp372;
  const Scalar _tmp377 = _tmp233 * _tmp376;
  const Scalar _tmp378 = _tmp149 * _tmp332;
  const Scalar _tmp379 = _tmp208 * _tmp373;
  const Scalar _tmp380 = _tmp169 * _tmp313;
  const Scalar _tmp381 = _tmp183 * _tmp334;
  const Scalar _tmp382 = _tmp169 * _tmp311;
  const Scalar _tmp383 = _tmp149 * _tmp362 - _tmp151 * _tmp313 - _tmp167 * _tmp378 -
                         _tmp167 * _tmp380 + _tmp167 * _tmp382 + _tmp230 * _tmp368 + _tmp366;
  const Scalar _tmp384 = _tmp358 + _tmp364;
  const Scalar _tmp385 = _tmp129 + _tmp384;
  const Scalar _tmp386 = -_tmp179 * _tmp383 - _tmp181 * _tmp378 - _tmp181 * _tmp380 +
                         _tmp181 * _tmp382 + _tmp230 * _tmp371 + _tmp231 * _tmp353 -
                         _tmp231 * _tmp356 + _tmp385;
  const Scalar _tmp387 = _tmp234 * (-_tmp207 * _tmp378 - _tmp207 * _tmp380 + _tmp207 * _tmp382 -
                                    _tmp216 * _tmp386 + _tmp230 * _tmp331 + _tmp232 * _tmp379 -
                                    _tmp232 * _tmp381 - _tmp303 - _tmp318 + _tmp319);
  const Scalar _tmp388 = _tmp182 * _tmp335;
  const Scalar _tmp389 = _tmp233 * _tmp388;
  const Scalar _tmp390 = _tmp183 * (_tmp377 + _tmp386 + _tmp387 - _tmp389);
  const Scalar _tmp391 = _tmp183 * _tmp314;
  const Scalar _tmp392 = _tmp169 * _tmp327;
  const Scalar _tmp393 = _tmp170 * _tmp373;
  const Scalar _tmp394 = _tmp183 * _tmp315;
  const Scalar _tmp395 =
      -_tmp170 * _tmp390 + _tmp236 * _tmp393 - _tmp236 * _tmp394 - _tmp311 + _tmp313;
  const Scalar _tmp396 = _tmp344 * fh1;
  const Scalar _tmp397 = _tmp188 * _tmp189;
  const Scalar _tmp398 = _tmp229 * _tmp238;
  const Scalar _tmp399 = _tmp341 * fh1;
  const Scalar _tmp400 = _tmp345 * fh1;
  const Scalar _tmp401 = _tmp218 * _tmp372;
  const Scalar _tmp402 = Scalar(1.0) * _tmp332;
  const Scalar _tmp403 = _tmp167 * _tmp402;
  const Scalar _tmp404 = _tmp213 * _tmp368;
  const Scalar _tmp405 = _tmp167 * _tmp169 * _tmp249 * _tmp355 - _tmp179 * _tmp403 +
                         _tmp179 * _tmp404 + _tmp181 * _tmp402 - _tmp213 * _tmp371 -
                         _tmp214 * _tmp353;
  const Scalar _tmp406 = _tmp234 * (_tmp207 * _tmp402 - _tmp213 * _tmp331 + _tmp215 * _tmp379 -
                                    _tmp215 * _tmp381 - _tmp216 * _tmp405);
  const Scalar _tmp407 = _tmp217 * _tmp388;
  const Scalar _tmp408 = _tmp401 + _tmp405 + _tmp406 - _tmp407;
  const Scalar _tmp409 = _tmp220 * _tmp393 - _tmp220 * _tmp394 - _tmp222 * _tmp408;
  const Scalar _tmp410 =
      -_tmp193 * _tmp201 *
          (-_tmp138 * _tmp307 * _tmp337 - _tmp141 * _tmp336 +
           _tmp160 * _tmp171 * _tmp325 * _tmp337 + _tmp187 * _tmp336 + _tmp210 * _tmp314 -
           _tmp210 * _tmp339 - _tmp316 * _tmp338 + _tmp333 * _tmp338) -
      _tmp193 * _tmp229 *
          (_tmp141 * _tmp390 + _tmp224 * _tmp395 - _tmp236 * _tmp374 + _tmp236 * _tmp391 +
           _tmp237 * _tmp347 - _tmp237 * _tmp375 - _tmp237 * _tmp392 - _tmp309 * _tmp348) -
      _tmp194 * (_tmp163 * _tmp186 * _tmp333 + _tmp171 * _tmp186 * _tmp327 +
                 _tmp185 * _tmp187 * _tmp373 - _tmp185 * _tmp224 * _tmp394 - _tmp185 * _tmp374 -
                 _tmp186 * _tmp309 + _tmp186 * _tmp314 - _tmp186 * _tmp339) -
      _tmp212 * _tmp346 -
      _tmp228 * (-_tmp183 * _tmp220 * _tmp309 - _tmp220 * _tmp374 + _tmp220 * _tmp391 +
                 _tmp221 * _tmp408 + _tmp223 * _tmp347 - _tmp223 * _tmp375 - _tmp223 * _tmp392 +
                 _tmp224 * _tmp409) +
      _tmp239 * _tmp396 - _tmp239 * _tmp399 - _tmp290 * _tmp291 + _tmp291 * _tmp400 +
      _tmp296 * _tmp297 + _tmp296 * _tmp298 + _tmp296 * _tmp397 + _tmp296 * _tmp398 -
      _tmp297 * _tmp317 - _tmp298 * _tmp317 - _tmp317 * _tmp397 - _tmp317 * _tmp398;
  const Scalar _tmp411 = _tmp282 * _tmp410;
  const Scalar _tmp412 = Scalar(9.6622558468725703) * _tmp410;
  const Scalar _tmp413 = Scalar(0.5) * _tmp342 * fh1;
  const Scalar _tmp414 = Scalar(6.59232) * _tmp29;
  const Scalar _tmp415 = Scalar(6.59232) * _tmp68;
  const Scalar _tmp416 = Scalar(6.59232) * _tmp71;
  const Scalar _tmp417 = Scalar(6.59232) * _tmp18;
  const Scalar _tmp418 = fh1 * (_tmp357 + _tmp384);
  const Scalar _tmp419 = _tmp13 * _tmp415 - _tmp226 * _tmp418 - _tmp24 * _tmp416 -
                         _tmp257 * _tmp289 + _tmp257 * _tmp345 - _tmp288 * fv1 + _tmp414 * _tmp65 -
                         _tmp417 * _tmp74;
  const Scalar _tmp420 = _tmp172 * _tmp373;
  const Scalar _tmp421 = _tmp242 * _tmp356;
  const Scalar _tmp422 = _tmp242 * _tmp353;
  const Scalar _tmp423 = Scalar(1.6799999999999999) * _tmp127 + _tmp354;
  const Scalar _tmp424 = _tmp179 * _tmp423;
  const Scalar _tmp425 =
      (-_tmp349 - _tmp350 + _tmp351 - _tmp421 + _tmp422 - _tmp424) / std::pow(_tmp244, Scalar(2));
  const Scalar _tmp426 = _tmp242 * _tmp425;
  const Scalar _tmp427 = _tmp183 * _tmp370;
  const Scalar _tmp428 = _tmp245 * _tmp423;
  const Scalar _tmp429 = -_tmp219 * _tmp426 + _tmp219 * _tmp428 + _tmp220 * _tmp420 -
                         _tmp220 * _tmp427 - _tmp252 * _tmp408 + _tmp253 * _tmp401 +
                         _tmp253 * _tmp406 - _tmp253 * _tmp407 + _tmp403 - _tmp404;
  const Scalar _tmp430 = Scalar(1.0) * _tmp425;
  const Scalar _tmp431 = Scalar(1.0) * _tmp352;
  const Scalar _tmp432 =
      -_tmp175 * _tmp353 + _tmp175 * _tmp356 + Scalar(1.0) * _tmp179 * _tmp300 + _tmp294;
  const Scalar _tmp433 = _tmp245 * _tmp432;
  const Scalar _tmp434 = _tmp184 * _tmp425;
  const Scalar _tmp435 = _tmp285 + _tmp77;
  const Scalar _tmp436 = _tmp284 + _tmp435;
  const Scalar _tmp437 = _tmp185 * _tmp420 - _tmp185 * _tmp427 - _tmp242 * _tmp433 +
                         _tmp242 * _tmp434 - _tmp269 * _tmp423 + _tmp436;
  const Scalar _tmp438 = _tmp249 * _tmp426;
  const Scalar _tmp439 = _tmp242 * _tmp352;
  const Scalar _tmp440 = _tmp13 * _tmp416 + _tmp199 * _tmp418 + _tmp24 * _tmp415 +
                         _tmp257 * _tmp341 - _tmp257 * _tmp344 + _tmp340 * fv1 + _tmp414 * _tmp74 +
                         _tmp417 * _tmp65;
  const Scalar _tmp441 = -_tmp172 * _tmp390 - _tmp235 * _tmp426 + _tmp235 * _tmp428 +
                         _tmp236 * _tmp420 - _tmp236 * _tmp427 + _tmp253 * _tmp377 +
                         _tmp253 * _tmp387 - _tmp253 * _tmp389 + _tmp383;
  const Scalar _tmp442 = _tmp182 * _tmp210;
  const Scalar _tmp443 = _tmp425 * _tmp442;
  const Scalar _tmp444 =
      -_tmp243 * _tmp430 + _tmp246 * _tmp421 - _tmp246 * _tmp422 + _tmp246 * _tmp424;
  const Scalar _tmp445 = _tmp246 * _tmp353;
  const Scalar _tmp446 = _tmp246 * _tmp376;
  const Scalar _tmp447 = _tmp246 * _tmp388;
  const Scalar _tmp448 = _tmp172 * _tmp336 - _tmp210 * _tmp370 + _tmp242 * _tmp446 -
                         _tmp242 * _tmp447 + _tmp247 * _tmp423 - _tmp426 * _tmp442;
  const Scalar _tmp449 =
      (_tmp241 *
           (-_tmp195 * _tmp262 * _tmp413 - _tmp196 * _tmp255 * _tmp413 +
            Scalar(1.0) * _tmp250 * _tmp346 +
            _tmp251 * (_tmp248 * _tmp431 - _tmp249 * _tmp448 - _tmp443 + _tmp446 - _tmp447) +
            Scalar(1.0) * _tmp255 * _tmp290 +
            _tmp256 * (-_tmp219 * _tmp430 + _tmp246 * _tmp401 + _tmp246 * _tmp406 -
                       _tmp246 * _tmp407 - _tmp249 * _tmp429 + _tmp254 * _tmp431) +
            Scalar(1.0) * _tmp258 * (-_tmp246 * _tmp439 + _tmp259 * _tmp423 + _tmp430 - _tmp438) +
            _tmp260 * _tmp440 + Scalar(1.0) * _tmp262 * _tmp399 +
            _tmp263 * (-_tmp233 * _tmp443 + _tmp246 * _tmp377 + _tmp246 * _tmp387 -
                       _tmp246 * _tmp389 - _tmp249 * _tmp441 + _tmp261 * _tmp431) +
            Scalar(1.0) * _tmp266 * _tmp419 +
            _tmp268 * (-_tmp179 * _tmp430 + _tmp246 * _tmp356 - _tmp249 * _tmp444 +
                       _tmp265 * _tmp431 - _tmp445) +
            _tmp271 *
                (_tmp184 * _tmp430 - _tmp246 * _tmp432 - _tmp249 * _tmp437 + _tmp270 * _tmp431)) -
       _tmp272 * _tmp411) /
      std::sqrt(Scalar(std::pow(_tmp272, Scalar(2)) * _tmp282 + 1));
  const Scalar _tmp450 = _tmp105 + _tmp304;
  const Scalar _tmp451 = 2 * _tmp275 * _tmp436 + 2 * _tmp276 * (_tmp322 + _tmp450);
  const Scalar _tmp452 = Scalar(1.0) * _tmp273;
  const Scalar _tmp453 = -_tmp151 - p_init2 + Scalar(8.3700199099999999);
  const Scalar _tmp454 = _tmp186 * _tmp189;
  const Scalar _tmp455 = _tmp201 * _tmp210;
  const Scalar _tmp456 = _tmp169 * _tmp229;
  const Scalar _tmp457 = _tmp169 * fh1;
  const Scalar _tmp458 = _tmp223 * _tmp457;
  const Scalar _tmp459 =
      -_tmp171 * _tmp454 - _tmp171 * _tmp455 + _tmp226 * _tmp458 + _tmp237 * _tmp456;
  const Scalar _tmp460 = Scalar(9.6622558468725703) * _tmp459;
  const Scalar _tmp461 = _tmp246 * _tmp258;
  const Scalar _tmp462 = _tmp178 * _tmp242;
  const Scalar _tmp463 = _tmp178 * _tmp227;
  const Scalar _tmp464 = _tmp178 * _tmp189;
  const Scalar _tmp465 = _tmp178 * _tmp267;
  const Scalar _tmp466 = _tmp178 * _tmp201;
  const Scalar _tmp467 = _tmp178 * _tmp229;
  const Scalar _tmp468 = _tmp248 * _tmp466 + _tmp254 * _tmp463 + _tmp261 * _tmp467 +
                         _tmp265 * _tmp465 + _tmp270 * _tmp464 - _tmp461 * _tmp462;
  const Scalar _tmp469 = std::pow(_tmp459, Scalar(-2));
  const Scalar _tmp470 = _tmp251 * _tmp335;
  const Scalar _tmp471 = _tmp237 * _tmp457;
  const Scalar _tmp472 = _tmp185 * _tmp189;
  const Scalar _tmp473 = _tmp373 * _tmp472;
  const Scalar _tmp474 = _tmp210 * _tmp346;
  const Scalar _tmp475 =
      -_tmp169 * _tmp394 * _tmp472 + _tmp171 * _tmp470 + _tmp171 * _tmp473 - _tmp171 * _tmp474 -
      _tmp223 * _tmp227 * _tmp332 + _tmp226 * _tmp409 * _tmp457 - _tmp229 * _tmp237 * _tmp332 +
      _tmp289 * _tmp458 - _tmp316 * _tmp455 + _tmp333 * _tmp454 + _tmp333 * _tmp455 +
      _tmp341 * _tmp471 - _tmp344 * _tmp471 - _tmp345 * _tmp458 + _tmp395 * _tmp456;
  const Scalar _tmp476 = _tmp469 * _tmp475;
  const Scalar _tmp477 = _tmp178 * _tmp254;
  const Scalar _tmp478 = _tmp178 * _tmp261;
  const Scalar _tmp479 = _tmp246 * _tmp440;
  const Scalar _tmp480 = Scalar(1.0) / (_tmp459);
  const Scalar _tmp481 =
      (-_tmp468 * _tmp476 +
       _tmp480 * (_tmp178 * _tmp248 * _tmp346 + _tmp178 * _tmp265 * _tmp419 -
                  _tmp178 * _tmp423 * _tmp461 - _tmp189 * _tmp270 * _tmp352 -
                  _tmp201 * _tmp248 * _tmp352 - _tmp227 * _tmp254 * _tmp352 -
                  _tmp229 * _tmp261 * _tmp352 + _tmp258 * _tmp438 - _tmp265 * _tmp267 * _tmp352 +
                  _tmp290 * _tmp477 - _tmp396 * _tmp478 + _tmp399 * _tmp478 - _tmp400 * _tmp477 +
                  _tmp429 * _tmp463 + _tmp437 * _tmp464 + _tmp439 * _tmp461 + _tmp441 * _tmp467 +
                  _tmp444 * _tmp465 + _tmp448 * _tmp466 - _tmp462 * _tmp479)) /
      std::sqrt(Scalar(std::pow(_tmp468, Scalar(2)) * _tmp469 + 1));
  const Scalar _tmp482 = std::asinh(_tmp468 * _tmp480);
  const Scalar _tmp483 = Scalar(9.6622558468725703) * _tmp475;
  const Scalar _tmp484 = Scalar(4.7752063900000001) - _tmp156;
  const Scalar _tmp485 = Scalar(2.71799795) - _tmp159;
  const Scalar _tmp486 = std::pow(_tmp484, Scalar(2)) + std::pow(_tmp485, Scalar(2));
  const Scalar _tmp487 = std::sqrt(_tmp486);
  const Scalar _tmp488 = 2 * _tmp484 * (_tmp435 + _tmp88) + 2 * _tmp485 * (_tmp450 + _tmp98);
  const Scalar _tmp489 = Scalar(0.1034955) * _tmp480;
  const Scalar _tmp490 = -_tmp460 * _tmp482 - _tmp487;
  const Scalar _tmp491 = _tmp489 * _tmp490;
  const Scalar _tmp492 = Scalar(1.0) * _tmp482;
  const Scalar _tmp493 = -_tmp165 - p_init2 + Scalar(8.36416322);
  const Scalar _tmp494 = _tmp183 * fh1;
  const Scalar _tmp495 = _tmp220 * _tmp494;
  const Scalar _tmp496 = _tmp226 * _tmp495 + _tmp229 * _tmp348 + _tmp454 + _tmp455;
  const Scalar _tmp497 = Scalar(1.0) / (_tmp496);
  const Scalar _tmp498 = _tmp227 * _tmp245;
  const Scalar _tmp499 = _tmp229 * _tmp245;
  const Scalar _tmp500 = _tmp189 * _tmp269 - _tmp201 * _tmp247 - _tmp219 * _tmp498 -
                         _tmp235 * _tmp499 - _tmp264 * _tmp267 + _tmp461;
  const Scalar _tmp501 = std::asinh(_tmp497 * _tmp500);
  const Scalar _tmp502 = Scalar(1.0) * _tmp501;
  const Scalar _tmp503 = std::pow(_tmp496, Scalar(-2));
  const Scalar _tmp504 = _tmp235 * _tmp245;
  const Scalar _tmp505 = _tmp219 * _tmp245;
  const Scalar _tmp506 = _tmp236 * _tmp494;
  const Scalar _tmp507 = -_tmp220 * _tmp227 * _tmp373 + _tmp226 * _tmp408 * _tmp494 -
                         _tmp229 * _tmp236 * _tmp373 + _tmp229 * _tmp390 + _tmp289 * _tmp495 +
                         _tmp341 * _tmp506 - _tmp344 * _tmp506 - _tmp345 * _tmp495 - _tmp470 -
                         _tmp473 + _tmp474;
  const Scalar _tmp508 = _tmp503 * _tmp507;
  const Scalar _tmp509 =
      (_tmp497 * (_tmp179 * _tmp268 * _tmp425 + _tmp182 * _tmp425 * _tmp455 + _tmp189 * _tmp433 -
                  _tmp189 * _tmp434 - _tmp201 * _tmp446 + _tmp201 * _tmp447 +
                  _tmp219 * _tmp227 * _tmp425 + _tmp229 * _tmp235 * _tmp425 -
                  _tmp246 * _tmp355 * _tmp465 - _tmp247 * _tmp346 - _tmp258 * _tmp430 -
                  _tmp264 * _tmp419 + _tmp267 * _tmp445 - _tmp290 * _tmp505 - _tmp377 * _tmp499 -
                  _tmp387 * _tmp499 + _tmp389 * _tmp499 + _tmp396 * _tmp504 - _tmp399 * _tmp504 +
                  _tmp400 * _tmp505 - _tmp401 * _tmp498 - _tmp406 * _tmp498 + _tmp407 * _tmp498 +
                  _tmp479) -
       _tmp500 * _tmp508) /
      std::sqrt(Scalar(std::pow(_tmp500, Scalar(2)) * _tmp503 + 1));
  const Scalar _tmp510 = Scalar(9.6622558468725703) * _tmp496;
  const Scalar _tmp511 = -_tmp133 + Scalar(-8.3196563700000006);
  const Scalar _tmp512 = -_tmp137 + Scalar(-1.9874742000000001);
  const Scalar _tmp513 = std::pow(_tmp511, Scalar(2)) + std::pow(_tmp512, Scalar(2));
  const Scalar _tmp514 = std::sqrt(_tmp513);
  const Scalar _tmp515 = -_tmp501 * _tmp510 - _tmp514;
  const Scalar _tmp516 = Scalar(0.1034955) * _tmp497;
  const Scalar _tmp517 = _tmp515 * _tmp516;
  const Scalar _tmp518 = 2 * _tmp511 * (_tmp320 + _tmp77) + 2 * _tmp512 * (_tmp106 + _tmp322);
  const Scalar _tmp519 = Scalar(9.6622558468725703) * _tmp507;
  const Scalar _tmp520 = -_tmp153 - p_init2 + Scalar(8.4718465799999993);

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) =
      Scalar(0.5) * _tmp107 *
          std::cosh(Scalar(0.1034955) * _tmp0 *
                    (-_tmp54 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp0 * fv1))) /
          _tmp54 -
      Scalar(1) / Scalar(2) * (_tmp107 + 2 * _tmp114 * (_tmp120 + _tmp130)) /
          std::sqrt(Scalar(std::pow(_tmp114, Scalar(2)) + _tmp53));
  _res(1, 0) = _tmp274 * (-Scalar(1.0) * _tmp449 * std::cosh(_tmp452) -
                          (-Scalar(0.1034955) * _tmp279 * _tmp411 +
                           _tmp280 * (-_tmp273 * _tmp412 - _tmp274 * _tmp449 -
                                      Scalar(1) / Scalar(2) * _tmp451 / _tmp278)) *
                              std::cosh(_tmp281)) +
               _tmp412 * (-std::sinh(_tmp281) - std::sinh(_tmp452)) -
               Scalar(1) / Scalar(2) * (2 * _tmp385 * _tmp453 + _tmp451) /
                   std::sqrt(Scalar(_tmp277 + std::pow(_tmp453, Scalar(2))));
  _res(2, 0) = _tmp460 * (-Scalar(1.0) * _tmp481 * std::cosh(_tmp492) -
                          (-Scalar(0.1034955) * _tmp476 * _tmp490 +
                           _tmp489 * (-_tmp460 * _tmp481 - _tmp482 * _tmp483 -
                                      Scalar(1) / Scalar(2) * _tmp488 / _tmp487)) *
                              std::cosh(_tmp491)) +
               _tmp483 * (-std::sinh(_tmp491) - std::sinh(_tmp492)) -
               Scalar(1) / Scalar(2) * (_tmp488 + 2 * _tmp493 * (_tmp129 + _tmp359)) /
                   std::sqrt(Scalar(_tmp486 + std::pow(_tmp493, Scalar(2))));
  _res(3, 0) = _tmp510 * (-Scalar(1.0) * _tmp509 * std::cosh(_tmp502) -
                          (-Scalar(0.1034955) * _tmp508 * _tmp515 +
                           _tmp516 * (-_tmp501 * _tmp519 - _tmp509 * _tmp510 -
                                      Scalar(1) / Scalar(2) * _tmp518 / _tmp514)) *
                              std::cosh(_tmp517)) +
               _tmp519 * (-std::sinh(_tmp502) - std::sinh(_tmp517)) -
               Scalar(1) / Scalar(2) * (_tmp518 + 2 * _tmp520 * (_tmp130 + _tmp364)) /
                   std::sqrt(Scalar(_tmp513 + std::pow(_tmp520, Scalar(2))));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
