// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost1_wrt_ry_Nl21
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     rx: Scalar
 *     ry: Scalar
 *     rz: Scalar
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost1WrtRyNl21(
    const Scalar fh1, const Scalar fv1, const Scalar rx, const Scalar ry, const Scalar rz,
    const Scalar p_init0, const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x,
    const Scalar rot_init_y, const Scalar rot_init_z, const Scalar rot_init_w,
    const Scalar epsilon) {
  // Total ops: 1620

  // Unused inputs
  (void)p_init2;
  (void)epsilon;

  // Input arrays

  // Intermediate terms (495)
  const Scalar _tmp0 = std::pow(ry, Scalar(2));
  const Scalar _tmp1 = _tmp0 + std::pow(rx, Scalar(2)) + std::pow(rz, Scalar(2));
  const Scalar _tmp2 = std::sqrt(_tmp1);
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = std::cos(_tmp3);
  const Scalar _tmp5 = _tmp4 * rot_init_z;
  const Scalar _tmp6 = std::sin(_tmp3);
  const Scalar _tmp7 = _tmp6 / _tmp2;
  const Scalar _tmp8 = _tmp7 * rot_init_x;
  const Scalar _tmp9 = _tmp8 * ry;
  const Scalar _tmp10 = _tmp7 * rot_init_y;
  const Scalar _tmp11 = _tmp7 * rot_init_w;
  const Scalar _tmp12 = -_tmp10 * rx + _tmp11 * rz + _tmp5 + _tmp9;
  const Scalar _tmp13 = -2 * std::pow(_tmp12, Scalar(2));
  const Scalar _tmp14 = _tmp4 * rot_init_x;
  const Scalar _tmp15 = _tmp7 * rot_init_z;
  const Scalar _tmp16 = _tmp15 * ry;
  const Scalar _tmp17 = _tmp10 * rz + _tmp11 * rx + _tmp14 - _tmp16;
  const Scalar _tmp18 = 1 - 2 * std::pow(_tmp17, Scalar(2));
  const Scalar _tmp19 = Scalar(0.20999999999999999) * _tmp13 + Scalar(0.20999999999999999) * _tmp18;
  const Scalar _tmp20 = _tmp4 * rot_init_y;
  const Scalar _tmp21 = _tmp11 * ry;
  const Scalar _tmp22 = _tmp15 * rx + _tmp20 + _tmp21 - _tmp8 * rz;
  const Scalar _tmp23 = 2 * _tmp12;
  const Scalar _tmp24 = _tmp22 * _tmp23;
  const Scalar _tmp25 = _tmp4 * rot_init_w;
  const Scalar _tmp26 = _tmp10 * ry;
  const Scalar _tmp27 = -_tmp15 * rz + _tmp25 - _tmp26 - _tmp8 * rx;
  const Scalar _tmp28 = 2 * _tmp27;
  const Scalar _tmp29 = _tmp17 * _tmp28;
  const Scalar _tmp30 = _tmp24 - _tmp29;
  const Scalar _tmp31 = -Scalar(0.010999999999999999) * _tmp30;
  const Scalar _tmp32 = 2 * _tmp17 * _tmp22;
  const Scalar _tmp33 = _tmp12 * _tmp28;
  const Scalar _tmp34 = Scalar(0.20999999999999999) * _tmp32 + Scalar(0.20999999999999999) * _tmp33;
  const Scalar _tmp35 = _tmp31 - _tmp34;
  const Scalar _tmp36 = _tmp19 + _tmp35;
  const Scalar _tmp37 = _tmp36 + p_init1;
  const Scalar _tmp38 = Scalar(4.8333311099999996) - _tmp37;
  const Scalar _tmp39 = -2 * std::pow(_tmp22, Scalar(2));
  const Scalar _tmp40 = Scalar(0.20999999999999999) * _tmp13 +
                        Scalar(0.20999999999999999) * _tmp39 + Scalar(0.20999999999999999);
  const Scalar _tmp41 = -_tmp40;
  const Scalar _tmp42 = _tmp17 * _tmp23;
  const Scalar _tmp43 = _tmp22 * _tmp28;
  const Scalar _tmp44 = _tmp42 + _tmp43;
  const Scalar _tmp45 = -Scalar(0.010999999999999999) * _tmp44;
  const Scalar _tmp46 = Scalar(0.20999999999999999) * _tmp32 - Scalar(0.20999999999999999) * _tmp33;
  const Scalar _tmp47 = _tmp45 + _tmp46;
  const Scalar _tmp48 = _tmp41 + _tmp47;
  const Scalar _tmp49 = _tmp48 + p_init0;
  const Scalar _tmp50 = -_tmp49 + Scalar(-1.79662371);
  const Scalar _tmp51 =
      std::sqrt(Scalar(std::pow(_tmp38, Scalar(2)) + std::pow(_tmp50, Scalar(2))));
  const Scalar _tmp52 = Scalar(1.0) / (fh1);
  const Scalar _tmp53 = (Scalar(1) / Scalar(2)) / _tmp1;
  const Scalar _tmp54 = _tmp0 * _tmp53;
  const Scalar _tmp55 = _tmp53 * ry;
  const Scalar _tmp56 = _tmp55 * rz;
  const Scalar _tmp57 = _tmp55 * rx;
  const Scalar _tmp58 = _tmp6 / (_tmp1 * std::sqrt(_tmp1));
  const Scalar _tmp59 = _tmp0 * _tmp58;
  const Scalar _tmp60 = _tmp58 * ry;
  const Scalar _tmp61 = _tmp60 * rx;
  const Scalar _tmp62 = _tmp60 * rz;
  const Scalar _tmp63 = -_tmp15 + _tmp20 * _tmp56 + _tmp25 * _tmp57 - _tmp5 * _tmp54 +
                        _tmp59 * rot_init_z - _tmp61 * rot_init_w - _tmp62 * rot_init_y -
                        Scalar(1) / Scalar(2) * _tmp9;
  const Scalar _tmp64 = Scalar(0.021999999999999999) * _tmp27;
  const Scalar _tmp65 = _tmp63 * _tmp64;
  const Scalar _tmp66 = -_tmp10 - _tmp14 * _tmp57 - _tmp20 * _tmp54 -
                        Scalar(1) / Scalar(2) * _tmp21 - _tmp5 * _tmp56 + _tmp59 * rot_init_y +
                        _tmp61 * rot_init_x + _tmp62 * rot_init_z;
  const Scalar _tmp67 = _tmp17 * _tmp66;
  const Scalar _tmp68 = Scalar(0.021999999999999999) * _tmp67;
  const Scalar _tmp69 = _tmp14 * _tmp54 - Scalar(1) / Scalar(2) * _tmp16 - _tmp20 * _tmp57 +
                        _tmp25 * _tmp56 - _tmp59 * rot_init_x + _tmp61 * rot_init_y -
                        _tmp62 * rot_init_w + _tmp8;
  const Scalar _tmp70 = Scalar(0.021999999999999999) * _tmp22;
  const Scalar _tmp71 = _tmp69 * _tmp70;
  const Scalar _tmp72 = _tmp11 - _tmp14 * _tmp56 + _tmp25 * _tmp54 -
                        Scalar(1) / Scalar(2) * _tmp26 + _tmp5 * _tmp57 - _tmp59 * rot_init_w -
                        _tmp61 * rot_init_z + _tmp62 * rot_init_x;
  const Scalar _tmp73 = Scalar(0.021999999999999999) * _tmp12;
  const Scalar _tmp74 = _tmp72 * _tmp73;
  const Scalar _tmp75 = -_tmp65 - _tmp68 + _tmp71 + _tmp74;
  const Scalar _tmp76 = Scalar(0.83999999999999997) * _tmp69;
  const Scalar _tmp77 = _tmp12 * _tmp76;
  const Scalar _tmp78 = _tmp17 * _tmp63;
  const Scalar _tmp79 = Scalar(0.83999999999999997) * _tmp78;
  const Scalar _tmp80 = _tmp77 + _tmp79;
  const Scalar _tmp81 = Scalar(0.41999999999999998) * _tmp69;
  const Scalar _tmp82 = _tmp27 * _tmp81;
  const Scalar _tmp83 = Scalar(0.41999999999999998) * _tmp66;
  const Scalar _tmp84 = _tmp12 * _tmp83;
  const Scalar _tmp85 = _tmp82 + _tmp84;
  const Scalar _tmp86 = Scalar(0.41999999999999998) * _tmp72;
  const Scalar _tmp87 = _tmp17 * _tmp86;
  const Scalar _tmp88 = Scalar(0.41999999999999998) * _tmp63;
  const Scalar _tmp89 = _tmp22 * _tmp88;
  const Scalar _tmp90 = _tmp87 + _tmp89;
  const Scalar _tmp91 = _tmp85 + _tmp90;
  const Scalar _tmp92 = _tmp80 + _tmp91;
  const Scalar _tmp93 = -_tmp87 - _tmp89;
  const Scalar _tmp94 = _tmp85 + _tmp93;
  const Scalar _tmp95 = _tmp64 * _tmp72;
  const Scalar _tmp96 = _tmp66 * _tmp70;
  const Scalar _tmp97 = _tmp17 * _tmp69;
  const Scalar _tmp98 = Scalar(0.021999999999999999) * _tmp97;
  const Scalar _tmp99 = _tmp63 * _tmp73;
  const Scalar _tmp100 = _tmp95 + _tmp96 + _tmp98 + _tmp99;
  const Scalar _tmp101 = -_tmp77;
  const Scalar _tmp102 = _tmp22 * _tmp72;
  const Scalar _tmp103 = Scalar(0.83999999999999997) * _tmp102;
  const Scalar _tmp104 = _tmp101 - _tmp103;
  const Scalar _tmp105 = _tmp100 + _tmp104;
  const Scalar _tmp106 = _tmp27 * _tmp88;
  const Scalar _tmp107 = Scalar(0.41999999999999998) * _tmp67;
  const Scalar _tmp108 = _tmp22 * _tmp81;
  const Scalar _tmp109 = _tmp12 * _tmp86;
  const Scalar _tmp110 = _tmp106 + _tmp107 + _tmp108 + _tmp109;
  const Scalar _tmp111 = Scalar(0.043999999999999997) * _tmp102;
  const Scalar _tmp112 = Scalar(0.043999999999999997) * _tmp78;
  const Scalar _tmp113 = _tmp111 + _tmp112;
  const Scalar _tmp114 = _tmp27 * _tmp86;
  const Scalar _tmp115 = _tmp22 * _tmp83;
  const Scalar _tmp116 = _tmp17 * _tmp81;
  const Scalar _tmp117 = _tmp12 * _tmp88;
  const Scalar _tmp118 = _tmp114 + _tmp115 - _tmp116 - _tmp117;
  const Scalar _tmp119 = _tmp113 + _tmp118;
  const Scalar _tmp120 = _tmp110 + _tmp119;
  const Scalar _tmp121 = -_tmp19;
  const Scalar _tmp122 = _tmp31 + _tmp34;
  const Scalar _tmp123 = _tmp121 + _tmp122;
  const Scalar _tmp124 = _tmp123 + p_init1;
  const Scalar _tmp125 = -_tmp124 + Scalar(-8.3888750099999996);
  const Scalar _tmp126 = _tmp45 - _tmp46;
  const Scalar _tmp127 = _tmp126 + _tmp40;
  const Scalar _tmp128 = _tmp127 + p_init0;
  const Scalar _tmp129 = Scalar(2.5202214700000001) - _tmp128;
  const Scalar _tmp130 =
      std::sqrt(Scalar(std::pow(_tmp125, Scalar(2)) + std::pow(_tmp129, Scalar(2))));
  const Scalar _tmp131 = _tmp122 + _tmp19;
  const Scalar _tmp132 = _tmp131 + p_init1;
  const Scalar _tmp133 = _tmp132 + Scalar(-4.7752063900000001);
  const Scalar _tmp134 = _tmp40 + _tmp47;
  const Scalar _tmp135 = _tmp134 + p_init0;
  const Scalar _tmp136 = _tmp135 + Scalar(-2.71799795);
  const Scalar _tmp137 = std::pow(_tmp133, Scalar(2)) + std::pow(_tmp136, Scalar(2));
  const Scalar _tmp138 = std::pow(_tmp137, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp139 = _tmp136 * _tmp138;
  const Scalar _tmp140 = _tmp128 + Scalar(-2.5202214700000001);
  const Scalar _tmp141 = Scalar(1.0) / (_tmp140);
  const Scalar _tmp142 = _tmp124 + Scalar(8.3888750099999996);
  const Scalar _tmp143 = _tmp141 * _tmp142;
  const Scalar _tmp144 = _tmp121 + _tmp35;
  const Scalar _tmp145 = _tmp144 + p_init1;
  const Scalar _tmp146 = _tmp145 + Scalar(8.3196563700000006);
  const Scalar _tmp147 = _tmp126 + _tmp41;
  const Scalar _tmp148 = _tmp147 + p_init0;
  const Scalar _tmp149 = _tmp148 + Scalar(1.9874742000000001);
  const Scalar _tmp150 = std::pow(_tmp146, Scalar(2)) + std::pow(_tmp149, Scalar(2));
  const Scalar _tmp151 = std::pow(_tmp150, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp152 = _tmp149 * _tmp151;
  const Scalar _tmp153 = _tmp146 * _tmp151;
  const Scalar _tmp154 = _tmp143 * _tmp152 - _tmp153;
  const Scalar _tmp155 = std::pow(_tmp140, Scalar(2));
  const Scalar _tmp156 = std::pow(_tmp142, Scalar(2)) + _tmp155;
  const Scalar _tmp157 = std::sqrt(_tmp156);
  const Scalar _tmp158 = Scalar(1.0) / (_tmp157);
  const Scalar _tmp159 = _tmp123 * _tmp158;
  const Scalar _tmp160 = _tmp142 * _tmp158;
  const Scalar _tmp161 = _tmp127 * _tmp160 - _tmp140 * _tmp159;
  const Scalar _tmp162 = _tmp141 * _tmp157;
  const Scalar _tmp163 = _tmp161 * _tmp162;
  const Scalar _tmp164 = _tmp133 * _tmp138;
  const Scalar _tmp165 = _tmp131 * _tmp139 - _tmp134 * _tmp164 + _tmp139 * _tmp163;
  const Scalar _tmp166 = _tmp139 * _tmp143 - _tmp164;
  const Scalar _tmp167 = Scalar(1.0) / (_tmp166);
  const Scalar _tmp168 = _tmp154 * _tmp167;
  const Scalar _tmp169 =
      _tmp144 * _tmp152 - _tmp147 * _tmp153 + _tmp152 * _tmp163 - _tmp165 * _tmp168;
  const Scalar _tmp170 = Scalar(1.0) / (_tmp169);
  const Scalar _tmp171 = Scalar(1.0) * _tmp167;
  const Scalar _tmp172 = _tmp170 * _tmp171;
  const Scalar _tmp173 = _tmp154 * _tmp172;
  const Scalar _tmp174 = Scalar(1.0) * _tmp170;
  const Scalar _tmp175 = -_tmp139 * _tmp173 + _tmp152 * _tmp174;
  const Scalar _tmp176 = _tmp37 + Scalar(-4.8333311099999996);
  const Scalar _tmp177 = _tmp49 + Scalar(1.79662371);
  const Scalar _tmp178 = std::pow(_tmp176, Scalar(2)) + std::pow(_tmp177, Scalar(2));
  const Scalar _tmp179 = std::pow(_tmp178, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp180 = _tmp179 * _tmp48;
  const Scalar _tmp181 = _tmp177 * _tmp179;
  const Scalar _tmp182 = fh1 * (_tmp176 * _tmp180 - _tmp181 * _tmp36);
  const Scalar _tmp183 = _tmp162 * _tmp182;
  const Scalar _tmp184 = _tmp181 * fh1;
  const Scalar _tmp185 =
      Scalar(0.20999999999999999) * _tmp42 - Scalar(0.20999999999999999) * _tmp43;
  const Scalar _tmp186 =
      -Scalar(0.010999999999999999) * _tmp18 - Scalar(0.010999999999999999) * _tmp39;
  const Scalar _tmp187 =
      Scalar(0.20999999999999999) * _tmp24 + Scalar(0.20999999999999999) * _tmp29;
  const Scalar _tmp188 = _tmp186 - _tmp187;
  const Scalar _tmp189 = _tmp185 + _tmp188;
  const Scalar _tmp190 = _tmp139 * _tmp189;
  const Scalar _tmp191 = _tmp186 + _tmp187;
  const Scalar _tmp192 = _tmp185 + _tmp191;
  const Scalar _tmp193 = -_tmp139 * _tmp192 + _tmp190;
  const Scalar _tmp194 = -_tmp185;
  const Scalar _tmp195 = _tmp188 + _tmp194;
  const Scalar _tmp196 = _tmp152 * _tmp189;
  const Scalar _tmp197 = -_tmp143 * _tmp190 + _tmp164 * _tmp192;
  const Scalar _tmp198 = -_tmp143 * _tmp196 + _tmp153 * _tmp195 - _tmp168 * _tmp197;
  const Scalar _tmp199 = Scalar(1.0) * _tmp123;
  const Scalar _tmp200 = -_tmp199;
  const Scalar _tmp201 = _tmp131 + _tmp200;
  const Scalar _tmp202 = Scalar(1.0) / (_tmp201);
  const Scalar _tmp203 = Scalar(1.0) * _tmp127;
  const Scalar _tmp204 = -_tmp134 + _tmp203;
  const Scalar _tmp205 = _tmp202 * _tmp204;
  const Scalar _tmp206 = -_tmp152 * _tmp195 - _tmp168 * _tmp193 + _tmp196 - _tmp198 * _tmp205;
  const Scalar _tmp207 = Scalar(1.0) / (_tmp206);
  const Scalar _tmp208 = _tmp143 * _tmp167;
  const Scalar _tmp209 = _tmp143 * _tmp189;
  const Scalar _tmp210 = _tmp197 * _tmp208 + _tmp209;
  const Scalar _tmp211 = -_tmp189 + _tmp193 * _tmp208 - _tmp205 * _tmp210;
  const Scalar _tmp212 = _tmp169 * _tmp207;
  const Scalar _tmp213 = -_tmp163 + _tmp165 * _tmp208 - _tmp211 * _tmp212;
  const Scalar _tmp214 = _tmp170 * _tmp213;
  const Scalar _tmp215 = _tmp206 * _tmp214;
  const Scalar _tmp216 = _tmp211 + _tmp215;
  const Scalar _tmp217 = _tmp207 * _tmp216;
  const Scalar _tmp218 = _tmp154 * _tmp207;
  const Scalar _tmp219 = -_tmp143 - _tmp216 * _tmp218;
  const Scalar _tmp220 = _tmp139 * _tmp167;
  const Scalar _tmp221 = _tmp152 * _tmp217 + _tmp219 * _tmp220 + Scalar(1.0);
  const Scalar _tmp222 = _tmp162 * _tmp221;
  const Scalar _tmp223 = _tmp199 * _tmp205 + _tmp203;
  const Scalar _tmp224 = 0;
  const Scalar _tmp225 = _tmp207 * _tmp224;
  const Scalar _tmp226 = _tmp168 * _tmp225;
  const Scalar _tmp227 = -_tmp139 * _tmp226 + _tmp152 * _tmp225;
  const Scalar _tmp228 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp229 = _tmp162 * _tmp228;
  const Scalar _tmp230 = _tmp171 * _tmp197;
  const Scalar _tmp231 = -_tmp171 * _tmp193 + _tmp205 * _tmp230;
  const Scalar _tmp232 = -_tmp165 * _tmp171 - _tmp212 * _tmp231;
  const Scalar _tmp233 = _tmp170 * _tmp206;
  const Scalar _tmp234 = _tmp232 * _tmp233;
  const Scalar _tmp235 = _tmp231 + _tmp234;
  const Scalar _tmp236 = -_tmp218 * _tmp235 + Scalar(1.0);
  const Scalar _tmp237 = _tmp207 * _tmp235;
  const Scalar _tmp238 = _tmp152 * _tmp237 + _tmp220 * _tmp236;
  const Scalar _tmp239 = _tmp176 * _tmp179;
  const Scalar _tmp240 = _tmp239 * fh1;
  const Scalar _tmp241 = _tmp162 * _tmp240;
  const Scalar _tmp242 =
      -_tmp175 * _tmp183 - _tmp184 * _tmp222 - _tmp227 * _tmp229 - _tmp238 * _tmp241;
  const Scalar _tmp243 = Scalar(1.0) / (_tmp242);
  const Scalar _tmp244 = _tmp144 + _tmp200;
  const Scalar _tmp245 = _tmp205 * _tmp244;
  const Scalar _tmp246 = -_tmp147 + _tmp203 - _tmp245;
  const Scalar _tmp247 = Scalar(1.0) / (_tmp246);
  const Scalar _tmp248 = Scalar(1.0) * _tmp247;
  const Scalar _tmp249 = _tmp233 * _tmp248;
  const Scalar _tmp250 = -_tmp174 * _tmp198 + _tmp244 * _tmp249;
  const Scalar _tmp251 = Scalar(1.0) * _tmp202;
  const Scalar _tmp252 = _tmp249 - _tmp250 * _tmp251;
  const Scalar _tmp253 = Scalar(1.0) * _tmp182;
  const Scalar _tmp254 = _tmp198 * _tmp207;
  const Scalar _tmp255 = _tmp244 * _tmp247;
  const Scalar _tmp256 = _tmp210 + _tmp215 * _tmp255 - _tmp216 * _tmp254;
  const Scalar _tmp257 = _tmp215 * _tmp248 - _tmp251 * _tmp256;
  const Scalar _tmp258 = Scalar(1.0) * _tmp257;
  const Scalar _tmp259 = fh1 * (_tmp191 + _tmp194);
  const Scalar _tmp260 = _tmp181 * _tmp259 + Scalar(3.29616) * _tmp44 + _tmp48 * fv1;
  const Scalar _tmp261 = _tmp202 * _tmp248;
  const Scalar _tmp262 = Scalar(1.0) * _tmp244 * _tmp261 - Scalar(1.0) * _tmp248;
  const Scalar _tmp263 = -_tmp230 + _tmp234 * _tmp255 - _tmp235 * _tmp254;
  const Scalar _tmp264 = _tmp234 * _tmp248 - _tmp251 * _tmp263;
  const Scalar _tmp265 = Scalar(1.0) * _tmp264;
  const Scalar _tmp266 = _tmp223 * _tmp247;
  const Scalar _tmp267 = -_tmp198 * _tmp225 + _tmp200 - _tmp244 * _tmp266;
  const Scalar _tmp268 = Scalar(1.0) * _tmp228;
  const Scalar _tmp269 = -_tmp239 * _tmp259 - Scalar(3.29616) * _tmp30 - _tmp36 * fv1;
  const Scalar _tmp270 = _tmp205 * _tmp248;
  const Scalar _tmp271 = _tmp245 * _tmp248 + Scalar(1.0);
  const Scalar _tmp272 = -Scalar(1.0) * _tmp251 * _tmp271 + Scalar(1.0) * _tmp270;
  const Scalar _tmp273 =
      _tmp184 * _tmp258 + _tmp240 * _tmp265 + _tmp252 * _tmp253 + _tmp260 * _tmp262 +
      _tmp268 * (-_tmp223 * _tmp248 - _tmp251 * _tmp267 + Scalar(1.0)) + _tmp269 * _tmp272;
  const Scalar _tmp274 = std::asinh(_tmp243 * _tmp273);
  const Scalar _tmp275 = Scalar(9.6622558468725703) * _tmp242;
  const Scalar _tmp276 = -_tmp130 - _tmp274 * _tmp275;
  const Scalar _tmp277 = Scalar(0.1034955) * _tmp243;
  const Scalar _tmp278 = _tmp276 * _tmp277;
  const Scalar _tmp279 = Scalar(1.0) * _tmp274;
  const Scalar _tmp280 = -_tmp95 - _tmp96 - _tmp98 - _tmp99;
  const Scalar _tmp281 = _tmp103 + _tmp77;
  const Scalar _tmp282 = _tmp281 + _tmp94;
  const Scalar _tmp283 = _tmp280 + _tmp282;
  const Scalar _tmp284 = _tmp151 * _tmp283;
  const Scalar _tmp285 = -_tmp82 - _tmp84;
  const Scalar _tmp286 = _tmp285 + _tmp93;
  const Scalar _tmp287 = _tmp286 + _tmp80;
  const Scalar _tmp288 = _tmp65 + _tmp68 - _tmp71 - _tmp74;
  const Scalar _tmp289 = _tmp287 + _tmp288;
  const Scalar _tmp290 =
      (2 * _tmp146 * _tmp289 + 2 * _tmp149 * _tmp283) / (_tmp150 * std::sqrt(_tmp150));
  const Scalar _tmp291 = (Scalar(1) / Scalar(2)) * _tmp290;
  const Scalar _tmp292 = _tmp149 * _tmp291;
  const Scalar _tmp293 = _tmp101 - _tmp79;
  const Scalar _tmp294 = _tmp288 + _tmp293;
  const Scalar _tmp295 = _tmp294 + _tmp91;
  const Scalar _tmp296 = _tmp285 + _tmp90;
  const Scalar _tmp297 = _tmp104 + _tmp280;
  const Scalar _tmp298 = _tmp296 + _tmp297;
  const Scalar _tmp299 =
      (2 * _tmp133 * _tmp295 + 2 * _tmp136 * _tmp298) / (_tmp137 * std::sqrt(_tmp137));
  const Scalar _tmp300 = (Scalar(1) / Scalar(2)) * _tmp299;
  const Scalar _tmp301 = _tmp136 * _tmp300;
  const Scalar _tmp302 = _tmp113 - _tmp114 - _tmp115 + _tmp116 + _tmp117;
  const Scalar _tmp303 = -_tmp106 - _tmp107 - _tmp108 - _tmp109;
  const Scalar _tmp304 = _tmp302 + _tmp303;
  const Scalar _tmp305 = _tmp139 * _tmp304;
  const Scalar _tmp306 = _tmp110 + _tmp302;
  const Scalar _tmp307 = _tmp138 * _tmp298;
  const Scalar _tmp308 = _tmp189 * _tmp307;
  const Scalar _tmp309 = -_tmp139 * _tmp306 - _tmp189 * _tmp301 + _tmp192 * _tmp301 -
                         _tmp192 * _tmp307 + _tmp305 + _tmp308;
  const Scalar _tmp310 = _tmp152 * _tmp304;
  const Scalar _tmp311 = _tmp119 + _tmp303;
  const Scalar _tmp312 = _tmp189 * _tmp284;
  const Scalar _tmp313 = -Scalar(1.6799999999999999) * _tmp12 * _tmp69;
  const Scalar _tmp314 =
      (_tmp313 - Scalar(1.6799999999999999) * _tmp78) / std::pow(_tmp201, Scalar(2));
  const Scalar _tmp315 = _tmp204 * _tmp314;
  const Scalar _tmp316 = _tmp288 + _tmp92;
  const Scalar _tmp317 = _tmp141 * _tmp316;
  const Scalar _tmp318 = _tmp138 * _tmp295;
  const Scalar _tmp319 = _tmp297 + _tmp94;
  const Scalar _tmp320 = _tmp319 / _tmp155;
  const Scalar _tmp321 = _tmp142 * _tmp320;
  const Scalar _tmp322 = _tmp133 * _tmp300;
  const Scalar _tmp323 = (_tmp139 * _tmp317 - _tmp139 * _tmp321 - _tmp143 * _tmp301 +
                          _tmp143 * _tmp307 - _tmp318 + _tmp322) /
                         std::pow(_tmp166, Scalar(2));
  const Scalar _tmp324 = _tmp154 * _tmp323;
  const Scalar _tmp325 = _tmp146 * _tmp291;
  const Scalar _tmp326 = _tmp151 * _tmp289;
  const Scalar _tmp327 = _tmp143 * _tmp284 - _tmp143 * _tmp292 + _tmp152 * _tmp317 -
                         _tmp152 * _tmp321 + _tmp325 - _tmp326;
  const Scalar _tmp328 = _tmp167 * _tmp327;
  const Scalar _tmp329 = _tmp189 * _tmp317;
  const Scalar _tmp330 = -_tmp139 * _tmp329 - _tmp143 * _tmp305 - _tmp143 * _tmp308 +
                         _tmp164 * _tmp306 + _tmp190 * _tmp321 + _tmp192 * _tmp318 -
                         _tmp192 * _tmp322 + _tmp209 * _tmp301;
  const Scalar _tmp331 = -_tmp143 * _tmp310 - _tmp143 * _tmp312 + _tmp153 * _tmp311 -
                         _tmp168 * _tmp330 - _tmp195 * _tmp325 + _tmp195 * _tmp326 -
                         _tmp196 * _tmp317 + _tmp196 * _tmp321 + _tmp197 * _tmp324 -
                         _tmp197 * _tmp328 + _tmp209 * _tmp292;
  const Scalar _tmp332 = _tmp27 * _tmp76;
  const Scalar _tmp333 = Scalar(0.83999999999999997) * _tmp12 * _tmp66;
  const Scalar _tmp334 = -Scalar(0.83999999999999997) * _tmp17 * _tmp72 -
                         Scalar(0.83999999999999997) * _tmp22 * _tmp63;
  const Scalar _tmp335 = _tmp202 * (_tmp332 + _tmp333 + _tmp334);
  const Scalar _tmp336 = -_tmp152 * _tmp311 - _tmp168 * _tmp309 - _tmp189 * _tmp292 +
                         _tmp193 * _tmp324 - _tmp193 * _tmp328 - _tmp195 * _tmp284 +
                         _tmp195 * _tmp292 + _tmp198 * _tmp315 - _tmp198 * _tmp335 -
                         _tmp205 * _tmp331 + _tmp310 + _tmp312;
  const Scalar _tmp337 = _tmp336 / std::pow(_tmp206, Scalar(2));
  const Scalar _tmp338 = _tmp224 * _tmp337;
  const Scalar _tmp339 = _tmp139 * _tmp225;
  const Scalar _tmp340 = _tmp157 * _tmp320;
  const Scalar _tmp341 = _tmp184 * _tmp221;
  const Scalar _tmp342 = _tmp227 * _tmp228;
  const Scalar _tmp343 = _tmp140 * _tmp319 + _tmp142 * _tmp316;
  const Scalar _tmp344 = _tmp141 * _tmp158 * _tmp343;
  const Scalar _tmp345 = _tmp152 * _tmp337;
  const Scalar _tmp346 = _tmp139 * _tmp323;
  const Scalar _tmp347 = _tmp154 * _tmp337;
  const Scalar _tmp348 = _tmp161 * _tmp344;
  const Scalar _tmp349 = _tmp158 * _tmp316;
  const Scalar _tmp350 = _tmp343 / (_tmp156 * std::sqrt(_tmp156));
  const Scalar _tmp351 =
      _tmp162 * (_tmp123 * _tmp140 * _tmp350 - _tmp127 * _tmp142 * _tmp350 + _tmp127 * _tmp349 -
                 _tmp140 * _tmp349 - _tmp159 * _tmp319 + _tmp160 * _tmp319);
  const Scalar _tmp352 = _tmp161 * _tmp340;
  const Scalar _tmp353 = -_tmp131 * _tmp301 + _tmp131 * _tmp307 - _tmp134 * _tmp318 +
                         _tmp134 * _tmp322 + _tmp136 * _tmp318 + _tmp139 * _tmp348 +
                         _tmp139 * _tmp351 - _tmp139 * _tmp352 - _tmp163 * _tmp301 +
                         _tmp163 * _tmp307 - _tmp164 * _tmp298;
  const Scalar _tmp354 = _tmp144 * _tmp284 - _tmp144 * _tmp292 + _tmp147 * _tmp325 -
                         _tmp147 * _tmp326 + _tmp149 * _tmp326 + _tmp152 * _tmp348 +
                         _tmp152 * _tmp351 - _tmp152 * _tmp352 - _tmp153 * _tmp283 +
                         _tmp163 * _tmp284 - _tmp163 * _tmp292 + _tmp165 * _tmp324 -
                         _tmp165 * _tmp328 - _tmp168 * _tmp353;
  const Scalar _tmp355 = _tmp354 / std::pow(_tmp169, Scalar(2));
  const Scalar _tmp356 = _tmp206 * _tmp355;
  const Scalar _tmp357 = _tmp232 * _tmp356;
  const Scalar _tmp358 = _tmp204 * _tmp251;
  const Scalar _tmp359 = Scalar(1.0) * _tmp323;
  const Scalar _tmp360 = _tmp171 * _tmp330;
  const Scalar _tmp361 = -_tmp171 * _tmp309 + _tmp193 * _tmp359 - _tmp197 * _tmp323 * _tmp358 +
                         _tmp205 * _tmp360 - _tmp230 * _tmp315 + _tmp230 * _tmp335;
  const Scalar _tmp362 = _tmp207 * _tmp354;
  const Scalar _tmp363 = _tmp169 * _tmp337;
  const Scalar _tmp364 = _tmp233 * (_tmp165 * _tmp359 - _tmp171 * _tmp353 - _tmp212 * _tmp361 -
                                    _tmp231 * _tmp362 + _tmp231 * _tmp363);
  const Scalar _tmp365 = _tmp170 * _tmp336;
  const Scalar _tmp366 = _tmp232 * _tmp365;
  const Scalar _tmp367 = -_tmp357 + _tmp361 + _tmp364 + _tmp366;
  const Scalar _tmp368 = -_tmp218 * _tmp367 + _tmp235 * _tmp347 - _tmp237 * _tmp327;
  const Scalar _tmp369 = _tmp167 * _tmp236;
  const Scalar _tmp370 = _tmp152 * _tmp207;
  const Scalar _tmp371 = _tmp167 * _tmp307;
  const Scalar _tmp372 = _tmp281 + _tmp296;
  const Scalar _tmp373 = _tmp280 + _tmp372;
  const Scalar _tmp374 = _tmp286 + _tmp294;
  const Scalar _tmp375 =
      (2 * _tmp176 * _tmp374 + 2 * _tmp177 * _tmp373) / (_tmp178 * std::sqrt(_tmp178));
  const Scalar _tmp376 = (Scalar(1) / Scalar(2)) * _tmp375;
  const Scalar _tmp377 = _tmp177 * _tmp376;
  const Scalar _tmp378 = _tmp377 * fh1;
  const Scalar _tmp379 = _tmp179 * _tmp373;
  const Scalar _tmp380 = _tmp379 * fh1;
  const Scalar _tmp381 = _tmp167 * _tmp219;
  const Scalar _tmp382 = _tmp214 * _tmp336;
  const Scalar _tmp383 = _tmp213 * _tmp356;
  const Scalar _tmp384 = _tmp143 * _tmp323;
  const Scalar _tmp385 = _tmp167 * _tmp321;
  const Scalar _tmp386 = _tmp167 * _tmp317;
  const Scalar _tmp387 = _tmp143 * _tmp304 - _tmp189 * _tmp321 - _tmp197 * _tmp384 -
                         _tmp197 * _tmp385 + _tmp197 * _tmp386 + _tmp208 * _tmp330 + _tmp329;
  const Scalar _tmp388 = _tmp110 - _tmp111 - _tmp112 + _tmp118 - _tmp193 * _tmp384 -
                         _tmp193 * _tmp385 + _tmp193 * _tmp386 - _tmp205 * _tmp387 +
                         _tmp208 * _tmp309 + _tmp210 * _tmp315 - _tmp210 * _tmp335;
  const Scalar _tmp389 = _tmp233 * (-_tmp165 * _tmp384 - _tmp165 * _tmp385 + _tmp165 * _tmp386 +
                                    _tmp208 * _tmp353 - _tmp211 * _tmp362 + _tmp211 * _tmp363 -
                                    _tmp212 * _tmp388 - _tmp348 - _tmp351 + _tmp352);
  const Scalar _tmp390 = _tmp382 - _tmp383 + _tmp388 + _tmp389;
  const Scalar _tmp391 =
      _tmp216 * _tmp347 - _tmp217 * _tmp327 - _tmp218 * _tmp390 - _tmp317 + _tmp321;
  const Scalar _tmp392 = _tmp162 * _tmp238;
  const Scalar _tmp393 = _tmp176 * _tmp376;
  const Scalar _tmp394 = _tmp393 * fh1;
  const Scalar _tmp395 = Scalar(0.5) * _tmp170;
  const Scalar _tmp396 = _tmp154 * _tmp171 * _tmp355;
  const Scalar _tmp397 = Scalar(1.0) * _tmp355;
  const Scalar _tmp398 = _tmp238 * _tmp240;
  const Scalar _tmp399 = _tmp179 * _tmp374;
  const Scalar _tmp400 = _tmp399 * fh1;
  const Scalar _tmp401 = _tmp175 * _tmp182;
  const Scalar _tmp402 = fh1 * (_tmp176 * _tmp379 + _tmp180 * _tmp374 - _tmp181 * _tmp374 +
                                _tmp36 * _tmp377 - _tmp36 * _tmp379 - _tmp393 * _tmp48);
  const Scalar _tmp403 =
      -_tmp162 * _tmp175 * _tmp402 -
      _tmp162 * _tmp184 *
          (-_tmp216 * _tmp345 + _tmp217 * _tmp284 - _tmp217 * _tmp292 - _tmp219 * _tmp346 +
           _tmp219 * _tmp371 + _tmp220 * _tmp391 - _tmp301 * _tmp381 + _tmp370 * _tmp390) -
      _tmp183 * (_tmp136 * _tmp168 * _tmp299 * _tmp395 - _tmp139 * _tmp172 * _tmp327 +
                 _tmp139 * _tmp174 * _tmp324 + _tmp139 * _tmp396 - _tmp149 * _tmp290 * _tmp395 -
                 _tmp152 * _tmp397 - _tmp173 * _tmp307 + _tmp174 * _tmp284) +
      _tmp222 * _tmp378 - _tmp222 * _tmp380 -
      _tmp229 *
          (_tmp139 * _tmp168 * _tmp338 - _tmp152 * _tmp338 + _tmp225 * _tmp284 - _tmp225 * _tmp292 +
           _tmp226 * _tmp301 - _tmp226 * _tmp307 + _tmp324 * _tmp339 - _tmp328 * _tmp339) -
      _tmp241 * (_tmp220 * _tmp368 - _tmp235 * _tmp345 - _tmp236 * _tmp346 + _tmp236 * _tmp371 +
                 _tmp237 * _tmp284 - _tmp237 * _tmp292 - _tmp301 * _tmp369 + _tmp367 * _tmp370) +
      _tmp340 * _tmp341 + _tmp340 * _tmp342 + _tmp340 * _tmp398 + _tmp340 * _tmp401 -
      _tmp341 * _tmp344 - _tmp342 * _tmp344 - _tmp344 * _tmp398 - _tmp344 * _tmp401 +
      _tmp392 * _tmp394 - _tmp392 * _tmp400;
  const Scalar _tmp404 = Scalar(9.6622558468725703) * _tmp403;
  const Scalar _tmp405 = std::pow(_tmp242, Scalar(-2));
  const Scalar _tmp406 = _tmp403 * _tmp405;
  const Scalar _tmp407 = Scalar(0.5) * _tmp375 * fh1;
  const Scalar _tmp408 = _tmp198 * _tmp337;
  const Scalar _tmp409 = _tmp244 * _tmp315;
  const Scalar _tmp410 = -_tmp332 - _tmp333 + _tmp334;
  const Scalar _tmp411 = _tmp205 * _tmp410;
  const Scalar _tmp412 = _tmp244 * _tmp335;
  const Scalar _tmp413 =
      (-Scalar(1.6799999999999999) * _tmp102 + _tmp313 + _tmp409 - _tmp411 - _tmp412) /
      std::pow(_tmp246, Scalar(2));
  const Scalar _tmp414 = _tmp244 * _tmp413;
  const Scalar _tmp415 = _tmp247 * _tmp410;
  const Scalar _tmp416 = -_tmp215 * _tmp414 + _tmp215 * _tmp415 + _tmp216 * _tmp408 -
                         _tmp217 * _tmp331 - _tmp254 * _tmp390 + _tmp255 * _tmp382 -
                         _tmp255 * _tmp383 + _tmp255 * _tmp389 + _tmp387;
  const Scalar _tmp417 = Scalar(1.0) * _tmp413;
  const Scalar _tmp418 = Scalar(1.0) * _tmp314;
  const Scalar _tmp419 = _tmp248 * _tmp315;
  const Scalar _tmp420 =
      -_tmp248 * _tmp409 + _tmp248 * _tmp411 + _tmp248 * _tmp412 - _tmp358 * _tmp414;
  const Scalar _tmp421 = _tmp358 * _tmp413;
  const Scalar _tmp422 = _tmp248 * _tmp335;
  const Scalar _tmp423 = _tmp197 * _tmp359 - _tmp234 * _tmp414 + _tmp234 * _tmp415 +
                         _tmp235 * _tmp408 - _tmp237 * _tmp331 - _tmp254 * _tmp367 -
                         _tmp255 * _tmp357 + _tmp255 * _tmp364 + _tmp255 * _tmp366 - _tmp360;
  const Scalar _tmp424 = Scalar(6.59232) * _tmp27;
  const Scalar _tmp425 = _tmp120 * fh1;
  const Scalar _tmp426 = Scalar(6.59232) * _tmp22;
  const Scalar _tmp427 = Scalar(6.59232) * _tmp12;
  const Scalar _tmp428 = -_tmp239 * _tmp425 + _tmp259 * _tmp393 - _tmp259 * _tmp399 -
                         _tmp374 * fv1 + _tmp424 * _tmp63 - _tmp426 * _tmp69 - _tmp427 * _tmp72 +
                         Scalar(6.59232) * _tmp67;
  const Scalar _tmp429 = -_tmp199 * _tmp315 + _tmp199 * _tmp335 + _tmp316 * _tmp358 + _tmp319;
  const Scalar _tmp430 = _tmp247 * _tmp429;
  const Scalar _tmp431 = _tmp223 * _tmp413;
  const Scalar _tmp432 = _tmp293 + _tmp75;
  const Scalar _tmp433 = _tmp286 + _tmp432;
  const Scalar _tmp434 = _tmp224 * _tmp408 - _tmp225 * _tmp331 - _tmp244 * _tmp430 +
                         _tmp244 * _tmp431 - _tmp266 * _tmp410 + _tmp433;
  const Scalar _tmp435 = _tmp181 * _tmp425 - _tmp259 * _tmp377 + _tmp259 * _tmp379 + _tmp373 * fv1 +
                         _tmp424 * _tmp72 + _tmp426 * _tmp66 + _tmp427 * _tmp63 +
                         Scalar(6.59232) * _tmp97;
  const Scalar _tmp436 = _tmp244 * _tmp314;
  const Scalar _tmp437 = _tmp251 * _tmp414;
  const Scalar _tmp438 = _tmp248 * _tmp365;
  const Scalar _tmp439 = _tmp248 * _tmp356;
  const Scalar _tmp440 = _tmp233 * _tmp417;
  const Scalar _tmp441 = -_tmp174 * _tmp331 + _tmp198 * _tmp397 + _tmp244 * _tmp438 -
                         _tmp244 * _tmp439 - _tmp244 * _tmp440 + _tmp249 * _tmp410;
  const Scalar _tmp442 =
      (_tmp243 *
           (-_tmp176 * _tmp264 * _tmp407 - _tmp177 * _tmp257 * _tmp407 +
            Scalar(1.0) * _tmp184 *
                (-_tmp215 * _tmp417 + _tmp248 * _tmp382 - _tmp248 * _tmp383 + _tmp248 * _tmp389 -
                 _tmp251 * _tmp416 + _tmp256 * _tmp418) +
            Scalar(1.0) * _tmp240 *
                (-_tmp234 * _tmp417 - _tmp248 * _tmp357 + _tmp248 * _tmp364 + _tmp248 * _tmp366 -
                 _tmp251 * _tmp423 + _tmp263 * _tmp418) +
            Scalar(1.0) * _tmp252 * _tmp402 +
            _tmp253 * (_tmp250 * _tmp418 - _tmp251 * _tmp441 + _tmp438 - _tmp439 - _tmp440) +
            _tmp258 * _tmp380 +
            Scalar(1.0) * _tmp260 * (-_tmp248 * _tmp436 + _tmp261 * _tmp410 + _tmp417 - _tmp437) +
            _tmp262 * _tmp435 + _tmp265 * _tmp400 +
            _tmp268 *
                (_tmp223 * _tmp417 - _tmp248 * _tmp429 - _tmp251 * _tmp434 + _tmp267 * _tmp418) +
            Scalar(1.0) * _tmp269 *
                (-_tmp251 * _tmp420 + _tmp271 * _tmp418 - _tmp419 - _tmp421 + _tmp422) +
            _tmp272 * _tmp428) -
       _tmp273 * _tmp406) /
      std::sqrt(Scalar(std::pow(_tmp273, Scalar(2)) * _tmp405 + 1));
  const Scalar _tmp443 = _tmp225 * _tmp228;
  const Scalar _tmp444 = _tmp172 * _tmp182;
  const Scalar _tmp445 =
      -_tmp154 * _tmp444 - _tmp168 * _tmp443 + _tmp184 * _tmp381 + _tmp240 * _tmp369;
  const Scalar _tmp446 = std::pow(_tmp445, Scalar(-2));
  const Scalar _tmp447 = _tmp174 * _tmp182;
  const Scalar _tmp448 = _tmp228 * _tmp338;
  const Scalar _tmp449 = _tmp167 * _tmp184 * _tmp391 + _tmp167 * _tmp240 * _tmp368 +
                         _tmp168 * _tmp448 - _tmp173 * _tmp402 + _tmp182 * _tmp396 -
                         _tmp184 * _tmp219 * _tmp323 - _tmp236 * _tmp240 * _tmp323 +
                         _tmp324 * _tmp443 + _tmp324 * _tmp447 - _tmp327 * _tmp444 -
                         _tmp328 * _tmp443 - _tmp369 * _tmp394 + _tmp369 * _tmp400 -
                         _tmp378 * _tmp381 + _tmp380 * _tmp381;
  const Scalar _tmp450 = _tmp446 * _tmp449;
  const Scalar _tmp451 = Scalar(1.0) / (_tmp445);
  const Scalar _tmp452 = _tmp202 * _tmp271;
  const Scalar _tmp453 = _tmp202 * _tmp228;
  const Scalar _tmp454 = _tmp248 * _tmp260;
  const Scalar _tmp455 = _tmp202 * _tmp244;
  const Scalar _tmp456 = _tmp182 * _tmp202;
  const Scalar _tmp457 = _tmp202 * _tmp240;
  const Scalar _tmp458 = _tmp202 * fh1;
  const Scalar _tmp459 = _tmp256 * _tmp458;
  const Scalar _tmp460 = _tmp181 * _tmp459 + _tmp250 * _tmp456 + _tmp263 * _tmp457 +
                         _tmp267 * _tmp453 + _tmp269 * _tmp452 - _tmp454 * _tmp455;
  const Scalar _tmp461 = std::asinh(_tmp451 * _tmp460);
  const Scalar _tmp462 = Scalar(1.0) * _tmp461;
  const Scalar _tmp463 = _tmp263 * _tmp458;
  const Scalar _tmp464 = _tmp248 * _tmp435;
  const Scalar _tmp465 =
      (-_tmp450 * _tmp460 +
       _tmp451 * (_tmp181 * _tmp416 * _tmp458 - _tmp182 * _tmp250 * _tmp314 -
                  _tmp184 * _tmp256 * _tmp314 + _tmp202 * _tmp250 * _tmp402 +
                  _tmp202 * _tmp269 * _tmp420 - _tmp202 * _tmp410 * _tmp454 -
                  _tmp228 * _tmp267 * _tmp314 - _tmp240 * _tmp263 * _tmp314 + _tmp260 * _tmp437 -
                  _tmp269 * _tmp271 * _tmp314 - _tmp377 * _tmp459 + _tmp379 * _tmp459 -
                  _tmp393 * _tmp463 + _tmp399 * _tmp463 + _tmp423 * _tmp457 + _tmp428 * _tmp452 +
                  _tmp434 * _tmp453 + _tmp436 * _tmp454 + _tmp441 * _tmp456 - _tmp455 * _tmp464)) /
      std::sqrt(Scalar(_tmp446 * std::pow(_tmp460, Scalar(2)) + 1));
  const Scalar _tmp466 = Scalar(9.6622558468725703) * _tmp445;
  const Scalar _tmp467 = Scalar(4.7752063900000001) - _tmp132;
  const Scalar _tmp468 = Scalar(2.71799795) - _tmp135;
  const Scalar _tmp469 =
      std::sqrt(Scalar(std::pow(_tmp467, Scalar(2)) + std::pow(_tmp468, Scalar(2))));
  const Scalar _tmp470 = -_tmp461 * _tmp466 - _tmp469;
  const Scalar _tmp471 = Scalar(0.1034955) * _tmp451;
  const Scalar _tmp472 = _tmp470 * _tmp471;
  const Scalar _tmp473 = Scalar(9.6622558468725703) * _tmp449;
  const Scalar _tmp474 = _tmp184 * _tmp217 + _tmp237 * _tmp240 + _tmp443 + _tmp447;
  const Scalar _tmp475 = std::pow(_tmp474, Scalar(-2));
  const Scalar _tmp476 = _tmp174 * _tmp402 + _tmp184 * _tmp207 * _tmp390 -
                         _tmp184 * _tmp216 * _tmp337 + _tmp207 * _tmp240 * _tmp367 -
                         _tmp217 * _tmp378 + _tmp217 * _tmp380 - _tmp235 * _tmp240 * _tmp337 -
                         _tmp237 * _tmp394 + _tmp237 * _tmp400 - _tmp253 * _tmp355 - _tmp448;
  const Scalar _tmp477 = _tmp475 * _tmp476;
  const Scalar _tmp478 = Scalar(1.0) / (_tmp474);
  const Scalar _tmp479 = _tmp184 * _tmp247;
  const Scalar _tmp480 = _tmp240 * _tmp247;
  const Scalar _tmp481 = -_tmp182 * _tmp249 - _tmp215 * _tmp479 + _tmp228 * _tmp266 -
                         _tmp234 * _tmp480 - _tmp269 * _tmp270 + _tmp454;
  const Scalar _tmp482 = std::asinh(_tmp478 * _tmp481);
  const Scalar _tmp483 = Scalar(1.0) * _tmp482;
  const Scalar _tmp484 = _tmp215 * _tmp247;
  const Scalar _tmp485 = _tmp234 * _tmp247;
  const Scalar _tmp486 =
      (-_tmp477 * _tmp481 +
       _tmp478 * (-_tmp182 * _tmp438 + _tmp182 * _tmp439 + _tmp182 * _tmp440 +
                  _tmp184 * _tmp215 * _tmp413 + _tmp228 * _tmp430 - _tmp228 * _tmp431 +
                  _tmp234 * _tmp240 * _tmp413 - _tmp249 * _tmp402 - _tmp260 * _tmp417 +
                  _tmp269 * _tmp419 + _tmp269 * _tmp421 - _tmp269 * _tmp422 - _tmp270 * _tmp428 +
                  _tmp357 * _tmp480 - _tmp364 * _tmp480 - _tmp366 * _tmp480 + _tmp378 * _tmp484 -
                  _tmp380 * _tmp484 - _tmp382 * _tmp479 + _tmp383 * _tmp479 - _tmp389 * _tmp479 +
                  _tmp394 * _tmp485 - _tmp400 * _tmp485 + _tmp464)) /
      std::sqrt(Scalar(_tmp475 * std::pow(_tmp481, Scalar(2)) + 1));
  const Scalar _tmp487 = -_tmp145 + Scalar(-8.3196563700000006);
  const Scalar _tmp488 = -_tmp148 + Scalar(-1.9874742000000001);
  const Scalar _tmp489 =
      std::sqrt(Scalar(std::pow(_tmp487, Scalar(2)) + std::pow(_tmp488, Scalar(2))));
  const Scalar _tmp490 = Scalar(9.6622558468725703) * _tmp474;
  const Scalar _tmp491 = -_tmp482 * _tmp490 - _tmp489;
  const Scalar _tmp492 = Scalar(0.1034955) * _tmp478;
  const Scalar _tmp493 = _tmp491 * _tmp492;
  const Scalar _tmp494 = Scalar(9.6622558468725703) * _tmp476;

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) =
      _tmp120 -
      Scalar(0.5) * (2 * _tmp38 * (_tmp75 + _tmp92) + 2 * _tmp50 * (_tmp105 + _tmp94)) *
          std::sinh(Scalar(0.1034955) * _tmp52 *
                    (-_tmp51 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp52 * fv1))) /
          _tmp51;
  _res(1, 0) =
      -_tmp275 *
          (-Scalar(0.87653584775870996) * _tmp406 + Scalar(1.0) * _tmp442 * std::sinh(_tmp279) -
           (-Scalar(0.1034955) * _tmp276 * _tmp406 +
            _tmp277 * (-_tmp274 * _tmp404 - _tmp275 * _tmp442 -
                       Scalar(1) / Scalar(2) *
                           (2 * _tmp125 * _tmp433 + 2 * _tmp129 * (_tmp100 + _tmp372)) / _tmp130)) *
               std::sinh(_tmp278)) +
      _tmp304 -
      _tmp404 * (Scalar(0.87653584775870996) * _tmp243 - std::cosh(_tmp278) + std::cosh(_tmp279));
  _res(2, 0) =
      _tmp306 -
      _tmp466 *
          (-Scalar(0.86565325453551001) * _tmp450 + Scalar(1.0) * _tmp465 * std::sinh(_tmp462) -
           (-Scalar(0.1034955) * _tmp450 * _tmp470 +
            _tmp471 * (-_tmp461 * _tmp473 - _tmp465 * _tmp466 -
                       Scalar(1) / Scalar(2) *
                           (2 * _tmp467 * (_tmp287 + _tmp75) + 2 * _tmp468 * (_tmp100 + _tmp282)) /
                           _tmp469)) *
               std::sinh(_tmp472)) -
      _tmp473 * (Scalar(0.86565325453551001) * _tmp451 + std::cosh(_tmp462) - std::cosh(_tmp472));
  _res(3, 0) =
      _tmp311 -
      _tmp490 *
          (-Scalar(0.87679799772039002) * _tmp477 + Scalar(1.0) * _tmp486 * std::sinh(_tmp483) -
           (-Scalar(0.1034955) * _tmp477 * _tmp491 +
            _tmp492 * (-_tmp482 * _tmp494 - _tmp486 * _tmp490 -
                       Scalar(1) / Scalar(2) *
                           (2 * _tmp487 * (_tmp432 + _tmp91) + 2 * _tmp488 * (_tmp105 + _tmp296)) /
                           _tmp489)) *
               std::sinh(_tmp493)) -
      _tmp494 * (Scalar(0.87679799772039002) * _tmp478 + std::cosh(_tmp483) - std::cosh(_tmp493));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
