// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost2_Nl12
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     rx: Scalar
 *     ry: Scalar
 *     rz: Scalar
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost2Nl12(
    const Scalar fh1, const Scalar fv1, const Scalar rx, const Scalar ry, const Scalar rz,
    const Scalar p_init0, const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x,
    const Scalar rot_init_y, const Scalar rot_init_z, const Scalar rot_init_w,
    const Scalar epsilon) {
  // Total ops: 545

  // Unused inputs
  (void)epsilon;

  // Input arrays

  // Intermediate terms (170)
  const Scalar _tmp0 = Scalar(1.0) / (fh1);
  const Scalar _tmp1 = std::asinh(_tmp0 * fv1);
  const Scalar _tmp2 = Scalar(9.6622558468725703) * fh1;
  const Scalar _tmp3 = std::sqrt(
      Scalar(std::pow(rx, Scalar(2)) + std::pow(ry, Scalar(2)) + std::pow(rz, Scalar(2))));
  const Scalar _tmp4 = (Scalar(1) / Scalar(2)) * _tmp3;
  const Scalar _tmp5 = std::cos(_tmp4);
  const Scalar _tmp6 = std::sin(_tmp4) / _tmp3;
  const Scalar _tmp7 = _tmp6 * ry;
  const Scalar _tmp8 = _tmp6 * rx;
  const Scalar _tmp9 = _tmp6 * rz;
  const Scalar _tmp10 =
      _tmp5 * rot_init_x - _tmp7 * rot_init_z + _tmp8 * rot_init_w + _tmp9 * rot_init_y;
  const Scalar _tmp11 = -2 * std::pow(_tmp10, Scalar(2));
  const Scalar _tmp12 =
      _tmp5 * rot_init_z + _tmp7 * rot_init_x - _tmp8 * rot_init_y + _tmp9 * rot_init_w;
  const Scalar _tmp13 = -2 * std::pow(_tmp12, Scalar(2));
  const Scalar _tmp14 = Scalar(0.20999999999999999) * _tmp11 +
                        Scalar(0.20999999999999999) * _tmp13 + Scalar(0.20999999999999999);
  const Scalar _tmp15 =
      _tmp5 * rot_init_y + _tmp7 * rot_init_w + _tmp8 * rot_init_z - _tmp9 * rot_init_x;
  const Scalar _tmp16 = 2 * _tmp12 * _tmp15;
  const Scalar _tmp17 = 2 * _tmp5 * rot_init_w - 2 * _tmp7 * rot_init_y - 2 * _tmp8 * rot_init_x -
                        2 * _tmp9 * rot_init_z;
  const Scalar _tmp18 = _tmp10 * _tmp17;
  const Scalar _tmp19 = _tmp16 - _tmp18;
  const Scalar _tmp20 = -Scalar(0.010999999999999999) * _tmp19;
  const Scalar _tmp21 = 2 * _tmp10;
  const Scalar _tmp22 = _tmp15 * _tmp21;
  const Scalar _tmp23 = _tmp12 * _tmp17;
  const Scalar _tmp24 = Scalar(0.20999999999999999) * _tmp22 + Scalar(0.20999999999999999) * _tmp23;
  const Scalar _tmp25 = _tmp20 + _tmp24;
  const Scalar _tmp26 = _tmp14 + _tmp25;
  const Scalar _tmp27 = _tmp26 + p_init1;
  const Scalar _tmp28 = 1 - 2 * std::pow(_tmp15, Scalar(2));
  const Scalar _tmp29 = Scalar(0.20999999999999999) * _tmp13 + Scalar(0.20999999999999999) * _tmp28;
  const Scalar _tmp30 = Scalar(0.20999999999999999) * _tmp22 - Scalar(0.20999999999999999) * _tmp23;
  const Scalar _tmp31 = _tmp12 * _tmp21;
  const Scalar _tmp32 = _tmp15 * _tmp17;
  const Scalar _tmp33 = _tmp31 + _tmp32;
  const Scalar _tmp34 = -Scalar(0.010999999999999999) * _tmp33;
  const Scalar _tmp35 = _tmp30 + _tmp34;
  const Scalar _tmp36 = _tmp29 + _tmp35;
  const Scalar _tmp37 = _tmp36 + p_init0;
  const Scalar _tmp38 = Scalar(22.802596067096832) *
                            std::pow(Scalar(1 - Scalar(0.20941503221602112) * _tmp27), Scalar(2)) +
                        Scalar(7.3875128562042027) *
                            std::pow(Scalar(1 - Scalar(0.36791786395571047) * _tmp37), Scalar(2));
  const Scalar _tmp39 = Scalar(0.20999999999999999) * _tmp31 - Scalar(0.20999999999999999) * _tmp32;
  const Scalar _tmp40 =
      -Scalar(0.010999999999999999) * _tmp11 - Scalar(0.010999999999999999) * _tmp28;
  const Scalar _tmp41 = Scalar(0.20999999999999999) * _tmp16 + Scalar(0.20999999999999999) * _tmp18;
  const Scalar _tmp42 = _tmp40 + _tmp41;
  const Scalar _tmp43 = _tmp39 + _tmp42;
  const Scalar _tmp44 = -_tmp39;
  const Scalar _tmp45 = _tmp40 - _tmp41;
  const Scalar _tmp46 = _tmp44 + _tmp45;
  const Scalar _tmp47 = -_tmp14;
  const Scalar _tmp48 = _tmp20 - _tmp24;
  const Scalar _tmp49 = _tmp47 + _tmp48;
  const Scalar _tmp50 = _tmp49 + p_init1;
  const Scalar _tmp51 = -_tmp29;
  const Scalar _tmp52 = -_tmp30 + _tmp34;
  const Scalar _tmp53 = _tmp51 + _tmp52;
  const Scalar _tmp54 = _tmp53 + p_init0;
  const Scalar _tmp55 = Scalar(69.216682114881593) *
                            std::pow(Scalar(-Scalar(0.12019727204189803) * _tmp50 - 1), Scalar(2)) +
                        Scalar(3.9500536956656402) *
                            std::pow(Scalar(-Scalar(0.50315118556004401) * _tmp54 - 1), Scalar(2));
  const Scalar _tmp56 = _tmp29 + _tmp52;
  const Scalar _tmp57 = _tmp56 + p_init0;
  const Scalar _tmp58 = _tmp57 + Scalar(-2.5202214700000001);
  const Scalar _tmp59 = _tmp25 + _tmp47;
  const Scalar _tmp60 = _tmp59 + p_init1;
  const Scalar _tmp61 = _tmp60 + Scalar(8.3888750099999996);
  const Scalar _tmp62 = std::pow(Scalar(std::pow(_tmp58, Scalar(2)) + std::pow(_tmp61, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp63 = _tmp58 * _tmp62;
  const Scalar _tmp64 = _tmp54 + Scalar(1.9874742000000001);
  const Scalar _tmp65 = _tmp50 + Scalar(8.3196563700000006);
  const Scalar _tmp66 =
      std::sqrt(Scalar(std::pow(_tmp64, Scalar(2)) + std::pow(_tmp65, Scalar(2))));
  const Scalar _tmp67 = Scalar(1.0) / (_tmp66);
  const Scalar _tmp68 = Scalar(1.0) / (_tmp64);
  const Scalar _tmp69 = _tmp66 * _tmp68;
  const Scalar _tmp70 = _tmp69 * (-_tmp49 * _tmp64 * _tmp67 + _tmp53 * _tmp65 * _tmp67);
  const Scalar _tmp71 = _tmp61 * _tmp62;
  const Scalar _tmp72 = -_tmp56 * _tmp71 + _tmp59 * _tmp63 + _tmp63 * _tmp70;
  const Scalar _tmp73 = _tmp65 * _tmp68;
  const Scalar _tmp74 = Scalar(1.0) / (_tmp63 * _tmp73 - _tmp71);
  const Scalar _tmp75 = Scalar(1.0) * _tmp74;
  const Scalar _tmp76 = _tmp39 + _tmp45;
  const Scalar _tmp77 = _tmp46 * _tmp63;
  const Scalar _tmp78 = -_tmp63 * _tmp76 + _tmp77;
  const Scalar _tmp79 = Scalar(1.0) * _tmp49;
  const Scalar _tmp80 = -_tmp79;
  const Scalar _tmp81 = Scalar(1.0) / (_tmp59 + _tmp80);
  const Scalar _tmp82 = Scalar(1.0) * _tmp53;
  const Scalar _tmp83 = _tmp81 * (-_tmp56 + _tmp82);
  const Scalar _tmp84 = _tmp71 * _tmp76 - _tmp73 * _tmp77;
  const Scalar _tmp85 = _tmp75 * _tmp84;
  const Scalar _tmp86 = -_tmp75 * _tmp78 + _tmp83 * _tmp85;
  const Scalar _tmp87 = _tmp14 + _tmp48;
  const Scalar _tmp88 = _tmp87 + p_init1;
  const Scalar _tmp89 = _tmp88 + Scalar(-4.8333311099999996);
  const Scalar _tmp90 = _tmp35 + _tmp51;
  const Scalar _tmp91 = _tmp90 + p_init0;
  const Scalar _tmp92 = _tmp91 + Scalar(1.79662371);
  const Scalar _tmp93 = std::pow(Scalar(std::pow(_tmp89, Scalar(2)) + std::pow(_tmp92, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp94 = _tmp92 * _tmp93;
  const Scalar _tmp95 = _tmp46 * _tmp94;
  const Scalar _tmp96 = _tmp42 + _tmp44;
  const Scalar _tmp97 = _tmp89 * _tmp93;
  const Scalar _tmp98 = _tmp73 * _tmp94 - _tmp97;
  const Scalar _tmp99 = _tmp74 * _tmp98;
  const Scalar _tmp100 = -_tmp73 * _tmp95 - _tmp84 * _tmp99 + _tmp96 * _tmp97;
  const Scalar _tmp101 = -_tmp100 * _tmp83 - _tmp78 * _tmp99 - _tmp94 * _tmp96 + _tmp95;
  const Scalar _tmp102 = Scalar(1.0) / (_tmp101);
  const Scalar _tmp103 = _tmp70 * _tmp94 - _tmp72 * _tmp99 + _tmp87 * _tmp94 - _tmp90 * _tmp97;
  const Scalar _tmp104 = _tmp102 * _tmp103;
  const Scalar _tmp105 = Scalar(1.0) / (_tmp103);
  const Scalar _tmp106 = _tmp101 * _tmp105;
  const Scalar _tmp107 = _tmp106 * (-_tmp104 * _tmp86 - _tmp72 * _tmp75);
  const Scalar _tmp108 = _tmp107 + _tmp86;
  const Scalar _tmp109 = _tmp102 * _tmp94;
  const Scalar _tmp110 = _tmp102 * _tmp98;
  const Scalar _tmp111 = -_tmp108 * _tmp110 + Scalar(1.0);
  const Scalar _tmp112 = _tmp63 * _tmp74;
  const Scalar _tmp113 = _tmp27 + Scalar(-4.7752063900000001);
  const Scalar _tmp114 = _tmp37 + Scalar(-2.71799795);
  const Scalar _tmp115 =
      std::pow(Scalar(std::pow(_tmp113, Scalar(2)) + std::pow(_tmp114, Scalar(2))),
               Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp116 = _tmp113 * _tmp115;
  const Scalar _tmp117 = _tmp116 * fh1;
  const Scalar _tmp118 = Scalar(1.0) * _tmp105;
  const Scalar _tmp119 = _tmp63 * _tmp99;
  const Scalar _tmp120 = _tmp114 * _tmp115;
  const Scalar _tmp121 = fh1 * (_tmp116 * _tmp36 - _tmp120 * _tmp26);
  const Scalar _tmp122 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp123 = _tmp79 * _tmp83 + _tmp82;
  const Scalar _tmp124 = 0;
  const Scalar _tmp125 = _tmp102 * _tmp124;
  const Scalar _tmp126 = _tmp73 * _tmp74;
  const Scalar _tmp127 = _tmp126 * _tmp84 + _tmp46 * _tmp73;
  const Scalar _tmp128 = _tmp126 * _tmp78 - _tmp127 * _tmp83 - _tmp46;
  const Scalar _tmp129 = _tmp106 * (-_tmp104 * _tmp128 + _tmp126 * _tmp72 - _tmp70);
  const Scalar _tmp130 = _tmp128 + _tmp129;
  const Scalar _tmp131 = -_tmp110 * _tmp130 - _tmp73;
  const Scalar _tmp132 = _tmp120 * fh1;
  const Scalar _tmp133 = -_tmp117 * _tmp69 * (_tmp108 * _tmp109 + _tmp111 * _tmp112) -
                         _tmp121 * _tmp69 * (-_tmp118 * _tmp119 + _tmp118 * _tmp94) -
                         _tmp122 * _tmp69 * (-_tmp119 * _tmp125 + _tmp125 * _tmp94) -
                         _tmp132 * _tmp69 * (_tmp109 * _tmp130 + _tmp112 * _tmp131 + Scalar(1.0));
  const Scalar _tmp134 = Scalar(1.0) / (_tmp133);
  const Scalar _tmp135 = _tmp80 + _tmp87;
  const Scalar _tmp136 = _tmp135 * _tmp83;
  const Scalar _tmp137 = Scalar(1.0) / (-_tmp136 + _tmp82 - _tmp90);
  const Scalar _tmp138 = Scalar(1.0) * _tmp137;
  const Scalar _tmp139 = _tmp138 * _tmp83;
  const Scalar _tmp140 = _tmp136 * _tmp138 + Scalar(1.0);
  const Scalar _tmp141 = Scalar(1.0) * _tmp81;
  const Scalar _tmp142 = _tmp43 * fh1;
  const Scalar _tmp143 = -_tmp116 * _tmp142 - Scalar(3.29616) * _tmp19 - _tmp26 * fv1;
  const Scalar _tmp144 = _tmp123 * _tmp137;
  const Scalar _tmp145 = _tmp100 * _tmp102;
  const Scalar _tmp146 = _tmp81 * (-_tmp124 * _tmp145 - _tmp135 * _tmp144 + _tmp80);
  const Scalar _tmp147 = _tmp135 * _tmp137;
  const Scalar _tmp148 = _tmp107 * _tmp147 - _tmp108 * _tmp145 - _tmp85;
  const Scalar _tmp149 = _tmp106 * _tmp138;
  const Scalar _tmp150 = _tmp135 * _tmp138;
  const Scalar _tmp151 = -_tmp100 * _tmp118 + _tmp106 * _tmp150;
  const Scalar _tmp152 = _tmp127 + _tmp129 * _tmp147 - _tmp130 * _tmp145;
  const Scalar _tmp153 = _tmp120 * _tmp142 + Scalar(3.29616) * _tmp33 + _tmp36 * fv1;
  const Scalar _tmp154 =
      std::asinh(_tmp134 * (Scalar(1.0) * _tmp117 * (_tmp107 * _tmp138 - _tmp141 * _tmp148) +
                            Scalar(1.0) * _tmp121 * (-_tmp141 * _tmp151 + _tmp149) +
                            Scalar(1.0) * _tmp122 *
                                (-_tmp123 * _tmp138 - Scalar(1.0) * _tmp146 + Scalar(1.0)) +
                            Scalar(1.0) * _tmp132 * (_tmp129 * _tmp138 - _tmp141 * _tmp152) +
                            Scalar(1.0) * _tmp143 * (_tmp139 - _tmp140 * _tmp141) +
                            Scalar(1.0) * _tmp153 * (-_tmp138 + _tmp150 * _tmp81)));
  const Scalar _tmp155 = Scalar(9.6622558468725703) * _tmp133;
  const Scalar _tmp156 = Scalar(6.351516257848961) *
                             std::pow(Scalar(1 - Scalar(0.39679052492160538) * _tmp57), Scalar(2)) +
                         Scalar(70.3732239334025) *
                             std::pow(Scalar(-Scalar(0.11920549523123722) * _tmp60 - 1), Scalar(2));
  const Scalar _tmp157 = _tmp81 * fh1;
  const Scalar _tmp158 = _tmp138 * _tmp153;
  const Scalar _tmp159 = _tmp122 * _tmp125;
  const Scalar _tmp160 = _tmp118 * _tmp121;
  const Scalar _tmp161 =
      _tmp111 * _tmp117 * _tmp74 + _tmp131 * _tmp132 * _tmp74 - _tmp159 * _tmp99 - _tmp160 * _tmp99;
  const Scalar _tmp162 = Scalar(1.0) / (_tmp161);
  const Scalar _tmp163 =
      std::asinh(_tmp162 * (_tmp116 * _tmp148 * _tmp157 + _tmp120 * _tmp152 * _tmp157 +
                            _tmp121 * _tmp151 * _tmp81 + _tmp122 * _tmp146 -
                            _tmp135 * _tmp158 * _tmp81 + _tmp140 * _tmp143 * _tmp81));
  const Scalar _tmp164 = Scalar(9.6622558468725703) * _tmp161;
  const Scalar _tmp165 = Scalar(23.361089618893828) *
                             std::pow(Scalar(1 - Scalar(0.20689664689659551) * _tmp88), Scalar(2)) +
                         Scalar(3.2278567553341642) *
                             std::pow(Scalar(-Scalar(0.55659957866191134) * _tmp91 - 1), Scalar(2));
  const Scalar _tmp166 =
      _tmp102 * _tmp108 * _tmp117 + _tmp102 * _tmp130 * _tmp132 + _tmp159 + _tmp160;
  const Scalar _tmp167 = Scalar(1.0) / (_tmp166);
  const Scalar _tmp168 =
      std::asinh(_tmp167 * (-_tmp107 * _tmp117 * _tmp137 - _tmp121 * _tmp149 + _tmp122 * _tmp144 -
                            _tmp129 * _tmp132 * _tmp137 - _tmp139 * _tmp143 + _tmp158));
  const Scalar _tmp169 = Scalar(9.6622558468725703) * _tmp166;

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) =
      _tmp2 * (-std::sinh(Scalar(1.0) * _tmp1) -
               std::sinh(Scalar(0.1034955) * _tmp0 * (-_tmp1 * _tmp2 - std::sqrt(_tmp38)))) -
      Scalar(8.36416322) *
          std::sqrt(Scalar(Scalar(0.014294040284261563) * _tmp38 +
                           std::pow(Scalar(-Scalar(0.1195576860108189) * _tmp43 -
                                           Scalar(0.1195576860108189) * p_init2 + 1),
                                    Scalar(2))));
  _res(1, 0) =
      _tmp155 *
          (-std::sinh(Scalar(1.0) * _tmp154) -
           std::sinh(Scalar(0.1034955) * _tmp134 * (-_tmp154 * _tmp155 - std::sqrt(_tmp55)))) -
      Scalar(8.4718465799999993) *
          std::sqrt(Scalar(Scalar(0.013932974275675287) * _tmp55 +
                           std::pow(Scalar(-Scalar(0.11803802046660766) * _tmp46 -
                                           Scalar(0.11803802046660766) * p_init2 + 1),
                                    Scalar(2))));
  _res(2, 0) =
      _tmp164 *
          (-std::sinh(Scalar(1.0) * _tmp163) -
           std::sinh(Scalar(0.1034955) * _tmp162 * (-std::sqrt(_tmp156) - _tmp163 * _tmp164))) -
      Scalar(8.4693136199999994) *
          std::sqrt(Scalar(Scalar(0.013941309530580858) * _tmp156 +
                           std::pow(Scalar(-Scalar(0.11807332268798426) * _tmp76 -
                                           Scalar(0.11807332268798426) * p_init2 + 1),
                                    Scalar(2))));
  _res(3, 0) =
      _tmp169 *
          (-std::sinh(Scalar(1.0) * _tmp168) -
           std::sinh(Scalar(0.1034955) * _tmp167 * (-std::sqrt(_tmp165) - _tmp168 * _tmp169))) -
      Scalar(8.3700199099999999) *
          std::sqrt(Scalar(Scalar(0.01427404356387209) * _tmp165 +
                           std::pow(Scalar(-Scalar(0.11947402882581673) * _tmp96 -
                                           Scalar(0.11947402882581673) * p_init2 + 1),
                                    Scalar(2))));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
