// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost2_wrt_ry_Nl17
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     rx: Scalar
 *     ry: Scalar
 *     rz: Scalar
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost2WrtRyNl17(
    const Scalar fh1, const Scalar fv1, const Scalar rx, const Scalar ry, const Scalar rz,
    const Scalar p_init0, const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x,
    const Scalar rot_init_y, const Scalar rot_init_z, const Scalar rot_init_w,
    const Scalar epsilon) {
  // Total ops: 1662

  // Unused inputs
  (void)epsilon;

  // Input arrays

  // Intermediate terms (518)
  const Scalar _tmp0 = std::pow(ry, Scalar(2));
  const Scalar _tmp1 = _tmp0 + std::pow(rx, Scalar(2)) + std::pow(rz, Scalar(2));
  const Scalar _tmp2 = std::sqrt(_tmp1);
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = std::cos(_tmp3);
  const Scalar _tmp5 = _tmp4 * rot_init_x;
  const Scalar _tmp6 = std::sin(_tmp3);
  const Scalar _tmp7 = _tmp6 / _tmp2;
  const Scalar _tmp8 = _tmp7 * rot_init_z;
  const Scalar _tmp9 = _tmp8 * ry;
  const Scalar _tmp10 = _tmp7 * rot_init_w;
  const Scalar _tmp11 = _tmp7 * rot_init_y;
  const Scalar _tmp12 = _tmp10 * rx + _tmp11 * rz + _tmp5 - _tmp9;
  const Scalar _tmp13 = -2 * std::pow(_tmp12, Scalar(2));
  const Scalar _tmp14 = _tmp4 * rot_init_z;
  const Scalar _tmp15 = _tmp7 * rot_init_x;
  const Scalar _tmp16 = _tmp15 * ry;
  const Scalar _tmp17 = _tmp10 * rz - _tmp11 * rx + _tmp14 + _tmp16;
  const Scalar _tmp18 = -2 * std::pow(_tmp17, Scalar(2));
  const Scalar _tmp19 = Scalar(0.20999999999999999) * _tmp13 +
                        Scalar(0.20999999999999999) * _tmp18 + Scalar(0.20999999999999999);
  const Scalar _tmp20 = _tmp4 * rot_init_y;
  const Scalar _tmp21 = _tmp10 * ry;
  const Scalar _tmp22 = -_tmp15 * rz + _tmp20 + _tmp21 + _tmp8 * rx;
  const Scalar _tmp23 = 2 * _tmp17;
  const Scalar _tmp24 = _tmp22 * _tmp23;
  const Scalar _tmp25 = _tmp4 * rot_init_w;
  const Scalar _tmp26 = _tmp11 * ry;
  const Scalar _tmp27 = -_tmp15 * rx + _tmp25 - _tmp26 - _tmp8 * rz;
  const Scalar _tmp28 = 2 * _tmp27;
  const Scalar _tmp29 = _tmp12 * _tmp28;
  const Scalar _tmp30 = _tmp24 - _tmp29;
  const Scalar _tmp31 = -Scalar(0.010999999999999999) * _tmp30;
  const Scalar _tmp32 = 2 * _tmp12 * _tmp22;
  const Scalar _tmp33 = _tmp17 * _tmp28;
  const Scalar _tmp34 = Scalar(0.20999999999999999) * _tmp32 + Scalar(0.20999999999999999) * _tmp33;
  const Scalar _tmp35 = _tmp31 + _tmp34;
  const Scalar _tmp36 = _tmp19 + _tmp35;
  const Scalar _tmp37 = _tmp36 + p_init1;
  const Scalar _tmp38 = Scalar(4.7752063900000001) - _tmp37;
  const Scalar _tmp39 = 1 - 2 * std::pow(_tmp22, Scalar(2));
  const Scalar _tmp40 = Scalar(0.20999999999999999) * _tmp18 + Scalar(0.20999999999999999) * _tmp39;
  const Scalar _tmp41 = Scalar(0.20999999999999999) * _tmp32 - Scalar(0.20999999999999999) * _tmp33;
  const Scalar _tmp42 = _tmp12 * _tmp23;
  const Scalar _tmp43 = _tmp22 * _tmp28;
  const Scalar _tmp44 = _tmp42 + _tmp43;
  const Scalar _tmp45 = -Scalar(0.010999999999999999) * _tmp44;
  const Scalar _tmp46 = _tmp41 + _tmp45;
  const Scalar _tmp47 = _tmp40 + _tmp46;
  const Scalar _tmp48 = _tmp47 + p_init0;
  const Scalar _tmp49 = Scalar(2.71799795) - _tmp48;
  const Scalar _tmp50 = std::pow(_tmp38, Scalar(2)) + std::pow(_tmp49, Scalar(2));
  const Scalar _tmp51 = std::sqrt(_tmp50);
  const Scalar _tmp52 = Scalar(1.0) / (fh1);
  const Scalar _tmp53 = (Scalar(1) / Scalar(2)) / _tmp1;
  const Scalar _tmp54 = _tmp0 * _tmp53;
  const Scalar _tmp55 = _tmp53 * ry;
  const Scalar _tmp56 = _tmp55 * rz;
  const Scalar _tmp57 = _tmp55 * rx;
  const Scalar _tmp58 = _tmp6 / (_tmp1 * std::sqrt(_tmp1));
  const Scalar _tmp59 = _tmp0 * _tmp58;
  const Scalar _tmp60 = _tmp58 * ry;
  const Scalar _tmp61 = _tmp60 * rx;
  const Scalar _tmp62 = _tmp60 * rz;
  const Scalar _tmp63 = _tmp15 - _tmp20 * _tmp57 + _tmp25 * _tmp56 + _tmp5 * _tmp54 -
                        _tmp59 * rot_init_x + _tmp61 * rot_init_y - _tmp62 * rot_init_w -
                        Scalar(1) / Scalar(2) * _tmp9;
  const Scalar _tmp64 = Scalar(0.41999999999999998) * _tmp27;
  const Scalar _tmp65 = _tmp63 * _tmp64;
  const Scalar _tmp66 = -_tmp11 - _tmp14 * _tmp56 - _tmp20 * _tmp54 -
                        Scalar(1) / Scalar(2) * _tmp21 - _tmp5 * _tmp57 + _tmp59 * rot_init_y +
                        _tmp61 * rot_init_x + _tmp62 * rot_init_z;
  const Scalar _tmp67 = Scalar(0.41999999999999998) * _tmp17;
  const Scalar _tmp68 = _tmp66 * _tmp67;
  const Scalar _tmp69 = -_tmp65 - _tmp68;
  const Scalar _tmp70 = _tmp10 + _tmp14 * _tmp57 + _tmp25 * _tmp54 -
                        Scalar(1) / Scalar(2) * _tmp26 - _tmp5 * _tmp56 - _tmp59 * rot_init_w -
                        _tmp61 * rot_init_z + _tmp62 * rot_init_x;
  const Scalar _tmp71 = Scalar(0.41999999999999998) * _tmp12;
  const Scalar _tmp72 = _tmp70 * _tmp71;
  const Scalar _tmp73 = -_tmp14 * _tmp54 - Scalar(1) / Scalar(2) * _tmp16 + _tmp20 * _tmp56 +
                        _tmp25 * _tmp57 + _tmp59 * rot_init_z - _tmp61 * rot_init_w -
                        _tmp62 * rot_init_y - _tmp8;
  const Scalar _tmp74 = _tmp22 * _tmp73;
  const Scalar _tmp75 = Scalar(0.41999999999999998) * _tmp74;
  const Scalar _tmp76 = -_tmp72 - _tmp75;
  const Scalar _tmp77 = _tmp69 + _tmp76;
  const Scalar _tmp78 = Scalar(0.83999999999999997) * _tmp63;
  const Scalar _tmp79 = _tmp17 * _tmp78;
  const Scalar _tmp80 = _tmp12 * _tmp73;
  const Scalar _tmp81 = Scalar(0.83999999999999997) * _tmp80;
  const Scalar _tmp82 = _tmp79 + _tmp81;
  const Scalar _tmp83 = _tmp77 + _tmp82;
  const Scalar _tmp84 = Scalar(0.021999999999999999) * _tmp27;
  const Scalar _tmp85 = _tmp73 * _tmp84;
  const Scalar _tmp86 = Scalar(0.021999999999999999) * _tmp66;
  const Scalar _tmp87 = _tmp12 * _tmp86;
  const Scalar _tmp88 = Scalar(0.021999999999999999) * _tmp63;
  const Scalar _tmp89 = _tmp22 * _tmp88;
  const Scalar _tmp90 = Scalar(0.021999999999999999) * _tmp17;
  const Scalar _tmp91 = _tmp70 * _tmp90;
  const Scalar _tmp92 = -_tmp85 - _tmp87 + _tmp89 + _tmp91;
  const Scalar _tmp93 = _tmp65 + _tmp68;
  const Scalar _tmp94 = _tmp76 + _tmp93;
  const Scalar _tmp95 = _tmp70 * _tmp84;
  const Scalar _tmp96 = _tmp22 * _tmp86;
  const Scalar _tmp97 = _tmp12 * _tmp88;
  const Scalar _tmp98 = _tmp73 * _tmp90;
  const Scalar _tmp99 = _tmp95 + _tmp96 + _tmp97 + _tmp98;
  const Scalar _tmp100 = Scalar(0.83999999999999997) * _tmp70;
  const Scalar _tmp101 = _tmp100 * _tmp22;
  const Scalar _tmp102 = _tmp101 + _tmp79;
  const Scalar _tmp103 = _tmp102 + _tmp99;
  const Scalar _tmp104 = 2 * _tmp38 * (_tmp83 + _tmp92) + 2 * _tmp49 * (_tmp103 + _tmp94);
  const Scalar _tmp105 = _tmp64 * _tmp70;
  const Scalar _tmp106 = Scalar(0.41999999999999998) * _tmp22;
  const Scalar _tmp107 = _tmp106 * _tmp66;
  const Scalar _tmp108 = _tmp63 * _tmp71;
  const Scalar _tmp109 = _tmp67 * _tmp73;
  const Scalar _tmp110 = _tmp105 + _tmp107 - _tmp108 - _tmp109;
  const Scalar _tmp111 = _tmp22 * _tmp70;
  const Scalar _tmp112 = Scalar(0.043999999999999997) * _tmp111;
  const Scalar _tmp113 = Scalar(0.043999999999999997) * _tmp80;
  const Scalar _tmp114 = -_tmp112 - _tmp113;
  const Scalar _tmp115 = _tmp64 * _tmp73;
  const Scalar _tmp116 = _tmp66 * _tmp71;
  const Scalar _tmp117 = _tmp106 * _tmp63;
  const Scalar _tmp118 = _tmp67 * _tmp70;
  const Scalar _tmp119 = -_tmp115 - _tmp116 - _tmp117 - _tmp118;
  const Scalar _tmp120 = _tmp114 + _tmp119;
  const Scalar _tmp121 =
      Scalar(0.20999999999999999) * _tmp24 + Scalar(0.20999999999999999) * _tmp29;
  const Scalar _tmp122 =
      -Scalar(0.010999999999999999) * _tmp13 - Scalar(0.010999999999999999) * _tmp39;
  const Scalar _tmp123 =
      Scalar(0.20999999999999999) * _tmp42 - Scalar(0.20999999999999999) * _tmp43;
  const Scalar _tmp124 = _tmp122 + _tmp123;
  const Scalar _tmp125 = _tmp121 + _tmp124;
  const Scalar _tmp126 = -_tmp125 - p_init2 + Scalar(8.36416322);
  const Scalar _tmp127 = -_tmp105 - _tmp107 + _tmp108 + _tmp109;
  const Scalar _tmp128 = _tmp120 + _tmp127;
  const Scalar _tmp129 = _tmp122 - _tmp123;
  const Scalar _tmp130 = _tmp121 + _tmp129;
  const Scalar _tmp131 = -_tmp130 - p_init2 + Scalar(8.3700199099999999);
  const Scalar _tmp132 = _tmp72 + _tmp75;
  const Scalar _tmp133 = _tmp132 + _tmp93;
  const Scalar _tmp134 = _tmp133 + _tmp92;
  const Scalar _tmp135 = _tmp134 + _tmp82;
  const Scalar _tmp136 = _tmp31 - _tmp34;
  const Scalar _tmp137 = _tmp136 + _tmp19;
  const Scalar _tmp138 = _tmp137 + p_init1;
  const Scalar _tmp139 = Scalar(4.8333311099999996) - _tmp138;
  const Scalar _tmp140 = -_tmp79;
  const Scalar _tmp141 = -_tmp101 + _tmp140;
  const Scalar _tmp142 = _tmp141 + _tmp94;
  const Scalar _tmp143 = -_tmp40;
  const Scalar _tmp144 = _tmp143 + _tmp46;
  const Scalar _tmp145 = _tmp144 + p_init0;
  const Scalar _tmp146 = -_tmp145 + Scalar(-1.79662371);
  const Scalar _tmp147 = 2 * _tmp135 * _tmp139 + 2 * _tmp146 * (_tmp142 + _tmp99);
  const Scalar _tmp148 = std::pow(_tmp139, Scalar(2)) + std::pow(_tmp146, Scalar(2));
  const Scalar _tmp149 = -_tmp41 + _tmp45;
  const Scalar _tmp150 = _tmp149 + _tmp40;
  const Scalar _tmp151 = _tmp150 + p_init0;
  const Scalar _tmp152 = _tmp151 + Scalar(-2.5202214700000001);
  const Scalar _tmp153 = -_tmp19;
  const Scalar _tmp154 = _tmp153 + _tmp35;
  const Scalar _tmp155 = _tmp154 + p_init1;
  const Scalar _tmp156 = _tmp155 + Scalar(8.3888750099999996);
  const Scalar _tmp157 = std::pow(_tmp152, Scalar(2)) + std::pow(_tmp156, Scalar(2));
  const Scalar _tmp158 = std::pow(_tmp157, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp159 = _tmp152 * _tmp158;
  const Scalar _tmp160 = _tmp138 + Scalar(-4.8333311099999996);
  const Scalar _tmp161 = _tmp145 + Scalar(1.79662371);
  const Scalar _tmp162 = Scalar(1.0) / (_tmp161);
  const Scalar _tmp163 = _tmp160 * _tmp162;
  const Scalar _tmp164 = _tmp136 + _tmp153;
  const Scalar _tmp165 = _tmp164 + p_init1;
  const Scalar _tmp166 = _tmp165 + Scalar(8.3196563700000006);
  const Scalar _tmp167 = _tmp143 + _tmp149;
  const Scalar _tmp168 = _tmp167 + p_init0;
  const Scalar _tmp169 = _tmp168 + Scalar(1.9874742000000001);
  const Scalar _tmp170 = std::pow(_tmp166, Scalar(2)) + std::pow(_tmp169, Scalar(2));
  const Scalar _tmp171 = std::pow(_tmp170, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp172 = _tmp169 * _tmp171;
  const Scalar _tmp173 = _tmp166 * _tmp171;
  const Scalar _tmp174 = _tmp163 * _tmp172 - _tmp173;
  const Scalar _tmp175 = _tmp156 * _tmp158;
  const Scalar _tmp176 = _tmp159 * _tmp163 - _tmp175;
  const Scalar _tmp177 = Scalar(1.0) / (_tmp176);
  const Scalar _tmp178 = std::pow(_tmp161, Scalar(2));
  const Scalar _tmp179 = std::pow(_tmp160, Scalar(2)) + _tmp178;
  const Scalar _tmp180 = std::sqrt(_tmp179);
  const Scalar _tmp181 = Scalar(1.0) / (_tmp180);
  const Scalar _tmp182 = _tmp144 * _tmp181;
  const Scalar _tmp183 = _tmp161 * _tmp181;
  const Scalar _tmp184 = -_tmp137 * _tmp183 + _tmp160 * _tmp182;
  const Scalar _tmp185 = _tmp162 * _tmp180;
  const Scalar _tmp186 = _tmp184 * _tmp185;
  const Scalar _tmp187 = -_tmp150 * _tmp175 + _tmp154 * _tmp159 + _tmp159 * _tmp186;
  const Scalar _tmp188 = _tmp177 * _tmp187;
  const Scalar _tmp189 =
      _tmp164 * _tmp172 - _tmp167 * _tmp173 + _tmp172 * _tmp186 - _tmp174 * _tmp188;
  const Scalar _tmp190 = Scalar(1.0) / (_tmp189);
  const Scalar _tmp191 = Scalar(1.0) * _tmp177;
  const Scalar _tmp192 = _tmp190 * _tmp191;
  const Scalar _tmp193 = _tmp174 * _tmp192;
  const Scalar _tmp194 = Scalar(1.0) * _tmp190;
  const Scalar _tmp195 = -_tmp159 * _tmp193 + _tmp172 * _tmp194;
  const Scalar _tmp196 = _tmp37 + Scalar(-4.7752063900000001);
  const Scalar _tmp197 = _tmp48 + Scalar(-2.71799795);
  const Scalar _tmp198 = std::pow(_tmp196, Scalar(2)) + std::pow(_tmp197, Scalar(2));
  const Scalar _tmp199 = std::pow(_tmp198, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp200 = _tmp196 * _tmp199;
  const Scalar _tmp201 = _tmp199 * _tmp36;
  const Scalar _tmp202 = fh1 * (-_tmp197 * _tmp201 + _tmp200 * _tmp47);
  const Scalar _tmp203 = _tmp185 * _tmp202;
  const Scalar _tmp204 = _tmp200 * fh1;
  const Scalar _tmp205 = -_tmp121;
  const Scalar _tmp206 = _tmp124 + _tmp205;
  const Scalar _tmp207 = _tmp130 * _tmp159;
  const Scalar _tmp208 = -_tmp159 * _tmp206 + _tmp207;
  const Scalar _tmp209 = _tmp174 * _tmp177;
  const Scalar _tmp210 = -_tmp163 * _tmp207 + _tmp175 * _tmp206;
  const Scalar _tmp211 = _tmp130 * _tmp171;
  const Scalar _tmp212 = _tmp169 * _tmp211;
  const Scalar _tmp213 = _tmp129 + _tmp205;
  const Scalar _tmp214 = -_tmp163 * _tmp212 + _tmp173 * _tmp213 - _tmp209 * _tmp210;
  const Scalar _tmp215 = Scalar(1.0) * _tmp137;
  const Scalar _tmp216 = -_tmp215;
  const Scalar _tmp217 = _tmp154 + _tmp216;
  const Scalar _tmp218 = Scalar(1.0) / (_tmp217);
  const Scalar _tmp219 = Scalar(1.0) * _tmp144;
  const Scalar _tmp220 = -_tmp150 + _tmp219;
  const Scalar _tmp221 = _tmp218 * _tmp220;
  const Scalar _tmp222 = -_tmp172 * _tmp213 - _tmp208 * _tmp209 + _tmp212 - _tmp214 * _tmp221;
  const Scalar _tmp223 = Scalar(1.0) / (_tmp222);
  const Scalar _tmp224 = _tmp191 * _tmp210;
  const Scalar _tmp225 = -_tmp191 * _tmp208 + _tmp221 * _tmp224;
  const Scalar _tmp226 = _tmp189 * _tmp223;
  const Scalar _tmp227 = -_tmp187 * _tmp191 - _tmp225 * _tmp226;
  const Scalar _tmp228 = _tmp190 * _tmp222;
  const Scalar _tmp229 = _tmp227 * _tmp228;
  const Scalar _tmp230 = _tmp225 + _tmp229;
  const Scalar _tmp231 = _tmp223 * _tmp230;
  const Scalar _tmp232 = -_tmp174 * _tmp231 + Scalar(1.0);
  const Scalar _tmp233 = _tmp159 * _tmp177;
  const Scalar _tmp234 = _tmp172 * _tmp231 + _tmp232 * _tmp233;
  const Scalar _tmp235 = _tmp185 * _tmp234;
  const Scalar _tmp236 = _tmp215 * _tmp221 + _tmp219;
  const Scalar _tmp237 = 0;
  const Scalar _tmp238 = _tmp223 * _tmp237;
  const Scalar _tmp239 = _tmp159 * _tmp238;
  const Scalar _tmp240 = _tmp172 * _tmp238 - _tmp209 * _tmp239;
  const Scalar _tmp241 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp242 = _tmp185 * _tmp241;
  const Scalar _tmp243 = _tmp177 * _tmp208;
  const Scalar _tmp244 = _tmp130 * _tmp163;
  const Scalar _tmp245 = _tmp163 * _tmp177;
  const Scalar _tmp246 = _tmp210 * _tmp245 + _tmp244;
  const Scalar _tmp247 = -_tmp130 + _tmp163 * _tmp243 - _tmp221 * _tmp246;
  const Scalar _tmp248 = _tmp163 * _tmp188 - _tmp186 - _tmp226 * _tmp247;
  const Scalar _tmp249 = _tmp190 * _tmp248;
  const Scalar _tmp250 = _tmp222 * _tmp249;
  const Scalar _tmp251 = _tmp247 + _tmp250;
  const Scalar _tmp252 = _tmp223 * _tmp251;
  const Scalar _tmp253 = -_tmp163 - _tmp174 * _tmp252;
  const Scalar _tmp254 = _tmp172 * _tmp252 + _tmp233 * _tmp253 + Scalar(1.0);
  const Scalar _tmp255 = _tmp197 * _tmp199;
  const Scalar _tmp256 = _tmp255 * fh1;
  const Scalar _tmp257 = _tmp185 * _tmp256;
  const Scalar _tmp258 =
      -_tmp195 * _tmp203 - _tmp204 * _tmp235 - _tmp240 * _tmp242 - _tmp254 * _tmp257;
  const Scalar _tmp259 = Scalar(1.0) / (_tmp258);
  const Scalar _tmp260 = _tmp125 * fh1;
  const Scalar _tmp261 = _tmp199 * _tmp260;
  const Scalar _tmp262 = _tmp197 * _tmp261 + Scalar(3.29616) * _tmp44 + _tmp47 * fv1;
  const Scalar _tmp263 = _tmp164 + _tmp216;
  const Scalar _tmp264 = _tmp221 * _tmp263;
  const Scalar _tmp265 = -_tmp167 + _tmp219 - _tmp264;
  const Scalar _tmp266 = Scalar(1.0) / (_tmp265);
  const Scalar _tmp267 = Scalar(1.0) * _tmp266;
  const Scalar _tmp268 = _tmp218 * _tmp267;
  const Scalar _tmp269 = Scalar(1.0) * _tmp263 * _tmp268 - Scalar(1.0) * _tmp267;
  const Scalar _tmp270 = _tmp264 * _tmp267 + Scalar(1.0);
  const Scalar _tmp271 = _tmp218 * _tmp270;
  const Scalar _tmp272 = _tmp221 * _tmp267;
  const Scalar _tmp273 = -Scalar(1.0) * _tmp271 + _tmp272;
  const Scalar _tmp274 = -_tmp200 * _tmp260 - Scalar(3.29616) * _tmp30 - _tmp36 * fv1;
  const Scalar _tmp275 = Scalar(1.0) * _tmp274;
  const Scalar _tmp276 = _tmp228 * _tmp267;
  const Scalar _tmp277 = -_tmp194 * _tmp214 + _tmp263 * _tmp276;
  const Scalar _tmp278 = Scalar(1.0) * _tmp218;
  const Scalar _tmp279 = Scalar(1.0) * _tmp276 - Scalar(1.0) * _tmp277 * _tmp278;
  const Scalar _tmp280 = _tmp250 * _tmp266;
  const Scalar _tmp281 = -_tmp214 * _tmp252 + _tmp246 + _tmp263 * _tmp280;
  const Scalar _tmp282 = _tmp250 * _tmp267 - _tmp278 * _tmp281;
  const Scalar _tmp283 = Scalar(1.0) * _tmp282;
  const Scalar _tmp284 = _tmp229 * _tmp266;
  const Scalar _tmp285 = -_tmp214 * _tmp231 - _tmp224 + _tmp263 * _tmp284;
  const Scalar _tmp286 = _tmp229 * _tmp267 - _tmp278 * _tmp285;
  const Scalar _tmp287 = Scalar(1.0) * _tmp286;
  const Scalar _tmp288 = _tmp236 * _tmp266;
  const Scalar _tmp289 = -_tmp214 * _tmp238 + _tmp216 - _tmp263 * _tmp288;
  const Scalar _tmp290 = Scalar(1.0) * _tmp241;
  const Scalar _tmp291 = _tmp202 * _tmp279 + _tmp204 * _tmp287 + _tmp256 * _tmp283 +
                         _tmp262 * _tmp269 + _tmp273 * _tmp275 +
                         _tmp290 * (-_tmp236 * _tmp267 - _tmp278 * _tmp289 + Scalar(1.0));
  const Scalar _tmp292 = std::asinh(_tmp259 * _tmp291);
  const Scalar _tmp293 = Scalar(1.0) * _tmp292;
  const Scalar _tmp294 = std::pow(_tmp258, Scalar(-2));
  const Scalar _tmp295 = _tmp132 + _tmp69;
  const Scalar _tmp296 = -_tmp95 - _tmp96 - _tmp97 - _tmp98;
  const Scalar _tmp297 = _tmp102 + _tmp296;
  const Scalar _tmp298 = _tmp295 + _tmp297;
  const Scalar _tmp299 = _tmp298 / _tmp178;
  const Scalar _tmp300 = _tmp180 * _tmp299;
  const Scalar _tmp301 = _tmp204 * _tmp234;
  const Scalar _tmp302 = _tmp85 + _tmp87 - _tmp89 - _tmp91;
  const Scalar _tmp303 = _tmp140 - _tmp81;
  const Scalar _tmp304 = _tmp303 + _tmp77;
  const Scalar _tmp305 = _tmp302 + _tmp304;
  const Scalar _tmp306 = _tmp160 * _tmp305 + _tmp161 * _tmp298;
  const Scalar _tmp307 = _tmp162 * _tmp181 * _tmp306;
  const Scalar _tmp308 = _tmp133 + _tmp302;
  const Scalar _tmp309 = _tmp308 + _tmp82;
  const Scalar _tmp310 = _tmp142 + _tmp296;
  const Scalar _tmp311 =
      (2 * _tmp152 * _tmp310 + 2 * _tmp156 * _tmp309) / (_tmp157 * std::sqrt(_tmp157));
  const Scalar _tmp312 = (Scalar(1) / Scalar(2)) * _tmp311;
  const Scalar _tmp313 = _tmp156 * _tmp312;
  const Scalar _tmp314 = _tmp158 * _tmp310;
  const Scalar _tmp315 = _tmp160 * _tmp299;
  const Scalar _tmp316 = _tmp162 * _tmp305;
  const Scalar _tmp317 = _tmp152 * _tmp312;
  const Scalar _tmp318 = _tmp158 * _tmp309;
  const Scalar _tmp319 = (-_tmp159 * _tmp315 + _tmp159 * _tmp316 + _tmp163 * _tmp314 -
                          _tmp163 * _tmp317 + _tmp313 - _tmp318) /
                         std::pow(_tmp176, Scalar(2));
  const Scalar _tmp320 = _tmp159 * _tmp319;
  const Scalar _tmp321 = _tmp297 + _tmp94;
  const Scalar _tmp322 = _tmp171 * _tmp321;
  const Scalar _tmp323 = _tmp174 * _tmp319;
  const Scalar _tmp324 = _tmp302 + _tmp83;
  const Scalar _tmp325 =
      (2 * _tmp166 * _tmp324 + 2 * _tmp169 * _tmp321) / (_tmp170 * std::sqrt(_tmp170));
  const Scalar _tmp326 = (Scalar(1) / Scalar(2)) * _tmp325;
  const Scalar _tmp327 = _tmp169 * _tmp326;
  const Scalar _tmp328 = _tmp112 + _tmp113;
  const Scalar _tmp329 = _tmp115 + _tmp116 + _tmp117 + _tmp118;
  const Scalar _tmp330 = _tmp328 + _tmp329;
  const Scalar _tmp331 = _tmp110 + _tmp330;
  const Scalar _tmp332 = _tmp172 * _tmp331;
  const Scalar _tmp333 = _tmp166 * _tmp326;
  const Scalar _tmp334 = _tmp119 + _tmp328;
  const Scalar _tmp335 = _tmp110 + _tmp334;
  const Scalar _tmp336 = _tmp211 * _tmp321;
  const Scalar _tmp337 = _tmp171 * _tmp324;
  const Scalar _tmp338 = _tmp163 * _tmp322 - _tmp163 * _tmp327 - _tmp172 * _tmp315 +
                         _tmp172 * _tmp316 + _tmp333 - _tmp337;
  const Scalar _tmp339 = _tmp177 * _tmp338;
  const Scalar _tmp340 = _tmp130 * _tmp314;
  const Scalar _tmp341 = _tmp163 * _tmp331;
  const Scalar _tmp342 = _tmp127 + _tmp334;
  const Scalar _tmp343 = -_tmp159 * _tmp341 - _tmp163 * _tmp340 + _tmp175 * _tmp342 -
                         _tmp206 * _tmp313 + _tmp206 * _tmp318 + _tmp207 * _tmp315 -
                         _tmp207 * _tmp316 + _tmp244 * _tmp317;
  const Scalar _tmp344 = -_tmp163 * _tmp332 - _tmp163 * _tmp336 + _tmp173 * _tmp335 -
                         _tmp209 * _tmp343 + _tmp210 * _tmp323 - _tmp210 * _tmp339 +
                         _tmp212 * _tmp315 - _tmp212 * _tmp316 - _tmp213 * _tmp333 +
                         _tmp213 * _tmp337 + _tmp244 * _tmp327;
  const Scalar _tmp345 = -_tmp130 * _tmp317 + _tmp159 * _tmp331 - _tmp159 * _tmp342 -
                         _tmp206 * _tmp314 + _tmp206 * _tmp317 + _tmp340;
  const Scalar _tmp346 = _tmp27 * _tmp78;
  const Scalar _tmp347 = Scalar(0.83999999999999997) * _tmp17 * _tmp66;
  const Scalar _tmp348 = Scalar(1.6799999999999999) * _tmp17 * _tmp63;
  const Scalar _tmp349 = _tmp348 + Scalar(1.6799999999999999) * _tmp80;
  const Scalar _tmp350 = _tmp100 * _tmp12 + Scalar(0.83999999999999997) * _tmp74;
  const Scalar _tmp351 = (_tmp346 + _tmp347 + _tmp349 + _tmp350) / std::pow(_tmp217, Scalar(2));
  const Scalar _tmp352 = _tmp220 * _tmp351;
  const Scalar _tmp353 = -_tmp346 - _tmp347 + _tmp350;
  const Scalar _tmp354 = Scalar(1.6799999999999999) * _tmp111 + _tmp348 + _tmp353;
  const Scalar _tmp355 = _tmp218 * _tmp354;
  const Scalar _tmp356 = -_tmp130 * _tmp327 - _tmp172 * _tmp335 + _tmp208 * _tmp323 -
                         _tmp208 * _tmp339 - _tmp209 * _tmp345 - _tmp213 * _tmp322 +
                         _tmp213 * _tmp327 + _tmp214 * _tmp352 - _tmp214 * _tmp355 -
                         _tmp221 * _tmp344 + _tmp332 + _tmp336;
  const Scalar _tmp357 = _tmp249 * _tmp356;
  const Scalar _tmp358 = _tmp181 * _tmp298;
  const Scalar _tmp359 = _tmp306 / (_tmp179 * std::sqrt(_tmp179));
  const Scalar _tmp360 =
      _tmp185 * (_tmp137 * _tmp161 * _tmp359 - _tmp137 * _tmp358 - _tmp144 * _tmp160 * _tmp359 +
                 _tmp160 * _tmp358 + _tmp182 * _tmp305 - _tmp183 * _tmp305);
  const Scalar _tmp361 = _tmp184 * _tmp307;
  const Scalar _tmp362 = _tmp184 * _tmp300;
  const Scalar _tmp363 = _tmp150 * _tmp313 - _tmp150 * _tmp318 + _tmp152 * _tmp318 +
                         _tmp154 * _tmp314 - _tmp154 * _tmp317 + _tmp159 * _tmp360 +
                         _tmp159 * _tmp361 - _tmp159 * _tmp362 - _tmp175 * _tmp310 +
                         _tmp186 * _tmp314 - _tmp186 * _tmp317;
  const Scalar _tmp364 = _tmp164 * _tmp322 - _tmp164 * _tmp327 + _tmp167 * _tmp333 -
                         _tmp167 * _tmp337 + _tmp169 * _tmp337 + _tmp172 * _tmp360 +
                         _tmp172 * _tmp361 - _tmp172 * _tmp362 - _tmp173 * _tmp321 +
                         _tmp186 * _tmp322 - _tmp186 * _tmp327 + _tmp187 * _tmp323 -
                         _tmp188 * _tmp338 - _tmp209 * _tmp363;
  const Scalar _tmp365 = _tmp364 / std::pow(_tmp189, Scalar(2));
  const Scalar _tmp366 = _tmp222 * _tmp365;
  const Scalar _tmp367 = _tmp248 * _tmp366;
  const Scalar _tmp368 = _tmp356 / std::pow(_tmp222, Scalar(2));
  const Scalar _tmp369 = _tmp189 * _tmp368;
  const Scalar _tmp370 = _tmp163 * _tmp319;
  const Scalar _tmp371 = _tmp223 * _tmp364;
  const Scalar _tmp372 = _tmp177 * _tmp210;
  const Scalar _tmp373 = -_tmp130 * _tmp315 + _tmp130 * _tmp316 - _tmp210 * _tmp370 +
                         _tmp245 * _tmp343 - _tmp315 * _tmp372 + _tmp316 * _tmp372 + _tmp341;
  const Scalar _tmp374 = _tmp128 - _tmp208 * _tmp370 - _tmp221 * _tmp373 - _tmp243 * _tmp315 +
                         _tmp243 * _tmp316 + _tmp245 * _tmp345 + _tmp246 * _tmp352 -
                         _tmp246 * _tmp355;
  const Scalar _tmp375 = _tmp228 * (-_tmp187 * _tmp370 - _tmp188 * _tmp315 + _tmp188 * _tmp316 -
                                    _tmp226 * _tmp374 + _tmp245 * _tmp363 + _tmp247 * _tmp369 -
                                    _tmp247 * _tmp371 - _tmp360 - _tmp361 + _tmp362);
  const Scalar _tmp376 = _tmp223 * (_tmp357 - _tmp367 + _tmp374 + _tmp375);
  const Scalar _tmp377 = _tmp177 * _tmp314;
  const Scalar _tmp378 = _tmp172 * _tmp368;
  const Scalar _tmp379 = _tmp174 * _tmp368;
  const Scalar _tmp380 =
      -_tmp174 * _tmp376 + _tmp251 * _tmp379 - _tmp252 * _tmp338 + _tmp315 - _tmp316;
  const Scalar _tmp381 = _tmp177 * _tmp317;
  const Scalar _tmp382 = _tmp240 * _tmp241;
  const Scalar _tmp383 = _tmp195 * _tmp202;
  const Scalar _tmp384 = _tmp254 * _tmp256;
  const Scalar _tmp385 = _tmp141 + _tmp295;
  const Scalar _tmp386 = _tmp296 + _tmp385;
  const Scalar _tmp387 = _tmp199 * _tmp386;
  const Scalar _tmp388 = _tmp387 * fh1;
  const Scalar _tmp389 = _tmp185 * _tmp254;
  const Scalar _tmp390 = _tmp303 + _tmp308;
  const Scalar _tmp391 =
      (2 * _tmp196 * _tmp390 + 2 * _tmp197 * _tmp386) / (_tmp198 * std::sqrt(_tmp198));
  const Scalar _tmp392 = (Scalar(1) / Scalar(2)) * _tmp391;
  const Scalar _tmp393 = _tmp196 * _tmp392;
  const Scalar _tmp394 = _tmp393 * fh1;
  const Scalar _tmp395 = Scalar(1.0) * _tmp319;
  const Scalar _tmp396 = _tmp191 * _tmp343;
  const Scalar _tmp397 = _tmp210 * _tmp395;
  const Scalar _tmp398 = -_tmp191 * _tmp345 + _tmp208 * _tmp395 + _tmp221 * _tmp396 -
                         _tmp221 * _tmp397 - _tmp224 * _tmp352 + _tmp278 * _tmp354 * _tmp372;
  const Scalar _tmp399 = _tmp228 * (_tmp187 * _tmp395 - _tmp191 * _tmp363 + _tmp225 * _tmp369 -
                                    _tmp225 * _tmp371 - _tmp226 * _tmp398);
  const Scalar _tmp400 = _tmp190 * _tmp356;
  const Scalar _tmp401 = _tmp227 * _tmp400;
  const Scalar _tmp402 = _tmp227 * _tmp366;
  const Scalar _tmp403 = _tmp223 * (_tmp398 + _tmp399 + _tmp401 - _tmp402);
  const Scalar _tmp404 = -_tmp174 * _tmp403 + _tmp230 * _tmp379 - _tmp231 * _tmp338;
  const Scalar _tmp405 = _tmp199 * _tmp390;
  const Scalar _tmp406 = _tmp405 * fh1;
  const Scalar _tmp407 = _tmp197 * _tmp392;
  const Scalar _tmp408 = fh1 * (-_tmp197 * _tmp405 + _tmp200 * _tmp386 - _tmp201 * _tmp386 +
                                _tmp36 * _tmp407 - _tmp393 * _tmp47 + _tmp405 * _tmp47);
  const Scalar _tmp409 = _tmp407 * fh1;
  const Scalar _tmp410 = _tmp237 * _tmp368;
  const Scalar _tmp411 = _tmp209 * _tmp238;
  const Scalar _tmp412 = _tmp192 * _tmp338;
  const Scalar _tmp413 = _tmp174 * _tmp191 * _tmp365;
  const Scalar _tmp414 = Scalar(0.5) * _tmp190;
  const Scalar _tmp415 = Scalar(1.0) * _tmp365;
  const Scalar _tmp416 =
      -_tmp185 * _tmp195 * _tmp408 -
      _tmp185 * _tmp204 *
          (_tmp172 * _tmp403 - _tmp230 * _tmp378 + _tmp231 * _tmp322 - _tmp231 * _tmp327 -
           _tmp232 * _tmp320 + _tmp232 * _tmp377 - _tmp232 * _tmp381 + _tmp233 * _tmp404) -
      _tmp203 * (_tmp152 * _tmp209 * _tmp311 * _tmp414 + _tmp159 * _tmp194 * _tmp323 -
                 _tmp159 * _tmp412 + _tmp159 * _tmp413 - _tmp169 * _tmp325 * _tmp414 -
                 _tmp172 * _tmp415 - _tmp193 * _tmp314 + _tmp194 * _tmp322) +
      _tmp235 * _tmp394 - _tmp235 * _tmp406 -
      _tmp242 *
          (_tmp159 * _tmp209 * _tmp410 - _tmp172 * _tmp410 + _tmp238 * _tmp322 - _tmp238 * _tmp327 +
           _tmp239 * _tmp323 - _tmp239 * _tmp339 - _tmp314 * _tmp411 + _tmp317 * _tmp411) -
      _tmp257 * (_tmp172 * _tmp376 + _tmp233 * _tmp380 - _tmp251 * _tmp378 + _tmp252 * _tmp322 -
                 _tmp252 * _tmp327 - _tmp253 * _tmp320 + _tmp253 * _tmp377 - _tmp253 * _tmp381) +
      _tmp300 * _tmp301 + _tmp300 * _tmp382 + _tmp300 * _tmp383 + _tmp300 * _tmp384 -
      _tmp301 * _tmp307 - _tmp307 * _tmp382 - _tmp307 * _tmp383 - _tmp307 * _tmp384 -
      _tmp388 * _tmp389 + _tmp389 * _tmp409;
  const Scalar _tmp417 = _tmp294 * _tmp416;
  const Scalar _tmp418 = _tmp263 * _tmp352;
  const Scalar _tmp419 = _tmp221 * _tmp349;
  const Scalar _tmp420 = _tmp263 * _tmp355;
  const Scalar _tmp421 = (_tmp353 + _tmp418 - _tmp419 - _tmp420) / std::pow(_tmp265, Scalar(2));
  const Scalar _tmp422 = Scalar(1.0) * _tmp421;
  const Scalar _tmp423 = Scalar(1.0) * _tmp351;
  const Scalar _tmp424 = _tmp214 * _tmp368;
  const Scalar _tmp425 = _tmp263 * _tmp266;
  const Scalar _tmp426 = _tmp263 * _tmp421;
  const Scalar _tmp427 = -_tmp214 * _tmp403 - _tmp229 * _tmp426 + _tmp230 * _tmp424 -
                         _tmp231 * _tmp344 + _tmp284 * _tmp349 - _tmp396 + _tmp397 +
                         _tmp399 * _tmp425 + _tmp401 * _tmp425 - _tmp402 * _tmp425;
  const Scalar _tmp428 = Scalar(0.5) * _tmp391 * fh1;
  const Scalar _tmp429 = _tmp263 * _tmp351;
  const Scalar _tmp430 = _tmp278 * _tmp426;
  const Scalar _tmp431 = -_tmp214 * _tmp376 - _tmp250 * _tmp426 + _tmp251 * _tmp424 -
                         _tmp252 * _tmp344 + _tmp280 * _tmp349 + _tmp357 * _tmp425 -
                         _tmp367 * _tmp425 + _tmp373 + _tmp375 * _tmp425;
  const Scalar _tmp432 = _tmp267 * _tmp355;
  const Scalar _tmp433 =
      -_tmp264 * _tmp422 - _tmp267 * _tmp418 + _tmp267 * _tmp419 + _tmp267 * _tmp420;
  const Scalar _tmp434 = _tmp267 * _tmp352;
  const Scalar _tmp435 = Scalar(6.59232) * _tmp27;
  const Scalar _tmp436 = fh1 * (_tmp127 + _tmp330);
  const Scalar _tmp437 = Scalar(6.59232) * _tmp66;
  const Scalar _tmp438 = Scalar(6.59232) * _tmp63;
  const Scalar _tmp439 = Scalar(6.59232) * _tmp17;
  const Scalar _tmp440 = _tmp12 * _tmp438 + _tmp22 * _tmp437 + _tmp255 * _tmp436 -
                         _tmp260 * _tmp407 + _tmp261 * _tmp386 + _tmp386 * fv1 + _tmp435 * _tmp70 +
                         _tmp439 * _tmp73;
  const Scalar _tmp441 =
      -_tmp215 * _tmp352 + _tmp215 * _tmp355 + Scalar(1.0) * _tmp221 * _tmp305 + _tmp298;
  const Scalar _tmp442 = _tmp266 * _tmp441;
  const Scalar _tmp443 = _tmp236 * _tmp421;
  const Scalar _tmp444 = _tmp135 + _tmp237 * _tmp424 - _tmp238 * _tmp344 - _tmp263 * _tmp442 +
                         _tmp263 * _tmp443 - _tmp288 * _tmp349;
  const Scalar _tmp445 = _tmp267 * _tmp366;
  const Scalar _tmp446 = _tmp228 * _tmp422;
  const Scalar _tmp447 = _tmp267 * _tmp400;
  const Scalar _tmp448 = -_tmp194 * _tmp344 + _tmp214 * _tmp415 - _tmp263 * _tmp445 -
                         _tmp263 * _tmp446 + _tmp263 * _tmp447 + _tmp276 * _tmp349;
  const Scalar _tmp449 = _tmp12 * _tmp437 - _tmp200 * _tmp436 - _tmp22 * _tmp438 +
                         _tmp260 * _tmp393 - _tmp260 * _tmp405 - _tmp390 * fv1 + _tmp435 * _tmp73 -
                         _tmp439 * _tmp70;
  const Scalar _tmp450 =
      (_tmp259 *
           (-_tmp196 * _tmp286 * _tmp428 - _tmp197 * _tmp282 * _tmp428 +
            Scalar(1.0) * _tmp202 *
                (_tmp277 * _tmp423 - _tmp278 * _tmp448 - _tmp445 - _tmp446 + _tmp447) +
            Scalar(1.0) * _tmp204 *
                (-_tmp229 * _tmp422 + _tmp267 * _tmp399 + _tmp267 * _tmp401 - _tmp267 * _tmp402 -
                 _tmp278 * _tmp427 + _tmp285 * _tmp423) +
            Scalar(1.0) * _tmp256 *
                (-_tmp250 * _tmp422 + _tmp267 * _tmp357 - _tmp267 * _tmp367 + _tmp267 * _tmp375 -
                 _tmp278 * _tmp431 + _tmp281 * _tmp423) +
            Scalar(1.0) * _tmp262 * (-_tmp267 * _tmp429 + _tmp268 * _tmp349 + _tmp422 - _tmp430) +
            _tmp269 * _tmp440 + Scalar(1.0) * _tmp273 * _tmp449 +
            _tmp275 *
                (-_tmp221 * _tmp422 + _tmp270 * _tmp423 - _tmp278 * _tmp433 + _tmp432 - _tmp434) +
            _tmp279 * _tmp408 + _tmp283 * _tmp388 + _tmp287 * _tmp406 +
            _tmp290 *
                (_tmp236 * _tmp422 - _tmp267 * _tmp441 - _tmp278 * _tmp444 + _tmp289 * _tmp423)) -
       _tmp291 * _tmp417) /
      std::sqrt(Scalar(std::pow(_tmp291, Scalar(2)) * _tmp294 + 1));
  const Scalar _tmp451 = Scalar(9.6622558468725703) * _tmp292;
  const Scalar _tmp452 = std::sqrt(_tmp148);
  const Scalar _tmp453 = -_tmp258 * _tmp451 - _tmp452;
  const Scalar _tmp454 = Scalar(0.1034955) * _tmp259;
  const Scalar _tmp455 = _tmp453 * _tmp454;
  const Scalar _tmp456 = Scalar(9.6622558468725703) * _tmp258;
  const Scalar _tmp457 = _tmp218 * _tmp277;
  const Scalar _tmp458 = _tmp262 * _tmp267;
  const Scalar _tmp459 = _tmp218 * _tmp263;
  const Scalar _tmp460 = _tmp218 * _tmp241;
  const Scalar _tmp461 = _tmp218 * fh1;
  const Scalar _tmp462 = _tmp200 * _tmp461;
  const Scalar _tmp463 = _tmp255 * _tmp461;
  const Scalar _tmp464 = _tmp202 * _tmp457 + _tmp271 * _tmp274 + _tmp281 * _tmp463 +
                         _tmp285 * _tmp462 + _tmp289 * _tmp460 - _tmp458 * _tmp459;
  const Scalar _tmp465 = _tmp238 * _tmp241;
  const Scalar _tmp466 = _tmp177 * fh1;
  const Scalar _tmp467 = _tmp255 * _tmp466;
  const Scalar _tmp468 = _tmp232 * _tmp466;
  const Scalar _tmp469 =
      -_tmp193 * _tmp202 + _tmp200 * _tmp468 - _tmp209 * _tmp465 + _tmp253 * _tmp467;
  const Scalar _tmp470 = Scalar(1.0) / (_tmp469);
  const Scalar _tmp471 = std::asinh(_tmp464 * _tmp470);
  const Scalar _tmp472 = Scalar(1.0) * _tmp471;
  const Scalar _tmp473 = std::pow(_tmp469, Scalar(-2));
  const Scalar _tmp474 = _tmp253 * _tmp466;
  const Scalar _tmp475 = _tmp194 * _tmp202;
  const Scalar _tmp476 = _tmp241 * _tmp410;
  const Scalar _tmp477 = -_tmp193 * _tmp408 + _tmp200 * _tmp404 * _tmp466 - _tmp202 * _tmp412 +
                         _tmp202 * _tmp413 - _tmp204 * _tmp232 * _tmp319 + _tmp209 * _tmp476 -
                         _tmp253 * _tmp256 * _tmp319 + _tmp323 * _tmp465 + _tmp323 * _tmp475 -
                         _tmp339 * _tmp465 + _tmp380 * _tmp467 + _tmp387 * _tmp474 -
                         _tmp393 * _tmp468 + _tmp405 * _tmp468 - _tmp407 * _tmp474;
  const Scalar _tmp478 = _tmp473 * _tmp477;
  const Scalar _tmp479 = _tmp285 * _tmp461;
  const Scalar _tmp480 = _tmp281 * _tmp461;
  const Scalar _tmp481 = _tmp267 * _tmp440;
  const Scalar _tmp482 =
      (-_tmp464 * _tmp478 +
       _tmp470 * (_tmp202 * _tmp218 * _tmp448 - _tmp202 * _tmp277 * _tmp351 -
                  _tmp204 * _tmp285 * _tmp351 + _tmp218 * _tmp274 * _tmp433 -
                  _tmp218 * _tmp349 * _tmp458 - _tmp241 * _tmp289 * _tmp351 -
                  _tmp256 * _tmp281 * _tmp351 + _tmp262 * _tmp430 - _tmp270 * _tmp274 * _tmp351 +
                  _tmp271 * _tmp449 + _tmp387 * _tmp480 - _tmp393 * _tmp479 + _tmp405 * _tmp479 -
                  _tmp407 * _tmp480 + _tmp408 * _tmp457 + _tmp427 * _tmp462 + _tmp429 * _tmp458 +
                  _tmp431 * _tmp463 + _tmp444 * _tmp460 - _tmp459 * _tmp481)) /
      std::sqrt(Scalar(std::pow(_tmp464, Scalar(2)) * _tmp473 + 1));
  const Scalar _tmp483 = Scalar(9.6622558468725703) * _tmp469;
  const Scalar _tmp484 = -_tmp155 + Scalar(-8.3888750099999996);
  const Scalar _tmp485 = Scalar(2.5202214700000001) - _tmp151;
  const Scalar _tmp486 = std::pow(_tmp484, Scalar(2)) + std::pow(_tmp485, Scalar(2));
  const Scalar _tmp487 = std::sqrt(_tmp486);
  const Scalar _tmp488 = 2 * _tmp484 * (_tmp304 + _tmp92) + 2 * _tmp485 * (_tmp103 + _tmp295);
  const Scalar _tmp489 = Scalar(9.6622558468725703) * _tmp477;
  const Scalar _tmp490 = Scalar(0.1034955) * _tmp470;
  const Scalar _tmp491 = -_tmp471 * _tmp483 - _tmp487;
  const Scalar _tmp492 = _tmp490 * _tmp491;
  const Scalar _tmp493 = -_tmp206 - p_init2 + Scalar(8.4693136199999994);
  const Scalar _tmp494 = _tmp114 + _tmp329;
  const Scalar _tmp495 = _tmp252 * fh1;
  const Scalar _tmp496 = _tmp204 * _tmp231 + _tmp255 * _tmp495 + _tmp465 + _tmp475;
  const Scalar _tmp497 = Scalar(1.0) / (_tmp496);
  const Scalar _tmp498 = -_tmp202 * _tmp276 - _tmp204 * _tmp284 + _tmp241 * _tmp288 -
                         _tmp256 * _tmp280 - _tmp272 * _tmp274 + _tmp458;
  const Scalar _tmp499 = std::asinh(_tmp497 * _tmp498);
  const Scalar _tmp500 = Scalar(1.0) * _tmp499;
  const Scalar _tmp501 = Scalar(9.6622558468725703) * _tmp496;
  const Scalar _tmp502 = -_tmp165 + Scalar(-8.3196563700000006);
  const Scalar _tmp503 = -_tmp168 + Scalar(-1.9874742000000001);
  const Scalar _tmp504 = std::pow(_tmp502, Scalar(2)) + std::pow(_tmp503, Scalar(2));
  const Scalar _tmp505 = std::sqrt(_tmp504);
  const Scalar _tmp506 = -_tmp499 * _tmp501 - _tmp505;
  const Scalar _tmp507 = Scalar(0.1034955) * _tmp497;
  const Scalar _tmp508 = _tmp506 * _tmp507;
  const Scalar _tmp509 = _tmp194 * _tmp408 - _tmp202 * _tmp415 - _tmp204 * _tmp230 * _tmp368 +
                         _tmp204 * _tmp403 - _tmp231 * _tmp394 + _tmp231 * _tmp406 -
                         _tmp251 * _tmp256 * _tmp368 + _tmp256 * _tmp376 + _tmp387 * _tmp495 -
                         _tmp407 * _tmp495 - _tmp476;
  const Scalar _tmp510 = Scalar(9.6622558468725703) * _tmp509;
  const Scalar _tmp511 = _tmp256 * _tmp266;
  const Scalar _tmp512 = _tmp204 * _tmp266;
  const Scalar _tmp513 = std::pow(_tmp496, Scalar(-2));
  const Scalar _tmp514 = _tmp509 * _tmp513;
  const Scalar _tmp515 =
      (_tmp497 * (_tmp202 * _tmp445 + _tmp202 * _tmp446 - _tmp202 * _tmp447 +
                  _tmp204 * _tmp229 * _tmp421 + _tmp221 * _tmp275 * _tmp421 + _tmp241 * _tmp442 -
                  _tmp241 * _tmp443 + _tmp250 * _tmp256 * _tmp421 - _tmp262 * _tmp422 -
                  _tmp272 * _tmp449 - _tmp274 * _tmp432 + _tmp274 * _tmp434 - _tmp276 * _tmp408 -
                  _tmp280 * _tmp388 + _tmp280 * _tmp409 + _tmp284 * _tmp394 - _tmp284 * _tmp406 -
                  _tmp357 * _tmp511 + _tmp367 * _tmp511 - _tmp375 * _tmp511 - _tmp399 * _tmp512 -
                  _tmp401 * _tmp512 + _tmp402 * _tmp512 + _tmp481) -
       _tmp498 * _tmp514) /
      std::sqrt(Scalar(std::pow(_tmp498, Scalar(2)) * _tmp513 + 1));
  const Scalar _tmp516 = 2 * _tmp502 * (_tmp134 + _tmp303) + 2 * _tmp503 * (_tmp385 + _tmp99);
  const Scalar _tmp517 = -_tmp213 - p_init2 + Scalar(8.4718465799999993);

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) =
      Scalar(0.5) * _tmp104 *
          std::cosh(Scalar(0.1034955) * _tmp52 *
                    (-_tmp51 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp52 * fv1))) /
          _tmp51 -
      Scalar(1) / Scalar(2) * (_tmp104 + 2 * _tmp126 * (_tmp110 + _tmp120)) /
          std::sqrt(Scalar(std::pow(_tmp126, Scalar(2)) + _tmp50));
  _res(1, 0) = Scalar(9.6622558468725703) * _tmp416 * (-std::sinh(_tmp293) - std::sinh(_tmp455)) +
               _tmp456 * (-Scalar(1.0) * _tmp450 * std::cosh(_tmp293) -
                          (-Scalar(0.1034955) * _tmp417 * _tmp453 +
                           _tmp454 * (-Scalar(1) / Scalar(2) * _tmp147 / _tmp452 -
                                      _tmp416 * _tmp451 - _tmp450 * _tmp456)) *
                              std::cosh(_tmp455)) -
               Scalar(1) / Scalar(2) * (2 * _tmp128 * _tmp131 + _tmp147) /
                   std::sqrt(Scalar(std::pow(_tmp131, Scalar(2)) + _tmp148));
  _res(2, 0) = _tmp483 * (-Scalar(1.0) * _tmp482 * std::cosh(_tmp472) -
                          (-Scalar(0.1034955) * _tmp478 * _tmp491 +
                           _tmp490 * (-_tmp471 * _tmp489 - _tmp482 * _tmp483 -
                                      Scalar(1) / Scalar(2) * _tmp488 / _tmp487)) *
                              std::cosh(_tmp492)) +
               _tmp489 * (-std::sinh(_tmp472) - std::sinh(_tmp492)) -
               Scalar(1) / Scalar(2) * (_tmp488 + 2 * _tmp493 * (_tmp110 + _tmp494)) /
                   std::sqrt(Scalar(_tmp486 + std::pow(_tmp493, Scalar(2))));
  _res(3, 0) = _tmp501 * (-Scalar(1.0) * _tmp515 * std::cosh(_tmp500) -
                          (-Scalar(0.1034955) * _tmp506 * _tmp514 +
                           _tmp507 * (-_tmp499 * _tmp510 - _tmp501 * _tmp515 -
                                      Scalar(1) / Scalar(2) * _tmp516 / _tmp505)) *
                              std::cosh(_tmp508)) +
               _tmp510 * (-std::sinh(_tmp500) - std::sinh(_tmp508)) -
               Scalar(1) / Scalar(2) * (_tmp516 + 2 * _tmp517 * (_tmp127 + _tmp494)) /
                   std::sqrt(Scalar(_tmp504 + std::pow(_tmp517, Scalar(2))));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
