// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost2_wrt_rx_Nl9
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     rx: Scalar
 *     ry: Scalar
 *     rz: Scalar
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost2WrtRxNl9(
    const Scalar fh1, const Scalar fv1, const Scalar rx, const Scalar ry, const Scalar rz,
    const Scalar p_init0, const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x,
    const Scalar rot_init_y, const Scalar rot_init_z, const Scalar rot_init_w,
    const Scalar epsilon) {
  // Total ops: 1658

  // Unused inputs
  (void)epsilon;

  // Input arrays

  // Intermediate terms (515)
  const Scalar _tmp0 = std::pow(rx, Scalar(2));
  const Scalar _tmp1 = _tmp0 + std::pow(ry, Scalar(2)) + std::pow(rz, Scalar(2));
  const Scalar _tmp2 = std::sqrt(_tmp1);
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = std::cos(_tmp3);
  const Scalar _tmp5 = _tmp4 * rot_init_x;
  const Scalar _tmp6 = std::sin(_tmp3);
  const Scalar _tmp7 = _tmp6 / _tmp2;
  const Scalar _tmp8 = _tmp7 * rot_init_z;
  const Scalar _tmp9 = _tmp7 * rot_init_w;
  const Scalar _tmp10 = _tmp9 * rx;
  const Scalar _tmp11 = _tmp7 * rot_init_y;
  const Scalar _tmp12 = _tmp10 + _tmp11 * rz + _tmp5 - _tmp8 * ry;
  const Scalar _tmp13 = _tmp4 * rot_init_z;
  const Scalar _tmp14 = (Scalar(1) / Scalar(2)) / _tmp1;
  const Scalar _tmp15 = _tmp0 * _tmp14;
  const Scalar _tmp16 = _tmp14 * rx;
  const Scalar _tmp17 = _tmp16 * rz;
  const Scalar _tmp18 = _tmp4 * rot_init_w;
  const Scalar _tmp19 = _tmp16 * ry;
  const Scalar _tmp20 = _tmp11 * rx;
  const Scalar _tmp21 = _tmp6 / (_tmp1 * std::sqrt(_tmp1));
  const Scalar _tmp22 = _tmp0 * _tmp21;
  const Scalar _tmp23 = _tmp21 * rx;
  const Scalar _tmp24 = _tmp23 * ry;
  const Scalar _tmp25 = _tmp23 * rz;
  const Scalar _tmp26 = _tmp13 * _tmp15 - _tmp17 * _tmp5 + _tmp18 * _tmp19 -
                        Scalar(1) / Scalar(2) * _tmp20 - _tmp22 * rot_init_z - _tmp24 * rot_init_w +
                        _tmp25 * rot_init_x + _tmp8;
  const Scalar _tmp27 = Scalar(0.41999999999999998) * _tmp26;
  const Scalar _tmp28 = _tmp12 * _tmp27;
  const Scalar _tmp29 = _tmp4 * rot_init_y;
  const Scalar _tmp30 = _tmp8 * rx;
  const Scalar _tmp31 = _tmp7 * rot_init_x;
  const Scalar _tmp32 = _tmp29 + _tmp30 - _tmp31 * rz + _tmp9 * ry;
  const Scalar _tmp33 = _tmp31 * rx;
  const Scalar _tmp34 = -_tmp13 * _tmp19 + _tmp15 * _tmp18 + _tmp17 * _tmp29 - _tmp22 * rot_init_w +
                        _tmp24 * rot_init_z - _tmp25 * rot_init_y - Scalar(1) / Scalar(2) * _tmp33 +
                        _tmp9;
  const Scalar _tmp35 = Scalar(0.41999999999999998) * _tmp34;
  const Scalar _tmp36 = _tmp32 * _tmp35;
  const Scalar _tmp37 = -_tmp28 - _tmp36;
  const Scalar _tmp38 = _tmp13 - _tmp20 + _tmp31 * ry + _tmp9 * rz;
  const Scalar _tmp39 = -Scalar(1) / Scalar(2) * _tmp10 - _tmp13 * _tmp17 - _tmp15 * _tmp5 -
                        _tmp19 * _tmp29 + _tmp22 * rot_init_x + _tmp24 * rot_init_y +
                        _tmp25 * rot_init_z - _tmp31;
  const Scalar _tmp40 = Scalar(0.41999999999999998) * _tmp39;
  const Scalar _tmp41 = _tmp38 * _tmp40;
  const Scalar _tmp42 = -_tmp11 * ry + _tmp18 - _tmp33 - _tmp8 * rz;
  const Scalar _tmp43 = -_tmp11 - _tmp15 * _tmp29 + _tmp17 * _tmp18 + _tmp19 * _tmp5 +
                        _tmp22 * rot_init_y - _tmp24 * rot_init_x - _tmp25 * rot_init_w -
                        Scalar(1) / Scalar(2) * _tmp30;
  const Scalar _tmp44 = Scalar(0.41999999999999998) * _tmp43;
  const Scalar _tmp45 = _tmp42 * _tmp44;
  const Scalar _tmp46 = -_tmp41 - _tmp45;
  const Scalar _tmp47 = _tmp37 + _tmp46;
  const Scalar _tmp48 = _tmp38 * _tmp43;
  const Scalar _tmp49 = Scalar(0.83999999999999997) * _tmp48;
  const Scalar _tmp50 = -_tmp49;
  const Scalar _tmp51 = _tmp12 * _tmp34;
  const Scalar _tmp52 = Scalar(0.83999999999999997) * _tmp51;
  const Scalar _tmp53 = _tmp50 - _tmp52;
  const Scalar _tmp54 = _tmp47 + _tmp53;
  const Scalar _tmp55 = Scalar(0.021999999999999999) * _tmp39;
  const Scalar _tmp56 = _tmp12 * _tmp55;
  const Scalar _tmp57 = Scalar(0.021999999999999999) * _tmp43;
  const Scalar _tmp58 = _tmp32 * _tmp57;
  const Scalar _tmp59 = Scalar(0.021999999999999999) * _tmp38;
  const Scalar _tmp60 = _tmp26 * _tmp59;
  const Scalar _tmp61 = Scalar(0.021999999999999999) * _tmp42;
  const Scalar _tmp62 = _tmp34 * _tmp61;
  const Scalar _tmp63 = -_tmp56 + _tmp58 + _tmp60 - _tmp62;
  const Scalar _tmp64 = -2 * std::pow(_tmp38, Scalar(2));
  const Scalar _tmp65 = 1 - 2 * std::pow(_tmp12, Scalar(2));
  const Scalar _tmp66 = Scalar(0.20999999999999999) * _tmp64 + Scalar(0.20999999999999999) * _tmp65;
  const Scalar _tmp67 = -_tmp66;
  const Scalar _tmp68 = 2 * _tmp32 * _tmp38;
  const Scalar _tmp69 = 2 * _tmp42;
  const Scalar _tmp70 = _tmp12 * _tmp69;
  const Scalar _tmp71 = _tmp68 - _tmp70;
  const Scalar _tmp72 = -Scalar(0.010999999999999999) * _tmp71;
  const Scalar _tmp73 = 2 * _tmp12;
  const Scalar _tmp74 = _tmp32 * _tmp73;
  const Scalar _tmp75 = _tmp38 * _tmp69;
  const Scalar _tmp76 = Scalar(0.20999999999999999) * _tmp74 + Scalar(0.20999999999999999) * _tmp75;
  const Scalar _tmp77 = _tmp72 + _tmp76;
  const Scalar _tmp78 = _tmp67 + _tmp77;
  const Scalar _tmp79 = _tmp78 + p_init1;
  const Scalar _tmp80 = -_tmp79 + Scalar(-8.3888750099999996);
  const Scalar _tmp81 = _tmp28 + _tmp36;
  const Scalar _tmp82 = _tmp46 + _tmp81;
  const Scalar _tmp83 = _tmp26 * _tmp32;
  const Scalar _tmp84 = Scalar(0.83999999999999997) * _tmp83;
  const Scalar _tmp85 = _tmp49 + _tmp84;
  const Scalar _tmp86 = _tmp82 + _tmp85;
  const Scalar _tmp87 = _tmp32 * _tmp55;
  const Scalar _tmp88 = _tmp12 * _tmp57;
  const Scalar _tmp89 = _tmp34 * _tmp59;
  const Scalar _tmp90 = _tmp26 * _tmp61;
  const Scalar _tmp91 = _tmp87 + _tmp88 + _tmp89 + _tmp90;
  const Scalar _tmp92 = Scalar(0.20999999999999999) * _tmp74 - Scalar(0.20999999999999999) * _tmp75;
  const Scalar _tmp93 = -_tmp92;
  const Scalar _tmp94 = -2 * std::pow(_tmp32, Scalar(2));
  const Scalar _tmp95 = Scalar(0.20999999999999999) * _tmp64 +
                        Scalar(0.20999999999999999) * _tmp94 + Scalar(0.20999999999999999);
  const Scalar _tmp96 = _tmp38 * _tmp73;
  const Scalar _tmp97 = _tmp32 * _tmp69;
  const Scalar _tmp98 = _tmp96 + _tmp97;
  const Scalar _tmp99 = -Scalar(0.010999999999999999) * _tmp98;
  const Scalar _tmp100 = _tmp95 + _tmp99;
  const Scalar _tmp101 = _tmp100 + _tmp93;
  const Scalar _tmp102 = _tmp101 + p_init0;
  const Scalar _tmp103 = Scalar(2.5202214700000001) - _tmp102;
  const Scalar _tmp104 = 2 * _tmp103 * (_tmp86 + _tmp91) + 2 * _tmp80 * (_tmp54 + _tmp63);
  const Scalar _tmp105 = Scalar(1.0) / (fh1);
  const Scalar _tmp106 = std::pow(_tmp103, Scalar(2)) + std::pow(_tmp80, Scalar(2));
  const Scalar _tmp107 = std::sqrt(_tmp106);
  const Scalar _tmp108 =
      Scalar(0.20999999999999999) * _tmp68 + Scalar(0.20999999999999999) * _tmp70;
  const Scalar _tmp109 = -_tmp108;
  const Scalar _tmp110 =
      -Scalar(0.010999999999999999) * _tmp65 - Scalar(0.010999999999999999) * _tmp94;
  const Scalar _tmp111 =
      Scalar(0.20999999999999999) * _tmp96 - Scalar(0.20999999999999999) * _tmp97;
  const Scalar _tmp112 = _tmp110 + _tmp111;
  const Scalar _tmp113 = _tmp109 + _tmp112;
  const Scalar _tmp114 = -_tmp113 - p_init2 + Scalar(8.4693136199999994);
  const Scalar _tmp115 = _tmp12 * _tmp40;
  const Scalar _tmp116 = _tmp32 * _tmp44;
  const Scalar _tmp117 = _tmp27 * _tmp38;
  const Scalar _tmp118 = _tmp35 * _tmp42;
  const Scalar _tmp119 = _tmp115 + _tmp116 + _tmp117 + _tmp118;
  const Scalar _tmp120 = _tmp32 * _tmp40;
  const Scalar _tmp121 = _tmp12 * _tmp44;
  const Scalar _tmp122 = _tmp35 * _tmp38;
  const Scalar _tmp123 = _tmp27 * _tmp42;
  const Scalar _tmp124 = _tmp120 - _tmp121 - _tmp122 + _tmp123;
  const Scalar _tmp125 = Scalar(0.043999999999999997) * _tmp83;
  const Scalar _tmp126 = Scalar(0.043999999999999997) * _tmp51;
  const Scalar _tmp127 = -_tmp125 - _tmp126;
  const Scalar _tmp128 = _tmp124 + _tmp127;
  const Scalar _tmp129 = _tmp108 + _tmp112;
  const Scalar _tmp130 = -_tmp129 - p_init2 + Scalar(8.36416322);
  const Scalar _tmp131 = _tmp66 + _tmp77;
  const Scalar _tmp132 = _tmp131 + p_init1;
  const Scalar _tmp133 = Scalar(4.7752063900000001) - _tmp132;
  const Scalar _tmp134 = _tmp100 + _tmp92;
  const Scalar _tmp135 = _tmp134 + p_init0;
  const Scalar _tmp136 = Scalar(2.71799795) - _tmp135;
  const Scalar _tmp137 = std::pow(_tmp133, Scalar(2)) + std::pow(_tmp136, Scalar(2));
  const Scalar _tmp138 = -_tmp115 - _tmp116 - _tmp117 - _tmp118;
  const Scalar _tmp139 = _tmp128 + _tmp138;
  const Scalar _tmp140 = _tmp41 + _tmp45;
  const Scalar _tmp141 = _tmp140 + _tmp37;
  const Scalar _tmp142 = _tmp141 + _tmp91;
  const Scalar _tmp143 = _tmp49 + _tmp52;
  const Scalar _tmp144 = _tmp143 + _tmp47;
  const Scalar _tmp145 = _tmp144 + _tmp63;
  const Scalar _tmp146 = 2 * _tmp133 * _tmp145 + 2 * _tmp136 * (_tmp142 + _tmp85);
  const Scalar _tmp147 = std::sqrt(_tmp137);
  const Scalar _tmp148 = Scalar(1.0) * _tmp131;
  const Scalar _tmp149 = -_tmp148;
  const Scalar _tmp150 = _tmp72 - _tmp76;
  const Scalar _tmp151 = _tmp150 + _tmp67;
  const Scalar _tmp152 = _tmp149 + _tmp151;
  const Scalar _tmp153 = _tmp150 + _tmp66;
  const Scalar _tmp154 = _tmp149 + _tmp153;
  const Scalar _tmp155 = Scalar(1.0) / (_tmp154);
  const Scalar _tmp156 = -_tmp95 + _tmp99;
  const Scalar _tmp157 = _tmp156 + _tmp92;
  const Scalar _tmp158 = Scalar(1.0) * _tmp134;
  const Scalar _tmp159 = -_tmp157 + _tmp158;
  const Scalar _tmp160 = _tmp155 * _tmp159;
  const Scalar _tmp161 = _tmp152 * _tmp160;
  const Scalar _tmp162 = _tmp156 + _tmp93;
  const Scalar _tmp163 = _tmp158 - _tmp161 - _tmp162;
  const Scalar _tmp164 = Scalar(1.0) / (_tmp163);
  const Scalar _tmp165 = Scalar(1.0) * _tmp164;
  const Scalar _tmp166 = _tmp153 + p_init1;
  const Scalar _tmp167 = _tmp166 + Scalar(-4.8333311099999996);
  const Scalar _tmp168 = _tmp157 + p_init0;
  const Scalar _tmp169 = _tmp168 + Scalar(1.79662371);
  const Scalar _tmp170 = std::pow(_tmp167, Scalar(2)) + std::pow(_tmp169, Scalar(2));
  const Scalar _tmp171 = std::pow(_tmp170, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp172 = _tmp169 * _tmp171;
  const Scalar _tmp173 = _tmp132 + Scalar(-4.7752063900000001);
  const Scalar _tmp174 = _tmp135 + Scalar(-2.71799795);
  const Scalar _tmp175 = std::pow(_tmp174, Scalar(2));
  const Scalar _tmp176 = std::pow(_tmp173, Scalar(2)) + _tmp175;
  const Scalar _tmp177 = std::sqrt(_tmp176);
  const Scalar _tmp178 = Scalar(1.0) / (_tmp177);
  const Scalar _tmp179 = _tmp173 * _tmp178;
  const Scalar _tmp180 = _tmp131 * _tmp178;
  const Scalar _tmp181 = _tmp134 * _tmp179 - _tmp174 * _tmp180;
  const Scalar _tmp182 = Scalar(1.0) / (_tmp174);
  const Scalar _tmp183 = _tmp177 * _tmp182;
  const Scalar _tmp184 = _tmp181 * _tmp183;
  const Scalar _tmp185 = _tmp167 * _tmp171;
  const Scalar _tmp186 = _tmp153 * _tmp172 - _tmp157 * _tmp185 + _tmp172 * _tmp184;
  const Scalar _tmp187 = _tmp173 * _tmp182;
  const Scalar _tmp188 = _tmp172 * _tmp187 - _tmp185;
  const Scalar _tmp189 = Scalar(1.0) / (_tmp188);
  const Scalar _tmp190 = Scalar(1.0) * _tmp189;
  const Scalar _tmp191 = _tmp110 - _tmp111;
  const Scalar _tmp192 = _tmp108 + _tmp191;
  const Scalar _tmp193 = _tmp129 * _tmp172;
  const Scalar _tmp194 = _tmp185 * _tmp192 - _tmp187 * _tmp193;
  const Scalar _tmp195 = _tmp190 * _tmp194;
  const Scalar _tmp196 = _tmp171 * _tmp192;
  const Scalar _tmp197 = -_tmp169 * _tmp196 + _tmp193;
  const Scalar _tmp198 = _tmp160 * _tmp195 - _tmp190 * _tmp197;
  const Scalar _tmp199 = _tmp151 + p_init1;
  const Scalar _tmp200 = _tmp199 + Scalar(8.3196563700000006);
  const Scalar _tmp201 = _tmp162 + p_init0;
  const Scalar _tmp202 = _tmp201 + Scalar(1.9874742000000001);
  const Scalar _tmp203 = std::pow(_tmp200, Scalar(2)) + std::pow(_tmp202, Scalar(2));
  const Scalar _tmp204 = std::pow(_tmp203, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp205 = _tmp202 * _tmp204;
  const Scalar _tmp206 = _tmp200 * _tmp204;
  const Scalar _tmp207 = _tmp187 * _tmp205 - _tmp206;
  const Scalar _tmp208 = _tmp189 * _tmp207;
  const Scalar _tmp209 =
      _tmp151 * _tmp205 - _tmp162 * _tmp206 + _tmp184 * _tmp205 - _tmp186 * _tmp208;
  const Scalar _tmp210 = _tmp129 * _tmp205;
  const Scalar _tmp211 = _tmp109 + _tmp191;
  const Scalar _tmp212 = -_tmp187 * _tmp210 - _tmp194 * _tmp208 + _tmp206 * _tmp211;
  const Scalar _tmp213 = -_tmp160 * _tmp212 - _tmp197 * _tmp208 - _tmp205 * _tmp211 + _tmp210;
  const Scalar _tmp214 = Scalar(1.0) / (_tmp213);
  const Scalar _tmp215 = _tmp209 * _tmp214;
  const Scalar _tmp216 = -_tmp186 * _tmp190 - _tmp198 * _tmp215;
  const Scalar _tmp217 = Scalar(1.0) / (_tmp209);
  const Scalar _tmp218 = _tmp213 * _tmp217;
  const Scalar _tmp219 = _tmp216 * _tmp218;
  const Scalar _tmp220 = _tmp152 * _tmp164;
  const Scalar _tmp221 = _tmp198 + _tmp219;
  const Scalar _tmp222 = _tmp214 * _tmp221;
  const Scalar _tmp223 = -_tmp195 - _tmp212 * _tmp222 + _tmp219 * _tmp220;
  const Scalar _tmp224 = Scalar(1.0) * _tmp155;
  const Scalar _tmp225 = _tmp165 * _tmp219 - _tmp223 * _tmp224;
  const Scalar _tmp226 = _tmp102 + Scalar(-2.5202214700000001);
  const Scalar _tmp227 = _tmp79 + Scalar(8.3888750099999996);
  const Scalar _tmp228 = std::pow(_tmp226, Scalar(2)) + std::pow(_tmp227, Scalar(2));
  const Scalar _tmp229 = std::pow(_tmp228, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp230 = _tmp227 * _tmp229;
  const Scalar _tmp231 = _tmp230 * fh1;
  const Scalar _tmp232 = Scalar(1.0) * _tmp231;
  const Scalar _tmp233 = _tmp226 * _tmp229;
  const Scalar _tmp234 = fh1 * (_tmp101 * _tmp230 - _tmp233 * _tmp78);
  const Scalar _tmp235 = Scalar(1.0) * _tmp217;
  const Scalar _tmp236 = _tmp165 * _tmp218;
  const Scalar _tmp237 = _tmp152 * _tmp236 - _tmp212 * _tmp235;
  const Scalar _tmp238 = -Scalar(1.0) * _tmp224 * _tmp237 + Scalar(1.0) * _tmp236;
  const Scalar _tmp239 = _tmp113 * fh1;
  const Scalar _tmp240 = -_tmp230 * _tmp239 - Scalar(3.29616) * _tmp71 - _tmp78 * fv1;
  const Scalar _tmp241 = _tmp161 * _tmp165 + Scalar(1.0);
  const Scalar _tmp242 = _tmp155 * _tmp241;
  const Scalar _tmp243 = _tmp160 * _tmp165;
  const Scalar _tmp244 = -Scalar(1.0) * _tmp242 + Scalar(1.0) * _tmp243;
  const Scalar _tmp245 = _tmp148 * _tmp160 + _tmp158;
  const Scalar _tmp246 = 0;
  const Scalar _tmp247 = _tmp214 * _tmp246;
  const Scalar _tmp248 = _tmp164 * _tmp245;
  const Scalar _tmp249 = _tmp149 - _tmp152 * _tmp248 - _tmp212 * _tmp247;
  const Scalar _tmp250 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp251 = Scalar(1.0) * _tmp250;
  const Scalar _tmp252 = _tmp187 * _tmp189;
  const Scalar _tmp253 = _tmp129 * _tmp187;
  const Scalar _tmp254 = _tmp194 * _tmp252 + _tmp253;
  const Scalar _tmp255 = -_tmp129 - _tmp160 * _tmp254 + _tmp197 * _tmp252;
  const Scalar _tmp256 = -_tmp184 + _tmp186 * _tmp252 - _tmp215 * _tmp255;
  const Scalar _tmp257 = _tmp218 * _tmp256;
  const Scalar _tmp258 = _tmp255 + _tmp257;
  const Scalar _tmp259 = _tmp214 * _tmp258;
  const Scalar _tmp260 = -_tmp212 * _tmp259 + _tmp220 * _tmp257 + _tmp254;
  const Scalar _tmp261 = _tmp165 * _tmp257 - _tmp224 * _tmp260;
  const Scalar _tmp262 = Scalar(1.0) * fh1;
  const Scalar _tmp263 = _tmp261 * _tmp262;
  const Scalar _tmp264 = _tmp155 * _tmp165;
  const Scalar _tmp265 = _tmp152 * _tmp264 - _tmp165;
  const Scalar _tmp266 = _tmp101 * fv1 + _tmp233 * _tmp239 + Scalar(3.29616) * _tmp98;
  const Scalar _tmp267 = Scalar(1.0) * _tmp266;
  const Scalar _tmp268 =
      _tmp225 * _tmp232 + _tmp233 * _tmp263 + _tmp234 * _tmp238 + _tmp240 * _tmp244 +
      _tmp251 * (-_tmp165 * _tmp245 - _tmp224 * _tmp249 + Scalar(1.0)) + _tmp265 * _tmp267;
  const Scalar _tmp269 = _tmp233 * fh1;
  const Scalar _tmp270 = _tmp207 * _tmp214;
  const Scalar _tmp271 = -_tmp187 - _tmp258 * _tmp270;
  const Scalar _tmp272 = _tmp172 * _tmp189;
  const Scalar _tmp273 = _tmp205 * _tmp259 + _tmp271 * _tmp272 + Scalar(1.0);
  const Scalar _tmp274 = _tmp183 * _tmp273;
  const Scalar _tmp275 = -_tmp221 * _tmp270 + Scalar(1.0);
  const Scalar _tmp276 = _tmp205 * _tmp222 + _tmp272 * _tmp275;
  const Scalar _tmp277 = _tmp183 * _tmp231;
  const Scalar _tmp278 = _tmp172 * _tmp208;
  const Scalar _tmp279 = _tmp205 * _tmp247 - _tmp247 * _tmp278;
  const Scalar _tmp280 = _tmp183 * _tmp250;
  const Scalar _tmp281 = _tmp205 * _tmp235 - _tmp235 * _tmp278;
  const Scalar _tmp282 = _tmp183 * _tmp281;
  const Scalar _tmp283 =
      -_tmp234 * _tmp282 - _tmp269 * _tmp274 - _tmp276 * _tmp277 - _tmp279 * _tmp280;
  const Scalar _tmp284 = Scalar(1.0) / (_tmp283);
  const Scalar _tmp285 = std::asinh(_tmp268 * _tmp284);
  const Scalar _tmp286 = Scalar(9.6622558468725703) * _tmp283;
  const Scalar _tmp287 = -_tmp147 - _tmp285 * _tmp286;
  const Scalar _tmp288 = Scalar(0.1034955) * _tmp284;
  const Scalar _tmp289 = _tmp287 * _tmp288;
  const Scalar _tmp290 = _tmp50 - _tmp84;
  const Scalar _tmp291 = -_tmp87 - _tmp88 - _tmp89 - _tmp90;
  const Scalar _tmp292 = _tmp290 + _tmp291;
  const Scalar _tmp293 = _tmp292 + _tmp82;
  const Scalar _tmp294 = _tmp293 / _tmp175;
  const Scalar _tmp295 = _tmp177 * _tmp294;
  const Scalar _tmp296 = _tmp234 * _tmp281;
  const Scalar _tmp297 = _tmp173 * _tmp294;
  const Scalar _tmp298 = _tmp291 + _tmp86;
  const Scalar _tmp299 = _tmp56 - _tmp58 - _tmp60 + _tmp62;
  const Scalar _tmp300 = _tmp299 + _tmp54;
  const Scalar _tmp301 =
      (2 * _tmp167 * _tmp300 + 2 * _tmp169 * _tmp298) / (_tmp170 * std::sqrt(_tmp170));
  const Scalar _tmp302 = (Scalar(1) / Scalar(2)) * _tmp301;
  const Scalar _tmp303 = _tmp169 * _tmp302;
  const Scalar _tmp304 = _tmp167 * _tmp302;
  const Scalar _tmp305 = _tmp171 * _tmp298;
  const Scalar _tmp306 = _tmp140 + _tmp81;
  const Scalar _tmp307 = _tmp306 + _tmp53;
  const Scalar _tmp308 = _tmp299 + _tmp307;
  const Scalar _tmp309 = _tmp182 * _tmp308;
  const Scalar _tmp310 = _tmp171 * _tmp300;
  const Scalar _tmp311 = (-_tmp172 * _tmp297 + _tmp172 * _tmp309 - _tmp187 * _tmp303 +
                          _tmp187 * _tmp305 + _tmp304 - _tmp310) /
                         std::pow(_tmp188, Scalar(2));
  const Scalar _tmp312 = _tmp207 * _tmp311;
  const Scalar _tmp313 = _tmp141 + _tmp291 + _tmp85;
  const Scalar _tmp314 = _tmp144 + _tmp299;
  const Scalar _tmp315 =
      (2 * _tmp200 * _tmp314 + 2 * _tmp202 * _tmp313) / (_tmp203 * std::sqrt(_tmp203));
  const Scalar _tmp316 = Scalar(0.5) * _tmp217;
  const Scalar _tmp317 = _tmp208 * _tmp305;
  const Scalar _tmp318 = _tmp204 * _tmp313;
  const Scalar _tmp319 = _tmp173 * _tmp308 + _tmp174 * _tmp293;
  const Scalar _tmp320 = _tmp178 * _tmp182 * _tmp319;
  const Scalar _tmp321 = _tmp181 * _tmp320;
  const Scalar _tmp322 = _tmp181 * _tmp295;
  const Scalar _tmp323 = _tmp319 / (_tmp176 * std::sqrt(_tmp176));
  const Scalar _tmp324 = _tmp178 * _tmp308;
  const Scalar _tmp325 =
      _tmp183 * (_tmp131 * _tmp174 * _tmp323 - _tmp134 * _tmp173 * _tmp323 + _tmp134 * _tmp324 -
                 _tmp174 * _tmp324 + _tmp179 * _tmp293 - _tmp180 * _tmp293);
  const Scalar _tmp326 = -_tmp153 * _tmp303 + _tmp153 * _tmp305 + _tmp157 * _tmp304 -
                         _tmp157 * _tmp310 + _tmp169 * _tmp310 + _tmp172 * _tmp321 -
                         _tmp172 * _tmp322 + _tmp172 * _tmp325 - _tmp184 * _tmp303 +
                         _tmp184 * _tmp305 - _tmp185 * _tmp298;
  const Scalar _tmp327 = (Scalar(1) / Scalar(2)) * _tmp315;
  const Scalar _tmp328 = _tmp200 * _tmp327;
  const Scalar _tmp329 = _tmp204 * _tmp314;
  const Scalar _tmp330 = _tmp202 * _tmp327;
  const Scalar _tmp331 = _tmp187 * _tmp318 - _tmp187 * _tmp330 - _tmp205 * _tmp297 +
                         _tmp205 * _tmp309 + _tmp328 - _tmp329;
  const Scalar _tmp332 = _tmp189 * _tmp331;
  const Scalar _tmp333 = _tmp151 * _tmp318 - _tmp151 * _tmp330 + _tmp162 * _tmp328 -
                         _tmp162 * _tmp329 + _tmp184 * _tmp318 - _tmp184 * _tmp330 +
                         _tmp186 * _tmp312 - _tmp186 * _tmp332 + _tmp202 * _tmp329 +
                         _tmp205 * _tmp321 - _tmp205 * _tmp322 + _tmp205 * _tmp325 -
                         _tmp206 * _tmp313 - _tmp208 * _tmp326;
  const Scalar _tmp334 = _tmp333 / std::pow(_tmp209, Scalar(2));
  const Scalar _tmp335 = Scalar(1.0) * _tmp334;
  const Scalar _tmp336 = _tmp190 * _tmp217 * _tmp331;
  const Scalar _tmp337 = _tmp231 * _tmp276;
  const Scalar _tmp338 = _tmp129 * _tmp305;
  const Scalar _tmp339 = _tmp125 + _tmp126;
  const Scalar _tmp340 = -_tmp120 + _tmp121 + _tmp122 - _tmp123;
  const Scalar _tmp341 = _tmp119 + _tmp340;
  const Scalar _tmp342 = _tmp339 + _tmp341;
  const Scalar _tmp343 = _tmp172 * _tmp342;
  const Scalar _tmp344 = _tmp124 + _tmp339;
  const Scalar _tmp345 = _tmp119 + _tmp344;
  const Scalar _tmp346 = -_tmp129 * _tmp303 - _tmp172 * _tmp345 + _tmp192 * _tmp303 -
                         _tmp196 * _tmp298 + _tmp338 + _tmp343;
  const Scalar _tmp347 = _tmp205 * _tmp342;
  const Scalar _tmp348 = _tmp138 + _tmp344;
  const Scalar _tmp349 = Scalar(0.83999999999999997) * _tmp12 * _tmp26;
  const Scalar _tmp350 = Scalar(0.83999999999999997) * _tmp32 * _tmp34;
  const Scalar _tmp351 = -Scalar(0.83999999999999997) * _tmp38 * _tmp39 -
                         Scalar(0.83999999999999997) * _tmp42 * _tmp43;
  const Scalar _tmp352 = -_tmp349 - _tmp350 + _tmp351;
  const Scalar _tmp353 = _tmp352 / std::pow(_tmp154, Scalar(2));
  const Scalar _tmp354 = _tmp159 * _tmp353;
  const Scalar _tmp355 = _tmp129 * _tmp318;
  const Scalar _tmp356 = _tmp129 * _tmp309;
  const Scalar _tmp357 = _tmp185 * _tmp345 - _tmp187 * _tmp338 - _tmp187 * _tmp343 -
                         _tmp192 * _tmp304 + _tmp192 * _tmp310 + _tmp193 * _tmp297 -
                         _tmp193 * _tmp309 + _tmp253 * _tmp303;
  const Scalar _tmp358 = -_tmp187 * _tmp347 - _tmp187 * _tmp355 + _tmp194 * _tmp312 -
                         _tmp194 * _tmp332 - _tmp205 * _tmp356 + _tmp206 * _tmp348 -
                         _tmp208 * _tmp357 + _tmp210 * _tmp297 - _tmp211 * _tmp328 +
                         _tmp211 * _tmp329 + _tmp253 * _tmp330;
  const Scalar _tmp359 = Scalar(1.6799999999999999) * _tmp48;
  const Scalar _tmp360 = -_tmp359 - Scalar(1.6799999999999999) * _tmp83;
  const Scalar _tmp361 = _tmp155 * _tmp360;
  const Scalar _tmp362 = -_tmp129 * _tmp330 - _tmp160 * _tmp358 + _tmp197 * _tmp312 -
                         _tmp197 * _tmp332 - _tmp205 * _tmp348 - _tmp208 * _tmp346 -
                         _tmp211 * _tmp318 + _tmp211 * _tmp330 + _tmp212 * _tmp354 -
                         _tmp212 * _tmp361 + _tmp347 + _tmp355;
  const Scalar _tmp363 = _tmp362 / std::pow(_tmp213, Scalar(2));
  const Scalar _tmp364 = _tmp246 * _tmp363;
  const Scalar _tmp365 = _tmp172 * _tmp311;
  const Scalar _tmp366 = _tmp246 * _tmp270;
  const Scalar _tmp367 = _tmp269 * _tmp273;
  const Scalar _tmp368 = _tmp141 + _tmp292;
  const Scalar _tmp369 = _tmp143 + _tmp306;
  const Scalar _tmp370 = _tmp299 + _tmp369;
  const Scalar _tmp371 =
      (2 * _tmp226 * _tmp368 + 2 * _tmp227 * _tmp370) / (_tmp228 * std::sqrt(_tmp228));
  const Scalar _tmp372 = (Scalar(1) / Scalar(2)) * _tmp371;
  const Scalar _tmp373 = _tmp226 * _tmp372;
  const Scalar _tmp374 = _tmp373 * fh1;
  const Scalar _tmp375 = _tmp250 * _tmp279;
  const Scalar _tmp376 = _tmp229 * _tmp368;
  const Scalar _tmp377 = _tmp376 * fh1;
  const Scalar _tmp378 = _tmp189 * _tmp271;
  const Scalar _tmp379 = _tmp187 * _tmp311;
  const Scalar _tmp380 = _tmp189 * _tmp309;
  const Scalar _tmp381 = _tmp189 * _tmp297;
  const Scalar _tmp382 = -_tmp129 * _tmp297 + _tmp187 * _tmp342 - _tmp194 * _tmp379 +
                         _tmp194 * _tmp380 - _tmp194 * _tmp381 + _tmp252 * _tmp357 + _tmp356;
  const Scalar _tmp383 = _tmp139 - _tmp160 * _tmp382 - _tmp197 * _tmp379 + _tmp197 * _tmp380 -
                         _tmp197 * _tmp381 + _tmp252 * _tmp346 + _tmp254 * _tmp354 -
                         _tmp254 * _tmp361;
  const Scalar _tmp384 = _tmp209 * _tmp363;
  const Scalar _tmp385 = _tmp214 * _tmp333;
  const Scalar _tmp386 = _tmp218 * (-_tmp186 * _tmp379 + _tmp186 * _tmp380 - _tmp186 * _tmp381 -
                                    _tmp215 * _tmp383 + _tmp252 * _tmp326 + _tmp255 * _tmp384 -
                                    _tmp255 * _tmp385 - _tmp321 + _tmp322 - _tmp325);
  const Scalar _tmp387 = _tmp217 * _tmp362;
  const Scalar _tmp388 = _tmp256 * _tmp387;
  const Scalar _tmp389 = _tmp213 * _tmp334;
  const Scalar _tmp390 = _tmp256 * _tmp389;
  const Scalar _tmp391 = _tmp383 + _tmp386 + _tmp388 - _tmp390;
  const Scalar _tmp392 = _tmp205 * _tmp214;
  const Scalar _tmp393 = _tmp258 * _tmp363;
  const Scalar _tmp394 =
      _tmp207 * _tmp393 - _tmp259 * _tmp331 - _tmp270 * _tmp391 + _tmp297 - _tmp309;
  const Scalar _tmp395 = _tmp189 * _tmp305;
  const Scalar _tmp396 = _tmp183 * _tmp276;
  const Scalar _tmp397 = _tmp227 * _tmp372;
  const Scalar _tmp398 = _tmp397 * fh1;
  const Scalar _tmp399 = _tmp229 * _tmp370;
  const Scalar _tmp400 = _tmp399 * fh1;
  const Scalar _tmp401 = _tmp221 * _tmp363;
  const Scalar _tmp402 = _tmp216 * _tmp387;
  const Scalar _tmp403 = _tmp216 * _tmp389;
  const Scalar _tmp404 = _tmp190 * _tmp357;
  const Scalar _tmp405 = Scalar(1.0) * _tmp160;
  const Scalar _tmp406 = Scalar(1.0) * _tmp311;
  const Scalar _tmp407 = _tmp160 * _tmp404 - _tmp190 * _tmp346 - _tmp194 * _tmp311 * _tmp405 -
                         _tmp195 * _tmp354 + _tmp195 * _tmp361 + _tmp197 * _tmp406;
  const Scalar _tmp408 = _tmp218 * (_tmp186 * _tmp406 - _tmp190 * _tmp326 + _tmp198 * _tmp384 -
                                    _tmp198 * _tmp385 - _tmp215 * _tmp407);
  const Scalar _tmp409 = _tmp402 - _tmp403 + _tmp407 + _tmp408;
  const Scalar _tmp410 = _tmp207 * _tmp401 - _tmp222 * _tmp331 - _tmp270 * _tmp409;
  const Scalar _tmp411 = _tmp189 * _tmp275;
  const Scalar _tmp412 = fh1 * (-_tmp101 * _tmp397 + _tmp101 * _tmp399 + _tmp230 * _tmp368 -
                                _tmp233 * _tmp370 + _tmp373 * _tmp78 - _tmp376 * _tmp78);
  const Scalar _tmp413 =
      -_tmp183 * _tmp234 *
          (_tmp169 * _tmp208 * _tmp301 * _tmp316 + _tmp172 * _tmp235 * _tmp312 - _tmp172 * _tmp336 -
           _tmp202 * _tmp315 * _tmp316 - _tmp205 * _tmp335 - _tmp235 * _tmp317 + _tmp235 * _tmp318 +
           _tmp278 * _tmp335) -
      _tmp183 * _tmp269 *
          (-_tmp205 * _tmp393 + _tmp259 * _tmp318 - _tmp259 * _tmp330 - _tmp271 * _tmp365 +
           _tmp271 * _tmp395 + _tmp272 * _tmp394 - _tmp303 * _tmp378 + _tmp391 * _tmp392) +
      _tmp274 * _tmp374 - _tmp274 * _tmp377 -
      _tmp277 * (-_tmp205 * _tmp401 + _tmp222 * _tmp318 - _tmp222 * _tmp330 + _tmp272 * _tmp410 -
                 _tmp275 * _tmp365 + _tmp275 * _tmp395 - _tmp303 * _tmp411 + _tmp392 * _tmp409) -
      _tmp280 * (-_tmp172 * _tmp247 * _tmp332 - _tmp205 * _tmp364 + _tmp208 * _tmp247 * _tmp303 -
                 _tmp247 * _tmp317 + _tmp247 * _tmp318 - _tmp247 * _tmp330 + _tmp278 * _tmp364 +
                 _tmp365 * _tmp366) -
      _tmp282 * _tmp412 + _tmp295 * _tmp296 + _tmp295 * _tmp337 + _tmp295 * _tmp367 +
      _tmp295 * _tmp375 - _tmp296 * _tmp320 - _tmp320 * _tmp337 - _tmp320 * _tmp367 -
      _tmp320 * _tmp375 + _tmp396 * _tmp398 - _tmp396 * _tmp400;
  const Scalar _tmp414 = Scalar(9.6622558468725703) * _tmp413;
  const Scalar _tmp415 = std::pow(_tmp283, Scalar(-2));
  const Scalar _tmp416 = _tmp413 * _tmp415;
  const Scalar _tmp417 = Scalar(6.59232) * _tmp39;
  const Scalar _tmp418 = Scalar(6.59232) * _tmp43;
  const Scalar _tmp419 = Scalar(6.59232) * _tmp38;
  const Scalar _tmp420 = _tmp138 + _tmp340;
  const Scalar _tmp421 = fh1 * (_tmp339 + _tmp420);
  const Scalar _tmp422 = Scalar(6.59232) * _tmp42;
  const Scalar _tmp423 = _tmp12 * _tmp418 + _tmp233 * _tmp421 - _tmp239 * _tmp373 +
                         _tmp239 * _tmp376 + _tmp26 * _tmp422 + _tmp32 * _tmp417 +
                         _tmp34 * _tmp419 + _tmp368 * fv1;
  const Scalar _tmp424 = _tmp165 * _tmp361;
  const Scalar _tmp425 = _tmp165 * _tmp354;
  const Scalar _tmp426 = Scalar(1.0) * _tmp353;
  const Scalar _tmp427 = _tmp152 * _tmp354;
  const Scalar _tmp428 = _tmp352 + _tmp359 + Scalar(1.6799999999999999) * _tmp51;
  const Scalar _tmp429 = _tmp160 * _tmp428;
  const Scalar _tmp430 = _tmp152 * _tmp361;
  const Scalar _tmp431 = (_tmp349 + _tmp350 + _tmp351 + _tmp360 + _tmp427 - _tmp429 - _tmp430) /
                         std::pow(_tmp163, Scalar(2));
  const Scalar _tmp432 = Scalar(1.0) * _tmp431;
  const Scalar _tmp433 =
      _tmp155 * (-_tmp161 * _tmp432 - _tmp165 * _tmp427 + _tmp165 * _tmp429 + _tmp165 * _tmp430);
  const Scalar _tmp434 = _tmp160 * _tmp432;
  const Scalar _tmp435 = Scalar(0.5) * _tmp371 * fh1;
  const Scalar _tmp436 = _tmp152 * _tmp353;
  const Scalar _tmp437 = _tmp152 * _tmp431;
  const Scalar _tmp438 = _tmp212 * _tmp214;
  const Scalar _tmp439 = _tmp164 * _tmp428;
  const Scalar _tmp440 = _tmp194 * _tmp406 + _tmp212 * _tmp401 - _tmp219 * _tmp437 +
                         _tmp219 * _tmp439 + _tmp220 * _tmp402 - _tmp220 * _tmp403 +
                         _tmp220 * _tmp408 - _tmp222 * _tmp358 - _tmp404 - _tmp409 * _tmp438;
  const Scalar _tmp441 = _tmp12 * _tmp417 - _tmp230 * _tmp421 + _tmp239 * _tmp397 -
                         _tmp239 * _tmp399 - _tmp26 * _tmp419 - _tmp32 * _tmp418 +
                         _tmp34 * _tmp422 - _tmp370 * fv1;
  const Scalar _tmp442 = _tmp218 * _tmp432;
  const Scalar _tmp443 = _tmp165 * _tmp389;
  const Scalar _tmp444 = _tmp165 * _tmp387;
  const Scalar _tmp445 = -_tmp152 * _tmp442 - _tmp152 * _tmp443 + _tmp152 * _tmp444 +
                         _tmp212 * _tmp335 - _tmp235 * _tmp358 + _tmp236 * _tmp428;
  const Scalar _tmp446 = Scalar(1.0) * _tmp234;
  const Scalar _tmp447 = -_tmp148 * _tmp354 + _tmp148 * _tmp361 + _tmp293 + _tmp308 * _tmp405;
  const Scalar _tmp448 = _tmp164 * _tmp447;
  const Scalar _tmp449 = _tmp212 * _tmp363;
  const Scalar _tmp450 = _tmp245 * _tmp431;
  const Scalar _tmp451 = _tmp145 - _tmp152 * _tmp448 + _tmp152 * _tmp450 + _tmp246 * _tmp449 -
                         _tmp247 * _tmp358 - _tmp248 * _tmp428;
  const Scalar _tmp452 = _tmp220 * _tmp386 + _tmp220 * _tmp388 - _tmp220 * _tmp390 -
                         _tmp257 * _tmp437 + _tmp257 * _tmp439 + _tmp258 * _tmp449 -
                         _tmp259 * _tmp358 + _tmp382 - _tmp391 * _tmp438;
  const Scalar _tmp453 =
      (-_tmp268 * _tmp416 +
       _tmp284 *
           (-_tmp225 * _tmp227 * _tmp435 + _tmp225 * _tmp262 * _tmp399 -
            _tmp226 * _tmp261 * _tmp435 +
            _tmp232 * (_tmp165 * _tmp402 - _tmp165 * _tmp403 + _tmp165 * _tmp408 -
                       _tmp219 * _tmp432 + _tmp223 * _tmp426 - _tmp224 * _tmp440) +
            _tmp233 * _tmp262 *
                (_tmp165 * _tmp386 + _tmp165 * _tmp388 - _tmp165 * _tmp390 - _tmp224 * _tmp452 -
                 _tmp257 * _tmp432 + _tmp260 * _tmp426) +
            _tmp238 * _tmp412 +
            Scalar(1.0) * _tmp240 *
                (_tmp241 * _tmp426 + _tmp424 - _tmp425 - Scalar(1.0) * _tmp433 - _tmp434) +
            _tmp244 * _tmp441 +
            _tmp251 *
                (-_tmp165 * _tmp447 - _tmp224 * _tmp451 + _tmp245 * _tmp432 + _tmp249 * _tmp426) +
            _tmp263 * _tmp376 + Scalar(1.0) * _tmp265 * _tmp423 +
            _tmp267 * (-_tmp165 * _tmp436 - _tmp224 * _tmp437 + _tmp264 * _tmp428 + _tmp432) +
            _tmp446 * (-_tmp224 * _tmp445 + _tmp237 * _tmp426 - _tmp442 - _tmp443 + _tmp444))) /
      std::sqrt(Scalar(std::pow(_tmp268, Scalar(2)) * _tmp415 + 1));
  const Scalar _tmp454 = Scalar(1.0) * _tmp285;
  const Scalar _tmp455 = _tmp155 * _tmp231;
  const Scalar _tmp456 = _tmp155 * _tmp250;
  const Scalar _tmp457 = _tmp155 * _tmp237;
  const Scalar _tmp458 = _tmp155 * _tmp269;
  const Scalar _tmp459 = _tmp165 * _tmp266;
  const Scalar _tmp460 = _tmp155 * _tmp459;
  const Scalar _tmp461 = -_tmp152 * _tmp460 + _tmp223 * _tmp455 + _tmp234 * _tmp457 +
                         _tmp240 * _tmp242 + _tmp249 * _tmp456 + _tmp260 * _tmp458;
  const Scalar _tmp462 = _tmp234 * _tmp235;
  const Scalar _tmp463 = _tmp247 * _tmp250;
  const Scalar _tmp464 =
      -_tmp208 * _tmp462 - _tmp208 * _tmp463 + _tmp231 * _tmp411 + _tmp269 * _tmp378;
  const Scalar _tmp465 = Scalar(1.0) / (_tmp464);
  const Scalar _tmp466 = std::asinh(_tmp461 * _tmp465);
  const Scalar _tmp467 = Scalar(1.0) * _tmp466;
  const Scalar _tmp468 = _tmp155 * _tmp260;
  const Scalar _tmp469 = _tmp155 * _tmp223;
  const Scalar _tmp470 = _tmp267 * _tmp431;
  const Scalar _tmp471 = _tmp152 * _tmp155;
  const Scalar _tmp472 = _tmp165 * _tmp423;
  const Scalar _tmp473 = std::pow(_tmp464, Scalar(-2));
  const Scalar _tmp474 = _tmp334 * _tmp446;
  const Scalar _tmp475 = _tmp235 * _tmp412;
  const Scalar _tmp476 = _tmp250 * _tmp364;
  const Scalar _tmp477 = _tmp189 * _tmp231 * _tmp410 + _tmp189 * _tmp269 * _tmp394 +
                         _tmp208 * _tmp474 - _tmp208 * _tmp475 + _tmp208 * _tmp476 -
                         _tmp231 * _tmp275 * _tmp311 - _tmp234 * _tmp336 +
                         _tmp250 * _tmp311 * _tmp366 - _tmp269 * _tmp271 * _tmp311 +
                         _tmp312 * _tmp462 - _tmp332 * _tmp463 - _tmp374 * _tmp378 +
                         _tmp377 * _tmp378 - _tmp398 * _tmp411 + _tmp400 * _tmp411;
  const Scalar _tmp478 = _tmp473 * _tmp477;
  const Scalar _tmp479 =
      (-_tmp461 * _tmp478 +
       _tmp465 * (_tmp155 * _tmp234 * _tmp445 - _tmp223 * _tmp231 * _tmp353 -
                  _tmp234 * _tmp237 * _tmp353 - _tmp240 * _tmp241 * _tmp353 + _tmp240 * _tmp433 +
                  _tmp242 * _tmp441 - _tmp249 * _tmp250 * _tmp353 - _tmp260 * _tmp269 * _tmp353 -
                  _tmp374 * _tmp468 + _tmp377 * _tmp468 - _tmp398 * _tmp469 + _tmp400 * _tmp469 +
                  _tmp412 * _tmp457 - _tmp428 * _tmp460 + _tmp436 * _tmp459 + _tmp440 * _tmp455 +
                  _tmp451 * _tmp456 + _tmp452 * _tmp458 + _tmp470 * _tmp471 - _tmp471 * _tmp472)) /
      std::sqrt(Scalar(std::pow(_tmp461, Scalar(2)) * _tmp473 + 1));
  const Scalar _tmp480 = Scalar(9.6622558468725703) * _tmp466;
  const Scalar _tmp481 = Scalar(4.8333311099999996) - _tmp166;
  const Scalar _tmp482 = -_tmp168 + Scalar(-1.79662371);
  const Scalar _tmp483 = std::pow(_tmp481, Scalar(2)) + std::pow(_tmp482, Scalar(2));
  const Scalar _tmp484 = std::sqrt(_tmp483);
  const Scalar _tmp485 = 2 * _tmp481 * (_tmp369 + _tmp63) + 2 * _tmp482 * (_tmp142 + _tmp290);
  const Scalar _tmp486 = Scalar(9.6622558468725703) * _tmp464;
  const Scalar _tmp487 = Scalar(0.1034955) * _tmp465;
  const Scalar _tmp488 = -_tmp464 * _tmp480 - _tmp484;
  const Scalar _tmp489 = _tmp487 * _tmp488;
  const Scalar _tmp490 = -_tmp192 - p_init2 + Scalar(8.3700199099999999);
  const Scalar _tmp491 = -_tmp211 - p_init2 + Scalar(8.4718465799999993);
  const Scalar _tmp492 = -_tmp199 + Scalar(-8.3196563700000006);
  const Scalar _tmp493 = -_tmp201 + Scalar(-1.9874742000000001);
  const Scalar _tmp494 = std::pow(_tmp492, Scalar(2)) + std::pow(_tmp493, Scalar(2));
  const Scalar _tmp495 =
      2 * _tmp492 * (_tmp307 + _tmp63) + 2 * _tmp493 * (_tmp290 + _tmp82 + _tmp91);
  const Scalar _tmp496 = std::sqrt(_tmp494);
  const Scalar _tmp497 = _tmp222 * _tmp231 + _tmp259 * _tmp269 + _tmp462 + _tmp463;
  const Scalar _tmp498 = Scalar(1.0) / (_tmp497);
  const Scalar _tmp499 = _tmp164 * _tmp257;
  const Scalar _tmp500 = _tmp164 * _tmp231;
  const Scalar _tmp501 = -_tmp219 * _tmp500 - _tmp234 * _tmp236 - _tmp240 * _tmp243 +
                         _tmp248 * _tmp250 - _tmp269 * _tmp499 + _tmp459;
  const Scalar _tmp502 = std::asinh(_tmp498 * _tmp501);
  const Scalar _tmp503 = Scalar(9.6622558468725703) * _tmp497;
  const Scalar _tmp504 = -_tmp496 - _tmp502 * _tmp503;
  const Scalar _tmp505 = Scalar(0.1034955) * _tmp498;
  const Scalar _tmp506 = _tmp504 * _tmp505;
  const Scalar _tmp507 = Scalar(1.0) * _tmp502;
  const Scalar _tmp508 = _tmp214 * _tmp231 * _tmp409 + _tmp214 * _tmp269 * _tmp391 -
                         _tmp222 * _tmp398 + _tmp222 * _tmp400 - _tmp231 * _tmp401 -
                         _tmp259 * _tmp374 + _tmp259 * _tmp377 - _tmp269 * _tmp393 - _tmp474 +
                         _tmp475 - _tmp476;
  const Scalar _tmp509 = Scalar(9.6622558468725703) * _tmp508;
  const Scalar _tmp510 = std::pow(_tmp497, Scalar(-2));
  const Scalar _tmp511 = _tmp164 * _tmp219;
  const Scalar _tmp512 = _tmp164 * _tmp269;
  const Scalar _tmp513 = _tmp508 * _tmp510;
  const Scalar _tmp514 =
      (_tmp498 * (_tmp219 * _tmp231 * _tmp431 + _tmp234 * _tmp442 + _tmp234 * _tmp443 -
                  _tmp234 * _tmp444 - _tmp236 * _tmp412 - _tmp240 * _tmp424 + _tmp240 * _tmp425 +
                  _tmp240 * _tmp434 - _tmp243 * _tmp441 + _tmp250 * _tmp448 - _tmp250 * _tmp450 +
                  _tmp257 * _tmp269 * _tmp431 + _tmp374 * _tmp499 - _tmp377 * _tmp499 -
                  _tmp386 * _tmp512 - _tmp388 * _tmp512 + _tmp390 * _tmp512 + _tmp398 * _tmp511 -
                  _tmp400 * _tmp511 - _tmp402 * _tmp500 + _tmp403 * _tmp500 - _tmp408 * _tmp500 -
                  _tmp470 + _tmp472) -
       _tmp501 * _tmp513) /
      std::sqrt(Scalar(std::pow(_tmp501, Scalar(2)) * _tmp510 + 1));

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) =
      Scalar(0.5) * _tmp104 *
          std::cosh(Scalar(0.1034955) * _tmp105 *
                    (-_tmp107 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp105 * fv1))) /
          _tmp107 -
      Scalar(1) / Scalar(2) * (_tmp104 + 2 * _tmp114 * (_tmp119 + _tmp128)) /
          std::sqrt(Scalar(_tmp106 + std::pow(_tmp114, Scalar(2))));
  _res(1, 0) = _tmp286 * (-Scalar(1.0) * _tmp453 * std::cosh(_tmp454) -
                          (-Scalar(0.1034955) * _tmp287 * _tmp416 +
                           _tmp288 * (-Scalar(1) / Scalar(2) * _tmp146 / _tmp147 -
                                      _tmp285 * _tmp414 - _tmp286 * _tmp453)) *
                              std::cosh(_tmp289)) +
               _tmp414 * (-std::sinh(_tmp289) - std::sinh(_tmp454)) -
               Scalar(1) / Scalar(2) * (2 * _tmp130 * _tmp139 + _tmp146) /
                   std::sqrt(Scalar(std::pow(_tmp130, Scalar(2)) + _tmp137));
  _res(2, 0) = Scalar(9.6622558468725703) * _tmp477 * (-std::sinh(_tmp467) - std::sinh(_tmp489)) +
               _tmp486 * (-Scalar(1.0) * _tmp479 * std::cosh(_tmp467) -
                          (-Scalar(0.1034955) * _tmp478 * _tmp488 +
                           _tmp487 * (-_tmp477 * _tmp480 - _tmp479 * _tmp486 -
                                      Scalar(1) / Scalar(2) * _tmp485 / _tmp484)) *
                              std::cosh(_tmp489)) -
               Scalar(1) / Scalar(2) * (_tmp485 + 2 * _tmp490 * (_tmp127 + _tmp420)) /
                   std::sqrt(Scalar(_tmp483 + std::pow(_tmp490, Scalar(2))));
  _res(3, 0) = _tmp503 * (-Scalar(1.0) * _tmp514 * std::cosh(_tmp507) -
                          (-Scalar(0.1034955) * _tmp504 * _tmp513 +
                           _tmp505 * (-Scalar(1) / Scalar(2) * _tmp495 / _tmp496 -
                                      _tmp502 * _tmp509 - _tmp503 * _tmp514)) *
                              std::cosh(_tmp506)) +
               _tmp509 * (-std::sinh(_tmp506) - std::sinh(_tmp507)) -
               Scalar(1) / Scalar(2) * (2 * _tmp491 * (_tmp127 + _tmp341) + _tmp495) /
                   std::sqrt(Scalar(std::pow(_tmp491, Scalar(2)) + _tmp494));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
