// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost2_wrt_rx_Nl15
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     rx: Scalar
 *     ry: Scalar
 *     rz: Scalar
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost2WrtRxNl15(
    const Scalar fh1, const Scalar fv1, const Scalar rx, const Scalar ry, const Scalar rz,
    const Scalar p_init0, const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x,
    const Scalar rot_init_y, const Scalar rot_init_z, const Scalar rot_init_w,
    const Scalar epsilon) {
  // Total ops: 1663

  // Unused inputs
  (void)epsilon;

  // Input arrays

  // Intermediate terms (518)
  const Scalar _tmp0 = std::pow(rx, Scalar(2));
  const Scalar _tmp1 = _tmp0 + std::pow(ry, Scalar(2)) + std::pow(rz, Scalar(2));
  const Scalar _tmp2 = std::sqrt(_tmp1);
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = std::cos(_tmp3);
  const Scalar _tmp5 = _tmp4 * rot_init_x;
  const Scalar _tmp6 = std::sin(_tmp3);
  const Scalar _tmp7 = _tmp6 / _tmp2;
  const Scalar _tmp8 = _tmp7 * rot_init_z;
  const Scalar _tmp9 = _tmp7 * rot_init_w;
  const Scalar _tmp10 = _tmp9 * rx;
  const Scalar _tmp11 = _tmp7 * rot_init_y;
  const Scalar _tmp12 = _tmp10 + _tmp11 * rz + _tmp5 - _tmp8 * ry;
  const Scalar _tmp13 = _tmp4 * rot_init_z;
  const Scalar _tmp14 = _tmp7 * rot_init_x;
  const Scalar _tmp15 = _tmp11 * rx;
  const Scalar _tmp16 = _tmp13 + _tmp14 * ry - _tmp15 + _tmp9 * rz;
  const Scalar _tmp17 = 2 * _tmp16;
  const Scalar _tmp18 = _tmp12 * _tmp17;
  const Scalar _tmp19 = _tmp4 * rot_init_y;
  const Scalar _tmp20 = _tmp8 * rx;
  const Scalar _tmp21 = -_tmp14 * rz + _tmp19 + _tmp20 + _tmp9 * ry;
  const Scalar _tmp22 = _tmp4 * rot_init_w;
  const Scalar _tmp23 = _tmp14 * rx;
  const Scalar _tmp24 = -_tmp11 * ry + _tmp22 - _tmp23 - _tmp8 * rz;
  const Scalar _tmp25 = 2 * _tmp24;
  const Scalar _tmp26 = _tmp21 * _tmp25;
  const Scalar _tmp27 = Scalar(0.20999999999999999) * _tmp18 - Scalar(0.20999999999999999) * _tmp26;
  const Scalar _tmp28 = -2 * std::pow(_tmp21, Scalar(2));
  const Scalar _tmp29 = 1 - 2 * std::pow(_tmp12, Scalar(2));
  const Scalar _tmp30 =
      -Scalar(0.010999999999999999) * _tmp28 - Scalar(0.010999999999999999) * _tmp29;
  const Scalar _tmp31 = _tmp17 * _tmp21;
  const Scalar _tmp32 = _tmp12 * _tmp25;
  const Scalar _tmp33 = Scalar(0.20999999999999999) * _tmp31 + Scalar(0.20999999999999999) * _tmp32;
  const Scalar _tmp34 = _tmp30 + _tmp33;
  const Scalar _tmp35 = _tmp27 + _tmp34;
  const Scalar _tmp36 = -_tmp35 - p_init2 + Scalar(8.36416322);
  const Scalar _tmp37 = 2 * _tmp12 * _tmp21;
  const Scalar _tmp38 = _tmp16 * _tmp25;
  const Scalar _tmp39 = Scalar(0.20999999999999999) * _tmp37 + Scalar(0.20999999999999999) * _tmp38;
  const Scalar _tmp40 = _tmp31 - _tmp32;
  const Scalar _tmp41 = -Scalar(0.010999999999999999) * _tmp40;
  const Scalar _tmp42 = -2 * std::pow(_tmp16, Scalar(2));
  const Scalar _tmp43 = Scalar(0.20999999999999999) * _tmp29 + Scalar(0.20999999999999999) * _tmp42;
  const Scalar _tmp44 = _tmp41 + _tmp43;
  const Scalar _tmp45 = _tmp39 + _tmp44;
  const Scalar _tmp46 = _tmp45 + p_init1;
  const Scalar _tmp47 = Scalar(4.7752063900000001) - _tmp46;
  const Scalar _tmp48 = Scalar(0.20999999999999999) * _tmp28 +
                        Scalar(0.20999999999999999) * _tmp42 + Scalar(0.20999999999999999);
  const Scalar _tmp49 = _tmp18 + _tmp26;
  const Scalar _tmp50 = -Scalar(0.010999999999999999) * _tmp49;
  const Scalar _tmp51 = Scalar(0.20999999999999999) * _tmp37 - Scalar(0.20999999999999999) * _tmp38;
  const Scalar _tmp52 = _tmp50 + _tmp51;
  const Scalar _tmp53 = _tmp48 + _tmp52;
  const Scalar _tmp54 = _tmp53 + p_init0;
  const Scalar _tmp55 = Scalar(2.71799795) - _tmp54;
  const Scalar _tmp56 = std::pow(_tmp47, Scalar(2)) + std::pow(_tmp55, Scalar(2));
  const Scalar _tmp57 = (Scalar(1) / Scalar(2)) / _tmp1;
  const Scalar _tmp58 = _tmp0 * _tmp57;
  const Scalar _tmp59 = _tmp57 * rx;
  const Scalar _tmp60 = _tmp59 * rz;
  const Scalar _tmp61 = _tmp59 * ry;
  const Scalar _tmp62 = _tmp6 / (_tmp1 * std::sqrt(_tmp1));
  const Scalar _tmp63 = _tmp0 * _tmp62;
  const Scalar _tmp64 = _tmp62 * rx;
  const Scalar _tmp65 = _tmp64 * ry;
  const Scalar _tmp66 = _tmp64 * rot_init_z;
  const Scalar _tmp67 = -Scalar(1) / Scalar(2) * _tmp10 - _tmp13 * _tmp60 - _tmp14 -
                        _tmp19 * _tmp61 - _tmp5 * _tmp58 + _tmp63 * rot_init_x +
                        _tmp65 * rot_init_y + _tmp66 * rz;
  const Scalar _tmp68 = Scalar(0.41999999999999998) * _tmp67;
  const Scalar _tmp69 = _tmp21 * _tmp68;
  const Scalar _tmp70 = _tmp64 * rz;
  const Scalar _tmp71 = -_tmp11 - _tmp19 * _tmp58 - Scalar(1) / Scalar(2) * _tmp20 +
                        _tmp22 * _tmp60 + _tmp5 * _tmp61 + _tmp63 * rot_init_y -
                        _tmp65 * rot_init_x - _tmp70 * rot_init_w;
  const Scalar _tmp72 = Scalar(0.41999999999999998) * _tmp71;
  const Scalar _tmp73 = _tmp12 * _tmp72;
  const Scalar _tmp74 = -_tmp13 * _tmp61 + _tmp19 * _tmp60 + _tmp22 * _tmp58 -
                        Scalar(1) / Scalar(2) * _tmp23 - _tmp63 * rot_init_w + _tmp66 * ry -
                        _tmp70 * rot_init_y + _tmp9;
  const Scalar _tmp75 = Scalar(0.41999999999999998) * _tmp74;
  const Scalar _tmp76 = _tmp16 * _tmp75;
  const Scalar _tmp77 = _tmp13 * _tmp58 - Scalar(1) / Scalar(2) * _tmp15 + _tmp22 * _tmp61 -
                        _tmp5 * _tmp60 - _tmp63 * rot_init_z - _tmp65 * rot_init_w +
                        _tmp70 * rot_init_x + _tmp8;
  const Scalar _tmp78 = Scalar(0.41999999999999998) * _tmp77;
  const Scalar _tmp79 = _tmp24 * _tmp78;
  const Scalar _tmp80 = _tmp69 - _tmp73 - _tmp76 + _tmp79;
  const Scalar _tmp81 = _tmp21 * _tmp77;
  const Scalar _tmp82 = Scalar(0.043999999999999997) * _tmp81;
  const Scalar _tmp83 = _tmp12 * _tmp74;
  const Scalar _tmp84 = Scalar(0.043999999999999997) * _tmp83;
  const Scalar _tmp85 = -_tmp82 - _tmp84;
  const Scalar _tmp86 = _tmp80 + _tmp85;
  const Scalar _tmp87 = _tmp12 * _tmp68;
  const Scalar _tmp88 = _tmp21 * _tmp72;
  const Scalar _tmp89 = _tmp16 * _tmp78;
  const Scalar _tmp90 = _tmp24 * _tmp75;
  const Scalar _tmp91 = -_tmp87 - _tmp88 - _tmp89 - _tmp90;
  const Scalar _tmp92 = _tmp16 * _tmp68;
  const Scalar _tmp93 = _tmp24 * _tmp72;
  const Scalar _tmp94 = _tmp92 + _tmp93;
  const Scalar _tmp95 = _tmp12 * _tmp78;
  const Scalar _tmp96 = _tmp21 * _tmp75;
  const Scalar _tmp97 = -_tmp95 - _tmp96;
  const Scalar _tmp98 = _tmp94 + _tmp97;
  const Scalar _tmp99 = Scalar(0.021999999999999999) * _tmp67;
  const Scalar _tmp100 = _tmp21 * _tmp99;
  const Scalar _tmp101 = Scalar(0.021999999999999999) * _tmp71;
  const Scalar _tmp102 = _tmp101 * _tmp12;
  const Scalar _tmp103 = Scalar(0.021999999999999999) * _tmp16;
  const Scalar _tmp104 = _tmp103 * _tmp74;
  const Scalar _tmp105 = Scalar(0.021999999999999999) * _tmp24;
  const Scalar _tmp106 = _tmp105 * _tmp77;
  const Scalar _tmp107 = _tmp100 + _tmp102 + _tmp104 + _tmp106;
  const Scalar _tmp108 = _tmp16 * _tmp71;
  const Scalar _tmp109 = Scalar(0.83999999999999997) * _tmp108;
  const Scalar _tmp110 = Scalar(0.83999999999999997) * _tmp77;
  const Scalar _tmp111 = _tmp110 * _tmp21;
  const Scalar _tmp112 = _tmp109 + _tmp111;
  const Scalar _tmp113 = _tmp107 + _tmp112;
  const Scalar _tmp114 = Scalar(0.83999999999999997) * _tmp83;
  const Scalar _tmp115 = _tmp109 + _tmp114;
  const Scalar _tmp116 = -_tmp92 - _tmp93;
  const Scalar _tmp117 = _tmp116 + _tmp97;
  const Scalar _tmp118 = _tmp115 + _tmp117;
  const Scalar _tmp119 = _tmp12 * _tmp99;
  const Scalar _tmp120 = _tmp101 * _tmp21;
  const Scalar _tmp121 = _tmp103 * _tmp77;
  const Scalar _tmp122 = _tmp105 * _tmp74;
  const Scalar _tmp123 = -_tmp119 + _tmp120 + _tmp121 - _tmp122;
  const Scalar _tmp124 = 2 * _tmp47 * (_tmp118 + _tmp123) + 2 * _tmp55 * (_tmp113 + _tmp98);
  const Scalar _tmp125 = std::sqrt(_tmp56);
  const Scalar _tmp126 = Scalar(1.0) / (fh1);
  const Scalar _tmp127 = _tmp30 - _tmp33;
  const Scalar _tmp128 = _tmp127 + _tmp27;
  const Scalar _tmp129 = -_tmp128 - p_init2 + Scalar(8.4693136199999994);
  const Scalar _tmp130 = _tmp41 - _tmp43;
  const Scalar _tmp131 = _tmp130 + _tmp39;
  const Scalar _tmp132 = _tmp131 + p_init1;
  const Scalar _tmp133 = -_tmp132 + Scalar(-8.3888750099999996);
  const Scalar _tmp134 = _tmp50 - _tmp51;
  const Scalar _tmp135 = _tmp134 + _tmp48;
  const Scalar _tmp136 = _tmp135 + p_init0;
  const Scalar _tmp137 = Scalar(2.5202214700000001) - _tmp136;
  const Scalar _tmp138 = std::pow(_tmp133, Scalar(2)) + std::pow(_tmp137, Scalar(2));
  const Scalar _tmp139 = _tmp87 + _tmp88 + _tmp89 + _tmp90;
  const Scalar _tmp140 = _tmp139 + _tmp86;
  const Scalar _tmp141 = -_tmp109;
  const Scalar _tmp142 = -_tmp114 + _tmp141;
  const Scalar _tmp143 = _tmp123 + _tmp142;
  const Scalar _tmp144 = _tmp117 + _tmp143;
  const Scalar _tmp145 = _tmp95 + _tmp96;
  const Scalar _tmp146 = _tmp116 + _tmp145;
  const Scalar _tmp147 = 2 * _tmp133 * _tmp144 + 2 * _tmp137 * (_tmp113 + _tmp146);
  const Scalar _tmp148 = -_tmp39;
  const Scalar _tmp149 = _tmp148 + _tmp44;
  const Scalar _tmp150 = _tmp149 + p_init1;
  const Scalar _tmp151 = _tmp150 + Scalar(-4.8333311099999996);
  const Scalar _tmp152 = -_tmp48;
  const Scalar _tmp153 = _tmp152 + _tmp52;
  const Scalar _tmp154 = _tmp153 + p_init0;
  const Scalar _tmp155 = _tmp154 + Scalar(1.79662371);
  const Scalar _tmp156 = std::pow(_tmp151, Scalar(2)) + std::pow(_tmp155, Scalar(2));
  const Scalar _tmp157 = std::pow(_tmp156, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp158 = _tmp155 * _tmp157;
  const Scalar _tmp159 = _tmp136 + Scalar(-2.5202214700000001);
  const Scalar _tmp160 = Scalar(1.0) / (_tmp159);
  const Scalar _tmp161 = _tmp132 + Scalar(8.3888750099999996);
  const Scalar _tmp162 = _tmp160 * _tmp161;
  const Scalar _tmp163 = _tmp128 * _tmp162;
  const Scalar _tmp164 = -_tmp27;
  const Scalar _tmp165 = _tmp164 + _tmp34;
  const Scalar _tmp166 = _tmp151 * _tmp157;
  const Scalar _tmp167 = -_tmp158 * _tmp163 + _tmp165 * _tmp166;
  const Scalar _tmp168 = _tmp130 + _tmp148;
  const Scalar _tmp169 = _tmp168 + p_init1;
  const Scalar _tmp170 = _tmp169 + Scalar(8.3196563700000006);
  const Scalar _tmp171 = _tmp134 + _tmp152;
  const Scalar _tmp172 = _tmp171 + p_init0;
  const Scalar _tmp173 = _tmp172 + Scalar(1.9874742000000001);
  const Scalar _tmp174 = std::pow(_tmp170, Scalar(2)) + std::pow(_tmp173, Scalar(2));
  const Scalar _tmp175 = std::pow(_tmp174, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp176 = _tmp173 * _tmp175;
  const Scalar _tmp177 = _tmp170 * _tmp175;
  const Scalar _tmp178 = _tmp162 * _tmp176 - _tmp177;
  const Scalar _tmp179 = _tmp158 * _tmp162 - _tmp166;
  const Scalar _tmp180 = Scalar(1.0) / (_tmp179);
  const Scalar _tmp181 = _tmp178 * _tmp180;
  const Scalar _tmp182 = _tmp127 + _tmp164;
  const Scalar _tmp183 = -_tmp163 * _tmp176 - _tmp167 * _tmp181 + _tmp177 * _tmp182;
  const Scalar _tmp184 = Scalar(1.0) * _tmp131;
  const Scalar _tmp185 = -_tmp184;
  const Scalar _tmp186 = _tmp149 + _tmp185;
  const Scalar _tmp187 = Scalar(1.0) / (_tmp186);
  const Scalar _tmp188 = Scalar(1.0) * _tmp135;
  const Scalar _tmp189 = -_tmp153 + _tmp188;
  const Scalar _tmp190 = _tmp187 * _tmp189;
  const Scalar _tmp191 = _tmp128 * _tmp158;
  const Scalar _tmp192 = -_tmp158 * _tmp165 + _tmp191;
  const Scalar _tmp193 = _tmp128 * _tmp176;
  const Scalar _tmp194 = -_tmp176 * _tmp182 - _tmp181 * _tmp192 - _tmp183 * _tmp190 + _tmp193;
  const Scalar _tmp195 = Scalar(1.0) / (_tmp194);
  const Scalar _tmp196 = Scalar(1.0) * _tmp187;
  const Scalar _tmp197 = _tmp189 * _tmp196;
  const Scalar _tmp198 = _tmp180 * _tmp197;
  const Scalar _tmp199 = Scalar(1.0) * _tmp180;
  const Scalar _tmp200 = _tmp167 * _tmp198 - _tmp192 * _tmp199;
  const Scalar _tmp201 = std::pow(_tmp159, Scalar(2));
  const Scalar _tmp202 = std::pow(_tmp161, Scalar(2)) + _tmp201;
  const Scalar _tmp203 = std::sqrt(_tmp202);
  const Scalar _tmp204 = Scalar(1.0) / (_tmp203);
  const Scalar _tmp205 = _tmp159 * _tmp204;
  const Scalar _tmp206 = _tmp161 * _tmp204;
  const Scalar _tmp207 = -_tmp131 * _tmp205 + _tmp135 * _tmp206;
  const Scalar _tmp208 = _tmp160 * _tmp203;
  const Scalar _tmp209 = _tmp207 * _tmp208;
  const Scalar _tmp210 = _tmp149 * _tmp158 - _tmp153 * _tmp166 + _tmp158 * _tmp209;
  const Scalar _tmp211 =
      _tmp168 * _tmp176 - _tmp171 * _tmp177 + _tmp176 * _tmp209 - _tmp181 * _tmp210;
  const Scalar _tmp212 = _tmp195 * _tmp211;
  const Scalar _tmp213 = -_tmp199 * _tmp210 - _tmp200 * _tmp212;
  const Scalar _tmp214 = Scalar(1.0) / (_tmp211);
  const Scalar _tmp215 = _tmp194 * _tmp214;
  const Scalar _tmp216 = _tmp213 * _tmp215;
  const Scalar _tmp217 = _tmp200 + _tmp216;
  const Scalar _tmp218 = _tmp195 * _tmp217;
  const Scalar _tmp219 = -_tmp178 * _tmp218 + Scalar(1.0);
  const Scalar _tmp220 = _tmp158 * _tmp180;
  const Scalar _tmp221 = _tmp176 * _tmp218 + _tmp219 * _tmp220;
  const Scalar _tmp222 = _tmp46 + Scalar(-4.7752063900000001);
  const Scalar _tmp223 = _tmp54 + Scalar(-2.71799795);
  const Scalar _tmp224 = std::pow(_tmp222, Scalar(2)) + std::pow(_tmp223, Scalar(2));
  const Scalar _tmp225 = std::pow(_tmp224, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp226 = _tmp225 * fh1;
  const Scalar _tmp227 = _tmp222 * _tmp226;
  const Scalar _tmp228 = _tmp208 * _tmp227;
  const Scalar _tmp229 = _tmp225 * _tmp53;
  const Scalar _tmp230 = _tmp223 * _tmp225;
  const Scalar _tmp231 = fh1 * (_tmp222 * _tmp229 - _tmp230 * _tmp45);
  const Scalar _tmp232 = Scalar(1.0) * _tmp214;
  const Scalar _tmp233 = _tmp158 * _tmp181;
  const Scalar _tmp234 = _tmp176 * _tmp232 - _tmp232 * _tmp233;
  const Scalar _tmp235 = _tmp208 * _tmp234;
  const Scalar _tmp236 = _tmp230 * fh1;
  const Scalar _tmp237 = _tmp162 * _tmp180;
  const Scalar _tmp238 = _tmp163 + _tmp167 * _tmp237;
  const Scalar _tmp239 = -_tmp128 - _tmp190 * _tmp238 + _tmp192 * _tmp237;
  const Scalar _tmp240 = -_tmp209 + _tmp210 * _tmp237 - _tmp212 * _tmp239;
  const Scalar _tmp241 = _tmp215 * _tmp240;
  const Scalar _tmp242 = _tmp239 + _tmp241;
  const Scalar _tmp243 = _tmp195 * _tmp242;
  const Scalar _tmp244 = _tmp178 * _tmp195;
  const Scalar _tmp245 = -_tmp162 - _tmp242 * _tmp244;
  const Scalar _tmp246 = _tmp176 * _tmp243 + _tmp220 * _tmp245 + Scalar(1.0);
  const Scalar _tmp247 = _tmp208 * _tmp246;
  const Scalar _tmp248 = _tmp184 * _tmp190 + _tmp188;
  const Scalar _tmp249 = 0;
  const Scalar _tmp250 = _tmp195 * _tmp249;
  const Scalar _tmp251 = _tmp176 * _tmp250 - _tmp233 * _tmp250;
  const Scalar _tmp252 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp253 = _tmp208 * _tmp252;
  const Scalar _tmp254 =
      -_tmp221 * _tmp228 - _tmp231 * _tmp235 - _tmp236 * _tmp247 - _tmp251 * _tmp253;
  const Scalar _tmp255 = Scalar(1.0) / (_tmp254);
  const Scalar _tmp256 = _tmp167 * _tmp199;
  const Scalar _tmp257 = _tmp168 + _tmp185;
  const Scalar _tmp258 = _tmp190 * _tmp257;
  const Scalar _tmp259 = -_tmp171 + _tmp188 - _tmp258;
  const Scalar _tmp260 = Scalar(1.0) / (_tmp259);
  const Scalar _tmp261 = _tmp257 * _tmp260;
  const Scalar _tmp262 = -_tmp183 * _tmp218 + _tmp216 * _tmp261 - _tmp256;
  const Scalar _tmp263 = Scalar(1.0) * _tmp260;
  const Scalar _tmp264 = -_tmp196 * _tmp262 + _tmp216 * _tmp263;
  const Scalar _tmp265 = Scalar(1.0) * _tmp227;
  const Scalar _tmp266 = _tmp236 * _tmp35 + Scalar(3.29616) * _tmp49 + _tmp53 * fv1;
  const Scalar _tmp267 = _tmp187 * _tmp263;
  const Scalar _tmp268 = Scalar(1.0) * _tmp257 * _tmp267 - Scalar(1.0) * _tmp263;
  const Scalar _tmp269 = _tmp258 * _tmp263 + Scalar(1.0);
  const Scalar _tmp270 = _tmp187 * _tmp269;
  const Scalar _tmp271 = _tmp190 * _tmp263;
  const Scalar _tmp272 = -Scalar(1.0) * _tmp270 + _tmp271;
  const Scalar _tmp273 = _tmp226 * _tmp35;
  const Scalar _tmp274 = -_tmp222 * _tmp273 - Scalar(3.29616) * _tmp40 - _tmp45 * fv1;
  const Scalar _tmp275 = Scalar(1.0) * _tmp274;
  const Scalar _tmp276 = _tmp183 * _tmp195;
  const Scalar _tmp277 = _tmp248 * _tmp260;
  const Scalar _tmp278 = _tmp185 - _tmp249 * _tmp276 - _tmp257 * _tmp277;
  const Scalar _tmp279 = Scalar(1.0) * _tmp252;
  const Scalar _tmp280 = _tmp238 + _tmp241 * _tmp261 - _tmp242 * _tmp276;
  const Scalar _tmp281 = -_tmp196 * _tmp280 + _tmp241 * _tmp263;
  const Scalar _tmp282 = Scalar(1.0) * _tmp281;
  const Scalar _tmp283 = _tmp215 * _tmp263;
  const Scalar _tmp284 = -_tmp183 * _tmp232 + _tmp257 * _tmp283;
  const Scalar _tmp285 = -Scalar(1.0) * _tmp196 * _tmp284 + Scalar(1.0) * _tmp283;
  const Scalar _tmp286 = _tmp231 * _tmp285 + _tmp236 * _tmp282 + _tmp264 * _tmp265 +
                         _tmp266 * _tmp268 + _tmp272 * _tmp275 +
                         _tmp279 * (-_tmp196 * _tmp278 - _tmp248 * _tmp263 + Scalar(1.0));
  const Scalar _tmp287 = std::asinh(_tmp255 * _tmp286);
  const Scalar _tmp288 = Scalar(1.0) * _tmp287;
  const Scalar _tmp289 = std::pow(_tmp254, Scalar(-2));
  const Scalar _tmp290 = Scalar(0.83999999999999997) * _tmp16 * _tmp67;
  const Scalar _tmp291 = Scalar(0.83999999999999997) * _tmp24 * _tmp71;
  const Scalar _tmp292 = -_tmp110 * _tmp12 - Scalar(0.83999999999999997) * _tmp21 * _tmp74;
  const Scalar _tmp293 = -_tmp290 - _tmp291 + _tmp292;
  const Scalar _tmp294 = _tmp190 * _tmp293;
  const Scalar _tmp295 = -Scalar(1.6799999999999999) * _tmp108;
  const Scalar _tmp296 = _tmp295 - Scalar(1.6799999999999999) * _tmp81;
  const Scalar _tmp297 = _tmp187 * (_tmp290 + _tmp291 + _tmp292 + _tmp296);
  const Scalar _tmp298 = _tmp257 * _tmp297;
  const Scalar _tmp299 =
      (_tmp293 + _tmp295 - Scalar(1.6799999999999999) * _tmp83) / std::pow(_tmp186, Scalar(2));
  const Scalar _tmp300 = _tmp189 * _tmp257;
  const Scalar _tmp301 = _tmp299 * _tmp300;
  const Scalar _tmp302 = (-_tmp294 + _tmp296 - _tmp298 + _tmp301) / std::pow(_tmp259, Scalar(2));
  const Scalar _tmp303 = _tmp257 * _tmp302;
  const Scalar _tmp304 = _tmp196 * _tmp303;
  const Scalar _tmp305 = _tmp257 * _tmp299;
  const Scalar _tmp306 = Scalar(1.0) * _tmp302;
  const Scalar _tmp307 = _tmp145 + _tmp94;
  const Scalar _tmp308 = _tmp119 - _tmp120 - _tmp121 + _tmp122;
  const Scalar _tmp309 = _tmp142 + _tmp308;
  const Scalar _tmp310 = _tmp307 + _tmp309;
  const Scalar _tmp311 = -_tmp100 - _tmp102 - _tmp104 - _tmp106;
  const Scalar _tmp312 = -_tmp111 + _tmp141;
  const Scalar _tmp313 = _tmp146 + _tmp312;
  const Scalar _tmp314 = _tmp311 + _tmp313;
  const Scalar _tmp315 =
      (2 * _tmp222 * _tmp310 + 2 * _tmp223 * _tmp314) / (_tmp224 * std::sqrt(_tmp224));
  const Scalar _tmp316 = (Scalar(1) / Scalar(2)) * _tmp315;
  const Scalar _tmp317 = _tmp222 * _tmp316;
  const Scalar _tmp318 = _tmp35 * fh1;
  const Scalar _tmp319 = Scalar(6.59232) * _tmp67;
  const Scalar _tmp320 = Scalar(6.59232) * _tmp71;
  const Scalar _tmp321 = Scalar(6.59232) * _tmp16;
  const Scalar _tmp322 = -_tmp69 + _tmp73 + _tmp76 - _tmp79;
  const Scalar _tmp323 = _tmp82 + _tmp84;
  const Scalar _tmp324 = _tmp139 + _tmp323;
  const Scalar _tmp325 = _tmp322 + _tmp324;
  const Scalar _tmp326 = Scalar(6.59232) * _tmp24;
  const Scalar _tmp327 = _tmp12 * _tmp319 - _tmp21 * _tmp320 - _tmp227 * _tmp325 -
                         _tmp273 * _tmp310 - _tmp310 * fv1 + _tmp317 * _tmp318 - _tmp321 * _tmp77 +
                         _tmp326 * _tmp74;
  const Scalar _tmp328 = _tmp225 * _tmp314;
  const Scalar _tmp329 = _tmp328 * fh1;
  const Scalar _tmp330 = _tmp223 * _tmp316;
  const Scalar _tmp331 = _tmp12 * _tmp320 + _tmp21 * _tmp319 + _tmp236 * _tmp325 + _tmp314 * fv1 -
                         _tmp318 * _tmp330 + _tmp321 * _tmp74 + _tmp326 * _tmp77 + _tmp329 * _tmp35;
  const Scalar _tmp332 = Scalar(0.5) * _tmp315 * fh1;
  const Scalar _tmp333 = _tmp115 + _tmp307;
  const Scalar _tmp334 = _tmp308 + _tmp333;
  const Scalar _tmp335 = _tmp160 * _tmp334;
  const Scalar _tmp336 = _tmp112 + _tmp311;
  const Scalar _tmp337 = _tmp146 + _tmp336;
  const Scalar _tmp338 = _tmp117 + _tmp309;
  const Scalar _tmp339 =
      (2 * _tmp151 * _tmp338 + 2 * _tmp155 * _tmp337) / (_tmp156 * std::sqrt(_tmp156));
  const Scalar _tmp340 = (Scalar(1) / Scalar(2)) * _tmp339;
  const Scalar _tmp341 = _tmp155 * _tmp340;
  const Scalar _tmp342 = _tmp151 * _tmp340;
  const Scalar _tmp343 = _tmp157 * _tmp337;
  const Scalar _tmp344 = _tmp312 + _tmp98;
  const Scalar _tmp345 = _tmp311 + _tmp344;
  const Scalar _tmp346 = _tmp345 / _tmp201;
  const Scalar _tmp347 = _tmp161 * _tmp346;
  const Scalar _tmp348 = _tmp157 * _tmp338;
  const Scalar _tmp349 = (_tmp158 * _tmp335 - _tmp158 * _tmp347 - _tmp162 * _tmp341 +
                          _tmp162 * _tmp343 + _tmp342 - _tmp348) /
                         std::pow(_tmp179, Scalar(2));
  const Scalar _tmp350 = Scalar(1.0) * _tmp349;
  const Scalar _tmp351 = _tmp159 * _tmp345 + _tmp161 * _tmp334;
  const Scalar _tmp352 = _tmp351 / (_tmp202 * std::sqrt(_tmp202));
  const Scalar _tmp353 = _tmp208 * (_tmp131 * _tmp159 * _tmp352 - _tmp131 * _tmp204 * _tmp345 -
                                    _tmp135 * _tmp161 * _tmp352 + _tmp135 * _tmp204 * _tmp334 -
                                    _tmp205 * _tmp334 + _tmp206 * _tmp345);
  const Scalar _tmp354 = _tmp203 * _tmp346;
  const Scalar _tmp355 = _tmp207 * _tmp354;
  const Scalar _tmp356 = _tmp160 * _tmp204 * _tmp351;
  const Scalar _tmp357 = _tmp207 * _tmp356;
  const Scalar _tmp358 = -_tmp149 * _tmp341 + _tmp149 * _tmp343 + _tmp153 * _tmp342 -
                         _tmp153 * _tmp348 + _tmp155 * _tmp348 + _tmp158 * _tmp353 -
                         _tmp158 * _tmp355 + _tmp158 * _tmp357 - _tmp166 * _tmp337 -
                         _tmp209 * _tmp341 + _tmp209 * _tmp343;
  const Scalar _tmp359 = _tmp189 * _tmp299;
  const Scalar _tmp360 = _tmp128 * _tmp343;
  const Scalar _tmp361 = _tmp324 + _tmp80;
  const Scalar _tmp362 = _tmp323 + _tmp91;
  const Scalar _tmp363 = _tmp322 + _tmp362;
  const Scalar _tmp364 = _tmp162 * _tmp363;
  const Scalar _tmp365 = _tmp128 * _tmp335;
  const Scalar _tmp366 = -_tmp158 * _tmp364 - _tmp158 * _tmp365 - _tmp162 * _tmp360 +
                         _tmp163 * _tmp341 - _tmp165 * _tmp342 + _tmp165 * _tmp348 +
                         _tmp166 * _tmp361 + _tmp191 * _tmp347;
  const Scalar _tmp367 = -_tmp128 * _tmp341 - _tmp158 * _tmp361 + _tmp158 * _tmp363 +
                         _tmp165 * _tmp341 - _tmp165 * _tmp343 + _tmp360;
  const Scalar _tmp368 = -_tmp167 * _tmp197 * _tmp349 + _tmp192 * _tmp350 + _tmp198 * _tmp366 -
                         _tmp199 * _tmp367 + _tmp256 * _tmp297 - _tmp256 * _tmp359;
  const Scalar _tmp369 = _tmp336 + _tmp98;
  const Scalar _tmp370 = _tmp118 + _tmp308;
  const Scalar _tmp371 =
      (2 * _tmp170 * _tmp370 + 2 * _tmp173 * _tmp369) / (_tmp174 * std::sqrt(_tmp174));
  const Scalar _tmp372 = (Scalar(1) / Scalar(2)) * _tmp371;
  const Scalar _tmp373 = _tmp173 * _tmp372;
  const Scalar _tmp374 = _tmp362 + _tmp80;
  const Scalar _tmp375 = _tmp175 * _tmp370;
  const Scalar _tmp376 = _tmp175 * _tmp369;
  const Scalar _tmp377 = _tmp170 * _tmp372;
  const Scalar _tmp378 = -_tmp162 * _tmp373 + _tmp162 * _tmp376 + _tmp176 * _tmp335 -
                         _tmp176 * _tmp347 - _tmp375 + _tmp377;
  const Scalar _tmp379 = _tmp180 * _tmp378;
  const Scalar _tmp380 = _tmp178 * _tmp349;
  const Scalar _tmp381 = _tmp128 * _tmp376;
  const Scalar _tmp382 = -_tmp162 * _tmp381 + _tmp163 * _tmp373 - _tmp167 * _tmp379 +
                         _tmp167 * _tmp380 - _tmp176 * _tmp364 - _tmp176 * _tmp365 +
                         _tmp177 * _tmp374 - _tmp181 * _tmp366 + _tmp182 * _tmp375 -
                         _tmp182 * _tmp377 + _tmp193 * _tmp347;
  const Scalar _tmp383 = -_tmp128 * _tmp373 + _tmp176 * _tmp363 - _tmp176 * _tmp374 -
                         _tmp181 * _tmp367 + _tmp182 * _tmp373 - _tmp182 * _tmp376 -
                         _tmp183 * _tmp297 + _tmp183 * _tmp359 - _tmp190 * _tmp382 -
                         _tmp192 * _tmp379 + _tmp192 * _tmp380 + _tmp381;
  const Scalar _tmp384 = _tmp383 / std::pow(_tmp194, Scalar(2));
  const Scalar _tmp385 = _tmp211 * _tmp384;
  const Scalar _tmp386 = -_tmp168 * _tmp373 + _tmp168 * _tmp376 - _tmp171 * _tmp375 +
                         _tmp171 * _tmp377 + _tmp173 * _tmp375 + _tmp176 * _tmp353 -
                         _tmp176 * _tmp355 + _tmp176 * _tmp357 - _tmp177 * _tmp369 -
                         _tmp181 * _tmp358 - _tmp209 * _tmp373 + _tmp209 * _tmp376 -
                         _tmp210 * _tmp379 + _tmp210 * _tmp380;
  const Scalar _tmp387 = _tmp195 * _tmp386;
  const Scalar _tmp388 = _tmp215 * (-_tmp199 * _tmp358 + _tmp200 * _tmp385 - _tmp200 * _tmp387 +
                                    _tmp210 * _tmp350 - _tmp212 * _tmp368);
  const Scalar _tmp389 = _tmp386 / std::pow(_tmp211, Scalar(2));
  const Scalar _tmp390 = _tmp194 * _tmp213;
  const Scalar _tmp391 = _tmp389 * _tmp390;
  const Scalar _tmp392 = _tmp232 * _tmp302;
  const Scalar _tmp393 = _tmp214 * _tmp383;
  const Scalar _tmp394 = _tmp213 * _tmp393;
  const Scalar _tmp395 = Scalar(1.0) * _tmp299;
  const Scalar _tmp396 = _tmp217 * _tmp384;
  const Scalar _tmp397 = _tmp260 * _tmp293;
  const Scalar _tmp398 = _tmp368 + _tmp388 - _tmp391 + _tmp394;
  const Scalar _tmp399 = _tmp167 * _tmp350 + _tmp183 * _tmp396 - _tmp199 * _tmp366 -
                         _tmp216 * _tmp303 + _tmp216 * _tmp397 - _tmp218 * _tmp382 +
                         _tmp261 * _tmp388 - _tmp261 * _tmp391 + _tmp261 * _tmp394 -
                         _tmp276 * _tmp398;
  const Scalar _tmp400 = fh1 * (_tmp222 * _tmp328 + _tmp229 * _tmp310 - _tmp230 * _tmp310 -
                                _tmp317 * _tmp53 - _tmp328 * _tmp45 + _tmp330 * _tmp45);
  const Scalar _tmp401 = _tmp184 * _tmp297 - _tmp184 * _tmp359 + _tmp197 * _tmp334 + _tmp345;
  const Scalar _tmp402 = _tmp183 * _tmp384;
  const Scalar _tmp403 = _tmp248 * _tmp302;
  const Scalar _tmp404 = _tmp260 * _tmp401;
  const Scalar _tmp405 = _tmp144 + _tmp249 * _tmp402 - _tmp250 * _tmp382 + _tmp257 * _tmp403 -
                         _tmp257 * _tmp404 - _tmp277 * _tmp293;
  const Scalar _tmp406 = _tmp194 * _tmp392;
  const Scalar _tmp407 = _tmp194 * _tmp389;
  const Scalar _tmp408 = _tmp263 * _tmp407;
  const Scalar _tmp409 = Scalar(1.0) * _tmp389;
  const Scalar _tmp410 = _tmp263 * _tmp393;
  const Scalar _tmp411 = _tmp183 * _tmp409 - _tmp194 * _tmp232 * _tmp303 - _tmp232 * _tmp382 -
                         _tmp257 * _tmp408 + _tmp257 * _tmp410 + _tmp283 * _tmp293;
  const Scalar _tmp412 = Scalar(1.0) * _tmp231;
  const Scalar _tmp413 = _tmp226 * _tmp310;
  const Scalar _tmp414 = _tmp180 * _tmp347;
  const Scalar _tmp415 = _tmp162 * _tmp349;
  const Scalar _tmp416 = _tmp180 * _tmp335;
  const Scalar _tmp417 = -_tmp128 * _tmp347 - _tmp167 * _tmp414 - _tmp167 * _tmp415 +
                         _tmp167 * _tmp416 + _tmp237 * _tmp366 + _tmp364 + _tmp365;
  const Scalar _tmp418 = _tmp140 - _tmp190 * _tmp417 - _tmp192 * _tmp414 - _tmp192 * _tmp415 +
                         _tmp192 * _tmp416 + _tmp237 * _tmp367 - _tmp238 * _tmp297 +
                         _tmp238 * _tmp359;
  const Scalar _tmp419 = _tmp215 * (-_tmp210 * _tmp414 - _tmp210 * _tmp415 + _tmp210 * _tmp416 -
                                    _tmp212 * _tmp418 + _tmp237 * _tmp358 + _tmp239 * _tmp385 -
                                    _tmp239 * _tmp387 - _tmp353 + _tmp355 - _tmp357);
  const Scalar _tmp420 = _tmp240 * _tmp407;
  const Scalar _tmp421 = _tmp240 * _tmp393;
  const Scalar _tmp422 = _tmp418 + _tmp419 - _tmp420 + _tmp421;
  const Scalar _tmp423 = -_tmp241 * _tmp303 + _tmp241 * _tmp397 + _tmp242 * _tmp402 -
                         _tmp243 * _tmp382 + _tmp261 * _tmp419 - _tmp261 * _tmp420 +
                         _tmp261 * _tmp421 - _tmp276 * _tmp422 + _tmp417;
  const Scalar _tmp424 = _tmp263 * _tmp297;
  const Scalar _tmp425 =
      -_tmp196 * _tmp300 * _tmp302 + _tmp263 * _tmp294 + _tmp263 * _tmp298 - _tmp263 * _tmp301;
  const Scalar _tmp426 = _tmp197 * _tmp302;
  const Scalar _tmp427 = _tmp263 * _tmp359;
  const Scalar _tmp428 = _tmp269 * _tmp299;
  const Scalar _tmp429 = _tmp231 * _tmp234;
  const Scalar _tmp430 = _tmp330 * fh1;
  const Scalar _tmp431 = _tmp251 * _tmp252;
  const Scalar _tmp432 = _tmp178 * _tmp396 - _tmp218 * _tmp378 - _tmp244 * _tmp398;
  const Scalar _tmp433 = _tmp180 * _tmp219;
  const Scalar _tmp434 = _tmp176 * _tmp195;
  const Scalar _tmp435 = _tmp158 * _tmp349;
  const Scalar _tmp436 = _tmp180 * _tmp343;
  const Scalar _tmp437 = Scalar(0.5) * _tmp214;
  const Scalar _tmp438 = _tmp181 * _tmp343;
  const Scalar _tmp439 = _tmp158 * _tmp379;
  const Scalar _tmp440 = _tmp242 * _tmp384;
  const Scalar _tmp441 =
      _tmp178 * _tmp440 - _tmp243 * _tmp378 - _tmp244 * _tmp422 - _tmp335 + _tmp347;
  const Scalar _tmp442 = _tmp180 * _tmp245;
  const Scalar _tmp443 = _tmp236 * _tmp246;
  const Scalar _tmp444 = _tmp208 * _tmp221;
  const Scalar _tmp445 = _tmp317 * fh1;
  const Scalar _tmp446 = _tmp221 * _tmp227;
  const Scalar _tmp447 = _tmp249 * _tmp384;
  const Scalar _tmp448 =
      -_tmp208 * _tmp231 *
          (_tmp155 * _tmp181 * _tmp339 * _tmp437 + _tmp158 * _tmp232 * _tmp380 -
           _tmp173 * _tmp371 * _tmp437 - _tmp176 * _tmp409 + _tmp232 * _tmp376 - _tmp232 * _tmp438 -
           _tmp232 * _tmp439 + _tmp233 * _tmp409) -
      _tmp208 * _tmp236 *
          (-_tmp176 * _tmp440 + _tmp220 * _tmp441 - _tmp243 * _tmp373 + _tmp243 * _tmp376 -
           _tmp245 * _tmp435 + _tmp245 * _tmp436 - _tmp341 * _tmp442 + _tmp422 * _tmp434) -
      _tmp228 * (-_tmp176 * _tmp396 - _tmp218 * _tmp373 + _tmp218 * _tmp376 - _tmp219 * _tmp435 +
                 _tmp219 * _tmp436 + _tmp220 * _tmp432 - _tmp341 * _tmp433 + _tmp398 * _tmp434) -
      _tmp235 * _tmp400 - _tmp247 * _tmp329 + _tmp247 * _tmp430 -
      _tmp253 * (-_tmp176 * _tmp447 + _tmp181 * _tmp250 * _tmp341 + _tmp233 * _tmp447 +
                 _tmp244 * _tmp249 * _tmp435 - _tmp250 * _tmp373 + _tmp250 * _tmp376 -
                 _tmp250 * _tmp438 - _tmp250 * _tmp439) +
      _tmp354 * _tmp429 + _tmp354 * _tmp431 + _tmp354 * _tmp443 + _tmp354 * _tmp446 -
      _tmp356 * _tmp429 - _tmp356 * _tmp431 - _tmp356 * _tmp443 - _tmp356 * _tmp446 -
      _tmp413 * _tmp444 + _tmp444 * _tmp445;
  const Scalar _tmp449 = _tmp289 * _tmp448;
  const Scalar _tmp450 =
      (_tmp255 *
           (-_tmp222 * _tmp264 * _tmp332 - _tmp223 * _tmp281 * _tmp332 +
            Scalar(1.0) * _tmp236 *
                (-_tmp196 * _tmp423 - _tmp240 * _tmp406 + _tmp263 * _tmp419 - _tmp263 * _tmp420 +
                 _tmp263 * _tmp421 + _tmp280 * _tmp395) +
            Scalar(1.0) * _tmp264 * _tmp413 +
            _tmp265 * (-_tmp196 * _tmp399 + _tmp262 * _tmp395 + _tmp263 * _tmp388 -
                       _tmp263 * _tmp391 + _tmp263 * _tmp394 - _tmp390 * _tmp392) +
            Scalar(1.0) * _tmp266 * (-_tmp263 * _tmp305 + _tmp267 * _tmp293 - _tmp304 + _tmp306) +
            _tmp268 * _tmp331 + Scalar(1.0) * _tmp272 * _tmp327 +
            _tmp275 * (-_tmp196 * _tmp425 + _tmp424 - _tmp426 - _tmp427 + Scalar(1.0) * _tmp428) +
            _tmp279 *
                (-_tmp196 * _tmp405 + _tmp248 * _tmp306 - _tmp263 * _tmp401 + _tmp278 * _tmp395) +
            _tmp282 * _tmp329 + _tmp285 * _tmp400 +
            _tmp412 * (-_tmp196 * _tmp411 + _tmp284 * _tmp395 - _tmp406 - _tmp408 + _tmp410)) -
       _tmp286 * _tmp449) /
      std::sqrt(Scalar(std::pow(_tmp286, Scalar(2)) * _tmp289 + 1));
  const Scalar _tmp451 = std::sqrt(_tmp138);
  const Scalar _tmp452 = Scalar(9.6622558468725703) * _tmp254;
  const Scalar _tmp453 = -_tmp287 * _tmp452 - _tmp451;
  const Scalar _tmp454 = Scalar(0.1034955) * _tmp255;
  const Scalar _tmp455 = _tmp453 * _tmp454;
  const Scalar _tmp456 = Scalar(9.6622558468725703) * _tmp448;
  const Scalar _tmp457 = _tmp322 + _tmp85;
  const Scalar _tmp458 = -_tmp165 - p_init2 + Scalar(8.3700199099999999);
  const Scalar _tmp459 = -_tmp154 + Scalar(-1.79662371);
  const Scalar _tmp460 = Scalar(4.8333311099999996) - _tmp150;
  const Scalar _tmp461 = 2 * _tmp459 * (_tmp107 + _tmp344) + 2 * _tmp460 * (_tmp123 + _tmp333);
  const Scalar _tmp462 = std::pow(_tmp459, Scalar(2)) + std::pow(_tmp460, Scalar(2));
  const Scalar _tmp463 = _tmp263 * _tmp266;
  const Scalar _tmp464 = _tmp187 * _tmp463;
  const Scalar _tmp465 = _tmp187 * _tmp284;
  const Scalar _tmp466 = _tmp187 * _tmp236;
  const Scalar _tmp467 = _tmp187 * _tmp227;
  const Scalar _tmp468 = _tmp187 * _tmp252;
  const Scalar _tmp469 = _tmp231 * _tmp465 - _tmp257 * _tmp464 + _tmp262 * _tmp467 +
                         _tmp270 * _tmp274 + _tmp278 * _tmp468 + _tmp280 * _tmp466;
  const Scalar _tmp470 = _tmp231 * _tmp232;
  const Scalar _tmp471 = _tmp250 * _tmp252;
  const Scalar _tmp472 = _tmp180 * _tmp227;
  const Scalar _tmp473 =
      -_tmp181 * _tmp470 - _tmp181 * _tmp471 + _tmp219 * _tmp472 + _tmp236 * _tmp442;
  const Scalar _tmp474 = Scalar(1.0) / (_tmp473);
  const Scalar _tmp475 = std::asinh(_tmp469 * _tmp474);
  const Scalar _tmp476 = Scalar(1.0) * _tmp475;
  const Scalar _tmp477 = std::pow(_tmp473, Scalar(-2));
  const Scalar _tmp478 = _tmp249 * _tmp252;
  const Scalar _tmp479 = _tmp389 * _tmp412;
  const Scalar _tmp480 = _tmp232 * _tmp400;
  const Scalar _tmp481 = _tmp384 * _tmp478;
  const Scalar _tmp482 =
      _tmp180 * _tmp236 * _tmp441 + _tmp181 * _tmp479 - _tmp181 * _tmp480 + _tmp181 * _tmp481 -
      _tmp219 * _tmp227 * _tmp349 - _tmp236 * _tmp245 * _tmp349 + _tmp244 * _tmp349 * _tmp478 +
      _tmp329 * _tmp442 - _tmp379 * _tmp470 - _tmp379 * _tmp471 + _tmp380 * _tmp470 +
      _tmp413 * _tmp433 - _tmp430 * _tmp442 + _tmp432 * _tmp472 - _tmp433 * _tmp445;
  const Scalar _tmp483 = _tmp477 * _tmp482;
  const Scalar _tmp484 = _tmp187 * _tmp262;
  const Scalar _tmp485 = _tmp187 * _tmp280;
  const Scalar _tmp486 = _tmp263 * _tmp331;
  const Scalar _tmp487 =
      (-_tmp469 * _tmp483 +
       _tmp474 * (_tmp187 * _tmp231 * _tmp411 - _tmp187 * _tmp257 * _tmp486 +
                  _tmp187 * _tmp274 * _tmp425 - _tmp227 * _tmp262 * _tmp299 -
                  _tmp231 * _tmp284 * _tmp299 - _tmp236 * _tmp280 * _tmp299 -
                  _tmp252 * _tmp278 * _tmp299 + _tmp266 * _tmp304 + _tmp270 * _tmp327 -
                  _tmp274 * _tmp428 - _tmp293 * _tmp464 + _tmp305 * _tmp463 + _tmp329 * _tmp485 +
                  _tmp399 * _tmp467 + _tmp400 * _tmp465 + _tmp405 * _tmp468 + _tmp413 * _tmp484 +
                  _tmp423 * _tmp466 - _tmp430 * _tmp485 - _tmp445 * _tmp484)) /
      std::sqrt(Scalar(std::pow(_tmp469, Scalar(2)) * _tmp477 + 1));
  const Scalar _tmp488 = std::sqrt(_tmp462);
  const Scalar _tmp489 = Scalar(9.6622558468725703) * _tmp482;
  const Scalar _tmp490 = Scalar(9.6622558468725703) * _tmp473;
  const Scalar _tmp491 = Scalar(0.1034955) * _tmp474;
  const Scalar _tmp492 = -_tmp475 * _tmp490 - _tmp488;
  const Scalar _tmp493 = _tmp491 * _tmp492;
  const Scalar _tmp494 = -_tmp182 - p_init2 + Scalar(8.4718465799999993);
  const Scalar _tmp495 = -_tmp169 + Scalar(-8.3196563700000006);
  const Scalar _tmp496 = -_tmp172 + Scalar(-1.9874742000000001);
  const Scalar _tmp497 = std::pow(_tmp495, Scalar(2)) + std::pow(_tmp496, Scalar(2));
  const Scalar _tmp498 = 2 * _tmp495 * (_tmp143 + _tmp307) + 2 * _tmp496 * (_tmp107 + _tmp313);
  const Scalar _tmp499 = _tmp218 * _tmp227 + _tmp236 * _tmp243 + _tmp470 + _tmp471;
  const Scalar _tmp500 = Scalar(1.0) / (_tmp499);
  const Scalar _tmp501 = _tmp241 * _tmp260;
  const Scalar _tmp502 = _tmp216 * _tmp260;
  const Scalar _tmp503 = -_tmp227 * _tmp502 - _tmp231 * _tmp283 - _tmp236 * _tmp501 +
                         _tmp252 * _tmp277 - _tmp271 * _tmp274 + _tmp463;
  const Scalar _tmp504 = std::asinh(_tmp500 * _tmp503);
  const Scalar _tmp505 = Scalar(9.6622558468725703) * _tmp499;
  const Scalar _tmp506 = std::sqrt(_tmp497);
  const Scalar _tmp507 = -_tmp504 * _tmp505 - _tmp506;
  const Scalar _tmp508 = Scalar(0.1034955) * _tmp500;
  const Scalar _tmp509 = _tmp507 * _tmp508;
  const Scalar _tmp510 = Scalar(1.0) * _tmp504;
  const Scalar _tmp511 = _tmp195 * _tmp227 * _tmp398 + _tmp195 * _tmp236 * _tmp422 +
                         _tmp218 * _tmp413 - _tmp218 * _tmp445 - _tmp227 * _tmp396 -
                         _tmp236 * _tmp440 + _tmp243 * _tmp329 - _tmp243 * _tmp430 - _tmp479 +
                         _tmp480 - _tmp481;
  const Scalar _tmp512 = Scalar(9.6622558468725703) * _tmp511;
  const Scalar _tmp513 = std::pow(_tmp499, Scalar(-2));
  const Scalar _tmp514 = _tmp236 * _tmp260;
  const Scalar _tmp515 = _tmp227 * _tmp260;
  const Scalar _tmp516 = _tmp511 * _tmp513;
  const Scalar _tmp517 =
      (_tmp500 * (_tmp194 * _tmp302 * _tmp470 + _tmp216 * _tmp227 * _tmp302 + _tmp231 * _tmp408 -
                  _tmp231 * _tmp410 + _tmp236 * _tmp241 * _tmp302 - _tmp252 * _tmp403 +
                  _tmp252 * _tmp404 - _tmp266 * _tmp306 - _tmp271 * _tmp327 - _tmp274 * _tmp424 +
                  _tmp274 * _tmp426 + _tmp274 * _tmp427 - _tmp283 * _tmp400 - _tmp329 * _tmp501 -
                  _tmp388 * _tmp515 + _tmp391 * _tmp515 - _tmp394 * _tmp515 - _tmp413 * _tmp502 -
                  _tmp419 * _tmp514 + _tmp420 * _tmp514 - _tmp421 * _tmp514 + _tmp430 * _tmp501 +
                  _tmp445 * _tmp502 + _tmp486) -
       _tmp503 * _tmp516) /
      std::sqrt(Scalar(std::pow(_tmp503, Scalar(2)) * _tmp513 + 1));

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) =
      Scalar(0.5) * _tmp124 *
          std::cosh(Scalar(0.1034955) * _tmp126 *
                    (-_tmp125 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp126 * fv1))) /
          _tmp125 -
      Scalar(1) / Scalar(2) * (_tmp124 + 2 * _tmp36 * (_tmp86 + _tmp91)) /
          std::sqrt(Scalar(std::pow(_tmp36, Scalar(2)) + _tmp56));
  _res(1, 0) = _tmp452 * (-Scalar(1.0) * _tmp450 * std::cosh(_tmp288) -
                          (-Scalar(0.1034955) * _tmp449 * _tmp453 +
                           _tmp454 * (-Scalar(1) / Scalar(2) * _tmp147 / _tmp451 -
                                      _tmp287 * _tmp456 - _tmp450 * _tmp452)) *
                              std::cosh(_tmp455)) +
               _tmp456 * (-std::sinh(_tmp288) - std::sinh(_tmp455)) -
               Scalar(1) / Scalar(2) * (2 * _tmp129 * _tmp140 + _tmp147) /
                   std::sqrt(Scalar(std::pow(_tmp129, Scalar(2)) + _tmp138));
  _res(2, 0) = _tmp489 * (-std::sinh(_tmp476) - std::sinh(_tmp493)) +
               _tmp490 * (-Scalar(1.0) * _tmp487 * std::cosh(_tmp476) -
                          (-Scalar(0.1034955) * _tmp483 * _tmp492 +
                           _tmp491 * (-Scalar(1) / Scalar(2) * _tmp461 / _tmp488 -
                                      _tmp475 * _tmp489 - _tmp487 * _tmp490)) *
                              std::cosh(_tmp493)) -
               Scalar(1) / Scalar(2) * (2 * _tmp458 * (_tmp457 + _tmp91) + _tmp461) /
                   std::sqrt(Scalar(std::pow(_tmp458, Scalar(2)) + _tmp462));
  _res(3, 0) = _tmp505 * (-Scalar(1.0) * _tmp517 * std::cosh(_tmp510) -
                          (-Scalar(0.1034955) * _tmp507 * _tmp516 +
                           _tmp508 * (-Scalar(1) / Scalar(2) * _tmp498 / _tmp506 -
                                      _tmp504 * _tmp512 - _tmp505 * _tmp517)) *
                              std::cosh(_tmp509)) +
               _tmp512 * (-std::sinh(_tmp509) - std::sinh(_tmp510)) -
               Scalar(1) / Scalar(2) * (2 * _tmp494 * (_tmp139 + _tmp457) + _tmp498) /
                   std::sqrt(Scalar(std::pow(_tmp494, Scalar(2)) + _tmp497));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
