// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost1_wrt_fh1_Nl18
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     rx: Scalar
 *     ry: Scalar
 *     rz: Scalar
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost1WrtFh1Nl18(
    const Scalar fh1, const Scalar fv1, const Scalar rx, const Scalar ry, const Scalar rz,
    const Scalar p_init0, const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x,
    const Scalar rot_init_y, const Scalar rot_init_z, const Scalar rot_init_w,
    const Scalar epsilon) {
  // Total ops: 664

  // Unused inputs
  (void)p_init2;
  (void)epsilon;

  // Input arrays

  // Intermediate terms (220)
  const Scalar _tmp0 = Scalar(1.0) / (fh1);
  const Scalar _tmp1 = _tmp0 * fv1;
  const Scalar _tmp2 = std::asinh(_tmp1);
  const Scalar _tmp3 = Scalar(9.6622558468725703) * _tmp2;
  const Scalar _tmp4 = std::sqrt(
      Scalar(std::pow(rx, Scalar(2)) + std::pow(ry, Scalar(2)) + std::pow(rz, Scalar(2))));
  const Scalar _tmp5 = (Scalar(1) / Scalar(2)) * _tmp4;
  const Scalar _tmp6 = std::cos(_tmp5);
  const Scalar _tmp7 = std::sin(_tmp5) / _tmp4;
  const Scalar _tmp8 = _tmp7 * rot_init_x;
  const Scalar _tmp9 = _tmp7 * rx;
  const Scalar _tmp10 = _tmp7 * rz;
  const Scalar _tmp11 = _tmp10 * rot_init_w + _tmp6 * rot_init_z + _tmp8 * ry - _tmp9 * rot_init_y;
  const Scalar _tmp12 = -2 * std::pow(_tmp11, Scalar(2));
  const Scalar _tmp13 = _tmp7 * ry;
  const Scalar _tmp14 =
      _tmp10 * rot_init_y - _tmp13 * rot_init_z + _tmp6 * rot_init_x + _tmp9 * rot_init_w;
  const Scalar _tmp15 = 1 - 2 * std::pow(_tmp14, Scalar(2));
  const Scalar _tmp16 = Scalar(0.20999999999999999) * _tmp12 + Scalar(0.20999999999999999) * _tmp15;
  const Scalar _tmp17 =
      -_tmp10 * rot_init_x + _tmp13 * rot_init_w + _tmp6 * rot_init_y + _tmp9 * rot_init_z;
  const Scalar _tmp18 = 2 * _tmp11;
  const Scalar _tmp19 = _tmp17 * _tmp18;
  const Scalar _tmp20 =
      -_tmp10 * rot_init_z - _tmp13 * rot_init_y + _tmp6 * rot_init_w - _tmp8 * rx;
  const Scalar _tmp21 = 2 * _tmp14;
  const Scalar _tmp22 = _tmp20 * _tmp21;
  const Scalar _tmp23 = _tmp19 - _tmp22;
  const Scalar _tmp24 = -Scalar(0.010999999999999999) * _tmp23;
  const Scalar _tmp25 = _tmp17 * _tmp21;
  const Scalar _tmp26 = _tmp18 * _tmp20;
  const Scalar _tmp27 = Scalar(0.20999999999999999) * _tmp25 + Scalar(0.20999999999999999) * _tmp26;
  const Scalar _tmp28 = _tmp24 - _tmp27;
  const Scalar _tmp29 = _tmp16 + _tmp28;
  const Scalar _tmp30 = _tmp29 + p_init1;
  const Scalar _tmp31 = -2 * std::pow(_tmp17, Scalar(2));
  const Scalar _tmp32 = Scalar(0.20999999999999999) * _tmp12 +
                        Scalar(0.20999999999999999) * _tmp31 + Scalar(0.20999999999999999);
  const Scalar _tmp33 = -_tmp32;
  const Scalar _tmp34 = _tmp11 * _tmp21;
  const Scalar _tmp35 = 2 * _tmp17 * _tmp20;
  const Scalar _tmp36 = _tmp34 + _tmp35;
  const Scalar _tmp37 = -Scalar(0.010999999999999999) * _tmp36;
  const Scalar _tmp38 = Scalar(0.20999999999999999) * _tmp25 - Scalar(0.20999999999999999) * _tmp26;
  const Scalar _tmp39 = _tmp37 + _tmp38;
  const Scalar _tmp40 = _tmp33 + _tmp39;
  const Scalar _tmp41 = _tmp40 + p_init0;
  const Scalar _tmp42 =
      -_tmp3 * fh1 -
      Scalar(4.8333311099999996) *
          std::sqrt(
              Scalar(std::pow(Scalar(1 - Scalar(0.20689664689659551) * _tmp30), Scalar(2)) +
                     Scalar(0.13817235445745474) *
                         std::pow(Scalar(-Scalar(0.55659957866191134) * _tmp41 - 1), Scalar(2))));
  const Scalar _tmp43 = Scalar(0.1034955) * _tmp0;
  const Scalar _tmp44 = _tmp42 * _tmp43;
  const Scalar _tmp45 = Scalar(1.0) * _tmp2;
  const Scalar _tmp46 = std::pow(fh1, Scalar(-2));
  const Scalar _tmp47 =
      std::pow(Scalar(_tmp46 * std::pow(fv1, Scalar(2)) + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp48 = _tmp24 + _tmp27;
  const Scalar _tmp49 = _tmp16 + _tmp48;
  const Scalar _tmp50 = _tmp49 + p_init1;
  const Scalar _tmp51 = _tmp50 + Scalar(-4.7752063900000001);
  const Scalar _tmp52 = _tmp32 + _tmp39;
  const Scalar _tmp53 = _tmp52 + p_init0;
  const Scalar _tmp54 = _tmp53 + Scalar(-2.71799795);
  const Scalar _tmp55 = std::pow(Scalar(std::pow(_tmp51, Scalar(2)) + std::pow(_tmp54, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp56 = _tmp54 * _tmp55;
  const Scalar _tmp57 = Scalar(0.20999999999999999) * _tmp19 + Scalar(0.20999999999999999) * _tmp22;
  const Scalar _tmp58 = -_tmp57;
  const Scalar _tmp59 =
      -Scalar(0.010999999999999999) * _tmp15 - Scalar(0.010999999999999999) * _tmp31;
  const Scalar _tmp60 = Scalar(0.20999999999999999) * _tmp34 - Scalar(0.20999999999999999) * _tmp35;
  const Scalar _tmp61 = _tmp59 + _tmp60;
  const Scalar _tmp62 = _tmp58 + _tmp61;
  const Scalar _tmp63 = _tmp37 - _tmp38;
  const Scalar _tmp64 = _tmp32 + _tmp63;
  const Scalar _tmp65 = _tmp64 + p_init0;
  const Scalar _tmp66 = _tmp65 + Scalar(-2.5202214700000001);
  const Scalar _tmp67 = -_tmp16;
  const Scalar _tmp68 = _tmp48 + _tmp67;
  const Scalar _tmp69 = _tmp68 + p_init1;
  const Scalar _tmp70 = _tmp69 + Scalar(8.3888750099999996);
  const Scalar _tmp71 = std::pow(Scalar(std::pow(_tmp66, Scalar(2)) + std::pow(_tmp70, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp72 = _tmp66 * _tmp71;
  const Scalar _tmp73 = _tmp59 - _tmp60;
  const Scalar _tmp74 = _tmp58 + _tmp73;
  const Scalar _tmp75 = _tmp72 * _tmp74;
  const Scalar _tmp76 = -_tmp62 * _tmp72 + _tmp75;
  const Scalar _tmp77 = _tmp70 * _tmp71;
  const Scalar _tmp78 = _tmp28 + _tmp67;
  const Scalar _tmp79 = _tmp78 + p_init1;
  const Scalar _tmp80 = _tmp79 + Scalar(8.3196563700000006);
  const Scalar _tmp81 = _tmp33 + _tmp63;
  const Scalar _tmp82 = _tmp81 + p_init0;
  const Scalar _tmp83 = _tmp82 + Scalar(1.9874742000000001);
  const Scalar _tmp84 = Scalar(1.0) / (_tmp83);
  const Scalar _tmp85 = _tmp80 * _tmp84;
  const Scalar _tmp86 = Scalar(1.0) / (_tmp72 * _tmp85 - _tmp77);
  const Scalar _tmp87 = _tmp51 * _tmp55;
  const Scalar _tmp88 = _tmp56 * _tmp85 - _tmp87;
  const Scalar _tmp89 = _tmp86 * _tmp88;
  const Scalar _tmp90 = _tmp56 * _tmp74;
  const Scalar _tmp91 = _tmp57 + _tmp61;
  const Scalar _tmp92 = _tmp62 * _tmp77 - _tmp75 * _tmp85;
  const Scalar _tmp93 = -_tmp85 * _tmp90 + _tmp87 * _tmp91 - _tmp89 * _tmp92;
  const Scalar _tmp94 = Scalar(1.0) * _tmp78;
  const Scalar _tmp95 = -_tmp94;
  const Scalar _tmp96 = Scalar(1.0) / (_tmp68 + _tmp95);
  const Scalar _tmp97 = Scalar(1.0) * _tmp81;
  const Scalar _tmp98 = -_tmp64 + _tmp97;
  const Scalar _tmp99 = _tmp96 * _tmp98;
  const Scalar _tmp100 = -_tmp56 * _tmp91 - _tmp76 * _tmp89 + _tmp90 - _tmp93 * _tmp99;
  const Scalar _tmp101 = Scalar(1.0) / (_tmp100);
  const Scalar _tmp102 =
      std::sqrt(Scalar(std::pow(_tmp80, Scalar(2)) + std::pow(_tmp83, Scalar(2))));
  const Scalar _tmp103 = Scalar(1.0) / (_tmp102);
  const Scalar _tmp104 = _tmp102 * _tmp84;
  const Scalar _tmp105 = _tmp104 * (-_tmp103 * _tmp78 * _tmp83 + _tmp103 * _tmp80 * _tmp81);
  const Scalar _tmp106 = _tmp105 * _tmp72 - _tmp64 * _tmp77 + _tmp68 * _tmp72;
  const Scalar _tmp107 = Scalar(1.0) * _tmp86;
  const Scalar _tmp108 = Scalar(1.0) * _tmp96;
  const Scalar _tmp109 = -_tmp107 * _tmp76 + _tmp108 * _tmp86 * _tmp92 * _tmp98;
  const Scalar _tmp110 = _tmp105 * _tmp56 - _tmp106 * _tmp89 + _tmp49 * _tmp56 - _tmp52 * _tmp87;
  const Scalar _tmp111 = _tmp101 * _tmp110;
  const Scalar _tmp112 = Scalar(1.0) / (_tmp110);
  const Scalar _tmp113 = _tmp100 * _tmp112;
  const Scalar _tmp114 = _tmp113 * (-_tmp106 * _tmp107 - _tmp109 * _tmp111);
  const Scalar _tmp115 = _tmp101 * (_tmp109 + _tmp114);
  const Scalar _tmp116 = _tmp86 * (-_tmp115 * _tmp88 + Scalar(1.0));
  const Scalar _tmp117 = _tmp30 + Scalar(-4.8333311099999996);
  const Scalar _tmp118 = _tmp41 + Scalar(1.79662371);
  const Scalar _tmp119 =
      std::pow(Scalar(std::pow(_tmp117, Scalar(2)) + std::pow(_tmp118, Scalar(2))),
               Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp120 = _tmp117 * _tmp119;
  const Scalar _tmp121 = _tmp104 * _tmp120 * (_tmp115 * _tmp56 + _tmp116 * _tmp72);
  const Scalar _tmp122 = _tmp85 * _tmp86;
  const Scalar _tmp123 = _tmp122 * _tmp92 + _tmp74 * _tmp85;
  const Scalar _tmp124 = _tmp122 * _tmp76 - _tmp123 * _tmp99 - _tmp74;
  const Scalar _tmp125 = _tmp113 * (-_tmp105 + _tmp106 * _tmp122 - _tmp111 * _tmp124);
  const Scalar _tmp126 = _tmp101 * (_tmp124 + _tmp125);
  const Scalar _tmp127 = _tmp86 * (-_tmp126 * _tmp88 - _tmp85);
  const Scalar _tmp128 = _tmp118 * _tmp119;
  const Scalar _tmp129 = _tmp104 * _tmp128 * (_tmp126 * _tmp56 + _tmp127 * _tmp72 + Scalar(1.0));
  const Scalar _tmp130 = _tmp120 * _tmp40 - _tmp128 * _tmp29;
  const Scalar _tmp131 = Scalar(1.0) * _tmp112;
  const Scalar _tmp132 = _tmp72 * _tmp89;
  const Scalar _tmp133 = _tmp104 * _tmp130 * (-_tmp131 * _tmp132 + _tmp131 * _tmp56);
  const Scalar _tmp134 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp135 = _tmp94 * _tmp99 + _tmp97;
  const Scalar _tmp136 = 0;
  const Scalar _tmp137 = -_tmp104 * _tmp134 * (-_tmp132 * _tmp136 + _tmp136 * _tmp56) -
                         _tmp121 * fh1 - _tmp129 * fh1 - _tmp133 * fh1;
  const Scalar _tmp138 = std::pow(_tmp137, Scalar(-2));
  const Scalar _tmp139 = -_tmp121 - _tmp129 - _tmp133;
  const Scalar _tmp140 = _tmp138 * _tmp139;
  const Scalar _tmp141 = Scalar(1.0) / (_tmp137);
  const Scalar _tmp142 = _tmp49 + _tmp95;
  const Scalar _tmp143 = _tmp142 * _tmp99;
  const Scalar _tmp144 = Scalar(1.0) / (-_tmp143 - _tmp52 + _tmp97);
  const Scalar _tmp145 = _tmp135 * _tmp144;
  const Scalar _tmp146 = -_tmp136 * _tmp93 - _tmp142 * _tmp145 + _tmp95;
  const Scalar _tmp147 = Scalar(1.0) * _tmp144;
  const Scalar _tmp148 = _tmp142 * _tmp144;
  const Scalar _tmp149 = -_tmp107 * _tmp92 + _tmp114 * _tmp148 - _tmp115 * _tmp93;
  const Scalar _tmp150 = Scalar(1.0) * _tmp120 * (-_tmp108 * _tmp149 + _tmp114 * _tmp147);
  const Scalar _tmp151 = _tmp57 + _tmp73;
  const Scalar _tmp152 = _tmp151 * fh1;
  const Scalar _tmp153 = -_tmp120 * _tmp152 - Scalar(3.29616) * _tmp23 - _tmp29 * fv1;
  const Scalar _tmp154 = _tmp143 * _tmp147 + Scalar(1.0);
  const Scalar _tmp155 = _tmp147 * _tmp99;
  const Scalar _tmp156 = -Scalar(1.0) * _tmp108 * _tmp154 + Scalar(1.0) * _tmp155;
  const Scalar _tmp157 = _tmp128 * _tmp152 + Scalar(3.29616) * _tmp36 + _tmp40 * fv1;
  const Scalar _tmp158 = _tmp142 * _tmp96;
  const Scalar _tmp159 = _tmp147 * _tmp158;
  const Scalar _tmp160 = -Scalar(1.0) * _tmp147 + Scalar(1.0) * _tmp159;
  const Scalar _tmp161 = _tmp113 * _tmp147;
  const Scalar _tmp162 = -_tmp131 * _tmp93 + _tmp142 * _tmp161;
  const Scalar _tmp163 = Scalar(1.0) * _tmp130 * (-_tmp108 * _tmp162 + _tmp161);
  const Scalar _tmp164 = _tmp123 + _tmp125 * _tmp148 - _tmp126 * _tmp93;
  const Scalar _tmp165 = Scalar(1.0) * _tmp128 * (-_tmp108 * _tmp164 + _tmp125 * _tmp147);
  const Scalar _tmp166 =
      Scalar(1.0) * _tmp134 * (-_tmp108 * _tmp146 - _tmp135 * _tmp147 + Scalar(1.0)) +
      _tmp150 * fh1 + _tmp153 * _tmp156 + _tmp157 * _tmp160 + _tmp163 * fh1 + _tmp165 * fh1;
  const Scalar _tmp167 = std::asinh(_tmp141 * _tmp166);
  const Scalar _tmp168 = Scalar(1.0) * _tmp167;
  const Scalar _tmp169 = _tmp120 * _tmp151;
  const Scalar _tmp170 = _tmp128 * _tmp151;
  const Scalar _tmp171 = (-_tmp140 * _tmp166 + _tmp141 * (_tmp150 - _tmp156 * _tmp169 +
                                                          _tmp160 * _tmp170 + _tmp163 + _tmp165)) /
                         std::sqrt(Scalar(_tmp138 * std::pow(_tmp166, Scalar(2)) + 1));
  const Scalar _tmp172 = Scalar(9.6622558468725703) * _tmp137;
  const Scalar _tmp173 =
      -_tmp167 * _tmp172 -
      Scalar(8.3196563700000006) *
          std::sqrt(
              Scalar(std::pow(Scalar(-Scalar(0.12019727204189803) * _tmp79 - 1), Scalar(2)) +
                     Scalar(0.057067943376852184) *
                         std::pow(Scalar(-Scalar(0.50315118556004401) * _tmp82 - 1), Scalar(2))));
  const Scalar _tmp174 = Scalar(9.6622558468725703) * _tmp139;
  const Scalar _tmp175 = Scalar(0.1034955) * _tmp141;
  const Scalar _tmp176 = _tmp173 * _tmp175;
  const Scalar _tmp177 = _tmp130 * _tmp162 * _tmp96;
  const Scalar _tmp178 = _tmp120 * _tmp149 * _tmp96;
  const Scalar _tmp179 = _tmp128 * _tmp164 * _tmp96;
  const Scalar _tmp180 = _tmp154 * _tmp96;
  const Scalar _tmp181 = _tmp147 * _tmp157;
  const Scalar _tmp182 = _tmp134 * _tmp146 * _tmp96 + _tmp153 * _tmp180 - _tmp158 * _tmp181 +
                         _tmp177 * fh1 + _tmp178 * fh1 + _tmp179 * fh1;
  const Scalar _tmp183 = _tmp134 * _tmp136;
  const Scalar _tmp184 = _tmp116 * _tmp120;
  const Scalar _tmp185 = _tmp127 * _tmp128;
  const Scalar _tmp186 = _tmp130 * _tmp131;
  const Scalar _tmp187 = _tmp186 * fh1;
  const Scalar _tmp188 = -_tmp183 * _tmp89 + _tmp184 * fh1 + _tmp185 * fh1 - _tmp187 * _tmp89;
  const Scalar _tmp189 = Scalar(1.0) / (_tmp188);
  const Scalar _tmp190 = std::asinh(_tmp182 * _tmp189);
  const Scalar _tmp191 = Scalar(1.0) * _tmp190;
  const Scalar _tmp192 = std::pow(_tmp188, Scalar(-2));
  const Scalar _tmp193 = _tmp184 + _tmp185 - _tmp186 * _tmp89;
  const Scalar _tmp194 = _tmp192 * _tmp193;
  const Scalar _tmp195 = (-_tmp182 * _tmp194 + _tmp189 * (-_tmp159 * _tmp170 - _tmp169 * _tmp180 +
                                                          _tmp177 + _tmp178 + _tmp179)) /
                         std::sqrt(Scalar(std::pow(_tmp182, Scalar(2)) * _tmp192 + 1));
  const Scalar _tmp196 = Scalar(9.6622558468725703) * _tmp190;
  const Scalar _tmp197 =
      -_tmp188 * _tmp196 -
      Scalar(8.3888750099999996) *
          std::sqrt(
              Scalar(Scalar(0.090254729040973036) *
                         std::pow(Scalar(1 - Scalar(0.39679052492160538) * _tmp65), Scalar(2)) +
                     std::pow(Scalar(-Scalar(0.11920549523123722) * _tmp69 - 1), Scalar(2))));
  const Scalar _tmp198 = Scalar(9.6622558468725703) * _tmp188;
  const Scalar _tmp199 = Scalar(0.1034955) * _tmp189;
  const Scalar _tmp200 = _tmp197 * _tmp199;
  const Scalar _tmp201 = _tmp114 * _tmp120 * _tmp144;
  const Scalar _tmp202 = _tmp130 * _tmp161;
  const Scalar _tmp203 = _tmp125 * _tmp128 * _tmp144;
  const Scalar _tmp204 = _tmp134 * _tmp145 - _tmp153 * _tmp155 + _tmp181 - _tmp201 * fh1 -
                         _tmp202 * fh1 - _tmp203 * fh1;
  const Scalar _tmp205 = _tmp115 * _tmp120;
  const Scalar _tmp206 = _tmp126 * _tmp128;
  const Scalar _tmp207 = _tmp183 + _tmp187 + _tmp205 * fh1 + _tmp206 * fh1;
  const Scalar _tmp208 = Scalar(1.0) / (_tmp207);
  const Scalar _tmp209 = std::asinh(_tmp204 * _tmp208);
  const Scalar _tmp210 = Scalar(1.0) * _tmp209;
  const Scalar _tmp211 = std::pow(_tmp207, Scalar(-2));
  const Scalar _tmp212 = _tmp186 + _tmp205 + _tmp206;
  const Scalar _tmp213 = _tmp211 * _tmp212;
  const Scalar _tmp214 = (-_tmp204 * _tmp213 + _tmp208 * (_tmp147 * _tmp170 + _tmp155 * _tmp169 -
                                                          _tmp201 - _tmp202 - _tmp203)) /
                         std::sqrt(Scalar(std::pow(_tmp204, Scalar(2)) * _tmp211 + 1));
  const Scalar _tmp215 = Scalar(9.6622558468725703) * _tmp212;
  const Scalar _tmp216 = Scalar(9.6622558468725703) * _tmp207;
  const Scalar _tmp217 = Scalar(0.1034955) * _tmp208;
  const Scalar _tmp218 =
      -_tmp209 * _tmp216 -
      Scalar(4.7752063900000001) *
          std::sqrt(
              Scalar(std::pow(Scalar(1 - Scalar(0.20941503221602112) * _tmp50), Scalar(2)) +
                     Scalar(0.32397683292140877) *
                         std::pow(Scalar(1 - Scalar(0.36791786395571047) * _tmp53), Scalar(2))));
  const Scalar _tmp219 = _tmp217 * _tmp218;

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) = -Scalar(8.3700199099999999) * _tmp0 -
               Scalar(9.6622558468725703) * fh1 *
                   (-Scalar(1.0) * _tmp46 * _tmp47 * fv1 * std::sinh(_tmp45) -
                    Scalar(0.86625939559540499) * _tmp46 -
                    (-Scalar(0.1034955) * _tmp42 * _tmp46 +
                     _tmp43 * (Scalar(9.6622558468725703) * _tmp1 * _tmp47 - _tmp3)) *
                        std::sinh(_tmp44)) +
               Scalar(9.6622558468725703) * std::cosh(_tmp44) -
               Scalar(9.6622558468725703) * std::cosh(_tmp45);
  _res(1, 0) =
      -_tmp172 *
          (-Scalar(0.87679799772039002) * _tmp140 + Scalar(1.0) * _tmp171 * std::sinh(_tmp168) -
           (-Scalar(0.1034955) * _tmp140 * _tmp173 +
            _tmp175 * (-_tmp167 * _tmp174 - _tmp171 * _tmp172)) *
               std::sinh(_tmp176)) -
      _tmp174 * (Scalar(0.87679799772039002) * _tmp141 + std::cosh(_tmp168) - std::cosh(_tmp176));
  _res(2, 0) =
      -Scalar(9.6622558468725703) * _tmp193 *
          (Scalar(0.87653584775870996) * _tmp189 + std::cosh(_tmp191) - std::cosh(_tmp200)) -
      _tmp198 *
          (-Scalar(0.87653584775870996) * _tmp194 + Scalar(1.0) * _tmp195 * std::sinh(_tmp191) -
           (-Scalar(0.1034955) * _tmp194 * _tmp197 +
            _tmp199 * (-_tmp193 * _tmp196 - _tmp195 * _tmp198)) *
               std::sinh(_tmp200));
  _res(3, 0) =
      -_tmp215 * (Scalar(0.86565325453551001) * _tmp208 + std::cosh(_tmp210) - std::cosh(_tmp219)) -
      _tmp216 *
          (-Scalar(0.86565325453551001) * _tmp213 + Scalar(1.0) * _tmp214 * std::sinh(_tmp210) -
           (-Scalar(0.1034955) * _tmp213 * _tmp218 +
            _tmp217 * (-_tmp209 * _tmp215 - _tmp214 * _tmp216)) *
               std::sinh(_tmp219));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
